ITK: itk::GiplImageIOFactory Class Reference
itk::GiplImageIOFactory Class Reference
Module ITKIOGIPL
#include <itkGiplImageIOFactory.h>
Detailed Description
Create instances of GiplImageIO objects using an object factory.
Definition at line 32 of file itkGiplImageIOFactory.h.
Public Types
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = GiplImageIOFactory
using Superclass = ObjectFactoryBase
Public Types inherited from itk::ObjectFactoryBase
using ConstPointer = SmartPointer< const Self >
using InsertionPositionEnum = ObjectFactoryEnums::InsertionPosition
using Pointer = SmartPointer< Self >
using Self = ObjectFactoryBase
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
const char * GetDescription () const override
const char * GetITKSourceVersion () const override
virtual const char * GetNameOfClass () const
Public Member Functions inherited from itk::ObjectFactoryBase
virtual void Disable (const char *className)
virtual std::list< std::string > GetClassOverrideDescriptions ()
virtual std::list< std::string > GetClassOverrideNames ()
virtual std::list< std::string > GetClassOverrideWithNames ()
virtual const char * GetDescription () const =0
virtual bool GetEnableFlag (const char *className, const char *subclassName)
virtual std::list< bool > GetEnableFlags ()
virtual const char * GetITKSourceVersion () const =0
const char * GetLibraryPath ()
virtual const char * GetNameOfClass () const
virtual void SetEnableFlag (bool flag, const char *className, const char *subclassName)
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *)
unsigned long AddObserver (const EventObject &event, Command *) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const char * GetNameOfClass () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag)
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual Pointer CreateAnother () const
virtual void Delete ()
virtual int GetReferenceCount () const
itkTypeMacroNoParent (LightObject)
void Print (std::ostream &os, Indent indent=0) const
virtual void Register () const
virtual void SetReferenceCount (int)
virtual void UnRegister () const noexcept
Static Public Member Functions
static Pointer New ()
static void RegisterOneFactory ()
Static Public Member Functions inherited from itk::ObjectFactoryBase
static std::list< LightObject::Pointer > CreateAllInstance (const char *itkclassname)
static LightObject::Pointer CreateInstance (const char *itkclassname)
static std::list< ObjectFactoryBase * > GetRegisteredFactories ()
static void Initialize ()
static void RegisterFactoryInternal (ObjectFactoryBase *)
template<typename TFactory >
static void RegisterInternalFactoryOnce ()
static void ReHash ()
static void UnRegisterAllFactories ()
static void UnRegisterFactory (ObjectFactoryBase *)
static bool RegisterFactory (ObjectFactoryBase *, InsertionPositionEnum where=InsertionPositionEnum::INSERT_AT_BACK, vcl_size_t position=0)
static void SetStrictVersionChecking (bool)
static void StrictVersionCheckingOn ()
static void StrictVersionCheckingOff ()
static bool GetStrictVersionChecking ()
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Protected Member Functions
GiplImageIOFactory ()
~GiplImageIOFactory () override
Protected Member Functions inherited from itk::ObjectFactoryBase
virtual std::list< LightObject::Pointer > CreateAllObject (const char *itkclassname)
virtual LightObject::Pointer CreateObject (const char *itkclassname)
ObjectFactoryBase ()
void PrintSelf (std::ostream &os, Indent indent) const override
void RegisterOverride (const char *classOverride, const char *subclass, const char *description, bool enableFlag, CreateObjectFunctionBase *createFunction)
~ObjectFactoryBase () override
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
void PrintSelf (std::ostream &os, Indent indent) const override
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintSelf (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Additional Inherited Members
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount {}
Member Typedef Documentation
ConstPointer
using itk::GiplImageIOFactory::ConstPointer = SmartPointer<const Self>
Definition at line 41 of file itkGiplImageIOFactory.h.
Pointer
using itk::GiplImageIOFactory::Pointer = SmartPointer<Self>
Definition at line 40 of file itkGiplImageIOFactory.h.
Self
using itk::GiplImageIOFactory::Self = GiplImageIOFactory
Standard class type aliases.
Definition at line 38 of file itkGiplImageIOFactory.h.
Superclass
using itk::GiplImageIOFactory::Superclass = ObjectFactoryBase
Definition at line 39 of file itkGiplImageIOFactory.h.
Constructor & Destructor Documentation
GiplImageIOFactory()
itk::GiplImageIOFactory::GiplImageIOFactory () protected
~GiplImageIOFactory()
itk::GiplImageIOFactory::~GiplImageIOFactory () override protected
Member Function Documentation
GetDescription()
const char * itk::GiplImageIOFactory::GetDescription () const override virtual
Return a descriptive string describing the factory.
Implements itk::ObjectFactoryBase.
GetITKSourceVersion()
const char * itk::GiplImageIOFactory::GetITKSourceVersion () const override virtual
Class methods used to interface with the registered factories.
Implements itk::ObjectFactoryBase.
GetNameOfClass()
virtual const char * itk::GiplImageIOFactory::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::ObjectFactoryBase.
New()
static Pointer itk::GiplImageIOFactory::New () static
Method for class instantiation.
Referenced by RegisterOneFactory().
RegisterOneFactory()
static void itk::GiplImageIOFactory::RegisterOneFactory () inline static
Register one factory of this type
Definition at line 58 of file itkGiplImageIOFactory.h.
References New(), and itk::ObjectFactoryBase::RegisterFactoryInternal().
The documentation for this class was generated from the following file:
itkGiplImageIOFactory.h