ITK: itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData > Class Template Reference
itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData > Class Template Reference
Group Nonunit » Module ITKReview
#include <itkConstrainedRegionBasedLevelSetFunctionSharedData.h>
Public Types
using CentroidVectorType = Vector< float, Self::ImageDimension >
using ConstPointer = SmartPointer< const Self >
using FeatureImageConstPointer = typename FeatureImageType::ConstPointer
using FeatureImagePointer = typename FeatureImageType::Pointer
using FeatureImageType = TFeatureImage
using FeatureIndexType = typename FeatureImageType::IndexType
using FeaturePixelType = typename FeatureImageType::PixelType
using FeaturePointType = typename FeatureImageType::PointType
using FeatureRegionType = typename FeatureImageType::RegionType
using FeatureSizeType = typename FeatureImageType::SizeType
using FeatureSizeValueType = typename FeatureSizeType::SizeValueType
using FeatureSpacingType = typename FeatureImageType::SpacingType
using InputImageConstPointer = typename InputImageType::ConstPointer
using InputImagePointer = typename InputImageType::Pointer
using InputImageType = TInputImage
using InputIndexType = typename InputImageType::IndexType
using InputIndexValueType = typename InputIndexType::IndexValueType
using InputPixelType = typename InputImageType::PixelType
using InputPointType = typename InputImageType::PointType
using InputRegionType = typename InputImageType::RegionType
using InputSizeType = typename InputImageType::SizeType
using InputSizeValueType = typename InputSizeType::SizeValueType
using InputSpacingType = typename InputImageType::SpacingType
using KdTreePointer = typename TreeType::Pointer
using LevelSetDataPointer = typename LevelSetDataType::Pointer
using LevelSetDataPointerVector = std::vector< LevelSetDataPointer >
using LevelSetDataPointerVectorIterator = typename LevelSetDataPointerVector::iterator
using LevelSetDataType = TSingleData
using ListImageConstPointer = typename ListImageType::ConstPointer
using ListImagePointer = typename ListImageType::Pointer
using ListImageType = Image< ListPixelType, Self::ImageDimension >
using ListIndexType = typename ListImageType::IndexType
using ListIndexValueType = typename ListIndexType::IndexValueType
using ListIteratorType = ImageRegionIteratorWithIndex< ListImageType >
using ListPixelType = std::list< unsigned int >
using ListPointType = typename ListImageType::PointType
using ListRegionType = typename ListImageType::RegionType
using ListSizeType = typename ListImageType::SizeType
using ListSizeValueType = typename ListSizeType::SizeValueType
using ListSpacingType = typename ListImageType::SpacingType
using Pointer = SmartPointer< Self >
using SampleType = itk::Statistics::ListSample< CentroidVectorType >
using Self = ConstrainedRegionBasedLevelSetFunctionSharedData
using Superclass = RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >
using TreeGeneratorType = itk::Statistics::KdTreeGenerator< SampleType >
using TreePointer = typename TreeGeneratorType::Pointer
using TreeType = typename TreeGeneratorType::KdTreeType
Public Types inherited from itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >
using CentroidVectorType = Vector< float, Self::ImageDimension >
using ConstPointer = SmartPointer< const Self >
using FeatureImageConstPointer = typename FeatureImageType::ConstPointer
using FeatureImagePointer = typename FeatureImageType::Pointer
using FeatureImageType = TFeatureImage
using FeatureIndexType = typename FeatureImageType::IndexType
using FeaturePixelType = typename FeatureImageType::PixelType
using FeaturePointType = typename FeatureImageType::PointType
using FeatureRegionType = typename FeatureImageType::RegionType
using FeatureSizeType = typename FeatureImageType::SizeType
using FeatureSizeValueType = typename FeatureSizeType::SizeValueType
using FeatureSpacingType = typename FeatureImageType::SpacingType
using InputImageConstPointer = typename InputImageType::ConstPointer
using InputImagePointer = typename InputImageType::Pointer
using InputImageType = TInputImage
using InputIndexType = typename InputImageType::IndexType
using InputIndexValueType = typename InputIndexType::IndexValueType
using InputPixelType = typename InputImageType::PixelType
using InputPointType = typename InputImageType::PointType
using InputRegionType = typename InputImageType::RegionType
using InputSizeType = typename InputImageType::SizeType
using InputSizeValueType = typename InputSizeType::SizeValueType
using InputSpacingType = typename InputImageType::SpacingType
using KdTreePointer = typename TreeType::Pointer
using LevelSetDataPointer = typename LevelSetDataType::Pointer
using LevelSetDataPointerVector = std::vector< LevelSetDataPointer >
using LevelSetDataPointerVectorIterator = typename LevelSetDataPointerVector::iterator
using LevelSetDataType = TSingleData
using ListImageConstPointer = typename ListImageType::ConstPointer
using ListImagePointer = typename ListImageType::Pointer
using ListImageType = Image< ListPixelType, Self::ImageDimension >
using ListIndexType = typename ListImageType::IndexType
using ListIndexValueType = typename ListIndexType::IndexValueType
using ListIteratorType = ImageRegionIteratorWithIndex< ListImageType >
using ListPixelType = std::list< unsigned int >
using ListPointType = typename ListImageType::PointType
using ListRegionType = typename ListImageType::RegionType
using ListSizeType = typename ListImageType::SizeType
using ListSizeValueType = typename ListSizeType::SizeValueType
using ListSpacingType = typename ListImageType::SpacingType
using Pointer = SmartPointer< Self >
using SampleType = itk::Statistics::ListSample< CentroidVectorType >
using Self = RegionBasedLevelSetFunctionSharedData
using Superclass = LightObject
using TreeGeneratorType = itk::Statistics::KdTreeGenerator< SampleType >
using TreePointer = typename TreeGeneratorType::Pointer
using TreeType = typename TreeGeneratorType::KdTreeType
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
virtual const char * GetNameOfClass () const
void PopulateListImage () override
Public Member Functions inherited from itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >
void AllocateListImage (const FeatureImageType *featureImage)
void CreateHeavisideFunctionOfLevelSetImage (const unsigned int j, const InputImageType *image)
virtual const char * GetNameOfClass () const
virtual void PopulateListImage ()=0
void SetFunctionCount (const unsigned int n)
void SetKdTree (KdTreePointer kdtree)
void SetNumberOfNeighbors (const unsigned int n)
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual Pointer CreateAnother () const
virtual void Delete ()
virtual int GetReferenceCount () const
itkTypeMacroNoParent (LightObject)
void Print (std::ostream &os, Indent indent=0) const
virtual void Register () const
virtual void SetReferenceCount (int)
virtual void UnRegister () const noexcept
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Static Public Attributes
static constexpr unsigned int ImageDimension = TFeatureImage::ImageDimension
Static Public Attributes inherited from itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >
static constexpr unsigned int ImageDimension = TFeatureImage::ImageDimension
Protected Member Functions
ConstrainedRegionBasedLevelSetFunctionSharedData ()
~ConstrainedRegionBasedLevelSetFunctionSharedData () override=default
Protected Member Functions inherited from itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >
RegionBasedLevelSetFunctionSharedData ()
~RegionBasedLevelSetFunctionSharedData () override=default
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintSelf (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Additional Inherited Members
Public Attributes inherited from itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >
unsigned int m_FunctionCount {}
KdTreePointer m_KdTree {}
LevelSetDataPointerVector m_LevelSetDataPointerVector {}
ListImagePointer m_NearestNeighborListImage {}
unsigned int m_NumberOfNeighbors { 6 }
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount {}
Detailed Description
template<typename TInputImage, typename TFeatureImage, typename TSingleData>
class itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >
Helper class used to share data in the ScalarChanAndVeseLevelSetFunction.
This class holds cache data used during the computation of the LevelSet updates.
Based on the paper:
   "An active contour model without edges"
    T. Chan and L. Vese.
    In Scale-Space Theories in Computer Vision, pages 141-151, 1999.
Author
Mosaliganti K., Smith B., Gelas A., Gouaillard A., Megason S.
This code was taken from the Insight Journal paper:
"Cell Tracking using Coupled Active Surfaces for Nuclei and Membranes"
https://www.insight-journal.org/browse/publication/642
https://hdl.handle.net/10380/3055
That is based on the papers:
"Level Set Segmentation: Active Contours without edge"
https://www.insight-journal.org/browse/publication/322
https://hdl.handle.net/1926/1532
and
"Level set segmentation using coupled active surfaces"
https://www.insight-journal.org/browse/publication/323
https://hdl.handle.net/1926/1533
Definition at line 61 of file itkConstrainedRegionBasedLevelSetFunctionSharedData.h.
Member Typedef Documentation
CentroidVectorType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::CentroidVectorType = Vector<float, Self::ImageDimension>
Definition at line 118 of file itkRegionBasedLevelSetFunctionSharedData.h.
ConstPointer
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ConstPointer = SmartPointer<const Self>
Definition at line 70 of file itkConstrainedRegionBasedLevelSetFunctionSharedData.h.
FeatureImageConstPointer
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::FeatureImageConstPointer = typename FeatureImageType::ConstPointer
Definition at line 96 of file itkRegionBasedLevelSetFunctionSharedData.h.
FeatureImagePointer
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::FeatureImagePointer = typename FeatureImageType::Pointer
Definition at line 95 of file itkRegionBasedLevelSetFunctionSharedData.h.
FeatureImageType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::FeatureImageType = TFeatureImage
Definition at line 91 of file itkConstrainedRegionBasedLevelSetFunctionSharedData.h.
FeatureIndexType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::FeatureIndexType = typename FeatureImageType::IndexType
Definition at line 102 of file itkRegionBasedLevelSetFunctionSharedData.h.
FeaturePixelType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::FeaturePixelType = typename FeatureImageType::PixelType
Definition at line 97 of file itkRegionBasedLevelSetFunctionSharedData.h.
FeaturePointType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::FeaturePointType = typename FeatureImageType::PointType
Definition at line 103 of file itkRegionBasedLevelSetFunctionSharedData.h.
FeatureRegionType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::FeatureRegionType = typename FeatureImageType::RegionType
Definition at line 98 of file itkRegionBasedLevelSetFunctionSharedData.h.
FeatureSizeType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::FeatureSizeType = typename FeatureImageType::SizeType
Definition at line 99 of file itkRegionBasedLevelSetFunctionSharedData.h.
FeatureSizeValueType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::FeatureSizeValueType = typename FeatureSizeType::SizeValueType
Definition at line 100 of file itkRegionBasedLevelSetFunctionSharedData.h.
FeatureSpacingType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::FeatureSpacingType = typename FeatureImageType::SpacingType
Definition at line 101 of file itkRegionBasedLevelSetFunctionSharedData.h.
InputImageConstPointer
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::InputImageConstPointer = typename InputImageType::ConstPointer
Definition at line 84 of file itkRegionBasedLevelSetFunctionSharedData.h.
InputImagePointer
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::InputImagePointer = typename InputImageType::Pointer
Definition at line 83 of file itkRegionBasedLevelSetFunctionSharedData.h.
InputImageType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::InputImageType = TInputImage
Definition at line 79 of file itkConstrainedRegionBasedLevelSetFunctionSharedData.h.
InputIndexType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::InputIndexType = typename InputImageType::IndexType
Definition at line 90 of file itkRegionBasedLevelSetFunctionSharedData.h.
InputIndexValueType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::InputIndexValueType = typename InputIndexType::IndexValueType
Definition at line 91 of file itkRegionBasedLevelSetFunctionSharedData.h.
InputPixelType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::InputPixelType = typename InputImageType::PixelType
Definition at line 85 of file itkRegionBasedLevelSetFunctionSharedData.h.
InputPointType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::InputPointType = typename InputImageType::PointType
Definition at line 92 of file itkRegionBasedLevelSetFunctionSharedData.h.
InputRegionType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::InputRegionType = typename InputImageType::RegionType
Definition at line 86 of file itkRegionBasedLevelSetFunctionSharedData.h.
InputSizeType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::InputSizeType = typename InputImageType::SizeType
Definition at line 87 of file itkRegionBasedLevelSetFunctionSharedData.h.
InputSizeValueType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::InputSizeValueType = typename InputSizeType::SizeValueType
Definition at line 88 of file itkRegionBasedLevelSetFunctionSharedData.h.
InputSpacingType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::InputSpacingType = typename InputImageType::SpacingType
Definition at line 89 of file itkRegionBasedLevelSetFunctionSharedData.h.
KdTreePointer
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::KdTreePointer = typename TreeType::Pointer
Definition at line 123 of file itkRegionBasedLevelSetFunctionSharedData.h.
LevelSetDataPointer
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::LevelSetDataPointer = typename LevelSetDataType::Pointer
Definition at line 126 of file itkRegionBasedLevelSetFunctionSharedData.h.
LevelSetDataPointerVector
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::LevelSetDataPointerVector = std::vector<LevelSetDataPointer>
Definition at line 127 of file itkRegionBasedLevelSetFunctionSharedData.h.
LevelSetDataPointerVectorIterator
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::LevelSetDataPointerVectorIterator = typename LevelSetDataPointerVector::iterator
Definition at line 128 of file itkRegionBasedLevelSetFunctionSharedData.h.
LevelSetDataType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::LevelSetDataType = TSingleData
Definition at line 122 of file itkConstrainedRegionBasedLevelSetFunctionSharedData.h.
ListImageConstPointer
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListImageConstPointer = typename ListImageType::ConstPointer
Definition at line 108 of file itkRegionBasedLevelSetFunctionSharedData.h.
ListImagePointer
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListImagePointer = typename ListImageType::Pointer
Definition at line 107 of file itkRegionBasedLevelSetFunctionSharedData.h.
ListImageType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListImageType = Image<ListPixelType, Self::ImageDimension>
Definition at line 106 of file itkRegionBasedLevelSetFunctionSharedData.h.
ListIndexType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListIndexType = typename ListImageType::IndexType
Definition at line 113 of file itkRegionBasedLevelSetFunctionSharedData.h.
ListIndexValueType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListIndexValueType = typename ListIndexType::IndexValueType
Definition at line 114 of file itkRegionBasedLevelSetFunctionSharedData.h.
ListIteratorType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListIteratorType = ImageRegionIteratorWithIndex<ListImageType>
Definition at line 116 of file itkRegionBasedLevelSetFunctionSharedData.h.
ListPixelType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListPixelType = std::list<unsigned int>
Definition at line 105 of file itkRegionBasedLevelSetFunctionSharedData.h.
ListPointType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListPointType = typename ListImageType::PointType
Definition at line 115 of file itkRegionBasedLevelSetFunctionSharedData.h.
ListRegionType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListRegionType = typename ListImageType::RegionType
Definition at line 109 of file itkRegionBasedLevelSetFunctionSharedData.h.
ListSizeType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListSizeType = typename ListImageType::SizeType
Definition at line 110 of file itkRegionBasedLevelSetFunctionSharedData.h.
ListSizeValueType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListSizeValueType = typename ListSizeType::SizeValueType
Definition at line 111 of file itkRegionBasedLevelSetFunctionSharedData.h.
ListSpacingType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ListSpacingType = typename ListImageType::SpacingType
Definition at line 112 of file itkRegionBasedLevelSetFunctionSharedData.h.
Pointer
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::Pointer = SmartPointer<Self>
Definition at line 69 of file itkConstrainedRegionBasedLevelSetFunctionSharedData.h.
SampleType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::SampleType = itk::Statistics::ListSample<CentroidVectorType>
Definition at line 119 of file itkRegionBasedLevelSetFunctionSharedData.h.
Self
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::Self = ConstrainedRegionBasedLevelSetFunctionSharedData
Definition at line 67 of file itkConstrainedRegionBasedLevelSetFunctionSharedData.h.
Superclass
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::Superclass = RegionBasedLevelSetFunctionSharedData<TInputImage, TFeatureImage, TSingleData>
Definition at line 68 of file itkConstrainedRegionBasedLevelSetFunctionSharedData.h.
TreeGeneratorType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::TreeGeneratorType = itk::Statistics::KdTreeGenerator<SampleType>
Definition at line 120 of file itkRegionBasedLevelSetFunctionSharedData.h.
TreePointer
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::TreePointer = typename TreeGeneratorType::Pointer
Definition at line 121 of file itkRegionBasedLevelSetFunctionSharedData.h.
TreeType
template<typename TInputImage , typename TFeatureImage , typename TSingleData > using itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::TreeType = typename TreeGeneratorType::KdTreeType
Definition at line 122 of file itkRegionBasedLevelSetFunctionSharedData.h.
Constructor & Destructor Documentation
ConstrainedRegionBasedLevelSetFunctionSharedData()
template<typename TInputImage , typename TFeatureImage , typename TSingleData > itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ConstrainedRegionBasedLevelSetFunctionSharedData () inline protected
Definition at line 181 of file itkConstrainedRegionBasedLevelSetFunctionSharedData.h.
~ConstrainedRegionBasedLevelSetFunctionSharedData()
template<typename TInputImage , typename TFeatureImage , typename TSingleData > itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::~ConstrainedRegionBasedLevelSetFunctionSharedData () override protected default
Member Function Documentation
GetNameOfClass()
template<typename TInputImage , typename TFeatureImage , typename TSingleData > virtual const char * itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::GetNameOfClass () const virtual
Reimplemented from itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >.
New()
template<typename TInputImage , typename TFeatureImage , typename TSingleData > static Pointer itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::New () static
Method for creation through the object factory.
PopulateListImage()
template<typename TInputImage , typename TFeatureImage , typename TSingleData > void itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::PopulateListImage () inline override virtual
Implements itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >.
Definition at line 128 of file itkConstrainedRegionBasedLevelSetFunctionSharedData.h.
References itk::ImageConstIteratorWithIndex< TImage >::GetIndex(), itk::ImageConstIteratorWithIndex< TImage >::GoToBegin(), itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ImageDimension, itk::ImageConstIteratorWithIndex< TImage >::IsAtEnd(), itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::m_FunctionCount, itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::m_KdTree, itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::m_LevelSetDataPointerVector, itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::m_NearestNeighborListImage, itk::RegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::m_NumberOfNeighbors, and itk::ImageRegionIteratorWithIndex< TImage >::Set().
Member Data Documentation
ImageDimension
template<typename TInputImage , typename TFeatureImage , typename TSingleData > constexpr unsigned int itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::ImageDimension = TFeatureImage::ImageDimension static constexpr
Definition at line 72 of file itkConstrainedRegionBasedLevelSetFunctionSharedData.h.
Referenced by itk::ConstrainedRegionBasedLevelSetFunctionSharedData< TInputImage, TFeatureImage, TSingleData >::PopulateListImage().
The documentation for this class was generated from the following file:
itkConstrainedRegionBasedLevelSetFunctionSharedData.h