ITK: itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition > Class Template Reference
itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition > Class Template Reference
Group Numerics » Module ITKStatistics
#include <itkImageToNeighborhoodSampleAdaptor.h>
Classes
class ConstIterator
class Iterator
Public Types
using ConstPointer = SmartPointer< const Self >
using ImageConstPointer = typename ImageType::ConstPointer
using ImageIteratorType = ImageRegionIteratorWithIndex< TImage >
using ImagePointer = typename ImageType::Pointer
using ImageType = TImage
using IndexType = typename ImageType::IndexType
using MeasurementType = ValueType
using MeasurementVectorType = typename std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > >
using NeighborhoodIndexType = typename NeighborhoodIteratorType::IndexType
using NeighborhoodIteratorType = ConstNeighborhoodIterator< TImage, TBoundaryCondition >
using NeighborhoodRadiusType = typename NeighborhoodIteratorType::RadiusType
using NeighborhoodSizeType = typename NeighborhoodIteratorType::SizeType
using NeighborhoodType = typename NeighborhoodIteratorType::NeighborhoodType
using NonConstNeighborhoodIteratorType = NeighborhoodIterator< TImage, TBoundaryCondition >
using OffsetTableType = typename RegionType::OffsetTableType
using OffsetType = typename ImageType::OffsetType
using OffsetValueType = typename ImageType::OffsetValueType
using PixelContainerConstPointer = typename ImageType::PixelContainerConstPointer
using PixelType = typename ImageType::PixelType
using Pointer = SmartPointer< Self >
using RegionType = typename ImageType::RegionType
using Self = ImageToNeighborhoodSampleAdaptor
using SizeType = typename ImageType::SizeType
using Superclass = ListSample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >
using ValueType = typename MeasurementVectorType::value_type
Public Types inherited from itk::Statistics::ListSample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >
using ConstPointer = SmartPointer< const Self >
using InternalDataContainerType = std::vector< MeasurementVectorType >
using Pointer = SmartPointer< Self >
using Self = ListSample
using Superclass = Sample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >
using ValueType = MeasurementVectorType
Public Types inherited from itk::Statistics::Sample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >
using AbsoluteFrequencyType = MeasurementVectorTraits::AbsoluteFrequencyType
using ConstPointer = SmartPointer< const Self >
using InstanceIdentifier = typename MeasurementVectorTraits::InstanceIdentifier
using MeasurementType = typename MeasurementVectorTraitsTypes< MeasurementVectorType >::ValueType
using MeasurementVectorSizeType = unsigned int
using MeasurementVectorType = std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > >
using Pointer = SmartPointer< Self >
using Self = Sample
using Superclass = DataObject
using TotalAbsoluteFrequencyType = NumericTraits< AbsoluteFrequencyType >::AccumulateType
Public Types inherited from itk::DataObject
using ConstPointer = SmartPointer< const Self >
using DataObjectIdentifierType = std::string
using DataObjectPointerArraySizeType = std::vector< Pointer >::size_type
using Pointer = SmartPointer< Self >
using Self = DataObject
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
AbsoluteFrequencyType GetFrequency (InstanceIdentifier id) const override
const TImage * GetImage () const
const MeasurementVectorType & GetMeasurementVector (InstanceIdentifier id) const override
virtual const char * GetNameOfClass () const
NeighborhoodRadiusType GetRadius () const
RegionType GetRegion () const
TotalAbsoluteFrequencyType GetTotalFrequency () const override
virtual bool GetUseImageRegion () const
void SetImage (const TImage *image)
void SetRadius (const NeighborhoodRadiusType &radius)
void SetRegion (const RegionType &region)
void SetUseImageRegion (const bool flag)
InstanceIdentifier Size () const override
virtual void UseImageRegionOn ()
Iterator Begin ()
Iterator End ()
ConstIterator Begin () const
ConstIterator End () const
Public Member Functions inherited from itk::Statistics::ListSample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >
Iterator Begin ()
ConstIterator Begin () const
void Clear ()
Iterator End ()
ConstIterator End () const
AbsoluteFrequencyType GetFrequency (InstanceIdentifier instanceId) const override
const MeasurementVectorType & GetMeasurementVector (InstanceIdentifier instanceId) const override
virtual const char * GetNameOfClass () const
TotalAbsoluteFrequencyType GetTotalFrequency () const override
void Graft (const DataObject *thatObject) override
void PushBack (const MeasurementVectorType &mv)
void Resize (InstanceIdentifier newsize)
void SetMeasurement (InstanceIdentifier instanceId, unsigned int dim, const MeasurementType &value)
void SetMeasurementVector (InstanceIdentifier instanceId, const MeasurementVectorType &mv)
InstanceIdentifier Size () const override
Public Member Functions inherited from itk::Statistics::Sample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >
virtual AbsoluteFrequencyType GetFrequency (InstanceIdentifier id) const=0
virtual const MeasurementVectorType & GetMeasurementVector (InstanceIdentifier id) const=0
virtual MeasurementVectorSizeType GetMeasurementVectorSize () const
virtual const char * GetNameOfClass () const
virtual TotalAbsoluteFrequencyType GetTotalFrequency () const=0
void Graft (const DataObject *thatObject) override
virtual InstanceIdentifier Size () const=0
virtual void SetMeasurementVectorSize (MeasurementVectorSizeType s)
Public Member Functions inherited from itk::DataObject
virtual void CopyInformation (const DataObject *)
virtual void DataHasBeenGenerated ()
void DisconnectPipeline ()
bool GetDataReleased () const
virtual const char * GetNameOfClass () const
virtual const bool & GetReleaseDataFlag () const
SmartPointer< ProcessObject > GetSource () const
DataObjectPointerArraySizeType GetSourceOutputIndex () const
const DataObjectIdentifierType & GetSourceOutputName () const
virtual ModifiedTimeType GetUpdateMTime () const
virtual void Graft (const DataObject *)
virtual void Initialize ()
virtual void PrepareForNewData ()
virtual void PropagateRequestedRegion ()
void ReleaseData ()
virtual void ReleaseDataFlagOn ()
virtual bool RequestedRegionIsOutsideOfTheBufferedRegion ()
virtual void ResetPipeline ()
void SetReleaseDataFlag (bool flag)
virtual void SetRequestedRegion (const DataObject *)
virtual void SetRequestedRegionToLargestPossibleRegion ()
bool ShouldIReleaseData () const
virtual void Update ()
virtual void UpdateOutputData ()
virtual void UpdateOutputInformation ()
void UpdateSource () const
virtual bool VerifyRequestedRegion ()
void SetPipelineMTime (ModifiedTimeType time)
virtual const ModifiedTimeType & GetPipelineMTime () const
virtual void SetRealTimeStamp (RealTimeStamp _arg)
virtual const RealTimeStamp & GetRealTimeStamp () const
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *)
unsigned long AddObserver (const EventObject &event, Command *) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const char * GetNameOfClass () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag)
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual Pointer CreateAnother () const
virtual void Delete ()
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
virtual void Register () const
virtual void SetReferenceCount (int)
virtual void UnRegister () const noexcept
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::Statistics::ListSample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >
static Pointer New ()
Static Public Member Functions inherited from itk::DataObject
static bool GetGlobalReleaseDataFlag ()
static void GlobalReleaseDataFlagOff ()
static void GlobalReleaseDataFlagOn ()
static Pointer New ()
static void SetGlobalReleaseDataFlag (bool val)
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Protected Member Functions
ImageToNeighborhoodSampleAdaptor ()
void PrintSelf (std::ostream &os, Indent indent) const override
~ImageToNeighborhoodSampleAdaptor () override=default
Protected Member Functions inherited from itk::Statistics::ListSample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >
ListSample ()=default
void PrintSelf (std::ostream &os, Indent indent) const override
~ListSample () override=default
Protected Member Functions inherited from itk::Statistics::Sample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >
void PrintSelf (std::ostream &os, Indent indent) const override
Sample ()
~Sample () override=default
Protected Member Functions inherited from itk::DataObject
DataObject ()
void PrintSelf (std::ostream &os, Indent indent) const override
virtual void PropagateResetPipeline ()
~DataObject () override
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
void PrintSelf (std::ostream &os, Indent indent) const override
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintSelf (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Private Attributes
ImageConstPointer m_Image
InstanceIdentifier m_InstanceIdentifierInternal
MeasurementVectorType m_MeasurementVectorInternal
IndexType m_NeighborIndexInternal
OffsetTableType m_OffsetTable
NeighborhoodRadiusType m_Radius
RegionType m_Region
bool m_UseImageRegion { true }
Additional Inherited Members
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount
Detailed Description
template<typename TImage, typename TBoundaryCondition>
class itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >
This class provides ListSample interface to ITK Image.
After calling SetImage(const Image *) method to plug in the image object, users can use Sample interfaces to access Image neighborhoods. The resulting data are a list of measurement vectors where each measurement vector has one element, an itkConstNeighborhoodIterator.
This class handles images with scalar, fixed array or variable length vector pixel types.
See also
Sample, ListSample, Neighborhood
Definition at line 55 of file itkImageToNeighborhoodSampleAdaptor.h.
Member Typedef Documentation
ConstPointer
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::ConstPointer = SmartPointer<const Self>
Definition at line 67 of file itkImageToNeighborhoodSampleAdaptor.h.
ImageConstPointer
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::ImageConstPointer = typename ImageType::ConstPointer
Definition at line 78 of file itkImageToNeighborhoodSampleAdaptor.h.
ImageIteratorType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::ImageIteratorType = ImageRegionIteratorWithIndex<TImage>
Definition at line 87 of file itkImageToNeighborhoodSampleAdaptor.h.
ImagePointer
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::ImagePointer = typename ImageType::Pointer
Definition at line 77 of file itkImageToNeighborhoodSampleAdaptor.h.
ImageType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::ImageType = TImage
Image type alias
Definition at line 76 of file itkImageToNeighborhoodSampleAdaptor.h.
IndexType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::IndexType = typename ImageType::IndexType
Definition at line 79 of file itkImageToNeighborhoodSampleAdaptor.h.
MeasurementType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::MeasurementType = ValueType
Definition at line 101 of file itkImageToNeighborhoodSampleAdaptor.h.
MeasurementVectorType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::MeasurementVectorType = typename std::vector<ConstNeighborhoodIterator<TImage, TBoundaryCondition> >
Superclass type alias for Measurement vector, measurement, Instance Identifier, frequency, size, size element value
Definition at line 99 of file itkImageToNeighborhoodSampleAdaptor.h.
NeighborhoodIndexType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::NeighborhoodIndexType = typename NeighborhoodIteratorType::IndexType
Definition at line 94 of file itkImageToNeighborhoodSampleAdaptor.h.
NeighborhoodIteratorType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::NeighborhoodIteratorType = ConstNeighborhoodIterator<TImage, TBoundaryCondition>
Neighborhood Iterator type alias support
Definition at line 90 of file itkImageToNeighborhoodSampleAdaptor.h.
NeighborhoodRadiusType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::NeighborhoodRadiusType = typename NeighborhoodIteratorType::RadiusType
Definition at line 93 of file itkImageToNeighborhoodSampleAdaptor.h.
NeighborhoodSizeType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::NeighborhoodSizeType = typename NeighborhoodIteratorType::SizeType
Definition at line 95 of file itkImageToNeighborhoodSampleAdaptor.h.
NeighborhoodType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::NeighborhoodType = typename NeighborhoodIteratorType::NeighborhoodType
Definition at line 92 of file itkImageToNeighborhoodSampleAdaptor.h.
NonConstNeighborhoodIteratorType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::NonConstNeighborhoodIteratorType = NeighborhoodIterator<TImage, TBoundaryCondition>
Definition at line 91 of file itkImageToNeighborhoodSampleAdaptor.h.
OffsetTableType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::OffsetTableType = typename RegionType::OffsetTableType
Definition at line 85 of file itkImageToNeighborhoodSampleAdaptor.h.
OffsetType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::OffsetType = typename ImageType::OffsetType
Definition at line 80 of file itkImageToNeighborhoodSampleAdaptor.h.
OffsetValueType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::OffsetValueType = typename ImageType::OffsetValueType
Definition at line 81 of file itkImageToNeighborhoodSampleAdaptor.h.
PixelContainerConstPointer
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::PixelContainerConstPointer = typename ImageType::PixelContainerConstPointer
Definition at line 83 of file itkImageToNeighborhoodSampleAdaptor.h.
PixelType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::PixelType = typename ImageType::PixelType
Definition at line 82 of file itkImageToNeighborhoodSampleAdaptor.h.
Pointer
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::Pointer = SmartPointer<Self>
Definition at line 66 of file itkImageToNeighborhoodSampleAdaptor.h.
RegionType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::RegionType = typename ImageType::RegionType
Definition at line 84 of file itkImageToNeighborhoodSampleAdaptor.h.
Self
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::Self = ImageToNeighborhoodSampleAdaptor
Standard class type aliases
Definition at line 62 of file itkImageToNeighborhoodSampleAdaptor.h.
SizeType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::SizeType = typename ImageType::SizeType
Definition at line 86 of file itkImageToNeighborhoodSampleAdaptor.h.
Superclass
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::Superclass = ListSample<std::vector<ConstNeighborhoodIterator<TImage, TBoundaryCondition> >>
Definition at line 64 of file itkImageToNeighborhoodSampleAdaptor.h.
ValueType
template<typename TImage , typename TBoundaryCondition > using itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::ValueType = typename MeasurementVectorType::value_type
Definition at line 100 of file itkImageToNeighborhoodSampleAdaptor.h.
Constructor & Destructor Documentation
ImageToNeighborhoodSampleAdaptor()
template<typename TImage , typename TBoundaryCondition > itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::ImageToNeighborhoodSampleAdaptor () protected
~ImageToNeighborhoodSampleAdaptor()
template<typename TImage , typename TBoundaryCondition > itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::~ImageToNeighborhoodSampleAdaptor () override protected default
Member Function Documentation
Begin() [1/2]
template<typename TImage , typename TBoundaryCondition > Iterator itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::Begin () inline
returns an iterator that points to the beginning of the container
Definition at line 275 of file itkImageToNeighborhoodSampleAdaptor.h.
References itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GoToBegin().
Referenced by itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::ConstIterator::ConstIterator().
Begin() [2/2]
template<typename TImage , typename TBoundaryCondition > ConstIterator itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::Begin () const inline
returns an iterator that points to the beginning of the container
Definition at line 298 of file itkImageToNeighborhoodSampleAdaptor.h.
References itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GoToBegin().
End() [1/2]
template<typename TImage , typename TBoundaryCondition > Iterator itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::End () inline
returns an iterator that points to the end of the container
Definition at line 286 of file itkImageToNeighborhoodSampleAdaptor.h.
References itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GoToEnd().
End() [2/2]
template<typename TImage , typename TBoundaryCondition > ConstIterator itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::End () const inline
returns an iterator that points to the end of the container
Definition at line 309 of file itkImageToNeighborhoodSampleAdaptor.h.
References itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition >::GoToEnd().
GetFrequency()
template<typename TImage , typename TBoundaryCondition > AbsoluteFrequencyType itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::GetFrequency (InstanceIdentifier id) const override virtual
method to return frequency for a specified id
Implements itk::Statistics::Sample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >.
GetImage()
template<typename TImage , typename TBoundaryCondition > const TImage * itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::GetImage () const
Method to get the image
GetMeasurementVector()
template<typename TImage , typename TBoundaryCondition > const MeasurementVectorType & itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::GetMeasurementVector (InstanceIdentifier id) const override virtual
method to return measurement vector for a specified id
Implements itk::Statistics::Sample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >.
GetNameOfClass()
template<typename TImage , typename TBoundaryCondition > virtual const char * itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::Statistics::ListSample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >.
GetRadius()
template<typename TImage , typename TBoundaryCondition > NeighborhoodRadiusType itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::GetRadius () const
Method to get the radius
GetRegion()
template<typename TImage , typename TBoundaryCondition > RegionType itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::GetRegion () const
Method to get the region
GetTotalFrequency()
template<typename TImage , typename TBoundaryCondition > TotalAbsoluteFrequencyType itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::GetTotalFrequency () const override virtual
method to return the total frequency
Implements itk::Statistics::Sample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >.
GetUseImageRegion()
template<typename TImage , typename TBoundaryCondition > virtual bool itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::GetUseImageRegion () const virtual
Method to get UseImageRegion flag
New()
template<typename TImage , typename TBoundaryCondition > static Pointer itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::New () static
Method for creation through the object factory.
PrintSelf()
template<typename TImage , typename TBoundaryCondition > void itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from itk::DataObject.
SetImage()
template<typename TImage , typename TBoundaryCondition > void itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::SetImage (const TImage * image)
Method to set the image
SetRadius()
template<typename TImage , typename TBoundaryCondition > void itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::SetRadius (const NeighborhoodRadiusType & radius)
Method to set the radius
SetRegion()
template<typename TImage , typename TBoundaryCondition > void itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::SetRegion (const RegionType & region)
Method to set the region
SetUseImageRegion()
template<typename TImage , typename TBoundaryCondition > void itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::SetUseImageRegion (const bool flag)
Size()
template<typename TImage , typename TBoundaryCondition > InstanceIdentifier itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::Size () const override virtual
returns the number of measurement vectors in this container
Implements itk::Statistics::Sample< std::vector< ConstNeighborhoodIterator< TImage, TBoundaryCondition > > >.
UseImageRegionOn()
template<typename TImage , typename TBoundaryCondition > virtual void itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::UseImageRegionOn () virtual
Convenience methods to turn on/off the UseImageRegion flag
Member Data Documentation
m_Image
template<typename TImage , typename TBoundaryCondition > ImageConstPointer itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::m_Image private
Definition at line 325 of file itkImageToNeighborhoodSampleAdaptor.h.
m_InstanceIdentifierInternal
template<typename TImage , typename TBoundaryCondition > InstanceIdentifier itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::m_InstanceIdentifierInternal mutable private
Definition at line 327 of file itkImageToNeighborhoodSampleAdaptor.h.
m_MeasurementVectorInternal
template<typename TImage , typename TBoundaryCondition > MeasurementVectorType itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::m_MeasurementVectorInternal mutable private
Definition at line 326 of file itkImageToNeighborhoodSampleAdaptor.h.
m_NeighborIndexInternal
template<typename TImage , typename TBoundaryCondition > IndexType itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::m_NeighborIndexInternal mutable private
Definition at line 328 of file itkImageToNeighborhoodSampleAdaptor.h.
m_OffsetTable
template<typename TImage , typename TBoundaryCondition > OffsetTableType itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::m_OffsetTable private
Definition at line 332 of file itkImageToNeighborhoodSampleAdaptor.h.
m_Radius
template<typename TImage , typename TBoundaryCondition > NeighborhoodRadiusType itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::m_Radius private
Definition at line 329 of file itkImageToNeighborhoodSampleAdaptor.h.
m_Region
template<typename TImage , typename TBoundaryCondition > RegionType itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::m_Region private
Definition at line 330 of file itkImageToNeighborhoodSampleAdaptor.h.
m_UseImageRegion
template<typename TImage , typename TBoundaryCondition > bool itk::Statistics::ImageToNeighborhoodSampleAdaptor< TImage, TBoundaryCondition >::m_UseImageRegion { true } private
Definition at line 331 of file itkImageToNeighborhoodSampleAdaptor.h.
The documentation for this class was generated from the following file:
itkImageToNeighborhoodSampleAdaptor.h