ITK: itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry Class Reference
itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry Class Reference
Group Nonunit » Module ITKReview
#include <itkLabelGeometryImageFilter.h>
Detailed Description
template<typename TLabelImage, typename TIntensityImage = TLabelImage>
class itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry
Geometry stored per label.
Definition at line 161 of file itkLabelGeometryImageFilter.h.
Public Member Functions
LabelGeometry ()
Public Attributes
FixedArray< float, Self::ImageDimension > m_AxesLength
BoundingBoxType m_BoundingBox
LabelSizeType m_BoundingBoxSize
RealType m_BoundingBoxVolume
LabelPointType m_Centroid
RealType m_Eccentricity
VectorType m_Eigenvalues
MatrixType m_Eigenvectors
RealType m_Elongation
RealType m_FirstOrderCentralCrossMoment
SizeValueType m_FirstOrderRawCrossMoment
IndexArrayType m_FirstOrderRawMoments
AxesLengthType m_FirstOrderWeightedRawMoments
LabelPixelType m_Label
RealType m_Orientation
LabelPointType m_OrientedBoundingBoxOrigin
LabelPointType m_OrientedBoundingBoxSize
BoundingBoxVerticesType m_OrientedBoundingBoxVertices
RealType m_OrientedBoundingBoxVolume
IntensityImageType::Pointer m_OrientedIntensityImage
LabelImageType::Pointer m_OrientedLabelImage
LabelIndicesType m_PixelIndices
MatrixType m_RotationMatrix
MatrixType m_SecondOrderCentralMoments
MatrixType m_SecondOrderRawMoments
RealType m_Sum
LabelPointType m_WeightedCentroid
SizeValueType m_ZeroOrderMoment
Constructor & Destructor Documentation
LabelGeometry()
template<typename TLabelImage , typename TIntensityImage = TLabelImage> itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::LabelGeometry () inline
Definition at line 165 of file itkLabelGeometryImageFilter.h.
References itk::NumericTraits< T >::max(), New(), and itk::NumericTraits< T >::NonpositiveMin().
Member Data Documentation
m_AxesLength
template<typename TLabelImage , typename TIntensityImage = TLabelImage> FixedArray<float, Self::ImageDimension> itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_AxesLength
Definition at line 233 of file itkLabelGeometryImageFilter.h.
m_BoundingBox
template<typename TLabelImage , typename TIntensityImage = TLabelImage> BoundingBoxType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_BoundingBox
Definition at line 237 of file itkLabelGeometryImageFilter.h.
m_BoundingBoxSize
template<typename TLabelImage , typename TIntensityImage = TLabelImage> LabelSizeType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_BoundingBoxSize
Definition at line 238 of file itkLabelGeometryImageFilter.h.
m_BoundingBoxVolume
template<typename TLabelImage , typename TIntensityImage = TLabelImage> RealType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_BoundingBoxVolume
Definition at line 239 of file itkLabelGeometryImageFilter.h.
m_Centroid
template<typename TLabelImage , typename TIntensityImage = TLabelImage> LabelPointType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_Centroid
Definition at line 222 of file itkLabelGeometryImageFilter.h.
m_Eccentricity
template<typename TLabelImage , typename TIntensityImage = TLabelImage> RealType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_Eccentricity
Definition at line 234 of file itkLabelGeometryImageFilter.h.
m_Eigenvalues
template<typename TLabelImage , typename TIntensityImage = TLabelImage> VectorType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_Eigenvalues
Definition at line 231 of file itkLabelGeometryImageFilter.h.
m_Eigenvectors
template<typename TLabelImage , typename TIntensityImage = TLabelImage> MatrixType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_Eigenvectors
Definition at line 232 of file itkLabelGeometryImageFilter.h.
m_Elongation
template<typename TLabelImage , typename TIntensityImage = TLabelImage> RealType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_Elongation
Definition at line 235 of file itkLabelGeometryImageFilter.h.
m_FirstOrderCentralCrossMoment
template<typename TLabelImage , typename TIntensityImage = TLabelImage> RealType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_FirstOrderCentralCrossMoment
Definition at line 228 of file itkLabelGeometryImageFilter.h.
m_FirstOrderRawCrossMoment
template<typename TLabelImage , typename TIntensityImage = TLabelImage> SizeValueType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_FirstOrderRawCrossMoment
Definition at line 227 of file itkLabelGeometryImageFilter.h.
m_FirstOrderRawMoments
template<typename TLabelImage , typename TIntensityImage = TLabelImage> IndexArrayType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_FirstOrderRawMoments
Definition at line 225 of file itkLabelGeometryImageFilter.h.
m_FirstOrderWeightedRawMoments
template<typename TLabelImage , typename TIntensityImage = TLabelImage> AxesLengthType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_FirstOrderWeightedRawMoments
Definition at line 226 of file itkLabelGeometryImageFilter.h.
m_Label
template<typename TLabelImage , typename TIntensityImage = TLabelImage> LabelPixelType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_Label
Definition at line 220 of file itkLabelGeometryImageFilter.h.
m_Orientation
template<typename TLabelImage , typename TIntensityImage = TLabelImage> RealType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_Orientation
Definition at line 236 of file itkLabelGeometryImageFilter.h.
m_OrientedBoundingBoxOrigin
template<typename TLabelImage , typename TIntensityImage = TLabelImage> LabelPointType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_OrientedBoundingBoxOrigin
Definition at line 247 of file itkLabelGeometryImageFilter.h.
m_OrientedBoundingBoxSize
template<typename TLabelImage , typename TIntensityImage = TLabelImage> LabelPointType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_OrientedBoundingBoxSize
Definition at line 243 of file itkLabelGeometryImageFilter.h.
m_OrientedBoundingBoxVertices
template<typename TLabelImage , typename TIntensityImage = TLabelImage> BoundingBoxVerticesType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_OrientedBoundingBoxVertices
Definition at line 241 of file itkLabelGeometryImageFilter.h.
m_OrientedBoundingBoxVolume
template<typename TLabelImage , typename TIntensityImage = TLabelImage> RealType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_OrientedBoundingBoxVolume
Definition at line 242 of file itkLabelGeometryImageFilter.h.
m_OrientedIntensityImage
template<typename TLabelImage , typename TIntensityImage = TLabelImage> IntensityImageType::Pointer itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_OrientedIntensityImage
Definition at line 245 of file itkLabelGeometryImageFilter.h.
m_OrientedLabelImage
template<typename TLabelImage , typename TIntensityImage = TLabelImage> LabelImageType::Pointer itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_OrientedLabelImage
Definition at line 244 of file itkLabelGeometryImageFilter.h.
m_PixelIndices
template<typename TLabelImage , typename TIntensityImage = TLabelImage> LabelIndicesType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_PixelIndices
Definition at line 240 of file itkLabelGeometryImageFilter.h.
m_RotationMatrix
template<typename TLabelImage , typename TIntensityImage = TLabelImage> MatrixType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_RotationMatrix
Definition at line 246 of file itkLabelGeometryImageFilter.h.
m_SecondOrderCentralMoments
template<typename TLabelImage , typename TIntensityImage = TLabelImage> MatrixType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_SecondOrderCentralMoments
Definition at line 230 of file itkLabelGeometryImageFilter.h.
m_SecondOrderRawMoments
template<typename TLabelImage , typename TIntensityImage = TLabelImage> MatrixType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_SecondOrderRawMoments
Definition at line 229 of file itkLabelGeometryImageFilter.h.
m_Sum
template<typename TLabelImage , typename TIntensityImage = TLabelImage> RealType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_Sum
Definition at line 221 of file itkLabelGeometryImageFilter.h.
m_WeightedCentroid
template<typename TLabelImage , typename TIntensityImage = TLabelImage> LabelPointType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_WeightedCentroid
Definition at line 223 of file itkLabelGeometryImageFilter.h.
m_ZeroOrderMoment
template<typename TLabelImage , typename TIntensityImage = TLabelImage> SizeValueType itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::LabelGeometry::m_ZeroOrderMoment
Definition at line 224 of file itkLabelGeometryImageFilter.h.
The documentation for this class was generated from the following file:
itkLabelGeometryImageFilter.h