ITK: itk::ImageFunction< TInputImage, TOutput, TCoordinate > Class Template Reference
itk::ImageFunction< TInputImage, TOutput, TCoordinate > Class Template Reference abstract
Data Processing Objects » Functions » Image Functions | Group Core » Module ITKImageFunction
#include <itkImageFunction.h>
Detailed Description
template<typename TInputImage, typename TOutput, typename TCoordinate = float>
class itk::ImageFunction< TInputImage, TOutput, TCoordinate >
Evaluates a function of an image at specified position.
ImageFunction is a baseclass for all objects that evaluates a function of an image at index, continuous index or point. This class is templated over the input image type, the type of the function output and the coordinate representation type (e.g. float or double).
The input image is set via method SetInputImage(). Methods Evaluate, EvaluateAtIndex and EvaluateAtContinuousIndex respectively evaluates the function at an geometric point, image index and continuous image index.
Warning
Image BufferedRegion information is cached during in SetInputImage(image). If the image BufferedRegion has changed one must call SetInputImage(image) again to update the cache to the current values.
See also
Point
Index
ContinuousIndex
Definition at line 55 of file itkImageFunction.h.
Public Types
using ConstPointer = SmartPointer< const Self >
using ContinuousIndexType = ContinuousIndex< TCoordinate, Self::ImageDimension >
using CoordRepType = TCoordinate
using IndexType = typename InputImageType::IndexType
using IndexValueType = typename InputImageType::IndexValueType
using InputImageConstPointer = typename InputImageType::ConstPointer
using InputImageType = TInputImage
using InputPixelType = typename InputImageType::PixelType
using OutputType = TOutput
using Pointer = SmartPointer< Self >
using PointType = Point< TCoordinate, Self::ImageDimension >
using Self = ImageFunction
using Superclass = FunctionBase< Point< TCoordinate, Self::ImageDimension >, TOutput >
Public Types inherited from itk::FunctionBase< Point< float, TInputImage::ImageDimension >, TOutput >
using ConstPointer = SmartPointer< const Self >
using InputType = Point< float, TInputImage::ImageDimension >
using OutputType = TOutput
using Pointer = SmartPointer< Self >
using Self = FunctionBase
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
void ConvertContinuousIndexToNearestIndex (const ContinuousIndexType &cindex, IndexType &index) const
void ConvertPointToContinuousIndex (const PointType &point, ContinuousIndexType &cindex) const
OutputType Evaluate (const PointType &point) const override=0
virtual TOutput EvaluateAtContinuousIndex (const ContinuousIndexType &index) const =0
virtual TOutput EvaluateAtIndex (const IndexType &index) const =0
virtual const ContinuousIndexType & GetEndContinuousIndex () const
virtual const IndexType & GetEndIndex () const
const InputImageType * GetInputImage () const
const char * GetNameOfClass () const override
virtual const ContinuousIndexType & GetStartContinuousIndex () const
virtual const IndexType & GetStartIndex () const
virtual void SetInputImage (const InputImageType *ptr)
virtual bool IsInsideBuffer (const IndexType &index) const
virtual bool IsInsideBuffer (const ContinuousIndexType &index) const
virtual bool IsInsideBuffer (const PointType &point) const
void ConvertPointToNearestIndex (const PointType &point, IndexType &index) const
Public Member Functions inherited from itk::FunctionBase< Point< float, TInputImage::ImageDimension >, TOutput >
virtual OutputType Evaluate (const InputType &input) const=0
const char * GetNameOfClass () const override
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *cmd) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
const char * GetNameOfClass () const override
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag) const
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual Pointer CreateAnother () const
virtual void Delete ()
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
virtual void Register () const
virtual void SetReferenceCount (int)
virtual void UnRegister () const noexcept
Static Public Attributes
static constexpr unsigned int ImageDimension = TInputImage::ImageDimension
Protected Member Functions
ImageFunction ()
void PrintSelf (std::ostream &os, Indent indent) const override
~ImageFunction () override=default
Protected Member Functions inherited from itk::FunctionBase< Point< float, TInputImage::ImageDimension >, TOutput >
FunctionBase ()=default
~FunctionBase () override=default
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
void PrintSelf (std::ostream &os, Indent indent) const override
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintSelf (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Protected Attributes
ContinuousIndexType m_EndContinuousIndex {}
IndexType m_EndIndex {}
InputImageConstPointer m_Image {}
ContinuousIndexType m_StartContinuousIndex {}
IndexType m_StartIndex {}
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount {}
Additional Inherited Members
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Member Typedef Documentation
ConstPointer
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::ConstPointer = SmartPointer<const Self>
Definition at line 69 of file itkImageFunction.h.
ContinuousIndexType
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::ContinuousIndexType = ContinuousIndex<TCoordinate, Self::ImageDimension>
ContinuousIndex Type.
Definition at line 94 of file itkImageFunction.h.
CoordRepType
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::CoordRepType = TCoordinate
CoordRepType type alias support
Definition at line 87 of file itkImageFunction.h.
IndexType
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::IndexType = typename InputImageType::IndexType
Index Type.
Definition at line 90 of file itkImageFunction.h.
IndexValueType
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::IndexValueType = typename InputImageType::IndexValueType
Definition at line 91 of file itkImageFunction.h.
InputImageConstPointer
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::InputImageConstPointer = typename InputImageType::ConstPointer
InputImagePointer type alias support
Definition at line 81 of file itkImageFunction.h.
InputImageType
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::InputImageType = TInputImage
InputImageType type alias support
Definition at line 75 of file itkImageFunction.h.
InputPixelType
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::InputPixelType = typename InputImageType::PixelType
InputPixel type alias support
Definition at line 78 of file itkImageFunction.h.
OutputType
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::OutputType = TOutput
OutputType type alias support
Definition at line 84 of file itkImageFunction.h.
Pointer
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::Pointer = SmartPointer<Self>
Definition at line 68 of file itkImageFunction.h.
PointType
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::PointType = Point<TCoordinate, Self::ImageDimension>
Point Type.
Definition at line 97 of file itkImageFunction.h.
Self
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::Self = ImageFunction
Standard class type aliases.
Definition at line 64 of file itkImageFunction.h.
Superclass
template<typename TInputImage , typename TOutput , typename TCoordinate = float> using itk::ImageFunction< TInputImage, TOutput, TCoordinate >::Superclass = FunctionBase<Point<TCoordinate, Self::ImageDimension>, TOutput>
Definition at line 66 of file itkImageFunction.h.
Constructor & Destructor Documentation
ImageFunction()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> itk::ImageFunction< TInputImage, TOutput, TCoordinate >::ImageFunction () protected
~ImageFunction()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> itk::ImageFunction< TInputImage, TOutput, TCoordinate >::~ImageFunction () override protected default
Member Function Documentation
ConvertContinuousIndexToNearestIndex()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> void itk::ImageFunction< TInputImage, TOutput, TCoordinate >::ConvertContinuousIndexToNearestIndex (const ContinuousIndexType & cindex, IndexType & index) const inline
Convert continuous index to nearest index.
Definition at line 203 of file itkImageFunction.h.
ConvertPointToContinuousIndex()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> void itk::ImageFunction< TInputImage, TOutput, TCoordinate >::ConvertPointToContinuousIndex (const PointType & point, ContinuousIndexType & cindex) const inline
Convert point to continuous index
Definition at line 196 of file itkImageFunction.h.
References itk::point().
ConvertPointToNearestIndex()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> void itk::ImageFunction< TInputImage, TOutput, TCoordinate >::ConvertPointToNearestIndex (const PointType & point, IndexType & index) const inline
Convert point to nearest index.
Definition at line 187 of file itkImageFunction.h.
References itk::point().
Evaluate()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> OutputType itk::ImageFunction< TInputImage, TOutput, TCoordinate >::Evaluate (const PointType & point) const override pure virtual
Evaluate the function at specified Point position. Subclasses must provide this method.
Implements itk::FunctionBase< Point< float, TInputImage::ImageDimension >, TOutput >.
Implemented in itk::NeighborhoodOperatorImageFunction< TInputImage, TOutput >, itk::BSplineControlPointImageFunction< TInputImage, TCoordinate >, itk::BinaryThresholdImageFunction< TInputImage, TCoordinate >, itk::BinaryThresholdImageFunction< TInputImage, float >, itk::BSplineInterpolateImageFunction< TImageType, TCoordinate, TCoefficientType >, itk::BSplineInterpolateImageFunction< TImageType, float, TImageType::PixelType >, itk::CentralDifferenceImageFunction< TInputImage, TCoordinate, TOutputType >, itk::CovarianceImageFunction< TInputImage, TCoordinate >, itk::ExtrapolateImageFunction< TInputImage, TCoordinate >, itk::ExtrapolateImageFunction< TInputImage, float >, itk::GaussianBlurImageFunction< TInputImage, TOutput >, itk::InterpolateImageFunction< TInputImage, TCoordinate >, itk::InterpolateImageFunction< TImageType, double >, itk::InterpolateImageFunction< TImageType, float >, itk::InterpolateImageFunction< TInputImage, double >, itk::MahalanobisDistanceThresholdImageFunction< TInputImage, TCoordinate >, itk::MeanImageFunction< TInputImage, TCoordinate >, itk::MedianImageFunction< TInputImage, TCoordinate >, itk::NeighborhoodBinaryThresholdImageFunction< TInputImage, TCoordinate >, itk::RayCastInterpolateImageFunction< TInputImage, TCoordinate >, itk::ScatterMatrixImageFunction< TInputImage, TCoordinate >, itk::SumOfSquaresImageFunction< TInputImage, TCoordinate >, itk::VarianceImageFunction< TInputImage, TCoordinate >, itk::VectorInterpolateImageFunction< TInputImage, TCoordinate >, itk::VectorInterpolateImageFunction< TInputImage, double >, itk::VectorInterpolateImageFunction< TInputImage, float >, itk::VectorMeanImageFunction< TInputImage, TCoordinate >, itk::DiscreteGaussianDerivativeImageFunction< TInputImage, TOutput >, itk::DiscreteGradientMagnitudeGaussianImageFunction< TInputImage, TOutput >, and itk::DiscreteHessianGaussianImageFunction< TInputImage, TOutput >.
EvaluateAtContinuousIndex()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> virtual TOutput itk::ImageFunction< TInputImage, TOutput, TCoordinate >::EvaluateAtContinuousIndex (const ContinuousIndexType & index) const pure virtual
Evaluate the function at specified ContinuousIndex position. Subclasses must provide this method.
Implemented in itk::NeighborhoodOperatorImageFunction< TInputImage, TOutput >, itk::BSplineControlPointImageFunction< TInputImage, TCoordinate >, itk::CentralDifferenceImageFunction< TInputImage, TCoordinate, TOutputType >, itk::CovarianceImageFunction< TInputImage, TCoordinate >, itk::GaussianBlurImageFunction< TInputImage, TOutput >, itk::GaussianInterpolateImageFunction< TInputImage, TCoordinate >, itk::GaussianInterpolateImageFunction< TInputImage, double >, itk::LabelImageGaussianInterpolateImageFunction< TInputImage, TCoordinate, TPixelCompare >, itk::MeanImageFunction< TInputImage, TCoordinate >, itk::MedianImageFunction< TInputImage, TCoordinate >, itk::NeighborhoodBinaryThresholdImageFunction< TInputImage, TCoordinate >, itk::ScatterMatrixImageFunction< TInputImage, TCoordinate >, itk::SumOfSquaresImageFunction< TInputImage, TCoordinate >, itk::VarianceImageFunction< TInputImage, TCoordinate >, itk::VectorMeanImageFunction< TInputImage, TCoordinate >, itk::BinaryThresholdImageFunction< TInputImage, TCoordinate >, itk::BinaryThresholdImageFunction< TInputImage, float >, itk::BSplineInterpolateImageFunction< TImageType, TCoordinate, TCoefficientType >, itk::BSplineInterpolateImageFunction< TImageType, float, TImageType::PixelType >, itk::LinearInterpolateImageFunction< TInputImage, TCoordinate >, itk::MahalanobisDistanceThresholdImageFunction< TInputImage, TCoordinate >, itk::NearestNeighborExtrapolateImageFunction< TInputImage, TCoordinate >, itk::NearestNeighborInterpolateImageFunction< TInputImage, TCoordinate >, itk::RayCastInterpolateImageFunction< TInputImage, TCoordinate >, itk::VectorLinearInterpolateImageFunction< TInputImage, TCoordinate >, itk::VectorLinearInterpolateNearestNeighborExtrapolateImageFunction< TInputImage, TCoordinate >, itk::VectorNearestNeighborInterpolateImageFunction< TInputImage, TCoordinate >, itk::WindowedSincInterpolateImageFunction< TInputImage, VRadius, TWindowFunction, TBoundaryCondition, TCoordinate >, itk::ComplexBSplineInterpolateImageFunction< TImageType, TCoordinate, TCoefficientType >, itk::DiscreteGaussianDerivativeImageFunction< TInputImage, TOutput >, itk::DiscreteGradientMagnitudeGaussianImageFunction< TInputImage, TOutput >, itk::DiscreteHessianGaussianImageFunction< TInputImage, TOutput >, itk::ExtrapolateImageFunction< TInputImage, TCoordinate >, itk::ExtrapolateImageFunction< TInputImage, float >, itk::InterpolateImageFunction< TInputImage, TCoordinate >, itk::InterpolateImageFunction< TImageType, double >, itk::InterpolateImageFunction< TImageType, float >, itk::InterpolateImageFunction< TInputImage, double >, itk::VectorInterpolateImageFunction< TInputImage, TCoordinate >, itk::VectorInterpolateImageFunction< TInputImage, double >, and itk::VectorInterpolateImageFunction< TInputImage, float >.
EvaluateAtIndex()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> virtual TOutput itk::ImageFunction< TInputImage, TOutput, TCoordinate >::EvaluateAtIndex (const IndexType & index) const pure virtual
Evaluate the function at specified Index position. Subclasses must provide this method.
Implemented in itk::BSplineControlPointImageFunction< TInputImage, TCoordinate >, itk::BinaryThresholdImageFunction< TInputImage, TCoordinate >, itk::BinaryThresholdImageFunction< TInputImage, float >, itk::CentralDifferenceImageFunction< TInputImage, TCoordinate, TOutputType >, itk::CovarianceImageFunction< TInputImage, TCoordinate >, itk::GaussianBlurImageFunction< TInputImage, TOutput >, itk::GaussianDerivativeImageFunction< TInputImage, TOutput >, itk::InterpolateImageFunction< TInputImage, TCoordinate >, itk::InterpolateImageFunction< TImageType, double >, itk::InterpolateImageFunction< TImageType, float >, itk::InterpolateImageFunction< TInputImage, double >, itk::MahalanobisDistanceThresholdImageFunction< TInputImage, TCoordinate >, itk::MeanImageFunction< TInputImage, TCoordinate >, itk::MedianImageFunction< TInputImage, TCoordinate >, itk::NearestNeighborExtrapolateImageFunction< TInputImage, TCoordinate >, itk::NeighborhoodBinaryThresholdImageFunction< TInputImage, TCoordinate >, itk::NeighborhoodOperatorImageFunction< TInputImage, TOutput >, itk::ScatterMatrixImageFunction< TInputImage, TCoordinate >, itk::SumOfSquaresImageFunction< TInputImage, TCoordinate >, itk::VarianceImageFunction< TInputImage, TCoordinate >, itk::VectorInterpolateImageFunction< TInputImage, TCoordinate >, itk::VectorInterpolateImageFunction< TInputImage, double >, itk::VectorInterpolateImageFunction< TInputImage, float >, itk::VectorLinearInterpolateNearestNeighborExtrapolateImageFunction< TInputImage, TCoordinate >, itk::VectorMeanImageFunction< TInputImage, TCoordinate >, itk::DiscreteGaussianDerivativeImageFunction< TInputImage, TOutput >, itk::DiscreteGradientMagnitudeGaussianImageFunction< TInputImage, TOutput >, itk::DiscreteHessianGaussianImageFunction< TInputImage, TOutput >, itk::ExtrapolateImageFunction< TInputImage, TCoordinate >, and itk::ExtrapolateImageFunction< TInputImage, float >.
GetEndContinuousIndex()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> virtual const ContinuousIndexType & itk::ImageFunction< TInputImage, TOutput, TCoordinate >::GetEndContinuousIndex () const virtual
GetEndIndex()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> virtual const IndexType & itk::ImageFunction< TInputImage, TOutput, TCoordinate >::GetEndIndex () const virtual
GetInputImage()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> const InputImageType * itk::ImageFunction< TInputImage, TOutput, TCoordinate >::GetInputImage () const inline
Get the input image.
Definition at line 108 of file itkImageFunction.h.
GetNameOfClass()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> const char * itk::ImageFunction< TInputImage, TOutput, TCoordinate >::GetNameOfClass () const override virtual
See also
LightObject::GetNameOfClass()
Reimplemented from itk::Object.
Reimplemented in itk::InterpolateImageFunction< TImageType, double >, itk::InterpolateImageFunction< TImageType, float >, itk::InterpolateImageFunction< TInputImage, double >, itk::NeighborhoodOperatorImageFunction< TInputImage, TOutput >, itk::VectorInterpolateImageFunction< TInputImage, double >, and itk::VectorInterpolateImageFunction< TInputImage, float >.
GetStartContinuousIndex()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> virtual const ContinuousIndexType & itk::ImageFunction< TInputImage, TOutput, TCoordinate >::GetStartContinuousIndex () const virtual
GetStartIndex()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> virtual const IndexType & itk::ImageFunction< TInputImage, TOutput, TCoordinate >::GetStartIndex () const virtual
IsInsideBuffer() [1/3]
template<typename TInputImage , typename TOutput , typename TCoordinate = float> virtual bool itk::ImageFunction< TInputImage, TOutput, TCoordinate >::IsInsideBuffer (const ContinuousIndexType & index) const inline virtual
Check if a continuous index is inside the image buffer.
Warning
For efficiency, no validity checking of the input image is done.
Reimplemented in itk::RayCastInterpolateImageFunction< TInputImage, TCoordinate >, and itk::VectorLinearInterpolateNearestNeighborExtrapolateImageFunction< TInputImage, TCoordinate >.
Definition at line 156 of file itkImageFunction.h.
IsInsideBuffer() [2/3]
template<typename TInputImage , typename TOutput , typename TCoordinate = float> virtual bool itk::ImageFunction< TInputImage, TOutput, TCoordinate >::IsInsideBuffer (const IndexType & index) const inline virtual
Check if an index is inside the image buffer. We take into account the fact that each voxel has its center at the integer coordinate and extends half way to the next integer coordinate.
Warning
For efficiency, no validity checking of the input image is done.
Reimplemented in itk::RayCastInterpolateImageFunction< TInputImage, TCoordinate >, and itk::VectorLinearInterpolateNearestNeighborExtrapolateImageFunction< TInputImage, TCoordinate >.
Definition at line 135 of file itkImageFunction.h.
IsInsideBuffer() [3/3]
template<typename TInputImage , typename TOutput , typename TCoordinate = float> virtual bool itk::ImageFunction< TInputImage, TOutput, TCoordinate >::IsInsideBuffer (const PointType & point) const inline virtual
Check if a point is inside the image buffer.
Warning
For efficiency, no validity checking of the input image pointer is done.
Reimplemented in itk::RayCastInterpolateImageFunction< TInputImage, TCoordinate >, and itk::VectorLinearInterpolateNearestNeighborExtrapolateImageFunction< TInputImage, TCoordinate >.
Definition at line 174 of file itkImageFunction.h.
References itk::point().
PrintSelf()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> void itk::ImageFunction< TInputImage, TOutput, TCoordinate >::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from itk::Object.
Reimplemented in itk::InterpolateImageFunction< TImageType, double >, itk::InterpolateImageFunction< TImageType, float >, itk::InterpolateImageFunction< TInputImage, double >, and itk::NeighborhoodOperatorImageFunction< TInputImage, TOutput >.
SetInputImage()
template<typename TInputImage , typename TOutput , typename TCoordinate = float> virtual void itk::ImageFunction< TInputImage, TOutput, TCoordinate >::SetInputImage (const InputImageType * ptr) virtual
Set the input image.
Warning
this method caches BufferedRegion information. If the BufferedRegion has changed, user must call SetInputImage again to update cached values.
Reimplemented in itk::WindowedSincInterpolateImageFunction< TInputImage, VRadius, TWindowFunction, TBoundaryCondition, TCoordinate >, itk::BSplineControlPointImageFunction< TInputImage, TCoordinate >, itk::GaussianBlurImageFunction< TInputImage, TOutput >, itk::GaussianDerivativeImageFunction< TInputImage, TOutput >, itk::DiscreteGaussianDerivativeImageFunction< TInputImage, TOutput >, itk::DiscreteGradientMagnitudeGaussianImageFunction< TInputImage, TOutput >, itk::DiscreteHessianGaussianImageFunction< TInputImage, TOutput >, itk::BSplineInterpolateImageFunction< TImageType, TCoordinate, TCoefficientType >, itk::BSplineInterpolateImageFunction< TImageType, float, TImageType::PixelType >, itk::BSplineResampleImageFunction< TImageType, TCoordinate >, itk::ComplexBSplineInterpolateImageFunction< TImageType, TCoordinate, TCoefficientType >, itk::GaussianInterpolateImageFunction< TInputImage, TCoordinate >, itk::GaussianInterpolateImageFunction< TInputImage, double >, and itk::CentralDifferenceImageFunction< TInputImage, TCoordinate, TOutputType >.
Member Data Documentation
ImageDimension
template<typename TInputImage , typename TOutput , typename TCoordinate = float> constexpr unsigned int itk::ImageFunction< TInputImage, TOutput, TCoordinate >::ImageDimension = TInputImage::ImageDimension static constexpr
Dimension underlying input image.
Definition at line 61 of file itkImageFunction.h.
m_EndContinuousIndex
template<typename TInputImage , typename TOutput , typename TCoordinate = float> ContinuousIndexType itk::ImageFunction< TInputImage, TOutput, TCoordinate >::m_EndContinuousIndex {} protected
Definition at line 228 of file itkImageFunction.h.
m_EndIndex
template<typename TInputImage , typename TOutput , typename TCoordinate = float> IndexType itk::ImageFunction< TInputImage, TOutput, TCoordinate >::m_EndIndex {} protected
Definition at line 225 of file itkImageFunction.h.
m_Image
template<typename TInputImage , typename TOutput , typename TCoordinate = float> InputImageConstPointer itk::ImageFunction< TInputImage, TOutput, TCoordinate >::m_Image {} protected
Const pointer to the input image.
Definition at line 221 of file itkImageFunction.h.
m_StartContinuousIndex
template<typename TInputImage , typename TOutput , typename TCoordinate = float> ContinuousIndexType itk::ImageFunction< TInputImage, TOutput, TCoordinate >::m_StartContinuousIndex {} protected
Definition at line 227 of file itkImageFunction.h.
m_StartIndex
template<typename TInputImage , typename TOutput , typename TCoordinate = float> IndexType itk::ImageFunction< TInputImage, TOutput, TCoordinate >::m_StartIndex {} protected
Cache some values for testing if indices are inside buffered region.
Definition at line 224 of file itkImageFunction.h.
The documentation for this class was generated from the following file:
itkImageFunction.h