ITK: itk::Statistics::MersenneTwisterRandomVariateGenerator Class Reference
itk::Statistics::MersenneTwisterRandomVariateGenerator Class Reference
Group Core » Module ITKCommon
#include <itkMersenneTwisterRandomVariateGenerator.h>
Detailed Description
MersenneTwisterRandom random variate generator.
It is recommended to create a separate object in each thread. By default, each instantiated class will have a different seed created by the GetNextSeed method. The creation of the initial seeds are initialized once from the time. For deterministic behavior, the individual instances' seeds should be manual set to separate values in each thread.
It is no longer recommended to use this class using a "Singleton-like" GetInstance method for the global instance of this class. This usage may result in unsafe concurrent access to the global instance.
Warning
This class's instance methods are NEITHER reentrant nor concurrent thread-safe, except where marked as thread-safe. That is to say you can still use separate objects concurrently.
This notice was included with the original implementation. The only changes made were to obfuscate the author's email addresses.
MersenneTwister.h Mersenne Twister random number generator – a C++ class MTRand Based on code by Makoto Matsumoto, Takuji Nishimura, and Shawn Cokus Richard J. Wagner v1.0 15 May 2003 rjwagner at writeme dot com
The Mersenne Twister is an algorithm for generating random numbers. It was designed with consideration of the flaws in various other generators. The period, 2^19937-1, and the order of equidistribution, 623 dimensions, are far greater. The generator is also fast; it avoids multiplication and division, and it benefits from caches and pipelines. For more information see the inventors' web page at http:*www.math.keio.ac.jp/~matumoto/emt.html
Reference M. Matsumoto and T. Nishimura, "Mersenne Twister: A 623-Dimensionally Equidistributed Uniform Pseudo-Random Number Generator", ACM Transactions on Modeling and Computer Simulation, Vol. 8, No. 1, January 1998, pp 3-30.
Copyright (C) 1997 - 2002, Makoto Matsumoto and Takuji Nishimura, Copyright (C) 2000 - 2003, Richard J. Wagner All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
The names of its contributors may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The original code included the following notice:
When you use this, send an email to: matumoto at math dot keio dot ac dot jp
with an appropriate reference to your work.
It would be nice to CC: rjwagner at writeme dot com and Cokus at math dot washington dot edu when you write.
ITK Sphinx Examples:
<a href=
<a href=
Definition at line 127 of file itkMersenneTwisterRandomVariateGenerator.h.
Public Types
using ConstPointer = SmartPointer< const Self >
using IntegerType = uint32_t
using Pointer = SmartPointer< Self >
using Self = MersenneTwisterRandomVariateGenerator
using Superclass = RandomVariateGeneratorBase
Public Types inherited from itk::Statistics::RandomVariateGeneratorBase
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = RandomVariateGeneratorBase
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
IntegerType GetIntegerVariate (const IntegerType &n)
const char * GetNameOfClass () const override
IntegerType GetSeed () const
double GetUniformVariate (const double a, const double b)
double GetVariate () override
double GetVariateWithClosedRange ()
double GetVariateWithClosedRange (const double n)
double GetVariateWithOpenRange ()
double GetVariateWithOpenRange (const double n)
double GetVariateWithOpenUpperRange ()
double GetVariateWithOpenUpperRange (const double n)
void Initialize ()
void Initialize (const IntegerType seed)
double operator() ()
IntegerType GetIntegerVariate ()
double Get53BitVariate ()
double GetNormalVariate (const double mean=0.0, const double variance=1.0)
void SetSeed (const IntegerType oneSeed)
void SetSeed ()
Public Member Functions inherited from itk::Statistics::RandomVariateGeneratorBase
const char * GetNameOfClass () const override
virtual double GetVariate ()=0
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *cmd) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
const char * GetNameOfClass () const override
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag) const
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual Pointer CreateAnother () const
virtual void Delete ()
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
virtual void Register () const
virtual void SetReferenceCount (int)
virtual void UnRegister () const noexcept
Static Public Member Functions
static Pointer GetInstance ()
static IntegerType GetNextSeed ()
static Pointer New ()
static void ResetNextSeed ()
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Static Public Attributes
static constexpr IntegerType StateVectorLength = 624
Protected Member Functions
IntegerType hiBit (const IntegerType &u) const
IntegerType loBit (const IntegerType &u) const
IntegerType loBits (const IntegerType &u) const
MersenneTwisterRandomVariateGenerator ()
IntegerType mixBits (const IntegerType &u, const IntegerType &v) const
void PrintSelf (std::ostream &os, Indent indent) const override
void reload ()
IntegerType twist (const IntegerType &m, const IntegerType &s0, const IntegerType &s1) const
~MersenneTwisterRandomVariateGenerator () override
Protected Member Functions inherited from itk::Statistics::RandomVariateGeneratorBase
RandomVariateGeneratorBase ()
~RandomVariateGeneratorBase () override
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
void PrintSelf (std::ostream &os, Indent indent) const override
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintSelf (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Static Protected Member Functions
static IntegerType hash (time_t t, clock_t c)
Protected Attributes
int m_Left {}
IntegerType * m_PNext {}
std::atomic< IntegerType > m_Seed {}
IntegerType state [StateVectorLength]
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount {}
Static Protected Attributes
static constexpr unsigned int M = 397
Private Member Functions
itkGetGlobalDeclarationMacro (MersenneTwisterGlobals, PimplGlobals)
Static Private Member Functions
static Pointer CreateInstance ()
Private Attributes
std::mutex m_InstanceMutex {}
Static Private Attributes
static MersenneTwisterGlobals * m_PimplGlobals
Member Typedef Documentation
ConstPointer
using itk::Statistics::MersenneTwisterRandomVariateGenerator::ConstPointer = SmartPointer<const Self>
Definition at line 134 of file itkMersenneTwisterRandomVariateGenerator.h.
IntegerType
using itk::Statistics::MersenneTwisterRandomVariateGenerator::IntegerType = uint32_t
Definition at line 136 of file itkMersenneTwisterRandomVariateGenerator.h.
Pointer
using itk::Statistics::MersenneTwisterRandomVariateGenerator::Pointer = SmartPointer<Self>
Definition at line 133 of file itkMersenneTwisterRandomVariateGenerator.h.
Self
using itk::Statistics::MersenneTwisterRandomVariateGenerator::Self = MersenneTwisterRandomVariateGenerator
Standard class type aliases.
Definition at line 131 of file itkMersenneTwisterRandomVariateGenerator.h.
Superclass
using itk::Statistics::MersenneTwisterRandomVariateGenerator::Superclass = RandomVariateGeneratorBase
Definition at line 132 of file itkMersenneTwisterRandomVariateGenerator.h.
Constructor & Destructor Documentation
MersenneTwisterRandomVariateGenerator()
itk::Statistics::MersenneTwisterRandomVariateGenerator::MersenneTwisterRandomVariateGenerator () protected
~MersenneTwisterRandomVariateGenerator()
itk::Statistics::MersenneTwisterRandomVariateGenerator::~MersenneTwisterRandomVariateGenerator () override protected
Member Function Documentation
CreateInstance()
static Pointer itk::Statistics::MersenneTwisterRandomVariateGenerator::CreateInstance () static private
Internal method to actually create a new object.
Get53BitVariate()
double itk::Statistics::MersenneTwisterRandomVariateGenerator::Get53BitVariate () inline
Access to 53-bit random numbers (capacity of IEEE double precision) in the range [0,1)
Definition at line 501 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetIntegerVariate().
GetInstance()
static Pointer itk::Statistics::MersenneTwisterRandomVariateGenerator::GetInstance () static
Return the global Mersenne Twister instance.
This method returns a Singleton of the Mersenne Twister. The seed is initialized from the wall clock at first use, but can be globally set using the resulting instance's SetSeed().
Note
This method is thread-safe.
Examples
Examples/RegistrationITKv4/DeformableRegistration13.cxx.
GetIntegerVariate() [1/2]
MersenneTwisterRandomVariateGenerator::IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::GetIntegerVariate () inline
Get an integer variate in [0, 2^32-1]
Definition at line 419 of file itkMersenneTwisterRandomVariateGenerator.h.
References m_Left, m_PNext, and reload().
Referenced by Get53BitVariate(), GetIntegerVariate(), GetVariateWithClosedRange(), GetVariateWithOpenRange(), and GetVariateWithOpenUpperRange().
GetIntegerVariate() [2/2]
MersenneTwisterRandomVariateGenerator::IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::GetIntegerVariate (const IntegerType & n) inline
Get an integer variate in [0, n] for n < 2^32
Definition at line 477 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetIntegerVariate().
GetNameOfClass()
const char * itk::Statistics::MersenneTwisterRandomVariateGenerator::GetNameOfClass () const override virtual
See also
LightObject::GetNameOfClass()
Reimplemented from itk::LightObject.
GetNextSeed()
static IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::GetNextSeed () static
Return the next seed, derived as a sequence from the seed of the singleton instance.
Note
This method is thread-safe.
GetNormalVariate()
double itk::Statistics::MersenneTwisterRandomVariateGenerator::GetNormalVariate (const double mean = 0.0, const double variance = 1.0) inline
Access to a normal random number distribution.
Definition at line 514 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetVariateWithOpenRange(), GetVariateWithOpenUpperRange(), and itk::Math::pi.
GetSeed()
MersenneTwisterRandomVariateGenerator::IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::GetSeed () const inline
Return the current seed
Note
This method is thread-safe.
Definition at line 412 of file itkMersenneTwisterRandomVariateGenerator.h.
References m_Seed.
GetUniformVariate()
double itk::Statistics::MersenneTwisterRandomVariateGenerator::GetUniformVariate (const double a, const double b) inline
Access to a uniform random number distribution
Definition at line 528 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetVariateWithOpenUpperRange().
GetVariate()
double itk::Statistics::MersenneTwisterRandomVariateGenerator::GetVariate () inline override virtual
Get a variate in the range [0, 1] Do NOT use for CRYPTOGRAPHY without securely hashing several returned values together, otherwise the generator state can be learned after reading 624 consecutive values.
Implements itk::Statistics::RandomVariateGeneratorBase.
Definition at line 536 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetVariateWithClosedRange().
Referenced by operator()().
GetVariateWithClosedRange() [1/2]
double itk::Statistics::MersenneTwisterRandomVariateGenerator::GetVariateWithClosedRange () inline
Get a random variate in the range [0, 1]
Definition at line 436 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetIntegerVariate().
Referenced by GetVariate(), and GetVariateWithClosedRange().
GetVariateWithClosedRange() [2/2]
double itk::Statistics::MersenneTwisterRandomVariateGenerator::GetVariateWithClosedRange (const double n) inline
Get a random variate in the range [0, n]
Definition at line 443 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetVariateWithClosedRange().
GetVariateWithOpenRange() [1/2]
double itk::Statistics::MersenneTwisterRandomVariateGenerator::GetVariateWithOpenRange () inline
Get a range variate in the range (0, 1)
Definition at line 464 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetIntegerVariate().
Referenced by GetNormalVariate(), and GetVariateWithOpenRange().
GetVariateWithOpenRange() [2/2]
double itk::Statistics::MersenneTwisterRandomVariateGenerator::GetVariateWithOpenRange (const double n) inline
Get a range variate in the range (0, n)
Definition at line 471 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetVariateWithOpenRange().
GetVariateWithOpenUpperRange() [1/2]
double itk::Statistics::MersenneTwisterRandomVariateGenerator::GetVariateWithOpenUpperRange () inline
Get a range variate in the range [0, 1)
Definition at line 450 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetIntegerVariate().
Referenced by GetNormalVariate(), GetUniformVariate(), and GetVariateWithOpenUpperRange().
GetVariateWithOpenUpperRange() [2/2]
double itk::Statistics::MersenneTwisterRandomVariateGenerator::GetVariateWithOpenUpperRange (const double n) inline
Get a range variate in the range [0, n)
Definition at line 457 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetVariateWithOpenUpperRange().
hash()
static IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::hash (time_t t, clock_t c) static protected
Referenced by SetSeed().
hiBit()
IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::hiBit (const IntegerType & u) const inline protected
Definition at line 283 of file itkMersenneTwisterRandomVariateGenerator.h.
Initialize() [1/2]
void itk::Statistics::MersenneTwisterRandomVariateGenerator::Initialize () inline
Definition at line 391 of file itkMersenneTwisterRandomVariateGenerator.h.
References SetSeed().
Referenced by SetSeed().
Initialize() [2/2]
void itk::Statistics::MersenneTwisterRandomVariateGenerator::Initialize (const IntegerType seed) inline
Initialize with a simple IntegerType
Definition at line 344 of file itkMersenneTwisterRandomVariateGenerator.h.
References m_InstanceMutex, m_Seed, reload(), state, and StateVectorLength.
itkGetGlobalDeclarationMacro()
itk::Statistics::MersenneTwisterRandomVariateGenerator::itkGetGlobalDeclarationMacro (MersenneTwisterGlobals , PimplGlobals) private
Only used to synchronize the global variable across static libraries.
loBit()
IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::loBit (const IntegerType & u) const inline protected
Definition at line 288 of file itkMersenneTwisterRandomVariateGenerator.h.
loBits()
IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::loBits (const IntegerType & u) const inline protected
Definition at line 293 of file itkMersenneTwisterRandomVariateGenerator.h.
mixBits()
IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::mixBits (const IntegerType & u, const IntegerType & v) const inline protected
Definition at line 298 of file itkMersenneTwisterRandomVariateGenerator.h.
New()
static Pointer itk::Statistics::MersenneTwisterRandomVariateGenerator::New () static
Method for creation through the object factory.
This method allocates a new instance of a Mersenne Twister, and initializes it with the next seed from the global instance's seed.
Note
This method is thread-safe.
Referenced by itk::RandomPermutation::RandomPermutation().
operator()()
double itk::Statistics::MersenneTwisterRandomVariateGenerator::operator() () inline
Same as GetVariate()
Definition at line 542 of file itkMersenneTwisterRandomVariateGenerator.h.
References GetVariate().
PrintSelf()
void itk::Statistics::MersenneTwisterRandomVariateGenerator::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from itk::LightObject.
reload()
void itk::Statistics::MersenneTwisterRandomVariateGenerator::reload () inline protected
Reload array with N new values.
Definition at line 365 of file itkMersenneTwisterRandomVariateGenerator.h.
References M, m_Left, m_PNext, state, StateVectorLength, and twist().
Referenced by GetIntegerVariate(), and Initialize().
ResetNextSeed()
static void itk::Statistics::MersenneTwisterRandomVariateGenerator::ResetNextSeed () static
Resets the internal data that is used to calculate the next seed. (Does not reset the initial seed.) Allows generating a reproducible sequence of pseudo-random numbers.
SetSeed() [1/2]
void itk::Statistics::MersenneTwisterRandomVariateGenerator::SetSeed () inline
Re-seeding functions with same behavior as initializers
\note This method is thread-safe.
Definition at line 404 of file itkMersenneTwisterRandomVariateGenerator.h.
References hash(), and SetSeed().
Referenced by Initialize(), and SetSeed().
SetSeed() [2/2]
void itk::Statistics::MersenneTwisterRandomVariateGenerator::SetSeed (const IntegerType oneSeed) inline
Re-seeding functions with same behavior as initializers
\note This method is thread-safe.
Definition at line 397 of file itkMersenneTwisterRandomVariateGenerator.h.
References Initialize().
twist()
IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::twist (const IntegerType & m, const IntegerType & s0, const IntegerType & s1) const inline protected
Definition at line 304 of file itkMersenneTwisterRandomVariateGenerator.h.
Referenced by reload().
Member Data Documentation
M
constexpr unsigned int itk::Statistics::MersenneTwisterRandomVariateGenerator::M = 397 static constexpr protected
Period parameter
Definition at line 276 of file itkMersenneTwisterRandomVariateGenerator.h.
Referenced by reload().
m_InstanceMutex
std::mutex itk::Statistics::MersenneTwisterRandomVariateGenerator::m_InstanceMutex {} private
Definition at line 333 of file itkMersenneTwisterRandomVariateGenerator.h.
Referenced by Initialize().
m_Left
int itk::Statistics::MersenneTwisterRandomVariateGenerator::m_Left {} protected
Definition at line 319 of file itkMersenneTwisterRandomVariateGenerator.h.
Referenced by GetIntegerVariate(), and reload().
m_PimplGlobals
MersenneTwisterGlobals* itk::Statistics::MersenneTwisterRandomVariateGenerator::m_PimplGlobals static private
Definition at line 337 of file itkMersenneTwisterRandomVariateGenerator.h.
m_PNext
IntegerType* itk::Statistics::MersenneTwisterRandomVariateGenerator::m_PNext {} protected
Definition at line 316 of file itkMersenneTwisterRandomVariateGenerator.h.
Referenced by GetIntegerVariate(), and reload().
m_Seed
std::atomic<IntegerType> itk::Statistics::MersenneTwisterRandomVariateGenerator::m_Seed {} protected
Definition at line 322 of file itkMersenneTwisterRandomVariateGenerator.h.
Referenced by GetSeed(), and Initialize().
state
IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::state[StateVectorLength] protected
Definition at line 313 of file itkMersenneTwisterRandomVariateGenerator.h.
Referenced by Initialize(), and reload().
StateVectorLength
constexpr IntegerType itk::Statistics::MersenneTwisterRandomVariateGenerator::StateVectorLength = 624 static constexpr
Length of state vector
Definition at line 169 of file itkMersenneTwisterRandomVariateGenerator.h.
Referenced by Initialize(), and reload().
The documentation for this class was generated from the following file:
itkMersenneTwisterRandomVariateGenerator.h