ITK: itk::MetaArrayWriter Class Reference
itk::MetaArrayWriter Class Reference
#include <itkMetaArrayWriter.h>
Public Types
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = MetaArrayWriter
using Superclass = LightProcessObject
Public Types inherited from itk::LightProcessObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightProcessObject
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
void ConvertTo (MET_ValueEnumType _metaElementType)
virtual const char * GetNameOfClass () const
void Update ()
virtual void SetFileName (const char *_arg)
virtual const char * GetFileName () const
virtual void SetDataFileName (const char *_arg)
virtual const char * GetDataFileName () const
virtual void BinaryOn ()
virtual void SetBinary (bool _arg)
virtual bool GetBinary () const
template<typename TValue >
void SetInput (MET_ValueEnumType _metaElementType, const Array< TValue > *_array)
template<typename TValue , unsigned int VLength>
void SetInput (MET_ValueEnumType _metaElementType, const FixedArray< TValue, VLength > *_array)
template<typename TValue , unsigned int VLength>
void SetInput (MET_ValueEnumType _metaElementType, const Vector< TValue, VLength > *_vector)
template<typename TValue , unsigned int VLength>
void SetInput (MET_ValueEnumType _metaElementType, const CovariantVector< TValue, VLength > *_vector)
template<typename TValue >
void SetInput (MET_ValueEnumType _metaElementType, const VariableLengthVector< TValue > *_vector)
template<typename TValue >
void SetMultiChannelInput (MET_ValueEnumType _metaElementType, int, const Array< TValue > *_array)
virtual void SetPrecision (unsigned int _arg)
virtual unsigned int GetPrecision () const
Public Member Functions inherited from itk::LightProcessObject
virtual void AbortGenerateDataOn ()
virtual const bool & GetAbortGenerateData () const
virtual const char * GetNameOfClass () const
virtual void SetAbortGenerateData (bool _arg)
virtual void UpdateOutputData ()
void UpdateProgress (float amount)
virtual void SetProgress (float _arg)
virtual const float & GetProgress () const
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *)
unsigned long AddObserver (const EventObject &event, Command *) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const char * GetNameOfClass () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag)
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual Pointer CreateAnother () const
virtual void Delete ()
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
virtual void Register () const
virtual void SetReferenceCount (int)
virtual void UnRegister () const noexcept
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::LightProcessObject
static Pointer New ()
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Protected Member Functions
MetaArrayWriter ()
void PrintSelf (std::ostream &os, Indent indent) const override
~MetaArrayWriter () override
Protected Member Functions inherited from itk::LightProcessObject
virtual void GenerateData ()
LightProcessObject ()
void PrintSelf (std::ostream &os, Indent indent) const override
~LightProcessObject () override
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
void PrintSelf (std::ostream &os, Indent indent) const override
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintSelf (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Private Attributes
bool m_Binary { false }
const void * m_Buffer { nullptr }
std::string m_DataFileName
std::string m_FileName
MetaArray m_MetaArray
unsigned int m_Precision { 6 }
Additional Inherited Members
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount
Detailed Description
Definition at line 30 of file itkMetaArrayWriter.h.
Member Typedef Documentation
ConstPointer
using itk::MetaArrayWriter::ConstPointer = SmartPointer<const Self>
Definition at line 38 of file itkMetaArrayWriter.h.
Pointer
using itk::MetaArrayWriter::Pointer = SmartPointer<Self>
Definition at line 37 of file itkMetaArrayWriter.h.
Self
using itk::MetaArrayWriter::Self = MetaArrayWriter
SmartPointer type alias support
Definition at line 34 of file itkMetaArrayWriter.h.
Superclass
using itk::MetaArrayWriter::Superclass = LightProcessObject
Definition at line 35 of file itkMetaArrayWriter.h.
Constructor & Destructor Documentation
MetaArrayWriter()
itk::MetaArrayWriter::MetaArrayWriter () protected
~MetaArrayWriter()
itk::MetaArrayWriter::~MetaArrayWriter () override protected
Member Function Documentation
BinaryOn()
virtual void itk::MetaArrayWriter::BinaryOn () virtual
Boolean to set binary mode. If set to On, data will be stored in the file in binary format; if set to Off, data will be stored in ascci format. Default is Off.
ConvertTo()
void itk::MetaArrayWriter::ConvertTo (MET_ValueEnumType _metaElementType)
Set the data type written to the file.
GetBinary()
virtual bool itk::MetaArrayWriter::GetBinary () const virtual
Boolean to set binary mode. If set to On, data will be stored in the file in binary format; if set to Off, data will be stored in ascci format. Default is Off.
GetDataFileName()
virtual const char * itk::MetaArrayWriter::GetDataFileName () const virtual
Set/Get the filename to which the data is written. Optional: use if header and data should be in separate files.
GetFileName()
virtual const char * itk::MetaArrayWriter::GetFileName () const virtual
Set/Get the filename.
GetNameOfClass()
virtual const char * itk::MetaArrayWriter::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::LightProcessObject.
GetPrecision()
virtual unsigned int itk::MetaArrayWriter::GetPrecision () const virtual
Set/Get the precision of the writing.
New()
static Pointer itk::MetaArrayWriter::New () static
Method for creation through the object factory.
PrintSelf()
void itk::MetaArrayWriter::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from itk::LightProcessObject.
SetBinary()
virtual void itk::MetaArrayWriter::SetBinary (bool _arg) virtual
Boolean to set binary mode. If set to On, data will be stored in the file in binary format; if set to Off, data will be stored in ascci format. Default is Off.
SetDataFileName()
virtual void itk::MetaArrayWriter::SetDataFileName (const char * _arg) virtual
Set/Get the filename to which the data is written. Optional: use if header and data should be in separate files.
SetFileName()
virtual void itk::MetaArrayWriter::SetFileName (const char * _arg) virtual
Set/Get the filename.
SetInput() [1/5]
template<typename TValue > void itk::MetaArrayWriter::SetInput (MET_ValueEnumType _metaElementType, const Array< TValue > * _array) inline
Set the input itk Array to write.
Definition at line 69 of file itkMetaArrayWriter.h.
References itk::Array< TValue >::Size().
SetInput() [2/5]
template<typename TValue , unsigned int VLength> void itk::MetaArrayWriter::SetInput (MET_ValueEnumType _metaElementType, const CovariantVector< TValue, VLength > * _vector) inline
Set the input itk CovariantVector to write.
Definition at line 99 of file itkMetaArrayWriter.h.
References itk::FixedArray< TValue, VLength >::GetDataPointer().
SetInput() [3/5]
template<typename TValue , unsigned int VLength> void itk::MetaArrayWriter::SetInput (MET_ValueEnumType _metaElementType, const FixedArray< TValue, VLength > * _array) inline
Set the input itk FixedArray to write.
Definition at line 79 of file itkMetaArrayWriter.h.
References itk::FixedArray< TValue, VLength >::GetDataPointer().
SetInput() [4/5]
template<typename TValue > void itk::MetaArrayWriter::SetInput (MET_ValueEnumType _metaElementType, const VariableLengthVector< TValue > * _vector) inline
Set the input itk VariableLengthVector to write.
Definition at line 109 of file itkMetaArrayWriter.h.
SetInput() [5/5]
template<typename TValue , unsigned int VLength> void itk::MetaArrayWriter::SetInput (MET_ValueEnumType _metaElementType, const Vector< TValue, VLength > * _vector) inline
Set the input itk Vector to write.
Definition at line 89 of file itkMetaArrayWriter.h.
References itk::FixedArray< TValue, VLength >::GetDataPointer().
SetMultiChannelInput()
template<typename TValue > void itk::MetaArrayWriter::SetMultiChannelInput (MET_ValueEnumType _metaElementType, int , const Array< TValue > * _array) inline
Copies the elements from an array of arrays into the output buffer. Requires all sub-arrays to have the same length. length of the major array is the "length" of the array, while the length of the sub-arrays is the "number of channels" at each array position. Expected form itk::Array< itk::Array< * > >. May work for othesub-array-types that define the [] operator and the GetSize() function.
Definition at line 125 of file itkMetaArrayWriter.h.
References itk::Array< TValue >::GetSize().
SetPrecision()
virtual void itk::MetaArrayWriter::SetPrecision (unsigned int _arg) virtual
Set/Get the precision of the writing.
Update()
void itk::MetaArrayWriter::Update ()
Write out the array.
Member Data Documentation
m_Binary
bool itk::MetaArrayWriter::m_Binary { false } private
Definition at line 162 of file itkMetaArrayWriter.h.
m_Buffer
const void* itk::MetaArrayWriter::m_Buffer { nullptr } private
Definition at line 171 of file itkMetaArrayWriter.h.
m_DataFileName
std::string itk::MetaArrayWriter::m_DataFileName private
Definition at line 167 of file itkMetaArrayWriter.h.
m_FileName
std::string itk::MetaArrayWriter::m_FileName private
Definition at line 166 of file itkMetaArrayWriter.h.
m_MetaArray
MetaArray itk::MetaArrayWriter::m_MetaArray private
Definition at line 169 of file itkMetaArrayWriter.h.
m_Precision
unsigned int itk::MetaArrayWriter::m_Precision { 6 } private
Definition at line 164 of file itkMetaArrayWriter.h.
The documentation for this class was generated from the following file:
itkMetaArrayWriter.h