ITK: itk::Functor::AccessorFunctor< TInput, TAccessor > Class Template Reference
itk::Functor::AccessorFunctor< TInput, TAccessor > Class Template Reference
Group Filtering » Module ITKImageIntensity
#include <itkAdaptImageFilter.h>
Detailed Description
template<typename TInput, typename TAccessor>
class itk::Functor::AccessorFunctor< TInput, TAccessor >
Convert an accessor to a functor so that it can be used in a UnaryFunctorImageFilter.
AccessorFunctor converts a data accessor to a functor object. This allows an accessor to be used as functor in a UnaryFunctorImageFilter, BinaryFunctorImageFilter, TernaryFunctorImageFilter, or NaryFunctionImageFilter.
Definition at line 39 of file itkAdaptImageFilter.h.
Public Types
using AccessorType = TAccessor
using Self = AccessorFunctor
Public Member Functions
AccessorFunctor ()
AccessorType & GetAccessor ()
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
AccessorFunctor & operator= (const AccessorFunctor &functor)
bool operator== (const Self &other) const
void SetAccessor (AccessorType &accessor)
~AccessorFunctor ()=default
Private Attributes
AccessorType m_Accessor
using OutputType = typename TAccessor::ExternalType
OutputType operator() (const TInput &A) const
Member Typedef Documentation
AccessorType
template<typename TInput , typename TAccessor > using itk::Functor::AccessorFunctor< TInput, TAccessor >::AccessorType = TAccessor
Definition at line 45 of file itkAdaptImageFilter.h.
OutputType
template<typename TInput , typename TAccessor > using itk::Functor::AccessorFunctor< TInput, TAccessor >::OutputType = typename TAccessor::ExternalType
operator(). This is the "call" method of the functor.
Definition at line 54 of file itkAdaptImageFilter.h.
Self
template<typename TInput , typename TAccessor > using itk::Functor::AccessorFunctor< TInput, TAccessor >::Self = AccessorFunctor
Standard class type aliases.
Definition at line 44 of file itkAdaptImageFilter.h.
Constructor & Destructor Documentation
AccessorFunctor()
template<typename TInput , typename TAccessor > itk::Functor::AccessorFunctor< TInput, TAccessor >::AccessorFunctor () inline
Constructor and destructor.
Definition at line 48 of file itkAdaptImageFilter.h.
~AccessorFunctor()
template<typename TInput , typename TAccessor > itk::Functor::AccessorFunctor< TInput, TAccessor >::~AccessorFunctor () default
Member Function Documentation
GetAccessor()
template<typename TInput , typename TAccessor > AccessorType & itk::Functor::AccessorFunctor< TInput, TAccessor >::GetAccessor () inline
Get the accessor. The accessor is returned by reference.
Definition at line 64 of file itkAdaptImageFilter.h.
References itk::Functor::AccessorFunctor< TInput, TAccessor >::m_Accessor.
Referenced by itk::AdaptImageFilter< TInputImage, TOutputImage, TAccessor >::GetAccessor(), and itk::AdaptImageFilter< TInputImage, TOutputImage, TAccessor >::SetAccessor().
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION()
template<typename TInput , typename TAccessor > itk::Functor::AccessorFunctor< TInput, TAccessor >::ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
operator()()
template<typename TInput , typename TAccessor > OutputType itk::Functor::AccessorFunctor< TInput, TAccessor >::operator() (const TInput & A) const inline
operator(). This is the "call" method of the functor.
Definition at line 56 of file itkAdaptImageFilter.h.
References itk::Functor::AccessorFunctor< TInput, TAccessor >::m_Accessor.
operator=()
template<typename TInput , typename TAccessor > AccessorFunctor & itk::Functor::AccessorFunctor< TInput, TAccessor >::operator= (const AccessorFunctor< TInput, TAccessor > & functor) inline
Assignment operator
Definition at line 71 of file itkAdaptImageFilter.h.
References itk::Functor::AccessorFunctor< TInput, TAccessor >::m_Accessor.
operator==()
template<typename TInput , typename TAccessor > bool itk::Functor::AccessorFunctor< TInput, TAccessor >::operator== (const Self & other) const inline
Needed to determine if two accessors are the same.
Definition at line 90 of file itkAdaptImageFilter.h.
References itk::Functor::AccessorFunctor< TInput, TAccessor >::m_Accessor.
SetAccessor()
template<typename TInput , typename TAccessor > void itk::Functor::AccessorFunctor< TInput, TAccessor >::SetAccessor (AccessorType & accessor) inline
Set the accessor object. This replaces the current accessor with a copy of the specified accessor. This allows the user to specify an accessor that has ivars set differently that the default accessor.
Definition at line 83 of file itkAdaptImageFilter.h.
References itk::Functor::AccessorFunctor< TInput, TAccessor >::m_Accessor.
Referenced by itk::AdaptImageFilter< TInputImage, TOutputImage, TAccessor >::SetAccessor().
Member Data Documentation
m_Accessor
template<typename TInput , typename TAccessor > AccessorType itk::Functor::AccessorFunctor< TInput, TAccessor >::m_Accessor private
Definition at line 98 of file itkAdaptImageFilter.h.
Referenced by itk::Functor::AccessorFunctor< TInput, TAccessor >::GetAccessor(), itk::Functor::AccessorFunctor< TInput, TAccessor >::operator()(), itk::Functor::AccessorFunctor< TInput, TAccessor >::operator=(), itk::Functor::AccessorFunctor< TInput, TAccessor >::operator==(), and itk::Functor::AccessorFunctor< TInput, TAccessor >::SetAccessor().
The documentation for this class was generated from the following file:
itkAdaptImageFilter.h