ITK: itk::Functor::IntensityLinearTransform< TInput, TOutput > Class Template Reference
itk::Functor::IntensityLinearTransform< TInput, TOutput > Class Template Reference
#include <itkRescaleIntensityImageFilter.h>
Public Types
using RealType = typename NumericTraits< TInput >::RealType
Public Member Functions
IntensityLinearTransform ()
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (IntensityLinearTransform)
TOutput operator() (const TInput &x) const
bool operator== (const IntensityLinearTransform &other) const
void SetFactor (RealType a)
void SetMaximum (TOutput max)
void SetMinimum (TOutput min)
void SetOffset (RealType b)
~IntensityLinearTransform ()=default
Private Attributes
RealType m_Factor
TOutput m_Maximum
TOutput m_Minimum
RealType m_Offset
Detailed Description
template<typename TInput, typename TOutput>
class itk::Functor::IntensityLinearTransform< TInput, TOutput >
Definition at line 31 of file itkRescaleIntensityImageFilter.h.
Member Typedef Documentation
RealType
template<typename TInput , typename TOutput > using itk::Functor::IntensityLinearTransform< TInput, TOutput >::RealType = typename NumericTraits<TInput>::RealType
Definition at line 34 of file itkRescaleIntensityImageFilter.h.
Constructor & Destructor Documentation
IntensityLinearTransform()
template<typename TInput , typename TOutput > itk::Functor::IntensityLinearTransform< TInput, TOutput >::IntensityLinearTransform () inline
Definition at line 35 of file itkRescaleIntensityImageFilter.h.
References itk::NumericTraits< T >::max(), and itk::NumericTraits< T >::NonpositiveMin().
~IntensityLinearTransform()
template<typename TInput , typename TOutput > itk::Functor::IntensityLinearTransform< TInput, TOutput >::~IntensityLinearTransform () default
Member Function Documentation
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION()
template<typename TInput , typename TOutput > itk::Functor::IntensityLinearTransform< TInput, TOutput >::ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (IntensityLinearTransform< TInput, TOutput >)
operator()()
template<typename TInput , typename TOutput > TOutput itk::Functor::IntensityLinearTransform< TInput, TOutput >::operator() (const TInput & x) const inline
Definition at line 82 of file itkRescaleIntensityImageFilter.h.
operator==()
template<typename TInput , typename TOutput > bool itk::Functor::IntensityLinearTransform< TInput, TOutput >::operator== (const IntensityLinearTransform< TInput, TOutput > & other) const inline
Definition at line 73 of file itkRescaleIntensityImageFilter.h.
References itk::Math::ExactlyEquals(), itk::Functor::IntensityLinearTransform< TInput, TOutput >::m_Factor, itk::Functor::IntensityLinearTransform< TInput, TOutput >::m_Maximum, itk::Functor::IntensityLinearTransform< TInput, TOutput >::m_Minimum, and itk::Functor::IntensityLinearTransform< TInput, TOutput >::m_Offset.
SetFactor()
template<typename TInput , typename TOutput > void itk::Functor::IntensityLinearTransform< TInput, TOutput >::SetFactor (RealType a) inline
Definition at line 52 of file itkRescaleIntensityImageFilter.h.
SetMaximum()
template<typename TInput , typename TOutput > void itk::Functor::IntensityLinearTransform< TInput, TOutput >::SetMaximum (TOutput max) inline
Definition at line 67 of file itkRescaleIntensityImageFilter.h.
SetMinimum()
template<typename TInput , typename TOutput > void itk::Functor::IntensityLinearTransform< TInput, TOutput >::SetMinimum (TOutput min) inline
Definition at line 62 of file itkRescaleIntensityImageFilter.h.
SetOffset()
template<typename TInput , typename TOutput > void itk::Functor::IntensityLinearTransform< TInput, TOutput >::SetOffset (RealType b) inline
Definition at line 57 of file itkRescaleIntensityImageFilter.h.
Member Data Documentation
m_Factor
template<typename TInput , typename TOutput > RealType itk::Functor::IntensityLinearTransform< TInput, TOutput >::m_Factor private
Definition at line 97 of file itkRescaleIntensityImageFilter.h.
Referenced by itk::Functor::IntensityLinearTransform< TInput, TOutput >::operator==().
m_Maximum
template<typename TInput , typename TOutput > TOutput itk::Functor::IntensityLinearTransform< TInput, TOutput >::m_Maximum private
Definition at line 99 of file itkRescaleIntensityImageFilter.h.
Referenced by itk::Functor::IntensityLinearTransform< TInput, TOutput >::operator==().
m_Minimum
template<typename TInput , typename TOutput > TOutput itk::Functor::IntensityLinearTransform< TInput, TOutput >::m_Minimum private
Definition at line 100 of file itkRescaleIntensityImageFilter.h.
Referenced by itk::Functor::IntensityLinearTransform< TInput, TOutput >::operator==().
m_Offset
template<typename TInput , typename TOutput > RealType itk::Functor::IntensityLinearTransform< TInput, TOutput >::m_Offset private
Definition at line 98 of file itkRescaleIntensityImageFilter.h.
Referenced by itk::Functor::IntensityLinearTransform< TInput, TOutput >::operator==().
The documentation for this class was generated from the following file:
itkRescaleIntensityImageFilter.h