ITK: itk::Functor::MaskInput< TInput, TMask, TOutput > Class Template Reference
itk::Functor::MaskInput< TInput, TMask, TOutput > Class Template Reference
Group Filtering » Module ITKImageIntensity
#include <itkMaskImageFilter.h>
Public Types
using AccumulatorType = typename NumericTraits< TInput >::AccumulateType
Public Member Functions
const TMask & GetMaskingValue () const
const TOutput & GetOutsideValue () const
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (MaskInput)
MaskInput ()
TOutput operator() (const TInput &A, const TMask &B) const
bool operator== (const MaskInput &) const
void SetMaskingValue (const TMask &maskingValue)
void SetOutsideValue (const TOutput &outsideValue)
~MaskInput ()=default
Private Member Functions
template<typename TPixelType >
void InitializeOutsideValue (TPixelType *)
template<typename TValue >
void InitializeOutsideValue (VariableLengthVector< TValue > *)
Private Attributes
TMask m_MaskingValue
TOutput m_OutsideValue
Detailed Description
template<typename TInput, typename TMask, typename TOutput = TInput>
class itk::Functor::MaskInput< TInput, TMask, TOutput >
Definition at line 36 of file itkMaskImageFilter.h.
Member Typedef Documentation
AccumulatorType
template<typename TInput , typename TMask , typename TOutput = TInput> using itk::Functor::MaskInput< TInput, TMask, TOutput >::AccumulatorType = typename NumericTraits<TInput>::AccumulateType
Definition at line 39 of file itkMaskImageFilter.h.
Constructor & Destructor Documentation
MaskInput()
template<typename TInput , typename TMask , typename TOutput = TInput> itk::Functor::MaskInput< TInput, TMask, TOutput >::MaskInput () inline
Definition at line 41 of file itkMaskImageFilter.h.
References itk::Functor::MaskInput< TInput, TMask, TOutput >::InitializeOutsideValue(), itk::Functor::MaskInput< TInput, TMask, TOutput >::m_MaskingValue, and itk::NumericTraits< T >::ZeroValue().
~MaskInput()
template<typename TInput , typename TMask , typename TOutput = TInput> itk::Functor::MaskInput< TInput, TMask, TOutput >::~MaskInput () default
Member Function Documentation
GetMaskingValue()
template<typename TInput , typename TMask , typename TOutput = TInput> const TMask & itk::Functor::MaskInput< TInput, TMask, TOutput >::GetMaskingValue () const inline
Method to get the masking value
Definition at line 91 of file itkMaskImageFilter.h.
References itk::Functor::MaskInput< TInput, TMask, TOutput >::m_MaskingValue.
GetOutsideValue()
template<typename TInput , typename TMask , typename TOutput = TInput> const TOutput & itk::Functor::MaskInput< TInput, TMask, TOutput >::GetOutsideValue () const inline
Method to get the outside value of the mask
Definition at line 77 of file itkMaskImageFilter.h.
References itk::Functor::MaskInput< TInput, TMask, TOutput >::m_OutsideValue.
InitializeOutsideValue() [1/2]
template<typename TInput , typename TMask , typename TOutput = TInput> template<typename TPixelType > void itk::Functor::MaskInput< TInput, TMask, TOutput >::InitializeOutsideValue (TPixelType *) inline private
Definition at line 99 of file itkMaskImageFilter.h.
References itk::Functor::MaskInput< TInput, TMask, TOutput >::m_OutsideValue, and itk::NumericTraits< T >::ZeroValue().
Referenced by itk::Functor::MaskInput< TInput, TMask, TOutput >::MaskInput().
InitializeOutsideValue() [2/2]
template<typename TInput , typename TMask , typename TOutput = TInput> template<typename TValue > void itk::Functor::MaskInput< TInput, TMask, TOutput >::InitializeOutsideValue (VariableLengthVector< TValue > *) inline private
Definition at line 106 of file itkMaskImageFilter.h.
References itk::Functor::MaskInput< TInput, TMask, TOutput >::m_OutsideValue.
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION()
template<typename TInput , typename TMask , typename TOutput = TInput> itk::Functor::MaskInput< TInput, TMask, TOutput >::ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (MaskInput< TInput, TMask, TOutput >)
operator()()
template<typename TInput , typename TMask , typename TOutput = TInput> TOutput itk::Functor::MaskInput< TInput, TMask, TOutput >::operator() (const TInput & A, const TMask & B) const inline
Definition at line 56 of file itkMaskImageFilter.h.
References itk::Functor::MaskInput< TInput, TMask, TOutput >::m_MaskingValue, and itk::Functor::MaskInput< TInput, TMask, TOutput >::m_OutsideValue.
operator==()
template<typename TInput , typename TMask , typename TOutput = TInput> bool itk::Functor::MaskInput< TInput, TMask, TOutput >::operator== (const MaskInput< TInput, TMask, TOutput > &) const inline
Definition at line 48 of file itkMaskImageFilter.h.
SetMaskingValue()
template<typename TInput , typename TMask , typename TOutput = TInput> void itk::Functor::MaskInput< TInput, TMask, TOutput >::SetMaskingValue (const TMask & maskingValue) inline
Method to explicitly set the masking value
Definition at line 84 of file itkMaskImageFilter.h.
References itk::Functor::MaskInput< TInput, TMask, TOutput >::m_MaskingValue.
SetOutsideValue()
template<typename TInput , typename TMask , typename TOutput = TInput> void itk::Functor::MaskInput< TInput, TMask, TOutput >::SetOutsideValue (const TOutput & outsideValue) inline
Method to explicitly set the outside value of the mask
Definition at line 70 of file itkMaskImageFilter.h.
References itk::Functor::MaskInput< TInput, TMask, TOutput >::m_OutsideValue.
Member Data Documentation
m_MaskingValue
template<typename TInput , typename TMask , typename TOutput = TInput> TMask itk::Functor::MaskInput< TInput, TMask, TOutput >::m_MaskingValue private
Definition at line 113 of file itkMaskImageFilter.h.
Referenced by itk::Functor::MaskInput< TInput, TMask, TOutput >::GetMaskingValue(), itk::Functor::MaskInput< TInput, TMask, TOutput >::MaskInput(), itk::Functor::MaskInput< TInput, TMask, TOutput >::operator()(), and itk::Functor::MaskInput< TInput, TMask, TOutput >::SetMaskingValue().
m_OutsideValue
template<typename TInput , typename TMask , typename TOutput = TInput> TOutput itk::Functor::MaskInput< TInput, TMask, TOutput >::m_OutsideValue private
Definition at line 112 of file itkMaskImageFilter.h.
Referenced by itk::Functor::MaskInput< TInput, TMask, TOutput >::GetOutsideValue(), itk::Functor::MaskInput< TInput, TMask, TOutput >::InitializeOutsideValue(), itk::Functor::MaskInput< TInput, TMask, TOutput >::operator()(), and itk::Functor::MaskInput< TInput, TMask, TOutput >::SetOutsideValue().
The documentation for this class was generated from the following file:
itkMaskImageFilter.h