ITK: itk::QuadEdge Class Reference
itk::QuadEdge Class Reference
Data Representation Objects » Mesh Representation Objects | Group Core » Module ITKQuadEdgeMesh
#include <itkQuadEdge.h>
Detailed Description
Base class for the implementation of a quad-edge data structure as proposed in "Guibas and Stolfi 1985".
Author
Alexandre Gouaillard, Leonardo Florez-Valencia, Eric Boix
This implementation was contributed as a paper to the Insight Journal https://doi.org/10.54294/4mx7kk
See also
"Accessing adjacent edges."
Definition at line 136 of file itkQuadEdge.h.
Public Types
using ConstIterator = QuadEdgeMeshConstIterator< Self >
using Iterator = QuadEdgeMeshIterator< Self >
using Self = QuadEdge
Public Member Functions
Self * GetDnext ()
const Self * GetDnext () const
Self * GetDprev ()
const Self * GetDprev () const
Self * GetInvDnext ()
const Self * GetInvDnext () const
Self * GetInvLnext ()
const Self * GetInvLnext () const
Self * GetInvOnext ()
const Self * GetInvOnext () const
Self * GetInvRnext ()
const Self * GetInvRnext () const
const Self * GetInvRot () const
Self * GetLnext ()
const Self * GetLnext () const
Self * GetLprev ()
const Self * GetLprev () const
Self * GetOprev ()
const Self * GetOprev () const
unsigned int GetOrder () const
Self * GetRnext ()
const Self * GetRnext () const
Self * GetRprev ()
const Self * GetRprev () const
const Self * GetSym () const
bool IsLnextGivenSizeCyclic (const int size) const
itkQEDefineIteratorMethodsMacro (Onext)
QuadEdge ()
QuadEdge (const QuadEdge &)=default
QuadEdge (QuadEdge &&)=default
QuadEdge & operator= (const QuadEdge &)=default
QuadEdge & operator= (QuadEdge &&)=default
virtual ~QuadEdge ()
void SetOnext (Self *onext)
void SetRot (Self *rot)
Self * GetOnext ()
Self * GetRot ()
const Self * GetOnext () const
const Self * GetRot () const
void Splice (Self *b)
Self * GetSym ()
Self * GetInvRot ()
bool IsHalfEdge () const
bool IsIsolated () const
bool IsEdgeInOnextRing (Self *testEdge) const
Member Typedef Documentation
ConstIterator
using itk::QuadEdge::ConstIterator = QuadEdgeMeshConstIterator<Self>
Definition at line 144 of file itkQuadEdge.h.
Iterator
using itk::QuadEdge::Iterator = QuadEdgeMeshIterator<Self>
Iterator types.
Definition at line 143 of file itkQuadEdge.h.
Self
using itk::QuadEdge::Self = QuadEdge
Hierarchy type alias & values.
Definition at line 140 of file itkQuadEdge.h.
Constructor & Destructor Documentation
QuadEdge() [1/3]
itk::QuadEdge::QuadEdge ()
Object creation methods.
QuadEdge() [2/3]
itk::QuadEdge::QuadEdge (const QuadEdge &) default
Object creation methods.
QuadEdge() [3/3]
itk::QuadEdge::QuadEdge (QuadEdge &&) default
Object creation methods.
~QuadEdge()
virtual itk::QuadEdge::~QuadEdge () virtual
Object creation methods.
Member Function Documentation
GetDnext() [1/2]
Self * itk::QuadEdge::GetDnext ()
Returns next edge with same right face and same Destination. The first edge encountered when moving counter-clockwise from e (see "Accessing adjacent edges").
GetDnext() [2/2]
const Self * itk::QuadEdge::GetDnext () const
GetDprev() [1/2]
Self * itk::QuadEdge::GetDprev ()
Returns the previous edge with same Right face and same Destination. The first edge encountered when moving clockwise from e around e->Dest. (see "Accessing adjacent edges").
GetDprev() [2/2]
const Self * itk::QuadEdge::GetDprev () const
GetInvDnext() [1/2]
Self * itk::QuadEdge::GetInvDnext () inline
Definition at line 375 of file itkQuadEdge.h.
GetInvDnext() [2/2]
const Self * itk::QuadEdge::GetInvDnext () const inline
Definition at line 420 of file itkQuadEdge.h.
GetInvLnext() [1/2]
Self * itk::QuadEdge::GetInvLnext () inline
Definition at line 365 of file itkQuadEdge.h.
GetInvLnext() [2/2]
const Self * itk::QuadEdge::GetInvLnext () const inline
Definition at line 410 of file itkQuadEdge.h.
GetInvOnext() [1/2]
Self * itk::QuadEdge::GetInvOnext () inline
Definition at line 360 of file itkQuadEdge.h.
GetInvOnext() [2/2]
const Self * itk::QuadEdge::GetInvOnext () const inline
Definition at line 405 of file itkQuadEdge.h.
GetInvRnext() [1/2]
Self * itk::QuadEdge::GetInvRnext () inline
Definition at line 370 of file itkQuadEdge.h.
GetInvRnext() [2/2]
const Self * itk::QuadEdge::GetInvRnext () const inline
Definition at line 415 of file itkQuadEdge.h.
GetInvRot() [1/2]
Self * itk::QuadEdge::GetInvRot () inline
Inverse operators
Definition at line 334 of file itkQuadEdge.h.
References GetRot().
GetInvRot() [2/2]
const Self * itk::QuadEdge::GetInvRot () const inline
Definition at line 380 of file itkQuadEdge.h.
References GetRot().
GetLnext() [1/2]
Self * itk::QuadEdge::GetLnext ()
Returns next edge with same Left face (see "Accessing adjacent edges").
GetLnext() [2/2]
const Self * itk::QuadEdge::GetLnext () const
GetLprev() [1/2]
Self * itk::QuadEdge::GetLprev ()
Returns previous edge with same Left face. The first edge encountered when moving clockwise from e around e->Left. (see "Accessing adjacent edges").
GetLprev() [2/2]
const Self * itk::QuadEdge::GetLprev () const
GetOnext() [1/2]
Self * itk::QuadEdge::GetOnext () inline
Sub-algebra Get methods. Returns edge with same Origin (see "Accessing adjacent edges").
Definition at line 190 of file itkQuadEdge.h.
Referenced by Splice().
GetOnext() [2/2]
const Self * itk::QuadEdge::GetOnext () const inline
Sub-algebra Get methods. Returns edge with same Origin (see "Accessing adjacent edges").
Definition at line 200 of file itkQuadEdge.h.
GetOprev() [1/2]
Self * itk::QuadEdge::GetOprev ()
Returns previous edge with same Origin (see "Accessing adjacent edges").
GetOprev() [2/2]
const Self * itk::QuadEdge::GetOprev () const
GetOrder()
unsigned int itk::QuadEdge::GetOrder () const
GetRnext() [1/2]
Self * itk::QuadEdge::GetRnext ()
Returns next edge with same Right face. The first edge encountered when moving counter-clockwise from e around e->Right. (see "Accessing adjacent edges").
GetRnext() [2/2]
const Self * itk::QuadEdge::GetRnext () const
GetRot() [1/2]
Self * itk::QuadEdge::GetRot () inline
Sub-algebra Get methods. Returns edge with same Origin (see "Accessing adjacent edges").
Definition at line 195 of file itkQuadEdge.h.
Referenced by GetInvRot(), and Splice().
GetRot() [2/2]
const Self * itk::QuadEdge::GetRot () const inline
Sub-algebra Get methods. Returns edge with same Origin (see "Accessing adjacent edges").
Definition at line 205 of file itkQuadEdge.h.
GetRprev() [1/2]
Self * itk::QuadEdge::GetRprev ()
Returns the previous edge with same Right face. The first edge encountered when moving clockwise from e around e->Right. (see "Accessing adjacent edges").
GetRprev() [2/2]
const Self * itk::QuadEdge::GetRprev () const
GetSym() [1/2]
Self * itk::QuadEdge::GetSym () inline
Returns the symmetric edge (see "Accessing adjacent edges").
Definition at line 251 of file itkQuadEdge.h.
GetSym() [2/2]
const Self * itk::QuadEdge::GetSym () const inline
Definition at line 262 of file itkQuadEdge.h.
IsEdgeInOnextRing()
bool itk::QuadEdge::IsEdgeInOnextRing (Self * testEdge) const
Queries.
IsHalfEdge()
bool itk::QuadEdge::IsHalfEdge () const inline
Queries.
Definition at line 427 of file itkQuadEdge.h.
IsIsolated()
bool itk::QuadEdge::IsIsolated () const inline
Queries.
Definition at line 432 of file itkQuadEdge.h.
IsLnextGivenSizeCyclic()
bool itk::QuadEdge::IsLnextGivenSizeCyclic (const int size) const
itkQEDefineIteratorMethodsMacro()
itk::QuadEdge::itkQEDefineIteratorMethodsMacro (Onext) inline
Basic iterators methods.
operator=() [1/2]
QuadEdge & itk::QuadEdge::operator= (const QuadEdge &) default
Object creation methods.
operator=() [2/2]
QuadEdge & itk::QuadEdge::operator= (QuadEdge &&) default
Object creation methods.
SetOnext()
void itk::QuadEdge::SetOnext (Self * onext) inline
Sub-algebra Set methods.
Definition at line 175 of file itkQuadEdge.h.
Referenced by Splice().
SetRot()
void itk::QuadEdge::SetRot (Self * rot) inline
Sub-algebra Set methods.
Definition at line 180 of file itkQuadEdge.h.
Splice()
void itk::QuadEdge::Splice (Self * b) inline
Basic quad-edge topological method.
This method describes all possible topological operations on an edge.
It is its own inverse. It works in two ways:
If this->GetOrg() != b->GetOrg(), it slice a face in two.
If this->GetOrg() == b->GetOrg(), it unifies two faces.
Warning
This class only handles of the connectivity and is not aware of the geometry that lies at the GeometricalQuadEdge level. It is strongly discouraged to use this method. Instead you should use itk::QuadEdgeMesh::Splice its geometry aware version.
Definition at line 230 of file itkQuadEdge.h.
References GetOnext(), GetRot(), and SetOnext().
The documentation for this class was generated from the following file:
itkQuadEdge.h