ITK: itk::ProcessObject Class Reference
itk::ProcessObject Class Reference
System Objects » ITK System Objects | Data Processing Objects | Group Core » Module ITKCommon
#include <itkProcessObject.h>
Public Types
using ConstPointer = SmartPointer< const Self >
using DataObjectIdentifierType = DataObject::DataObjectIdentifierType
using DataObjectPointer = DataObject::Pointer
using DataObjectPointerArray = std::vector< DataObjectPointer >
using DataObjectPointerArraySizeType = DataObjectPointerArray::size_type
using MultiThreaderType = MultiThreaderBase
using NameArray = std::vector< DataObjectIdentifierType >
using Pointer = SmartPointer< Self >
using Self = ProcessObject
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
virtual void AbortGenerateDataOn ()
virtual void EnlargeOutputRequestedRegion (DataObject *)
virtual const bool & GetAbortGenerateData () const
DataObjectPointerArray GetIndexedInputs ()
DataObjectPointerArray GetIndexedOutputs ()
NameArray GetInputNames () const
DataObjectPointerArray GetInputs ()
MultiThreaderType * GetMultiThreader () const
virtual const char * GetNameOfClass () const
DataObjectPointerArraySizeType GetNumberOfIndexedInputs () const
DataObjectPointerArraySizeType GetNumberOfIndexedOutputs () const
DataObjectPointerArraySizeType GetNumberOfInputs () const
DataObjectPointerArraySizeType GetNumberOfOutputs () const
virtual DataObjectPointerArraySizeType GetNumberOfValidRequiredInputs () const
NameArray GetOutputNames () const
DataObjectPointerArray GetOutputs ()
virtual float GetProgress () const
NameArray GetRequiredInputNames () const
bool HasInput (const DataObjectIdentifierType &key) const
bool HasOutput (const DataObjectIdentifierType &key) const
void IncrementProgress (float increment)
virtual DataObjectPointer MakeOutput (const DataObjectIdentifierType &)
virtual DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx)
virtual void PrepareOutputs ()
virtual void PropagateRequestedRegion (DataObject *output)
virtual void ResetPipeline ()
virtual void SetAbortGenerateData (bool _arg)
void SetMultiThreader (MultiThreaderType *threader)
virtual void Update ()
virtual void UpdateLargestPossibleRegion ()
virtual void UpdateOutputData (DataObject *output)
virtual void UpdateOutputInformation ()
void UpdateProgress (float progress)
virtual void SetReleaseDataFlag (bool val)
virtual bool GetReleaseDataFlag () const
void ReleaseDataFlagOn ()
void ReleaseDataFlagOff ()
virtual void SetReleaseDataBeforeUpdateFlag (bool _arg)
virtual const bool & GetReleaseDataBeforeUpdateFlag () const
virtual void ReleaseDataBeforeUpdateFlagOn ()
virtual void SetNumberOfWorkUnits (ThreadIdType _arg)
virtual const ThreadIdType & GetNumberOfWorkUnits () const
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *)
unsigned long AddObserver (const EventObject &event, Command *) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const char * GetNameOfClass () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag)
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual Pointer CreateAnother () const
virtual void Delete ()
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
virtual void Register () const
virtual void SetReferenceCount (int)
virtual void UnRegister () const noexcept
Protected Member Functions
virtual void AddInput (DataObject *input)
void AddOptionalInputName (const DataObjectIdentifierType &)
void AddOptionalInputName (const DataObjectIdentifierType &, DataObjectPointerArraySizeType idx)
virtual void AddOutput (DataObject *output)
bool AddRequiredInputName (const DataObjectIdentifierType &)
bool AddRequiredInputName (const DataObjectIdentifierType &, DataObjectPointerArraySizeType idx)
virtual void CacheInputReleaseDataFlags ()
virtual void GenerateData ()
virtual void GenerateInputRequestedRegion ()
virtual void GenerateOutputInformation ()
virtual void GenerateOutputRequestedRegion (DataObject *output)
DataObject * GetInput (const DataObjectIdentifierType &key)
const DataObject * GetInput (const DataObjectIdentifierType &key) const
virtual const DataObjectPointerArraySizeType & GetNumberOfRequiredInputs () const
virtual const DataObjectPointerArraySizeType & GetNumberOfRequiredOutputs () const
bool IsIndexedInputName (const DataObjectIdentifierType &) const
bool IsIndexedOutputName (const DataObjectIdentifierType &) const
bool IsRequiredInputName (const DataObjectIdentifierType &) const
DataObjectPointerArraySizeType MakeIndexFromInputName (const DataObjectIdentifierType &name) const
DataObjectPointerArraySizeType MakeIndexFromOutputName (const DataObjectIdentifierType &name) const
DataObjectIdentifierType MakeNameFromInputIndex (DataObjectPointerArraySizeType idx) const
DataObjectIdentifierType MakeNameFromOutputIndex (DataObjectPointerArraySizeType idx) const
virtual void PopBackInput ()
virtual void PopFrontInput ()
void PrintSelf (std::ostream &os, Indent indent) const override
ProcessObject ()
virtual void PropagateResetPipeline ()
virtual void PushBackInput (const DataObject *input)
virtual void PushFrontInput (const DataObject *input)
virtual void ReleaseInputs ()
virtual void RemoveInput (const DataObjectIdentifierType &key)
virtual void RemoveInput (DataObjectPointerArraySizeType)
virtual void RemoveOutput (const DataObjectIdentifierType &key)
virtual void RemoveOutput (DataObjectPointerArraySizeType idx)
bool RemoveRequiredInputName (const DataObjectIdentifierType &)
virtual void RestoreInputReleaseDataFlags ()
virtual void SetInput (const DataObjectIdentifierType &key, DataObject *input)
virtual void SetNthInput (DataObjectPointerArraySizeType idx, DataObject *input)
virtual void SetNthOutput (DataObjectPointerArraySizeType idx, DataObject *output)
void SetNumberOfIndexedInputs (DataObjectPointerArraySizeType num)
void SetNumberOfIndexedOutputs (DataObjectPointerArraySizeType num)
virtual void SetNumberOfRequiredInputs (DataObjectPointerArraySizeType)
virtual void SetNumberOfRequiredOutputs (DataObjectPointerArraySizeType _arg)
virtual void SetOutput (const DataObjectIdentifierType &name, DataObject *output)
virtual void SetPrimaryInput (DataObject *object)
virtual void SetPrimaryOutput (DataObject *object)
void SetRequiredInputNames (const NameArray &)
virtual void VerifyInputInformation () ITKv5_CONST
virtual void VerifyPreconditions () ITKv5_CONST
~ProcessObject () override
DataObject * GetInput (DataObjectPointerArraySizeType idx)
const DataObject * GetInput (DataObjectPointerArraySizeType idx) const
DataObject * GetPrimaryInput ()
const DataObject * GetPrimaryInput () const
virtual void SetPrimaryInputName (const DataObjectIdentifierType &key)
virtual const char * GetPrimaryInputName () const
DataObject * GetOutput (const DataObjectIdentifierType &key)
const DataObject * GetOutput (const DataObjectIdentifierType &key) const
virtual void SetPrimaryOutputName (const DataObjectIdentifierType &key)
virtual const char * GetPrimaryOutputName () const
DataObject * GetOutput (DataObjectPointerArraySizeType i)
const DataObject * GetOutput (DataObjectPointerArraySizeType i) const
DataObject * GetPrimaryOutput ()
const DataObject * GetPrimaryOutput () const
virtual bool GetThreaderUpdateProgress () const
virtual void ThreaderUpdateProgressOn ()
virtual void SetThreaderUpdateProgress (bool arg)
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
void PrintSelf (std::ostream &os, Indent indent) const override
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintSelf (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Static Protected Member Functions
static constexpr float progressFixedToFloat (uint32_t fixed)
static uint32_t progressFloatToFixed (float f)
Protected Attributes
TimeStamp m_OutputInformationMTime
bool m_Updating
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount
Private Types
using DataObjectPointerMap = std::map< DataObjectIdentifierType, DataObjectPointer >
using NameSet = std::set< DataObjectIdentifierType >
Private Member Functions
DataObjectPointerArraySizeType MakeIndexFromName (const DataObjectIdentifierType &) const
DataObjectIdentifierType MakeNameFromIndex (DataObjectPointerArraySizeType) const
Private Attributes
bool m_AbortGenerateData
std::map< DataObjectIdentifierType, bool > m_CachedInputReleaseDataFlags
std::vector< DataObjectPointerMap::iterator > m_IndexedInputs
std::vector< DataObjectPointerMap::iterator > m_IndexedOutputs
DataObjectPointerMap m_Inputs
itk::SmartPointer< MultiThreaderType > m_MultiThreader
DataObjectPointerArraySizeType m_NumberOfRequiredInputs
DataObjectPointerArraySizeType m_NumberOfRequiredOutputs
ThreadIdType m_NumberOfWorkUnits
DataObjectPointerMap m_Outputs
std::atomic< uint32_t > m_Progress
bool m_ReleaseDataBeforeUpdateFlag
NameSet m_RequiredInputNames
bool m_ThreaderUpdateProgress { true }
std::thread::id m_UpdateThreadID
Friends
class DataObject
class DataObjectConstIterator
class DataObjectIterator
class InputDataObjectConstIterator
class InputDataObjectIterator
class OutputDataObjectConstIterator
class OutputDataObjectIterator
class ProgressReporter
class TestProcessObject
class TotalProgressReporter
Additional Inherited Members
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Detailed Description
The base class for all process objects (source, filters, mappers) in the Insight data processing pipeline.
ProcessObject is an abstract object that specifies behavior and interface of network process objects (sources, filters, mappers). Source objects are creators of visualization data; filters input, process, and output image data; and mappers transform data into another form (like transforming coordinates or writing data to a file).
A major role of ProcessObject is to define the inputs and outputs of a filter. More than one input and/or output may exist for a given filter. Some classes (e.g., source objects or mapper objects) will not use inputs (the source) or outputs (mappers). In this case, the inputs or outputs is just ignored.
VOCABULARY:
named entry - an entry indexed by a DataObjectIdentifierType or string.
index entry - an entry indexed by an integer, which also always has a string identifier.
define an input/output - adds a named entry or a indexed entry.
required input - a precondition that the inputs is set before updating.
set the value - set the value of an input or output, and automatically define the entry if it does not exist.
Note
The Primary Input is always defined internally, and is handled as a special case for many methods.
Some inputs can be defined as required. Either explicitly by name or the older ITKv3 style where a certain number of index inputs are required.
The inputs and outputs are referenced by name and optionally by an integer index. The Primary input and the Primary output play a special role: they drive the pipeline.
In addition to the reference by name, it is possible to access the inputs and outputs with an index. The index by default is mapped internally to a name with '_' followed by the index number. This default name can be changed with the AddRequiredInputName method. The indexed input or output 0 is mapped to the Primary input or output. The name of the Primary input or output defaults to "Primary", but this can be changed with SetPrimaryInputName and SetPrimaryOutputName.
For complicated filters which have optional, or varied required inputs, named input access is preferred. However, indexed input access provides constant time access to input and output DataObjects, and so are more efficient. A name can also be associated with an indexed input. Neither type of input or output should be accessed in a tight loop.
ProcessObject invokes the following events: Command::StartEvent, Command::EndEvent These are convenience events you can use for any purpose (e.g., debugging info, highlighting/notifying user interface, etc.) See Command and LightObject for information on using AddObserver.
Another event Command::ProgressEvent can be observed. Some filters invoke this event periodically during their execution (with the progress, parameter, the fraction of work done). The use is similar to that of StartEvent and EndEvent. Filters may also check their AbortGenerateData flag to determine whether to prematurely end their execution.
An important feature of subclasses of ProcessObject is that it is possible to control the memory-management model (i.e., retain output versus delete output data). The ReleaseDataFlag enables the deletion of the output data once the downstream process object finishes processing the data (please see text). The ReleaseDataBeforeUpdateFlag enables the deletion of the ProcessObject's output data from a previous update if that output data is slated to be regenerated by the pipeline process. Setting this flag can control peak memory usage during a subsequent pipeline update. For a ProcessObject, the ReleaseDataFlag defaults to false and the ReleaseDataBeforeUpdateFlag defaults to true. Some subclasses of ProcessObject, for example ImageSource, use a default setting of false for the ReleaseDataBeforeUpdateFlag.
Subclasses of ProcessObject may override 4 of the methods of this class to control how a given filter may interact with the pipeline (dataflow). These methods are: GenerateOutputInformation(), EnlargeOutputRequestedRegion(), GenerateInputRequestedRegion(), and GenerateOutputRequestedRegion(). By overriding these methods, a filter can deviate from the base assumptions of the pipeline execution model.
Definition at line 138 of file itkProcessObject.h.
Member Typedef Documentation
ConstPointer
using itk::ProcessObject::ConstPointer = SmartPointer<const Self>
Definition at line 147 of file itkProcessObject.h.
DataObjectIdentifierType
using itk::ProcessObject::DataObjectIdentifierType = DataObject::DataObjectIdentifierType
Definition at line 161 of file itkProcessObject.h.
DataObjectPointer
using itk::ProcessObject::DataObjectPointer = DataObject::Pointer
Smart Pointer type to a DataObject.
Definition at line 153 of file itkProcessObject.h.
DataObjectPointerArray
using itk::ProcessObject::DataObjectPointerArray = std::vector<DataObjectPointer>
STL array of const pointer to the data objects STL array of pointer to the data objects
Definition at line 159 of file itkProcessObject.h.
DataObjectPointerArraySizeType
using itk::ProcessObject::DataObjectPointerArraySizeType = DataObjectPointerArray::size_type
Definition at line 193 of file itkProcessObject.h.
DataObjectPointerMap
using itk::ProcessObject::DataObjectPointerMap = std::map<DataObjectIdentifierType, DataObjectPointer> private
STL map to store the named inputs and outputs
Definition at line 958 of file itkProcessObject.h.
MultiThreaderType
using itk::ProcessObject::MultiThreaderType = MultiThreaderBase
Type of general multi-threader interface
Definition at line 167 of file itkProcessObject.h.
NameArray
using itk::ProcessObject::NameArray = std::vector<DataObjectIdentifierType>
STL array of data object names
Definition at line 164 of file itkProcessObject.h.
NameSet
using itk::ProcessObject::NameSet = std::set<DataObjectIdentifierType> private
STL map to store the named inputs and outputs
Definition at line 975 of file itkProcessObject.h.
Pointer
using itk::ProcessObject::Pointer = SmartPointer<Self>
Definition at line 146 of file itkProcessObject.h.
Self
using itk::ProcessObject::Self = ProcessObject
Standard class type aliases.
Definition at line 144 of file itkProcessObject.h.
Superclass
using itk::ProcessObject::Superclass = Object
Definition at line 145 of file itkProcessObject.h.
Constructor & Destructor Documentation
ProcessObject()
itk::ProcessObject::ProcessObject () protected
~ProcessObject()
itk::ProcessObject::~ProcessObject () override protected
Member Function Documentation
AbortGenerateDataOn()
virtual void itk::ProcessObject::AbortGenerateDataOn () virtual
Turn on and off the AbortGenerateData flag.
AddInput()
virtual void itk::ProcessObject::AddInput (DataObject * input) protected virtual
Sets first nullptr indexed input, appends to the end otherwise
AddOptionalInputName() [1/2]
void itk::ProcessObject::AddOptionalInputName (const DataObjectIdentifierType &) protected
Define a named input that is not required and optionally associate with a numbered index.
The previous named input associated with idx will be removed from the defined input names.
If the specified named inputs already exists with a non-null value, then that value will be used. Otherwise if the specified index has a non-null value, then that will be the value set.
AddOptionalInputName() [2/2]
void itk::ProcessObject::AddOptionalInputName (const DataObjectIdentifierType & , DataObjectPointerArraySizeType idx) protected
AddOutput()
virtual void itk::ProcessObject::AddOutput (DataObject * output) protected virtual
AddRequiredInputName() [1/2]
bool itk::ProcessObject::AddRequiredInputName (const DataObjectIdentifierType &) protected
Define a required named input and optionally associate it with a numbered index.
The previous named input associated with idx will be removed from the defined input names.
If the specified named inputs already exists with a non-null value, then that value will be used. Otherwise if the specified index has a non-null value, then that will be the value set.
AddRequiredInputName() [2/2]
bool itk::ProcessObject::AddRequiredInputName (const DataObjectIdentifierType & , DataObjectPointerArraySizeType idx) protected
CacheInputReleaseDataFlags()
virtual void itk::ProcessObject::CacheInputReleaseDataFlags () protected virtual
Cache the state of any ReleaseDataFlag's on the inputs. While the filter is executing, we need to set the ReleaseDataFlag's on the inputs to false in case the current filter is implemented using a mini-pipeline (which will try to release the inputs). After the filter finishes, we restore the state of the ReleaseDataFlag's before the call to ReleaseInputs().
EnlargeOutputRequestedRegion()
virtual void itk::ProcessObject::EnlargeOutputRequestedRegion (DataObject *) inline virtual
Give the process object a chance to indicate that it will produce more output than it was requested to produce. For example, many imaging filters must compute the entire output at once or can only produce output in complete slices. Such filters cannot handle smaller requested regions. These filters must provide an implementation of this method, setting the output requested region to the size they will produce. By default, a process object does not modify the size of the output requested region.
Reimplemented in itk::N4BiasFieldCorrectionImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::CurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::IsoContourDistanceImageFilter< TInputImage, TOutputImage >, itk::HalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::HalfHermitianToRealInverseFFTImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::InverseFFTImageFilter< TInputImage, TOutputImage >, itk::InverseFFTImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::HoughTransform2DCirclesImageFilter< TInputPixelType, TOutputPixelType, TRadiusPixelType >, itk::MultiScaleHessianBasedMeasureImageFilter< TInputImage, THessianImage, TOutputImage >, itk::LabelMapContourOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::LabelMapOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::OrientImageFilter< TInputImage, TOutputImage >, itk::BinaryContourImageFilter< TInputImage, TOutputImage >, itk::LabelContourImageFilter< TInputImage, TOutputImage >, itk::ImagePCAShapeModelEstimator< TInputImage, TOutputImage >, itk::BinaryFillholeImageFilter< TInputImage >, itk::BinaryGrindPeakImageFilter< TInputImage >, itk::BinaryReconstructionByDilationImageFilter< TInputImage >, itk::BinaryReconstructionByErosionImageFilter< TInputImage >, itk::BinaryShapeKeepNObjectsImageFilter< TInputImage >, itk::BinaryShapeOpeningImageFilter< TInputImage >, itk::BinaryStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::BinaryStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::ChangeRegionLabelMapFilter< TInputImage >, itk::LabelMapFilter< TInputImage, TOutputImage >, itk::LabelMapFilter< TImage, TImage >, itk::LabelMapFilter< TInputImage, TInputImage >, itk::LabelMapFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::LabelMapFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::LabelMapMaskImageFilter< TInputImage, TOutputImage >, itk::LabelMapToAttributeImageFilter< TInputImage, TOutputImage, TAttributeAccessor >, itk::LabelMapToBinaryImageFilter< TInputImage, TOutputImage >, itk::LabelShapeKeepNObjectsImageFilter< TInputImage >, itk::LabelShapeOpeningImageFilter< TInputImage >, itk::LabelStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::LabelStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::ShapeRelabelImageFilter< TInputImage >, itk::StatisticsRelabelImageFilter< TInputImage, TFeatureImage >, itk::ClosingByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::DoubleThresholdImageFilter< TInputImage, TOutputImage >, itk::GrayscaleConnectedClosingImageFilter< TInputImage, TOutputImage >, itk::GrayscaleConnectedOpeningImageFilter< TInputImage, TOutputImage >, itk::GrayscaleFillholeImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGeodesicDilateImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGeodesicErodeImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGrindPeakImageFilter< TInputImage, TOutputImage >, itk::HConcaveImageFilter< TInputImage, TOutputImage >, itk::HConvexImageFilter< TInputImage, TOutputImage >, itk::HMaximaImageFilter< TInputImage, TOutputImage >, itk::HMinimaImageFilter< TInputImage, TOutputImage >, itk::OpeningByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, TCompare >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::greater< TOutputImage::PixelType > >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::less< TOutputImage::PixelType > >, itk::RegionalMaximaImageFilter< TInputImage, TOutputImage >, itk::RegionalMinimaImageFilter< TInputImage, TOutputImage >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, TFunction1, TFunction2 >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::greater< TInputImage::PixelType >, std::greater< TOutputImage::PixelType > >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::less< TInputImage::PixelType >, std::less< TOutputImage::PixelType > >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, TAttribute, TFunction >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, typename TInputImage::SpacingType::ValueType, std::less< TInputImage::PixelType > >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, typename TInputImage::SpacingType::ValueType, std::greater< TInputImage::PixelType > >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TInputImage >, itk::KLMRegionGrowImageFilter< TInputImage, TOutputImage >, itk::MultiLabelSTAPLEImageFilter< TInputImage, TOutputImage, TWeights >, itk::ExtensionVelocitiesImageFilter< TLevelSet, TAuxValue, VAuxDimension >, itk::ReinitializeLevelSetImageFilter< TLevelSet >, itk::MRFImageFilter< TInputImage, TClassifiedImage >, itk::MorphologicalWatershedFromMarkersImageFilter< TInputImage, TLabelImage >, itk::MorphologicalWatershedImageFilter< TInputImage, TOutputImage >, itk::TobogganImageFilter< TInputImage, TOutputImage >, itk::Testing::HashImageFilter< TImageType >, itk::ContourDirectedMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::ContourMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::DirectedHausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::HausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::SimilarityIndexImageFilter< TInputImage1, TInputImage2 >, itk::WatershedImageFilter< TInputImage >, itk::ImportImageFilter< TPixel, VImageDimension >, itk::BSplineDecompositionImageFilter< TInputImage, TOutputImage >, itk::PipelineMonitorImageFilter< TImageType >, itk::MaskedFFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::FastMarchingExtensionImageFilter< TLevelSet, TAuxValue, VAuxDimension, TSpeedImage >, itk::FastMarchingImageFilter< TLevelSet, TSpeedImage >, itk::FastMarchingImageFilter< TLevelSet, Image< float, TLevelSet::ImageDimension > >, itk::ComplexToComplex1DFFTImageFilter< TInputImage, TOutputImage >, itk::ComplexToComplex1DFFTImageFilter< TInputImage, TInputImage >, itk::Forward1DFFTImageFilter< TInputImage, TOutputImage >, itk::Forward1DFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ForwardFFTImageFilter< TInputImage, TOutputImage >, itk::ForwardFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::Inverse1DFFTImageFilter< TInputImage, TOutputImage >, itk::Inverse1DFFTImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::RealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::RealToHalfHermitianForwardFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::HessianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::HoughTransform2DLinesImageFilter< TInputPixelType, TOutputPixelType >, itk::LaplacianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::RecursiveSeparableImageFilter< TInputImage, TOutputImage >, itk::RecursiveSeparableImageFilter< TInputImage, TInputImage >, itk::GradientMagnitudeRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::GradientRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::BSplineDownsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::BSplineUpsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::RegionOfInterestImageFilter< TInputImage, TOutputImage >, itk::ExtractOrthogonalSwath2DImageFilter< TImage >, itk::SmoothingRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::ImageFileReader< TOutputImage, ConvertPixelTraits >, itk::ImageSeriesReader< TOutputImage >, itk::BlockMatchingImageFilter< TFixedImage, TMovingImage, TFeatures, TDisplacements, TSimilarities >, itk::ConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::ConnectedThresholdImageFilter< TInputImage, TOutputImage >, itk::IsolatedConnectedImageFilter< TInputImage, TOutputImage >, itk::NeighborhoodConnectedImageFilter< TInputImage, TOutputImage >, itk::VectorConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::SLICImageFilter< TInputImage, TOutputImage, TDistancePixel >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, TBinaryPriorImage >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, Image< unsigned char, 2 > >, itk::IsolatedWatershedImageFilter< TInputImage, TOutputImage >, itk::TemporalProcessObject, and itk::MultiResolutionPDEDeformableRegistration< TFixedImage, TMovingImage, TDisplacementField, TRealType, TFloatImageType, TRegistrationType, TDefaultRegistrationType >.
Definition at line 425 of file itkProcessObject.h.
GenerateData()
virtual void itk::ProcessObject::GenerateData () inline protected virtual
This method causes the filter to generate its output.
Reimplemented in itk::DiscreteCurvatureTensorQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::VTKImageImport< TOutputImage >, itk::ExtractImageFilter< TInputImage, TOutputImage >, itk::ImageSource< TOutputImage >, itk::ImageSource< TImageType >, itk::ImageSource< TInputImage >, itk::ImageSource< TImage >, itk::ImageSource< TInputImage1 >, itk::ImageSource< Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageSource< VectorImage< float, TInputImage::ImageDimension > >, itk::ImageSource< Image< float, TInputImage::ImageDimension > >, itk::ImageSource< VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< DiffusionTensor3D< double >, 3 > >, itk::ImageSource< TEigenValueImage >, itk::ImageSource< Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageSource< TLevelSet >, itk::ImageSource< TSparseOutputImageType >, itk::ImageSource< Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< TPixel, 3 > >, itk::ImageSource< Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< double, 3 > >, itk::ImageSource< Image< SizeValueType, 3 > >, itk::ImageSource< Image< float, 3 > >, itk::ImageSource< Image< TOutputPixelType, 2 > >, itk::ImageSource< Image< double, TInputImage::ImageDimension > >, itk::ImageSource< TSparseOutputImage >, itk::ImageSource< Image< TPixel, 2 > >, itk::ImageSource< Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageSource< TLabelImage >, itk::ImageSource< Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageSource< Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageSource< TClassifiedImage >, itk::ImageSource< itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageSource< TDisplacementField >, itk::ImageSource< Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageSource< Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageSource< Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageSource< ImageType >, itk::ImportImageFilter< TPixel, VImageDimension >, itk::PointSetToImageFilter< TInputPointSet, TOutputImage >, itk::StreamingProcessObject, itk::FiniteDifferenceImageFilter< TInputImage, TOutputImage >, itk::FiniteDifferenceImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::FiniteDifferenceImageFilter< TInputImageType, TSparseOutputImageType >, itk::FiniteDifferenceImageFilter< TInputImage, TSparseOutputImage >, itk::FiniteDifferenceImageFilter< TDisplacementField, TDisplacementField >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, BinaryThresholdImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, BoxImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, CastImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, DiscreteGaussianImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, FiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TInputImage, InPlaceImageFilter< TInputImage, TInputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, MeanImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, typename TOutputImage::PixelType > >, itk::GPUImageToImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, InPlaceImageFilter< TInputImage, TOutputImage > >, itk::BSplineDecompositionImageFilter< TInputImage, TOutputImage >, itk::AutomaticTopologyMeshSource< TOutputMesh >, itk::BinaryMask3DMeshSource< TInputImage, TOutputMesh >, itk::ConnectedRegionsMeshFilter< TInputMesh, TOutputMesh >, itk::ImageToParametricSpaceFilter< TInputImage, TOutputMesh >, itk::InteriorExteriorMeshFilter< TInputMesh, TOutputMesh, TSpatialFunction >, itk::ParametricSpaceToImageSpaceMeshFilter< TInputMesh, TOutputMesh >, itk::RegularSphereMeshSource< TOutputMesh >, itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >, itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >, itk::TransformMeshFilter< TInputMesh, TOutputMesh, TTransform >, itk::TriangleMeshToBinaryImageFilter< TInputMesh, TOutputImage >, itk::TriangleMeshToSimplexMeshFilter< TInputMesh, TOutputMesh >, itk::VTKPolyDataReader< TOutputMesh >, itk::WarpMeshFilter< TInputMesh, TOutputMesh, TDisplacementField >, itk::SpatialObjectToImageFilter< TInputSpatialObject, TOutputImage >, itk::SpatialObjectToPointSetFilter< TPointBasedSpatialObject, TOutputPointSet >, itk::PipelineMonitorImageFilter< TImageType >, itk::TransformGeometryImageFilter< TInputImage, TOutputImage >, itk::AntiAliasBinaryImageFilter< TInputImage, TOutputImage >, itk::MRIBiasFieldCorrectionFilter< TInputImage, TOutputImage, TMaskImage >, itk::N4BiasFieldCorrectionImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::BinaryClosingByReconstructionImageFilter< TInputImage, TKernel >, itk::BinaryDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryMorphologicalClosingImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryMorphologicalOpeningImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryOpeningByReconstructionImageFilter< TInputImage, TKernel >, itk::BinaryPruningImageFilter< TInputImage, TOutputImage >, itk::BinaryThinningImageFilter< TInputImage, TOutputImage >, itk::ConvolutionImageFilter< TInputImage, TKernelImage, TOutputImage >, itk::FFTConvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::FFTConvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::FFTConvolutionImageFilter< TInputImage, TKernelSource::OutputImageType, TInputImage, double >, itk::FFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage >, itk::MaskedFFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::InverseDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::InverseDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::IterativeDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::IterativeDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::IterativeDeconvolutionImageFilter< TInputImage, TKernelSource::OutputImageType, TInputImage >, itk::TikhonovDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::WienerDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::PatchBasedDenoisingBaseImageFilter< TInputImage, TOutputImage >, itk::DisplacementFieldToBSplineImageFilter< TInputImage, TInputPointSet, TOutputImage >, itk::ExponentialDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::InverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::InvertDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::IterativeInverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::LandmarkDisplacementFieldSource< TOutputImage >, itk::ApproximateSignedDistanceMapImageFilter< TInputImage, TOutputImage >, itk::ContourMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::DanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::DanielssonDistanceMapImageFilter< ImageType, ImageType >, itk::FastChamferDistanceImageFilter< TInputImage, TOutputImage >, itk::HausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::IsoContourDistanceImageFilter< TInputImage, TOutputImage >, itk::SignedDanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::SignedMaurerDistanceMapImageFilter< TInputImage, TOutputImage >, itk::FastMarchingImageFilter< TLevelSet, TSpeedImage >, itk::FastMarchingImageFilter< TLevelSet, Image< float, TLevelSet::ImageDimension > >, itk::FastMarchingUpwindGradientImageFilter< TLevelSet, TSpeedImage >, itk::FFTShiftImageFilter< TInputImage, TOutputImage >, itk::FFTWForwardFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWRealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::VnlComplexToComplex1DFFTImageFilter< TInputImage, TOutputImage >, itk::VnlForward1DFFTImageFilter< TInputImage, TOutputImage >, itk::VnlForwardFFTImageFilter< TInputImage, TOutputImage >, itk::VnlHalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::VnlInverse1DFFTImageFilter< TInputImage, TOutputImage >, itk::VnlInverseFFTImageFilter< TInputImage, TOutputImage >, itk::VnlRealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::STAPLEImageFilter< TInputImage, TOutputImage >, itk::CannyEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::CannyEdgeDetectionImageFilter< ImageType, ImageType >, itk::DerivativeImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianDerivativeImageFilter< TInputImage, TOutputImage >, itk::GradientVectorFlowImageFilter< TInputImage, TOutputImage, TInternalPixel >, itk::Hessian3DToVesselnessMeasureImageFilter< TPixel >, itk::HessianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::HoughTransform2DCirclesImageFilter< TInputPixelType, TOutputPixelType, TRadiusPixelType >, itk::HoughTransform2DLinesImageFilter< TInputPixelType, TOutputPixelType >, itk::LaplacianImageFilter< TInputImage, TOutputImage >, itk::LaplacianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::LaplacianSharpeningImageFilter< TInputImage, TOutputImage >, itk::MaskFeaturePointSelectionFilter< TImage, TMask, TFeatures >, itk::MultiScaleHessianBasedMeasureImageFilter< TInputImage, THessianImage, TOutputImage >, itk::SobelEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::UnsharpMaskImageFilter< TInputImage, TOutputImage, TInternalPrecision >, itk::ZeroCrossingBasedEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::CastImageFilter< TInputImage, TOutputImage >, itk::CastImageFilter< FeatureImageType, ImageType >, itk::RecursiveSeparableImageFilter< TInputImage, TOutputImage >, itk::RecursiveSeparableImageFilter< TInputImage, TInputImage >, itk::LabelMapContourOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::LabelMapOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::DifferenceOfGaussiansGradientImageFilter< TInputImage, TDataType >, itk::GradientMagnitudeRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::GradientRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::BSplineDownsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::BSplineScatteredDataPointSetToImageFilter< TInputPointSet, TOutputImage >, itk::BSplineUpsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::ChangeInformationImageFilter< TInputImage >, itk::OrientImageFilter< TInputImage, TOutputImage >, itk::SliceBySliceImageFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::TileImageFilter< TInputImage, TOutputImage >, itk::ClampImageFilter< TInputImage, TOutputImage >, itk::NormalizeImageFilter< TInputImage, TOutputImage >, itk::NormalizeToConstantImageFilter< TInputImage, TOutputImage >, itk::PolylineMask2DImageFilter< TInputImage, TPolyline, TOutputImage >, itk::PolylineMaskImageFilter< TInputImage, TPolyline, TVector, TOutputImage >, itk::BinaryContourImageFilter< TInputImage, TOutputImage >, itk::LabelContourImageFilter< TInputImage, TOutputImage >, itk::GaborImageSource< TOutputImage >, itk::GaussianImageSource< TOutputImage >, itk::AccumulateImageFilter< TInputImage, TOutputImage >, itk::ImagePCAShapeModelEstimator< TInputImage, TOutputImage >, itk::ImageShapeModelEstimatorBase< TInputImage, TOutputImage >, itk::ImageShapeModelEstimatorBase< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::AggregateLabelMapFilter< TImage >, itk::AttributeKeepNObjectsLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeOpeningLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeRelabelLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeRelabelLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::AttributeSelectionLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeSelectionLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::AttributeUniqueLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeUniqueLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::BinaryFillholeImageFilter< TInputImage >, itk::BinaryGrindPeakImageFilter< TInputImage >, itk::BinaryNotImageFilter< TImage >, itk::BinaryReconstructionByDilationImageFilter< TInputImage >, itk::BinaryReconstructionByErosionImageFilter< TInputImage >, itk::BinaryShapeKeepNObjectsImageFilter< TInputImage >, itk::BinaryShapeOpeningImageFilter< TInputImage >, itk::BinaryStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::BinaryStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::ChangeLabelLabelMapFilter< TImage >, itk::ChangeRegionLabelMapFilter< TInputImage >, itk::ConvertLabelMapFilter< TInputImage, TOutputImage >, itk::LabelMapMaskImageFilter< TInputImage, TOutputImage >, itk::LabelMapToAttributeImageFilter< TInputImage, TOutputImage, TAttributeAccessor >, itk::LabelMapToBinaryImageFilter< TInputImage, TOutputImage >, itk::LabelShapeKeepNObjectsImageFilter< TInputImage >, itk::LabelShapeOpeningImageFilter< TInputImage >, itk::LabelStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::LabelStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::MergeLabelMapFilter< TImage >, itk::ObjectByObjectLabelMapFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::ShapeKeepNObjectsLabelMapFilter< TImage >, itk::ShapeOpeningLabelMapFilter< TImage >, itk::ShapeRelabelImageFilter< TInputImage >, itk::ShapeRelabelLabelMapFilter< TImage >, itk::ShapeUniqueLabelMapFilter< TImage >, itk::ShiftScaleLabelMapFilter< TImage >, itk::StatisticsKeepNObjectsLabelMapFilter< TImage >, itk::StatisticsOpeningLabelMapFilter< TImage >, itk::StatisticsRelabelImageFilter< TInputImage, TFeatureImage >, itk::StatisticsRelabelLabelMapFilter< TImage >, itk::StatisticsUniqueLabelMapFilter< TImage >, itk::BlackTopHatImageFilter< TInputImage, TOutputImage, TKernel >, itk::ClosingByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::DoubleThresholdImageFilter< TInputImage, TOutputImage >, itk::GrayscaleConnectedClosingImageFilter< TInputImage, TOutputImage >, itk::GrayscaleConnectedOpeningImageFilter< TInputImage, TOutputImage >, itk::GrayscaleDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleFillholeImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGeodesicDilateImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGeodesicErodeImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGrindPeakImageFilter< TInputImage, TOutputImage >, itk::GrayscaleMorphologicalClosingImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleMorphologicalOpeningImageFilter< TInputImage, TOutputImage, TKernel >, itk::HConcaveImageFilter< TInputImage, TOutputImage >, itk::HConvexImageFilter< TInputImage, TOutputImage >, itk::HMaximaImageFilter< TInputImage, TOutputImage >, itk::HMinimaImageFilter< TInputImage, TOutputImage >, itk::MorphologicalGradientImageFilter< TInputImage, TOutputImage, TKernel >, itk::OpeningByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, TCompare >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::greater< TOutputImage::PixelType > >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::less< TOutputImage::PixelType > >, itk::RegionalMaximaImageFilter< TInputImage, TOutputImage >, itk::RegionalMinimaImageFilter< TInputImage, TOutputImage >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, TFunction1, TFunction2 >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::greater< TInputImage::PixelType >, std::greater< TOutputImage::PixelType > >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::less< TInputImage::PixelType >, std::less< TOutputImage::PixelType > >, itk::WhiteTopHatImageFilter< TInputImage, TOutputImage, TKernel >, itk::ChainCodeToFourierSeriesPathFilter< TInputChainCodePath, TOutputFourierSeriesPath >, itk::ContourExtractor2DImageFilter< TInputImage >, itk::ExtractOrthogonalSwath2DImageFilter< TImage >, itk::OrthogonalSwath2DPathFilter< TFourierSeriesPath, TSwathMeritImage >, itk::PathToChainCodePathFilter< TInputPath, TOutputChainCodePath >, itk::PathToImageFilter< TInputPath, TOutputImage >, itk::BorderQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::CleanQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >, itk::DelaunayConformingQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscreteCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscreteCurvatureQuadEdgeMeshFilter< TInputMesh, TInputMesh >, itk::LaplacianDeformationQuadEdgeMeshFilterWithHardConstraints< TInputMesh, TOutputMesh, TSolverTraits >, itk::LaplacianDeformationQuadEdgeMeshFilterWithSoftConstraints< TInputMesh, TOutputMesh, TSolverTraits >, itk::NormalQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::ParameterizationQuadEdgeMeshFilter< TInputMesh, TOutputMesh, TSolverTraits >, itk::SmoothingQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::BinomialBlurImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TInputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::FFTDiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::SmoothingRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::SpatialFunctionImageEvaluatorFilter< TSpatialFunction, TInputImage, TOutputImage >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TOutputImage >, itk::HuangThresholdCalculator< THistogram, TOutput >, itk::IntermodesThresholdCalculator< THistogram, TOutput >, itk::IntermodesThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::IsoDataThresholdCalculator< THistogram, TOutput >, itk::KappaSigmaThresholdImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::KittlerIllingworthThresholdCalculator< THistogram, TOutput >, itk::LiThresholdCalculator< THistogram, TOutput >, itk::MaximumEntropyThresholdCalculator< THistogram, TOutput >, itk::MomentsThresholdCalculator< THistogram, TOutput >, itk::OtsuMultipleThresholdsImageFilter< TInputImage, TOutputImage >, itk::OtsuThresholdCalculator< THistogram, TOutput >, itk::OtsuThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::RenyiEntropyThresholdCalculator< THistogram, TOutput >, itk::ShanbhagThresholdCalculator< THistogram, TOutput >, itk::TriangleThresholdCalculator< THistogram, TOutput >, itk::YenThresholdCalculator< THistogram, TOutput >, itk::ImageFileReader< TOutputImage, ConvertPixelTraits >, itk::ImageFileWriter< TInputImage >, itk::ImageSeriesReader< TOutputImage >, itk::ImageSeriesWriter< TInputImage, TOutputImage >, itk::MeshFileReader< TOutputMesh, ConvertPointPixelTraits, ConvertCellPixelTraits >, itk::AreaClosingImageFilter< TInputImage, TOutputImage, TAttribute >, itk::AreaOpeningImageFilter< TInputImage, TOutputImage, TAttribute >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, TAttribute, TFunction >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, typename TInputImage::SpacingType::ValueType, std::less< TInputImage::PixelType > >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, typename TInputImage::SpacingType::ValueType, std::greater< TInputImage::PixelType > >, itk::ConformalFlatteningMeshFilter< TInputMesh, TOutputMesh >, itk::DirectFourierReconstructionImageToImageFilter< TInputImage, TOutputImage >, itk::GridForwardWarpImageFilter< TDisplacementField, TOutputImage >, itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >, itk::MiniPipelineSeparableImageFilter< TInputImage, TOutputImage, TFilter >, itk::MiniPipelineSeparableImageFilter< TInputImage, TOutputImage, RankImageFilter< TInputImage, TInputImage, FlatStructuringElement< TInputImage::ImageDimension > > >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFiniteDifferenceFunction, TIdCell >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFunction, unsigned int >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, ScalarChanAndVeseLevelSetFunction< TInputImage, TFeatureImage >, unsigned int >, itk::RobustAutomaticThresholdImageFilter< TInputImage, TGradientImage, TOutputImage >, itk::StochasticFractalDimensionImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::EigenAnalysis2DImageFilter< TInputImage, TEigenValueImage, TEigenVectorImage >, itk::NarrowBandImageFilterBase< TInputImage, TOutputImage >, itk::NarrowBandImageFilterBase< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::Statistics::CovarianceSampleFilter< TSample >, itk::HistogramToImageFilter< THistogram, TImage, TFunction >, itk::HistogramToImageFilter< THistogram, Image< double, 3 >, Function::HistogramEntropyFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< SizeValueType, 3 >, Function::HistogramIntensityFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< double, 3 >, Function::HistogramLogProbabilityFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< float, 3 >, Function::HistogramProbabilityFunction< SizeValueType, TImage::PixelType > >, itk::Statistics::HistogramToRunLengthFeaturesFilter< THistogram >, itk::Statistics::HistogramToTextureFeaturesFilter< THistogram >, itk::Statistics::ImageClassifierFilter< TSample, TInputImage, TOutputImage >, itk::Statistics::ImageToListSampleFilter< TImage, TMaskImage >, itk::Statistics::MeanSampleFilter< TSample >, itk::Statistics::NeighborhoodSampler< TSample >, itk::Statistics::SampleClassifierFilter< TSample >, itk::Statistics::ScalarImageToCooccurrenceListSampleFilter< TImage >, itk::Statistics::ScalarImageToCooccurrenceMatrixFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::Statistics::ScalarImageToRunLengthFeaturesFilter< TImageType, THistogramFrequencyContainer >, itk::Statistics::ScalarImageToRunLengthMatrixFilter< TImageType, THistogramFrequencyContainer >, itk::Statistics::ScalarImageToTextureFeaturesFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::Statistics::StandardDeviationPerComponentSampleFilter< TSample >, itk::Statistics::WeightedCovarianceSampleFilter< TSample >, itk::Statistics::WeightedMeanSampleFilter< TSample >, itk::BlockMatchingImageFilter< TFixedImage, TMovingImage, TFeatures, TDisplacements, TSimilarities >, itk::ImageRegistrationMethod< TFixedImage, TMovingImage >, itk::ImageToSpatialObjectRegistrationMethod< TFixedImage, TMovingSpatialObject >, itk::MultiResolutionImageRegistrationMethod< TFixedImage, TMovingImage >, itk::MultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::PointSetToImageRegistrationMethod< TFixedPointSet, TMovingImage >, itk::PointSetToPointSetRegistrationMethod< TFixedPointSet, TMovingPointSet >, itk::RecursiveMultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::MultiResolutionPDEDeformableRegistration< TFixedImage, TMovingImage, TDisplacementField, TRealType, TFloatImageType, TRegistrationType, TDefaultRegistrationType >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, BSplineSmoothingOnUpdateDisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, DisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, TimeVaryingBSplineVelocityFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::SyNImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::SyNImageRegistrationMethod< TFixedImage, TMovingImage, BSplineSmoothingOnUpdateDisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::TimeVaryingBSplineVelocityFieldImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::TimeVaryingVelocityFieldImageRegistrationMethodv4< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::BayesianClassifierImageFilter< TInputVectorImage, TLabelsType, TPosteriorsPrecisionType, TPriorsPrecisionType >, itk::BayesianClassifierInitializationImageFilter< TInputImage, TProbabilityPrecisionType >, itk::ScalarImageKmeansImageFilter< TInputImage, TOutputImage >, itk::ConnectedComponentFunctorImageFilter< TInputImage, TOutputImage, TFunctor, TMaskImage >, itk::ConnectedComponentFunctorImageFilter< TInputImage, TOutputImage, Functor::SimilarPixelsFunctor< TInputImage::ValueType >, TInputImage >, itk::ConnectedComponentFunctorImageFilter< TInputImage, TOutputImage, Functor::SimilarVectorsFunctor< TInputImage::ValueType >, TInputImage >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TInputImage >, itk::HardConnectedComponentImageFilter< TInputImage, TOutputImage >, itk::RelabelComponentImageFilter< TInputImage, TOutputImage >, itk::ThresholdMaximumConnectedComponentsImageFilter< TInputImage, TOutputImage >, itk::DeformableSimplexMesh3DFilter< TInputMesh, TOutputMesh >, itk::KLMRegionGrowImageFilter< TInputImage, TOutputImage >, itk::MultiLabelSTAPLEImageFilter< TInputImage, TOutputImage, TWeights >, itk::VotingBinaryIterativeHoleFillingImageFilter< TImage >, itk::BinaryMaskToNarrowBandPointSetFilter< TInputImage, TOutputMesh >, itk::CollidingFrontsImageFilter< TInputImage, TOutputImage >, itk::CurvesLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::GeodesicActiveContourLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::GeodesicActiveContourShapePriorLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::NarrowBandCurvesLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType, TOutputImage >, itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, float, Image< float, TInputImage::ImageDimension > >, itk::ParallelSparseFieldLevelSetImageFilter< TInputImage, TOutputImage >, itk::ReinitializeLevelSetImageFilter< TLevelSet >, itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >, itk::ShapeDetectionLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ShapePriorSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ShapePriorSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >, itk::LevelSetDomainMapImageFilter< TInputImage, TOutputImage >, itk::MRFImageFilter< TInputImage, TClassifiedImage >, itk::RGBGibbsPriorFilter< TInputImage, TClassifiedImage >, itk::ConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::ConnectedThresholdImageFilter< TInputImage, TOutputImage >, itk::IsolatedConnectedImageFilter< TInputImage, TOutputImage >, itk::NeighborhoodConnectedImageFilter< TInputImage, TOutputImage >, itk::VectorConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::SLICImageFilter< TInputImage, TOutputImage, TDistancePixel >, itk::VoronoiDiagram2DGenerator< TCoordType >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, TBinaryPriorImage >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, Image< unsigned char, 2 > >, itk::IsolatedWatershedImageFilter< TInputImage, TOutputImage >, itk::MorphologicalWatershedFromMarkersImageFilter< TInputImage, TLabelImage >, itk::MorphologicalWatershedImageFilter< TInputImage, TOutputImage >, itk::TobogganImageFilter< TInputImage, TOutputImage >, itk::watershed::BoundaryResolver< TPixelType, TDimension >, itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >, itk::WatershedImageFilter< TInputImage >, itk::watershed::Relabeler< TScalar, TImageDimension >, itk::watershed::Relabeler< ScalarType, Self::ImageDimension >, itk::watershed::Segmenter< TInputImage >, itk::watershed::Segmenter< InputImageType >, itk::watershed::SegmentTreeGenerator< TScalar >, itk::watershed::SegmentTreeGenerator< ScalarType >, and itk::TemporalProcessObject.
Definition at line 860 of file itkProcessObject.h.
GenerateInputRequestedRegion()
virtual void itk::ProcessObject::GenerateInputRequestedRegion () protected virtual
What is the input requested region that is required to produce the output requested region? By default, the largest possible region is always required but this is overridden in many subclasses. For instance, for an image processing filter where an output pixel is a simple function of an input pixel, the input requested region will be set to the output requested region. For an image processing filter where an output pixel is a function of the pixels in a neighborhood of an input pixel, then the input requested region will need to be larger than the output requested region (to avoid introducing artificial boundary conditions). This function should never request an input region that is outside the the input largest possible region (i.e. implementations of this method should crop the input requested region at the boundaries of the input largest possible region).
Reimplemented in itk::ImageToImageFilter< TInputImage, TOutputImage >, itk::ImageToImageFilter< TImageType, TImageType >, itk::ImageToImageFilter< TInputImage, TInputImage >, itk::ImageToImageFilter< TImage, TImage >, itk::ImageToImageFilter< TInputImage1, TInputImage1 >, itk::ImageToImageFilter< TInputVectorImage, Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage1, TOutputImage >, itk::ImageToImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TReferenceImagePixelType, 3 >, Image< DiffusionTensor3D< double >, 3 > >, itk::ImageToImageFilter< TInputImage, TEigenValueImage >, itk::ImageToImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< float, TLevelSet::ImageDimension >, TLevelSet >, itk::ImageToImageFilter< TInputImageType, TSparseOutputImageType >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TDisplacementField, TOutputImage >, itk::ImageToImageFilter< Image< SymmetricSecondRankTensor< double, 3 >, 3 >, Image< TPixel, 3 > >, itk::ImageToImageFilter< TInputImage, Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TInputPixelType, 2 >, Image< TOutputPixelType, 2 > >, itk::ImageToImageFilter< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TSparseOutputImage >, itk::ImageToImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageToImageFilter< TLabelImage, TLabelImage >, itk::ImageToImageFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TLabelImage, TOutputImage >, itk::ImageToImageFilter< TInputImage, TClassifiedImage >, itk::ImageToImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TLabelImage >, itk::ImageToImageFilter< TDisplacementField, TDisplacementField >, itk::ImageToImageFilter< TFeatureImage, TOutputImage >, itk::ImageToImageFilter< TLevelSet, TLevelSet >, itk::ImageToImageFilter< TInputImage, Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageToImageFilter< TMask, TImage >, itk::ImageToImageFilter< TTimeVaryingVelocityField, Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageToImageFilter< TInputImage, Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< ImageType, ImageType >, itk::ImageToImageFilter< FeatureImageType, ImageType >, itk::FiniteDifferenceImageFilter< TInputImage, TOutputImage >, itk::FiniteDifferenceImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::FiniteDifferenceImageFilter< TInputImageType, TSparseOutputImageType >, itk::FiniteDifferenceImageFilter< TInputImage, TSparseOutputImage >, itk::FiniteDifferenceImageFilter< TDisplacementField, TDisplacementField >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::BSplineDecompositionImageFilter< TInputImage, TOutputImage >, itk::MeshSource< TOutputMesh >, itk::MeshSource< PointSet< Vector< typename TFeatures::PointType::ValueType, TFeatures::PointDimension >, TFeatures::PointDimension > >, itk::MeshSource< TInputMesh >, itk::MeshSource< TOutput >, itk::MeshSource< PointSet< Matrix< SpacePrecisionType, TImage::ImageDimension, TImage::ImageDimension >, TImage::ImageDimension > >, itk::MeshSource< TOutputPointSet >, itk::MeshSource< VoronoiDiagram2D< TCoordType > >, itk::PipelineMonitorImageFilter< TImageType >, itk::BinaryClosingByReconstructionImageFilter< TInputImage, TKernel >, itk::BinaryOpeningByReconstructionImageFilter< TInputImage, TKernel >, itk::ObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::ConvolutionImageFilter< TInputImage, TKernelImage, TOutputImage >, itk::FFTConvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::FFTConvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::FFTConvolutionImageFilter< TInputImage, TKernelSource::OutputImageType, TInputImage, double >, itk::MaskedFFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::NormalizedCorrelationImageFilter< TInputImage, TMaskImage, TOutputImage, TOperatorValueType >, itk::CurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::IterativeDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::IterativeDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::IterativeDeconvolutionImageFilter< TInputImage, TKernelSource::OutputImageType, TInputImage >, itk::PatchBasedDenoisingBaseImageFilter< TInputImage, TOutputImage >, itk::PatchBasedDenoisingImageFilter< TInputImage, TOutputImage >, itk::DisplacementFieldJacobianDeterminantFilter< TInputImage, TRealType, TOutputImage >, itk::InverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::ContourDirectedMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::ContourMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::DirectedHausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::HausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::IsoContourDistanceImageFilter< TInputImage, TOutputImage >, itk::ComplexToComplex1DFFTImageFilter< TInputImage, TOutputImage >, itk::ComplexToComplex1DFFTImageFilter< TInputImage, TInputImage >, itk::ComplexToComplexFFTImageFilter< TInputImage, TOutputImage >, itk::ComplexToComplexFFTImageFilter< TInputImage, TInputImage >, itk::Forward1DFFTImageFilter< TInputImage, TOutputImage >, itk::Forward1DFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ForwardFFTImageFilter< TInputImage, TOutputImage >, itk::ForwardFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::FullToHalfHermitianImageFilter< TInputImage >, itk::HalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::HalfHermitianToRealInverseFFTImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::HalfToFullHermitianImageFilter< TInputImage >, itk::Inverse1DFFTImageFilter< TInputImage, TOutputImage >, itk::Inverse1DFFTImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::InverseFFTImageFilter< TInputImage, TOutputImage >, itk::InverseFFTImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::RealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::RealToHalfHermitianForwardFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::GPUDiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::SimilarityIndexImageFilter< TInputImage1, TInputImage2 >, itk::JoinSeriesImageFilter< TInputImage, TOutputImage >, itk::BilateralImageFilter< TInputImage, TOutputImage >, itk::DerivativeImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianDerivativeImageFilter< TInputImage, TOutputImage >, itk::HessianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::HoughTransform2DCirclesImageFilter< TInputPixelType, TOutputPixelType, TRadiusPixelType >, itk::HoughTransform2DLinesImageFilter< TInputPixelType, TOutputPixelType >, itk::LaplacianImageFilter< TInputImage, TOutputImage >, itk::LaplacianSharpeningImageFilter< TInputImage, TOutputImage >, itk::SobelEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::UnsharpMaskImageFilter< TInputImage, TOutputImage, TInternalPrecision >, itk::ZeroCrossingImageFilter< TInputImage, TOutputImage >, itk::BoxImageFilter< TInputImage, TOutputImage >, itk::BoxImageFilter< TImageType, TImageType >, itk::BoxImageFilter< TImage, TImage >, itk::BoxImageFilter< TInputImage, TInputImage >, itk::MaskNeighborhoodOperatorImageFilter< TInputImage, TMaskImage, TOutputImage, TOperatorValueType >, itk::NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, TOperatorValueType >, itk::NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, typename TOutputImage::PixelType >, itk::VectorNeighborhoodOperatorImageFilter< TInputImage, TOutputImage >, itk::LabelMapContourOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::LabelMapOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::GradientImageFilter< TInputImage, TOperatorValueType, TOutputValueType, TOutputImageType >, itk::GradientMagnitudeImageFilter< TInputImage, TOutputImage >, itk::GradientMagnitudeRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::GradientRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::VectorGradientMagnitudeImageFilter< TInputImage, TRealType, TOutputImage >, itk::BinShrinkImageFilter< TInputImage, TOutputImage >, itk::BSplineDownsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::BSplineUpsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::ChangeInformationImageFilter< TInputImage >, itk::CyclicShiftImageFilter< TInputImage, TOutputImage >, itk::CyclicShiftImageFilter< TInputImage, TOutputImage >, itk::ExpandImageFilter< TInputImage, TOutputImage >, itk::FlipImageFilter< TImage >, itk::InterpolateImagePointsFilter< TInputImage, TOutputImage, TCoordType, InterpolatorType >, itk::MirrorPadImageFilter< TInputImage, TOutputImage >, itk::OrientImageFilter< TInputImage, TOutputImage >, itk::PadImageFilterBase< TInputImage, TOutputImage >, itk::PadImageFilterBase< TInputImage, TInputImage >, itk::PasteImageFilter< TInputImage, TSourceImage, TOutputImage >, itk::PermuteAxesImageFilter< TImage >, itk::RegionOfInterestImageFilter< TInputImage, TOutputImage >, itk::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType, TTransformPrecisionType >, itk::ShrinkImageFilter< TInputImage, TOutputImage >, itk::SliceBySliceImageFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::SliceImageFilter< TInputImage, TOutputImage >, itk::TileImageFilter< TInputImage, TOutputImage >, itk::WarpImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::WarpVectorImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::HistogramMatchingImageFilter< TInputImage, TOutputImage, THistogramMeasurement >, itk::NormalizeImageFilter< TInputImage, TOutputImage >, itk::NormalizeToConstantImageFilter< TInputImage, TOutputImage >, itk::BinaryContourImageFilter< TInputImage, TOutputImage >, itk::LabelContourImageFilter< TInputImage, TOutputImage >, itk::AccumulateImageFilter< TInputImage, TOutputImage >, itk::ImagePCAShapeModelEstimator< TInputImage, TOutputImage >, itk::ProjectionImageFilter< TInputImage, TOutputImage, TAccumulator >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::BinaryAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Function::BinaryThresholdAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MaximumAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MeanAccumulator< TInputImage::PixelType, typename NumericTraits< typename TOutputImage::PixelType >::AccumulateType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MedianAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MinimumAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::StandardDeviationAccumulator< TInputImage::PixelType, typename NumericTraits< typename TOutputImage::PixelType >::AccumulateType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::SumAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::BinaryFillholeImageFilter< TInputImage >, itk::BinaryGrindPeakImageFilter< TInputImage >, itk::BinaryReconstructionByDilationImageFilter< TInputImage >, itk::BinaryReconstructionByErosionImageFilter< TInputImage >, itk::BinaryShapeKeepNObjectsImageFilter< TInputImage >, itk::BinaryShapeOpeningImageFilter< TInputImage >, itk::BinaryStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::BinaryStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::ChangeRegionLabelMapFilter< TInputImage >, itk::LabelMapFilter< TInputImage, TOutputImage >, itk::LabelMapFilter< TImage, TImage >, itk::LabelMapFilter< TInputImage, TInputImage >, itk::LabelMapFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::LabelMapFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::LabelMapMaskImageFilter< TInputImage, TOutputImage >, itk::LabelMapToAttributeImageFilter< TInputImage, TOutputImage, TAttributeAccessor >, itk::LabelMapToBinaryImageFilter< TInputImage, TOutputImage >, itk::LabelShapeKeepNObjectsImageFilter< TInputImage >, itk::LabelShapeOpeningImageFilter< TInputImage >, itk::LabelStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::LabelStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::ShapeRelabelImageFilter< TInputImage >, itk::StatisticsRelabelImageFilter< TInputImage, TFeatureImage >, itk::ClosingByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::DoubleThresholdImageFilter< TInputImage, TOutputImage >, itk::GrayscaleConnectedClosingImageFilter< TInputImage, TOutputImage >, itk::GrayscaleConnectedOpeningImageFilter< TInputImage, TOutputImage >, itk::GrayscaleFillholeImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGeodesicDilateImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGeodesicErodeImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGrindPeakImageFilter< TInputImage, TOutputImage >, itk::HConcaveImageFilter< TInputImage, TOutputImage >, itk::HConvexImageFilter< TInputImage, TOutputImage >, itk::HMaximaImageFilter< TInputImage, TOutputImage >, itk::HMinimaImageFilter< TInputImage, TOutputImage >, itk::OpeningByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, TCompare >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::greater< TOutputImage::PixelType > >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::less< TOutputImage::PixelType > >, itk::RegionalMaximaImageFilter< TInputImage, TOutputImage >, itk::RegionalMinimaImageFilter< TInputImage, TOutputImage >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, TFunction1, TFunction2 >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::greater< TInputImage::PixelType >, std::greater< TOutputImage::PixelType > >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::less< TInputImage::PixelType >, std::less< TOutputImage::PixelType > >, itk::ContourExtractor2DImageFilter< TInputImage >, itk::ExtractOrthogonalSwath2DImageFilter< TImage >, itk::PathAndImageToPathFilter< TInputPath, TInputImage, TOutputPath >, itk::PathAndImageToPathFilter< TFourierSeriesPath, TSwathMeritImage, OrthogonallyCorrected2DParametricPath >, itk::PathToPathFilter< TInputPath, TOutputPath >, itk::PathToPathFilter< TInputChainCodePath, TOutputFourierSeriesPath >, itk::PathToPathFilter< TFourierSeriesPath, OrthogonallyCorrected2DParametricPath >, itk::PathToPathFilter< TInputPath, TOutputChainCodePath >, itk::BinomialBlurImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TInputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::FFTDiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::SmoothingRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TOutputImage >, itk::KappaSigmaThresholdImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::OtsuMultipleThresholdsImageFilter< TInputImage, TOutputImage >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, TAttribute, TFunction >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, typename TInputImage::SpacingType::ValueType, std::less< TInputImage::PixelType > >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, typename TInputImage::SpacingType::ValueType, std::greater< TInputImage::PixelType > >, itk::DirectFourierReconstructionImageToImageFilter< TInputImage, TOutputImage >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFiniteDifferenceFunction, TIdCell >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFunction, unsigned int >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, ScalarChanAndVeseLevelSetFunction< TInputImage, TFeatureImage >, unsigned int >, itk::RobustAutomaticThresholdImageFilter< TInputImage, TGradientImage, TOutputImage >, itk::Statistics::ImageToListSampleFilter< TImage, TMaskImage >, itk::MultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::RecursiveMultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::GPUPDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TParentImageFilter >, itk::GPUPDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::MultiResolutionPDEDeformableRegistration< TFixedImage, TMovingImage, TDisplacementField, TRealType, TFloatImageType, TRegistrationType, TDefaultRegistrationType >, itk::PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TInputImage >, itk::RelabelComponentImageFilter< TInputImage, TOutputImage >, itk::KLMRegionGrowImageFilter< TInputImage, TOutputImage >, itk::BinaryMedianImageFilter< TInputImage, TOutputImage >, itk::MultiLabelSTAPLEImageFilter< TInputImage, TOutputImage, TWeights >, itk::VotingBinaryImageFilter< TInputImage, TOutputImage >, itk::ReinitializeLevelSetImageFilter< TLevelSet >, itk::MRFImageFilter< TInputImage, TClassifiedImage >, itk::ConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::ConnectedThresholdImageFilter< TInputImage, TOutputImage >, itk::IsolatedConnectedImageFilter< TInputImage, TOutputImage >, itk::NeighborhoodConnectedImageFilter< TInputImage, TOutputImage >, itk::VectorConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, TBinaryPriorImage >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, Image< unsigned char, 2 > >, itk::IsolatedWatershedImageFilter< TInputImage, TOutputImage >, itk::MorphologicalWatershedFromMarkersImageFilter< TInputImage, TLabelImage >, itk::MorphologicalWatershedImageFilter< TInputImage, TOutputImage >, itk::TobogganImageFilter< TInputImage, TOutputImage >, itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >, itk::watershed::Relabeler< TScalar, TImageDimension >, itk::watershed::Relabeler< ScalarType, Self::ImageDimension >, itk::watershed::Segmenter< TInputImage >, itk::watershed::Segmenter< InputImageType >, itk::watershed::SegmentTreeGenerator< TScalar >, itk::watershed::SegmentTreeGenerator< ScalarType >, itk::TemporalProcessObject, itk::VideoToVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::VideoToVideoFilter< TVideoStream, TVideoStream >, and itk::VideoToVideoFilter< itk::VideoStream< TImageToImageFilter::InputImageType >, itk::VideoStream< TImageToImageFilter::OutputImageType > >.
GenerateOutputInformation()
virtual void itk::ProcessObject::GenerateOutputInformation () protected virtual
Generate the information describing the output data. The default implementation of this method will copy information from the input to the output. A filter may override this method if its output will have different information than its input. For instance, a filter that shrinks an image will need to provide an implementation for this method that changes the spacing of the pixels. Such filters should call their superclass' implementation of this method prior to changing the information values they need (i.e. GenerateOutputInformation() should call Superclass::GenerateOutputInformation() prior to changing the information.
Reimplemented in itk::VTKImageImport< TOutputImage >, itk::ExtractImageFilter< TInputImage, TOutputImage >, itk::ImportImageFilter< TPixel, VImageDimension >, itk::PointSetToImageFilter< TInputPointSet, TOutputImage >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, TFunction >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::AccessorFunctor< TInputImage::PixelType, TAccessor > >, itk::UnaryFunctorImageFilter< TImage, TImage, Functor::BinaryNot< TImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::BinaryThreshold< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::ChangeLabel< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::Clamp< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::ExpNegative< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::IntensityWindowingTransform< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::InvertIntensityTransform< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TLabelImage, TOutputImage, Functor::LabelToRGBFunctor< TLabelImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::MatrixIndexSelection< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::NOT< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::IntensityLinearTransform< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::Sigmoid< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::SymmetricEigenAnalysisFixedDimensionFunction< TMatrixDimension, TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension >, Functor::TensorFractionalAnisotropyFunction< TInputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension >, Functor::TensorRelativeAnisotropyFunction< TInputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::ThresholdLabeler< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::VectorIndexSelectionCast< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::VectorMagnitudeLinearTransform< TInputImage::PixelType, TOutputImage::PixelType > >, itk::GPUUnaryFunctorImageFilter< TInputImage, TOutputImage, TFunction, TParentImageFilter >, itk::GPUUnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::GPUBinaryThreshold< TInputImage::PixelType, TOutputImage::PixelType >, BinaryThresholdImageFilter< TInputImage, TOutputImage > >, itk::GPUUnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::GPUCast< TInputImage::PixelType, TOutputImage::PixelType >, CastImageFilter< TInputImage, TOutputImage > >, itk::BinaryMask3DMeshSource< TInputImage, TOutputMesh >, itk::ImageToMeshFilter< TInputImage, TOutputMesh >, itk::ImageToMeshFilter< TImage, PointSet< Matrix< SpacePrecisionType, TImage::ImageDimension, TImage::ImageDimension >, TImage::ImageDimension > >, itk::ImageToParametricSpaceFilter< TInputImage, TOutputMesh >, itk::ParametricSpaceToImageSpaceMeshFilter< TInputMesh, TOutputMesh >, itk::TriangleMeshToBinaryImageFilter< TInputMesh, TOutputImage >, itk::SpatialObjectToImageFilter< TInputSpatialObject, TOutputImage >, itk::SpatialObjectToPointSetFilter< TPointBasedSpatialObject, TOutputPointSet >, itk::PipelineMonitorImageFilter< TImageType >, itk::RandomImageSource< TOutputImage >, itk::Testing::ExtractSliceImageFilter< TInputImage, TOutputImage >, itk::TransformGeometryImageFilter< TInputImage, TOutputImage >, itk::ScalarToRGBColormapImageFilter< TInputImage, TOutputImage >, itk::ConvolutionImageFilterBase< TInputImage, TKernelImage, TOutputImage >, itk::ConvolutionImageFilterBase< TInputImage, TInputImage, TInputImage >, itk::ConvolutionImageFilterBase< TInputImage, TKernelSource::OutputImageType, TInputImage >, itk::MaskedFFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::InverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::LandmarkDisplacementFieldSource< TOutputImage >, itk::TimeVaryingVelocityFieldIntegrationImageFilter< TTimeVaryingVelocityField, TDisplacementField >, itk::TransformToDisplacementFieldFilter< TOutputImage, TParametersValueType >, itk::FastMarchingExtensionImageFilter< TLevelSet, TAuxValue, VAuxDimension, TSpeedImage >, itk::FastMarchingImageFilter< TLevelSet, TSpeedImage >, itk::FastMarchingImageFilter< TLevelSet, Image< float, TLevelSet::ImageDimension > >, itk::FFTPadImageFilter< TInputImage, TOutputImage >, itk::FullToHalfHermitianImageFilter< TInputImage >, itk::HalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::HalfHermitianToRealInverseFFTImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::HalfToFullHermitianImageFilter< TInputImage >, itk::RealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::RealToHalfHermitianForwardFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ComposeImageFilter< TInputImage, TOutputImage >, itk::JoinSeriesImageFilter< TInputImage, TOutputImage >, itk::HoughTransform2DLinesImageFilter< TInputPixelType, TOutputPixelType >, itk::BinaryFunctorImageFilter< TInputImage1, TInputImage2, TOutputImage, TFunction >, itk::BinaryGeneratorImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::BinaryGeneratorImageFilter< TInputImage1, TInputImage1, TInputImage1 >, itk::BinaryGeneratorImageFilter< TInputImage1, TInputImage2, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::BinaryGeneratorImageFilter< TInputImage, TLabelImage, TOutputImage >, itk::BinaryGeneratorImageFilter< TInputImage1, TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::BinaryGeneratorImageFilter< TInputImage, TMaskImage, TInputImage >, itk::CastImageFilter< TInputImage, TOutputImage >, itk::CastImageFilter< FeatureImageType, ImageType >, itk::TernaryGeneratorImageFilter< TInputImage1, TInputImage2, TInputImage3, TOutputImage >, itk::TernaryGeneratorImageFilter< TMask, TImage, TImage, TImage >, itk::UnaryGeneratorImageFilter< TInputImage, TOutputImage >, itk::LabelMapContourOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::LabelMapOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::LabelMapToRGBImageFilter< TInputImage, TOutputImage >, itk::LabelOverlayImageFilter< TInputImage, TLabelImage, TOutputImage >, itk::LabelToRGBImageFilter< TLabelImage, TOutputImage >, itk::GradientImageFilter< TInputImage, TOperatorValueType, TOutputValueType, TOutputImageType >, itk::GradientRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::BinShrinkImageFilter< TInputImage, TOutputImage >, itk::BSplineDownsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::BSplineUpsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::ChangeInformationImageFilter< TInputImage >, itk::CropImageFilter< TInputImage, TOutputImage >, itk::ExpandImageFilter< TInputImage, TOutputImage >, itk::FlipImageFilter< TImage >, itk::InterpolateImagePointsFilter< TInputImage, TOutputImage, TCoordType, InterpolatorType >, itk::OrientImageFilter< TInputImage, TOutputImage >, itk::PadImageFilter< TInputImage, TOutputImage >, itk::PermuteAxesImageFilter< TImage >, itk::RegionOfInterestImageFilter< TInputImage, TOutputImage >, itk::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType, TTransformPrecisionType >, itk::ShrinkImageFilter< TInputImage, TOutputImage >, itk::SliceImageFilter< TInputImage, TOutputImage >, itk::TileImageFilter< TInputImage, TOutputImage >, itk::WarpImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::WarpVectorImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::GenerateImageSource< TOutputImage >, itk::PhysicalPointImageSource< TOutputImage >, itk::AccumulateImageFilter< TInputImage, TOutputImage >, itk::ProjectionImageFilter< TInputImage, TOutputImage, TAccumulator >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::BinaryAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Function::BinaryThresholdAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MaximumAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MeanAccumulator< TInputImage::PixelType, typename NumericTraits< typename TOutputImage::PixelType >::AccumulateType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MedianAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MinimumAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::StandardDeviationAccumulator< TInputImage::PixelType, typename NumericTraits< typename TOutputImage::PixelType >::AccumulateType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::SumAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::AutoCropLabelMapFilter< TInputImage >, itk::ChangeRegionLabelMapFilter< TInputImage >, itk::CropLabelMapFilter< TInputImage >, itk::LabelMapMaskImageFilter< TInputImage, TOutputImage >, itk::PadLabelMapFilter< TInputImage >, itk::RegionFromReferenceLabelMapFilter< TInputImage >, itk::ExtractOrthogonalSwath2DImageFilter< TImage >, itk::PathToImageFilter< TInputPath, TOutputImage >, itk::ImageFileReader< TOutputImage, ConvertPixelTraits >, itk::ImageSeriesReader< TOutputImage >, itk::MeshFileReader< TOutputMesh, ConvertPointPixelTraits, ConvertCellPixelTraits >, itk::DirectFourierReconstructionImageToImageFilter< TInputImage, TOutputImage >, itk::HistogramToImageFilter< THistogram, TImage, TFunction >, itk::HistogramToImageFilter< THistogram, Image< double, 3 >, Function::HistogramEntropyFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< SizeValueType, 3 >, Function::HistogramIntensityFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< double, 3 >, Function::HistogramLogProbabilityFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< float, 3 >, Function::HistogramProbabilityFunction< SizeValueType, TImage::PixelType > >, itk::Statistics::ImageToListSampleFilter< TImage, TMaskImage >, itk::BlockMatchingImageFilter< TFixedImage, TMovingImage, TFeatures, TDisplacements, TSimilarities >, itk::MultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::GPUPDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TParentImageFilter >, itk::GPUPDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::MultiResolutionPDEDeformableRegistration< TFixedImage, TMovingImage, TDisplacementField, TRealType, TFloatImageType, TRegistrationType, TDefaultRegistrationType >, itk::PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::BayesianClassifierImageFilter< TInputVectorImage, TLabelsType, TPosteriorsPrecisionType, TPriorsPrecisionType >, itk::BayesianClassifierInitializationImageFilter< TInputImage, TProbabilityPrecisionType >, itk::BinaryMaskToNarrowBandPointSetFilter< TInputImage, TOutputMesh >, itk::MRFImageFilter< TInputImage, TClassifiedImage >, and itk::VoronoiDiagram2DGenerator< TCoordType >.
GenerateOutputRequestedRegion()
virtual void itk::ProcessObject::GenerateOutputRequestedRegion (DataObject * output) protected virtual
Given one output whose requested region has been set, how should the requested regions for the remaining outputs of the process object be set? By default, all the outputs are set to the same requested region. If a filter needs to produce different requested regions for each output, for instance an image processing filter producing several outputs at different resolutions, then that filter may override this method and set the requested regions appropriately.
Note that a filter producing multiple outputs of different types is required to override this method. The default implementation can only correctly handle multiple outputs of the same type.
Reimplemented in itk::watershed::BoundaryResolver< TPixelType, TDimension >, itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >, itk::watershed::Relabeler< TScalar, TImageDimension >, itk::watershed::Relabeler< ScalarType, Self::ImageDimension >, itk::watershed::Segmenter< TInputImage >, itk::watershed::Segmenter< InputImageType >, itk::watershed::SegmentTreeGenerator< TScalar >, itk::watershed::SegmentTreeGenerator< ScalarType >, itk::TemporalProcessObject, itk::VideoToVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::VideoToVideoFilter< TVideoStream, TVideoStream >, itk::VideoToVideoFilter< itk::VideoStream< TImageToImageFilter::InputImageType >, itk::VideoStream< TImageToImageFilter::OutputImageType > >, itk::RecursiveMultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, and itk::MultiResolutionPyramidImageFilter< TInputImage, TOutputImage >.
GetAbortGenerateData()
virtual const bool & itk::ProcessObject::GetAbortGenerateData () const virtual
Get the AbortGenerateData flag for the process object.
GetIndexedInputs()
DataObjectPointerArray itk::ProcessObject::GetIndexedInputs ()
Return an array with all the indexed inputs.
GetIndexedOutputs()
DataObjectPointerArray itk::ProcessObject::GetIndexedOutputs ()
Return an array with the indexed outputs.
GetInput() [1/4]
DataObject * itk::ProcessObject::GetInput (const DataObjectIdentifierType & key) protected
Return an input.
nullptr is returned if the name or indexed input is undefined.
Referenced by itk::LabelMapToBinaryImageFilter< TInputImage, TOutputImage >::GetBackgroundImage(), itk::DisplacementFieldToBSplineImageFilter< TInputImage, TInputPointSet, TOutputImage >::GetConfidenceImage(), itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >::GetEquivalencyTable(), itk::LabelMapContourOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >::GetFeatureImage(), itk::LabelMapOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >::GetFeatureImage(), itk::BinaryImageToStatisticsLabelMapFilter< TInputImage, TFeatureImage, TOutputImage >::GetFeatureImage(), itk::BinaryStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >::GetFeatureImage(), itk::BinaryStatisticsOpeningImageFilter< TInputImage, TFeatureImage >::GetFeatureImage(), itk::LabelImageToStatisticsLabelMapFilter< TInputImage, TFeatureImage, TOutputImage >::GetFeatureImage(), itk::LabelMapMaskImageFilter< TInputImage, TOutputImage >::GetFeatureImage(), itk::LabelStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >::GetFeatureImage(), itk::LabelStatisticsOpeningImageFilter< TInputImage, TFeatureImage >::GetFeatureImage(), itk::StatisticsLabelMapFilter< TImage, TFeatureImage >::GetFeatureImage(), itk::StatisticsRelabelImageFilter< TInputImage, TFeatureImage >::GetFeatureImage(), itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType, TOutputImage >::GetFeatureImage(), itk::RobustAutomaticThresholdImageFilter< TInputImage, TGradientImage, TOutputImage >::GetGradientImage(), itk::HistogramThresholdCalculator< THistogram, TOutput >::GetInput(), itk::watershed::SegmentTreeGenerator< TScalar >::GetInputEquivalencyTable(), itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >::GetInputImage(), itk::watershed::Relabeler< TScalar, TImageDimension >::GetInputImage(), itk::watershed::Segmenter< TInputImage >::GetInputImage(), itk::watershed::SegmentTreeGenerator< TScalar >::GetInputSegmentTable(), itk::watershed::Relabeler< TScalar, TImageDimension >::GetInputSegmentTree(), itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >::GetIntensityInput(), itk::LabelMapFilter< TInputImage, TOutputImage >::GetLabelMap(), itk::MorphologicalWatershedFromMarkersImageFilter< TInputImage, TLabelImage >::GetMarkerImage(), itk::MaskImageFilter< TInputImage, TMaskImage, TOutputImage >::GetMaskImage(), itk::MaskNegatedImageFilter< TInputImage, TMaskImage, TOutputImage >::GetMaskImage(), itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel, THistogram >::GetMaskImage(), itk::KappaSigmaThresholdImageFilter< TInputImage, TMaskImage, TOutputImage >::GetMaskImage(), itk::DisplacementFieldToBSplineImageFilter< TInputImage, TInputPointSet, TOutputImage >::GetPointSet(), itk::DiffusionTensor3DReconstructionImageFilter< TReferenceImagePixelType, TGradientImagePixelType, TTensorPixelType, TMaskImageType >::GetReferenceImage(), itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >::SetFeatureImage(), and itk::DivideImageFilter< TInputImage1, TInputImage2, TOutputImage >::VerifyPreconditions().
GetInput() [2/4]
const DataObject * itk::ProcessObject::GetInput (const DataObjectIdentifierType & key) const protected
GetInput() [3/4]
DataObject * itk::ProcessObject::GetInput (DataObjectPointerArraySizeType idx) inline protected
Method used internally for getting an indexed input.
Definition at line 548 of file itkProcessObject.h.
GetInput() [4/4]
const DataObject * itk::ProcessObject::GetInput (DataObjectPointerArraySizeType idx) const inline protected
Method used internally for getting an indexed input.
Definition at line 553 of file itkProcessObject.h.
GetInputNames()
NameArray itk::ProcessObject::GetInputNames () const
Return an array with the names of the inputs defined.
The names are ordered lexicographically, and match the order of the data object produced by GetInputs().
GetInputs()
DataObjectPointerArray itk::ProcessObject::GetInputs ()
Return an array of DataObjects with the defined named inputs.
The order of the inputs matches the order of the input names produced by GetInputNames().
GetMultiThreader()
MultiThreaderType * itk::ProcessObject::GetMultiThreader () const inline
Return the multithreader used by this class.
Definition at line 507 of file itkProcessObject.h.
GetNameOfClass()
virtual const char * itk::ProcessObject::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from itk::Object.
Reimplemented in itk::VTKImageExport< TInputImage >, itk::VTKImageExportBase, itk::VTKImageImport< TOutputImage >, itk::ExtractImageFilter< TInputImage, TOutputImage >, itk::ImageSink< TInputImage >, itk::ImageSink< TLabelImage >, itk::ImageSink< TImage >, itk::ImageSource< TOutputImage >, itk::ImageSource< TImageType >, itk::ImageSource< TInputImage >, itk::ImageSource< TImage >, itk::ImageSource< TInputImage1 >, itk::ImageSource< Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageSource< VectorImage< float, TInputImage::ImageDimension > >, itk::ImageSource< Image< float, TInputImage::ImageDimension > >, itk::ImageSource< VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< DiffusionTensor3D< double >, 3 > >, itk::ImageSource< TEigenValueImage >, itk::ImageSource< Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageSource< TLevelSet >, itk::ImageSource< TSparseOutputImageType >, itk::ImageSource< Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< TPixel, 3 > >, itk::ImageSource< Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< double, 3 > >, itk::ImageSource< Image< SizeValueType, 3 > >, itk::ImageSource< Image< float, 3 > >, itk::ImageSource< Image< TOutputPixelType, 2 > >, itk::ImageSource< Image< double, TInputImage::ImageDimension > >, itk::ImageSource< TSparseOutputImage >, itk::ImageSource< Image< TPixel, 2 > >, itk::ImageSource< Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageSource< TLabelImage >, itk::ImageSource< Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageSource< Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageSource< TClassifiedImage >, itk::ImageSource< itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageSource< TDisplacementField >, itk::ImageSource< Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageSource< Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageSource< Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageSource< ImageType >, itk::ImageToImageFilter< TInputImage, TOutputImage >, itk::ImageToImageFilter< TImageType, TImageType >, itk::ImageToImageFilter< TInputImage, TInputImage >, itk::ImageToImageFilter< TImage, TImage >, itk::ImageToImageFilter< TInputImage1, TInputImage1 >, itk::ImageToImageFilter< TInputVectorImage, Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage1, TOutputImage >, itk::ImageToImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TReferenceImagePixelType, 3 >, Image< DiffusionTensor3D< double >, 3 > >, itk::ImageToImageFilter< TInputImage, TEigenValueImage >, itk::ImageToImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< float, TLevelSet::ImageDimension >, TLevelSet >, itk::ImageToImageFilter< TInputImageType, TSparseOutputImageType >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TDisplacementField, TOutputImage >, itk::ImageToImageFilter< Image< SymmetricSecondRankTensor< double, 3 >, 3 >, Image< TPixel, 3 > >, itk::ImageToImageFilter< TInputImage, Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TInputPixelType, 2 >, Image< TOutputPixelType, 2 > >, itk::ImageToImageFilter< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TSparseOutputImage >, itk::ImageToImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageToImageFilter< TLabelImage, TLabelImage >, itk::ImageToImageFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TLabelImage, TOutputImage >, itk::ImageToImageFilter< TInputImage, TClassifiedImage >, itk::ImageToImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TLabelImage >, itk::ImageToImageFilter< TDisplacementField, TDisplacementField >, itk::ImageToImageFilter< TFeatureImage, TOutputImage >, itk::ImageToImageFilter< TLevelSet, TLevelSet >, itk::ImageToImageFilter< TInputImage, Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageToImageFilter< TMask, TImage >, itk::ImageToImageFilter< TTimeVaryingVelocityField, Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageToImageFilter< TInputImage, Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< ImageType, ImageType >, itk::ImageToImageFilter< FeatureImageType, ImageType >, itk::ImportImageFilter< TPixel, VImageDimension >, itk::InPlaceImageFilter< TInputImage, TOutputImage >, itk::InPlaceImageFilter< TInputImage, TOutputImage >, itk::InPlaceImageFilter< TInputImage, TInputImage >, itk::InPlaceImageFilter< TInputImage1, TInputImage1 >, itk::InPlaceImageFilter< TInputImage1, TOutputImage >, itk::InPlaceImageFilter< TImage, TImage >, itk::InPlaceImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::InPlaceImageFilter< TInputImageType, TSparseOutputImageType >, itk::InPlaceImageFilter< TImageType, TImageType >, itk::InPlaceImageFilter< TInputImage, TSparseOutputImage >, itk::InPlaceImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::InPlaceImageFilter< TLabelImage, TOutputImage >, itk::InPlaceImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::InPlaceImageFilter< TFeatureImage, TOutputImage >, itk::InPlaceImageFilter< TDisplacementField, TDisplacementField >, itk::InPlaceImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::InPlaceImageFilter< TMask, TImage >, itk::InPlaceImageFilter< FeatureImageType, ImageType >, itk::PointSetToImageFilter< TInputPointSet, TOutputImage >, itk::StreamingImageFilter< TInputImage, TOutputImage >, itk::StreamingProcessObject, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, TFunction >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::AccessorFunctor< TInputImage::PixelType, TAccessor > >, itk::UnaryFunctorImageFilter< TImage, TImage, Functor::BinaryNot< TImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::BinaryThreshold< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::ChangeLabel< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::Clamp< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::ExpNegative< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::IntensityWindowingTransform< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::InvertIntensityTransform< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TLabelImage, TOutputImage, Functor::LabelToRGBFunctor< TLabelImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::MatrixIndexSelection< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::NOT< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::IntensityLinearTransform< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::Sigmoid< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::SymmetricEigenAnalysisFixedDimensionFunction< TMatrixDimension, TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::SymmetricEigenAnalysisFunction< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension >, Functor::TensorFractionalAnisotropyFunction< TInputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension >, Functor::TensorRelativeAnisotropyFunction< TInputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::ThresholdLabeler< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::VectorIndexSelectionCast< TInputImage::PixelType, TOutputImage::PixelType > >, itk::UnaryFunctorImageFilter< TInputImage, TInputImage, Functor::VectorMagnitudeLinearTransform< TInputImage::PixelType, TOutputImage::PixelType > >, itk::DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage >, itk::DenseFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField >, itk::FiniteDifferenceImageFilter< TInputImage, TOutputImage >, itk::FiniteDifferenceImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::FiniteDifferenceImageFilter< TInputImageType, TSparseOutputImageType >, itk::FiniteDifferenceImageFilter< TInputImage, TSparseOutputImage >, itk::FiniteDifferenceImageFilter< TDisplacementField, TDisplacementField >, itk::FiniteDifferenceSparseImageFilter< TInputImageType, TSparseOutputImageType >, itk::FiniteDifferenceSparseImageFilter< TInputImage, TSparseOutputImage >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, BinaryThresholdImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, BoxImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, CastImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, DiscreteGaussianImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, FiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TInputImage, InPlaceImageFilter< TInputImage, TInputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, MeanImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, typename TOutputImage::PixelType > >, itk::GPUImageToImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, InPlaceImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, BinaryThresholdImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, CastImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, FiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, InPlaceImageFilter< TInputImage, TOutputImage > >, itk::GPUUnaryFunctorImageFilter< TInputImage, TOutputImage, TFunction, TParentImageFilter >, itk::GPUUnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::GPUBinaryThreshold< TInputImage::PixelType, TOutputImage::PixelType >, BinaryThresholdImageFilter< TInputImage, TOutputImage > >, itk::GPUUnaryFunctorImageFilter< TInputImage, TOutputImage, Functor::GPUCast< TInputImage::PixelType, TOutputImage::PixelType >, CastImageFilter< TInputImage, TOutputImage > >, itk::GPUDenseFiniteDifferenceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUDenseFiniteDifferenceImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUDenseFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUDenseFiniteDifferenceImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUDenseFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::BSplineDecompositionImageFilter< TInputImage, TOutputImage >, itk::AutomaticTopologyMeshSource< TOutputMesh >, itk::BinaryMask3DMeshSource< TInputImage, TOutputMesh >, itk::ConnectedRegionsMeshFilter< TInputMesh, TOutputMesh >, itk::ImageToMeshFilter< TInputImage, TOutputMesh >, itk::ImageToMeshFilter< TImage, PointSet< Matrix< SpacePrecisionType, TImage::ImageDimension, TImage::ImageDimension >, TImage::ImageDimension > >, itk::ImageToParametricSpaceFilter< TInputImage, TOutputMesh >, itk::InteriorExteriorMeshFilter< TInputMesh, TOutputMesh, TSpatialFunction >, itk::MeshSource< TOutputMesh >, itk::MeshSource< PointSet< Vector< typename TFeatures::PointType::ValueType, TFeatures::PointDimension >, TFeatures::PointDimension > >, itk::MeshSource< TInputMesh >, itk::MeshSource< TOutput >, itk::MeshSource< PointSet< Matrix< SpacePrecisionType, TImage::ImageDimension, TImage::ImageDimension >, TImage::ImageDimension > >, itk::MeshSource< TOutputPointSet >, itk::MeshSource< VoronoiDiagram2D< TCoordType > >, itk::MeshToMeshFilter< TInputMesh, TOutputMesh >, itk::MeshToMeshFilter< PointSet< Matrix< SpacePrecisionType, TFixedImage::ImageDimension, TFixedImage::ImageDimension >, TFixedImage::ImageDimension >, PointSet< Vector< typename TFeatures::PointType::ValueType, TFeatures::PointDimension >, TFeatures::PointDimension > >, itk::MeshToMeshFilter< TInputMesh, TInputMesh >, itk::MeshToMeshFilter< TInput, TOutput >, itk::ParametricSpaceToImageSpaceMeshFilter< TInputMesh, TOutputMesh >, itk::RegularSphereMeshSource< TOutputMesh >, itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >, itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >, itk::TransformMeshFilter< TInputMesh, TOutputMesh, TTransform >, itk::TriangleMeshToBinaryImageFilter< TInputMesh, TOutputImage >, itk::TriangleMeshToSimplexMeshFilter< TInputMesh, TOutputMesh >, itk::VTKPolyDataReader< TOutputMesh >, itk::WarpMeshFilter< TInputMesh, TOutputMesh, TDisplacementField >, itk::QuadEdgeMeshToQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::QuadEdgeMeshToQuadEdgeMeshFilter< TInputMesh, TInputMesh >, itk::QuadEdgeMeshToQuadEdgeMeshFilter< TInput, TOutput >, itk::SpatialObjectToImageFilter< TInputSpatialObject, TOutputImage >, itk::SpatialObjectToPointSetFilter< TPointBasedSpatialObject, TOutputPointSet >, itk::PipelineMonitorImageFilter< TImageType >, itk::RandomImageSource< TOutputImage >, itk::Testing::ComparisonImageFilter< TInputImage, TOutputImage >, itk::Testing::ExtractSliceImageFilter< TInputImage, TOutputImage >, itk::Testing::HashImageFilter< TImageType >, itk::Testing::StretchIntensityImageFilter< TInputImage, TOutputImage >, itk::TransformGeometryImageFilter< TInputImage, TOutputImage >, itk::AnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::CurvatureAnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::VectorCurvatureAnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::VectorGradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::AntiAliasBinaryImageFilter< TInputImage, TOutputImage >, itk::MRIBiasFieldCorrectionFilter< TInputImage, TOutputImage, TMaskImage >, itk::N4BiasFieldCorrectionImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::BinaryClosingByReconstructionImageFilter< TInputImage, TKernel >, itk::BinaryDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryMorphologicalClosingImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryMorphologicalOpeningImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryOpeningByReconstructionImageFilter< TInputImage, TKernel >, itk::BinaryPruningImageFilter< TInputImage, TOutputImage >, itk::BinaryThinningImageFilter< TInputImage, TOutputImage >, itk::DilateObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::ErodeObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::FastIncrementalBinaryDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::ObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::ScalarToRGBColormapImageFilter< TInputImage, TOutputImage >, itk::ConvolutionImageFilter< TInputImage, TKernelImage, TOutputImage >, itk::ConvolutionImageFilterBase< TInputImage, TKernelImage, TOutputImage >, itk::ConvolutionImageFilterBase< TInputImage, TInputImage, TInputImage >, itk::ConvolutionImageFilterBase< TInputImage, TKernelSource::OutputImageType, TInputImage >, itk::FFTConvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::FFTConvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::FFTConvolutionImageFilter< TInputImage, TKernelSource::OutputImageType, TInputImage, double >, itk::FFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage >, itk::MaskedFFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::NormalizedCorrelationImageFilter< TInputImage, TMaskImage, TOutputImage, TOperatorValueType >, itk::BinaryMinMaxCurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::CurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::MinMaxCurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::InverseDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::InverseDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::IterativeDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::IterativeDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::IterativeDeconvolutionImageFilter< TInputImage, TKernelSource::OutputImageType, TInputImage >, itk::LandweberDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::LandweberDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::ParametricBlindLeastSquaresDeconvolutionImageFilter< TInputImage, TKernelSource, TOutputImage >, itk::ProjectedIterativeDeconvolutionImageFilter< LandweberDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double > >, itk::ProjectedLandweberDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::RichardsonLucyDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::TikhonovDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::WienerDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::PatchBasedDenoisingBaseImageFilter< TInputImage, TOutputImage >, itk::PatchBasedDenoisingImageFilter< TInputImage, TOutputImage >, itk::DiffusionTensor3DReconstructionImageFilter< TReferenceImagePixelType, TGradientImagePixelType, TTensorPixelType, TMaskImageType >, itk::TensorFractionalAnisotropyImageFilter< TInputImage, TOutputImage >, itk::TensorRelativeAnisotropyImageFilter< TInputImage, TOutputImage >, itk::DisplacementFieldJacobianDeterminantFilter< TInputImage, TRealType, TOutputImage >, itk::DisplacementFieldToBSplineImageFilter< TInputImage, TInputPointSet, TOutputImage >, itk::ExponentialDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::InverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::InvertDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::IterativeInverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::LandmarkDisplacementFieldSource< TOutputImage >, itk::TimeVaryingVelocityFieldIntegrationImageFilter< TTimeVaryingVelocityField, TDisplacementField >, itk::TransformToDisplacementFieldFilter< TOutputImage, TParametersValueType >, itk::ApproximateSignedDistanceMapImageFilter< TInputImage, TOutputImage >, itk::ContourDirectedMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::ContourMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::DanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::DanielssonDistanceMapImageFilter< ImageType, ImageType >, itk::DirectedHausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::FastChamferDistanceImageFilter< TInputImage, TOutputImage >, itk::HausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::IsoContourDistanceImageFilter< TInputImage, TOutputImage >, itk::SignedDanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::SignedMaurerDistanceMapImageFilter< TInputImage, TOutputImage >, itk::FastMarchingExtensionImageFilter< TLevelSet, TAuxValue, VAuxDimension, TSpeedImage >, itk::FastMarchingImageFilter< TLevelSet, TSpeedImage >, itk::FastMarchingImageFilter< TLevelSet, Image< float, TLevelSet::ImageDimension > >, itk::FastMarchingUpwindGradientImageFilter< TLevelSet, TSpeedImage >, itk::ComplexToComplex1DFFTImageFilter< TInputImage, TOutputImage >, itk::ComplexToComplex1DFFTImageFilter< TInputImage, TInputImage >, itk::ComplexToComplexFFTImageFilter< TInputImage, TOutputImage >, itk::ComplexToComplexFFTImageFilter< TInputImage, TInputImage >, itk::FFTPadImageFilter< TInputImage, TOutputImage >, itk::FFTShiftImageFilter< TInputImage, TOutputImage >, itk::FFTWComplexToComplex1DFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWComplexToComplexFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWForward1DFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWForwardFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWHalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWInverse1DFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWInverseFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWRealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::Forward1DFFTImageFilter< TInputImage, TOutputImage >, itk::Forward1DFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ForwardFFTImageFilter< TInputImage, TOutputImage >, itk::ForwardFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::FullToHalfHermitianImageFilter< TInputImage >, itk::HalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::HalfHermitianToRealInverseFFTImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::HalfToFullHermitianImageFilter< TInputImage >, itk::Inverse1DFFTImageFilter< TInputImage, TOutputImage >, itk::Inverse1DFFTImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::InverseFFTImageFilter< TInputImage, TOutputImage >, itk::InverseFFTImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::RealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::RealToHalfHermitianForwardFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::VnlComplexToComplex1DFFTImageFilter< TInputImage, TOutputImage >, itk::VnlComplexToComplexFFTImageFilter< TInputImage, TOutputImage >, itk::VnlForward1DFFTImageFilter< TInputImage, TOutputImage >, itk::VnlForwardFFTImageFilter< TInputImage, TOutputImage >, itk::VnlHalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::VnlInverse1DFFTImageFilter< TInputImage, TOutputImage >, itk::VnlInverseFFTImageFilter< TInputImage, TOutputImage >, itk::VnlRealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::GPUAnisotropicDiffusionImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUAnisotropicDiffusionImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUGradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUBoxImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUBoxImageFilter< TInputImage, TOutputImage, MeanImageFilter< TInputImage, TOutputImage > >, itk::GPUCastImageFilter< TInputImage, TOutputImage >, itk::GPUNeighborhoodOperatorImageFilter< TInputImage, TOutputImage, TOperatorValueType, TParentImageFilter >, itk::GPUDiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::GPUMeanImageFilter< TInputImage, TOutputImage >, itk::GPUBinaryThresholdImageFilter< TInputImage, TOutputImage >, itk::AbsoluteValueDifferenceImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::CheckerBoardImageFilter< TImage >, itk::SimilarityIndexImageFilter< TInputImage1, TInputImage2 >, itk::SquaredDifferenceImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::STAPLEImageFilter< TInputImage, TOutputImage >, itk::ComposeImageFilter< TInputImage, TOutputImage >, itk::JoinImageFilter< TInputImage1, TInputImage2 >, itk::JoinSeriesImageFilter< TInputImage, TOutputImage >, itk::BilateralImageFilter< TInputImage, TOutputImage >, itk::CannyEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::CannyEdgeDetectionImageFilter< ImageType, ImageType >, itk::DerivativeImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianDerivativeImageFilter< TInputImage, TOutputImage >, itk::GradientVectorFlowImageFilter< TInputImage, TOutputImage, TInternalPixel >, itk::Hessian3DToVesselnessMeasureImageFilter< TPixel >, itk::HessianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::HessianToObjectnessMeasureImageFilter< TInputImage, TOutputImage >, itk::HoughTransform2DCirclesImageFilter< TInputPixelType, TOutputPixelType, TRadiusPixelType >, itk::HoughTransform2DLinesImageFilter< TInputPixelType, TOutputPixelType >, itk::LaplacianImageFilter< TInputImage, TOutputImage >, itk::LaplacianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::LaplacianSharpeningImageFilter< TInputImage, TOutputImage >, itk::MaskFeaturePointSelectionFilter< TImage, TMask, TFeatures >, itk::MultiScaleHessianBasedMeasureImageFilter< TInputImage, THessianImage, TOutputImage >, itk::SimpleContourExtractorImageFilter< TInputImage, TOutputImage >, itk::SobelEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::UnsharpMaskImageFilter< TInputImage, TOutputImage, TInternalPrecision >, itk::ZeroCrossingBasedEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::ZeroCrossingImageFilter< TInputImage, TOutputImage >, itk::BinaryFunctorImageFilter< TInputImage1, TInputImage2, TOutputImage, TFunction >, itk::BinaryGeneratorImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::BinaryGeneratorImageFilter< TInputImage1, TInputImage1, TInputImage1 >, itk::BinaryGeneratorImageFilter< TInputImage1, TInputImage2, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::BinaryGeneratorImageFilter< TInputImage, TLabelImage, TOutputImage >, itk::BinaryGeneratorImageFilter< TInputImage1, TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::BinaryGeneratorImageFilter< TInputImage, TMaskImage, TInputImage >, itk::BoxImageFilter< TInputImage, TOutputImage >, itk::BoxImageFilter< TImageType, TImageType >, itk::BoxImageFilter< TImage, TImage >, itk::BoxImageFilter< TInputImage, TInputImage >, itk::CastImageFilter< TInputImage, TOutputImage >, itk::CastImageFilter< FeatureImageType, ImageType >, itk::KernelImageFilter< TInputImage, TOutputImage, TKernel >, itk::KernelImageFilter< TImageType, TImageType, Neighborhood< bool, TImageType::ImageDimension > >, itk::KernelImageFilter< TImage, TImage, TKernel >, itk::KernelImageFilter< TInputImage, TInputImage, TKernel >, itk::KernelImageFilter< TInputImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension > >, itk::MaskNeighborhoodOperatorImageFilter< TInputImage, TMaskImage, TOutputImage, TOperatorValueType >, itk::MovingHistogramImageFilter< TInputImage, TOutputImage, TKernel, THistogram >, itk::MovingHistogramImageFilter< TImageType, TImageType, Neighborhood< bool, TImageType::ImageDimension >, Function::AdaptiveEqualizationHistogram< TImageType::PixelType, TImageType::PixelType > >, itk::MovingHistogramImageFilter< TInputImage, TOutputImage, TKernel, Function::MorphologyHistogram< TInputImage::PixelType, std::greater< TInputImage::PixelType > > >, itk::MovingHistogramImageFilter< TInputImage, TOutputImage, TKernel, Function::MorphologyHistogram< TInputImage::PixelType, std::less< TInputImage::PixelType > > >, itk::MovingHistogramImageFilter< TInputImage, TOutputImage, TKernel, Function::MorphologicalGradientHistogram< TInputImage::PixelType > >, itk::MovingHistogramImageFilter< TInputImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension >, Function::RankHistogram< TInputImage::PixelType > >, itk::MovingHistogramImageFilterBase< TInputImage, TOutputImage, TKernel >, itk::MovingHistogramImageFilterBase< TImageType, TImageType, Neighborhood< bool, TImageType::ImageDimension > >, itk::MovingHistogramImageFilterBase< TInputImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension > >, itk::NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, TOperatorValueType >, itk::NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, typename TOutputImage::PixelType >, itk::NoiseImageFilter< TInputImage, TOutputImage >, itk::RecursiveSeparableImageFilter< TInputImage, TOutputImage >, itk::RecursiveSeparableImageFilter< TInputImage, TInputImage >, itk::TernaryFunctorImageFilter< TInputImage1, TInputImage2, TInputImage3, TOutputImage, TFunction >, itk::TernaryGeneratorImageFilter< TInputImage1, TInputImage2, TInputImage3, TOutputImage >, itk::TernaryGeneratorImageFilter< TMask, TImage, TImage, TImage >, itk::UnaryGeneratorImageFilter< TInputImage, TOutputImage >, itk::VectorNeighborhoodOperatorImageFilter< TInputImage, TOutputImage >, itk::FrequencyBandImageFilter< TImageType, TFrequencyIterator >, itk::UnaryFrequencyDomainFilter< TImageType, TFrequencyIterator >, itk::UnaryFrequencyDomainFilter< TImageType, FrequencyFFTLayoutImageRegionIteratorWithIndex< TImageType > >, itk::LabelMapContourOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::LabelMapOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::LabelMapToRGBImageFilter< TInputImage, TOutputImage >, itk::LabelOverlayImageFilter< TInputImage, TLabelImage, TOutputImage >, itk::LabelToRGBImageFilter< TLabelImage, TOutputImage >, itk::DifferenceOfGaussiansGradientImageFilter< TInputImage, TDataType >, itk::GradientImageFilter< TInputImage, TOperatorValueType, TOutputValueType, TOutputImageType >, itk::GradientMagnitudeImageFilter< TInputImage, TOutputImage >, itk::GradientMagnitudeRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::GradientRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::BinShrinkImageFilter< TInputImage, TOutputImage >, itk::BSplineCenteredL2ResampleImageFilterBase< TInputImage, TOutputImage >, itk::BSplineCenteredResampleImageFilterBase< TInputImage, TOutputImage >, itk::BSplineControlPointImageFilter< TInputImage, TOutputImage >, itk::BSplineDownsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::BSplineL2ResampleImageFilterBase< TInputImage, TOutputImage >, itk::BSplineResampleImageFilterBase< TInputImage, TOutputImage >, itk::BSplineScatteredDataPointSetToImageFilter< TInputPointSet, TOutputImage >, itk::BSplineUpsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::ChangeInformationImageFilter< TInputImage >, itk::ConstantPadImageFilter< TInputImage, TOutputImage >, itk::CropImageFilter< TInputImage, TOutputImage >, itk::CyclicShiftImageFilter< TInputImage, TOutputImage >, itk::CyclicShiftImageFilter< TInputImage, TOutputImage >, itk::ExpandImageFilter< TInputImage, TOutputImage >, itk::FlipImageFilter< TImage >, itk::InterpolateImageFilter< TInputImage, TOutputImage >, itk::InterpolateImagePointsFilter< TInputImage, TOutputImage, TCoordType, InterpolatorType >, itk::MirrorPadImageFilter< TInputImage, TOutputImage >, itk::OrientImageFilter< TInputImage, TOutputImage >, itk::PadImageFilter< TInputImage, TOutputImage >, itk::PadImageFilterBase< TInputImage, TOutputImage >, itk::PadImageFilterBase< TInputImage, TInputImage >, itk::PasteImageFilter< TInputImage, TSourceImage, TOutputImage >, itk::PermuteAxesImageFilter< TImage >, itk::RegionOfInterestImageFilter< TInputImage, TOutputImage >, itk::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType, TTransformPrecisionType >, itk::ShrinkImageFilter< TInputImage, TOutputImage >, itk::SliceBySliceImageFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::SliceImageFilter< TInputImage, TOutputImage >, itk::TileImageFilter< TInputImage, TOutputImage >, itk::WarpImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::WarpVectorImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::WrapPadImageFilter< TInputImage, TOutputImage >, itk::ZeroFluxNeumannPadImageFilter< TInputImage, TOutputImage >, itk::AbsImageFilter< TInputImage, TOutputImage >, itk::AcosImageFilter< TInputImage, TOutputImage >, itk::AdaptImageFilter< TInputImage, TOutputImage, TAccessor >, itk::AndImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::AsinImageFilter< TInputImage, TOutputImage >, itk::Atan2ImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::AtanImageFilter< TInputImage, TOutputImage >, itk::BinaryMagnitudeImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::BoundedReciprocalImageFilter< TInputImage, TOutputImage >, itk::ClampImageFilter< TInputImage, TOutputImage >, itk::ComplexToImaginaryImageFilter< TInputImage, TOutputImage >, itk::ComplexToModulusImageFilter< TInputImage, TOutputImage >, itk::ComplexToPhaseImageFilter< TInputImage, TOutputImage >, itk::ComplexToRealImageFilter< TInputImage, TOutputImage >, itk::ConstrainedValueAdditionImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::ConstrainedValueDifferenceImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::CosImageFilter< TInputImage, TOutputImage >, itk::DivideImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::DivideOrZeroOutImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::EdgePotentialImageFilter< TInputImage, TOutputImage >, itk::ExpImageFilter< TInputImage, TOutputImage >, itk::ExpNegativeImageFilter< TInputImage, TOutputImage >, itk::HistogramMatchingImageFilter< TInputImage, TOutputImage, THistogramMeasurement >, itk::IntensityWindowingImageFilter< TInputImage, TOutputImage >, itk::InvertIntensityImageFilter< TInputImage, TOutputImage >, itk::Log10ImageFilter< TInputImage, TOutputImage >, itk::LogImageFilter< TInputImage, TOutputImage >, itk::MagnitudeAndPhaseToComplexImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::MaskImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::MaskNegatedImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::MatrixIndexSelectionImageFilter< TInputImage, TOutputImage >, itk::MaximumImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::MinimumImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::ModulusImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::MultiplyImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::NaryAddImageFilter< TInputImage, TOutputImage >, itk::NaryFunctorImageFilter< TInputImage, TOutputImage, TFunction >, itk::NaryFunctorImageFilter< TInputImage, TOutputImage, Functor::Add1< TInputImage::PixelType, TInputImage::PixelType > >, itk::NaryFunctorImageFilter< TInputImage, TOutputImage, Functor::Maximum1< TInputImage::PixelType, TInputImage::PixelType > >, itk::NaryMaximumImageFilter< TInputImage, TOutputImage >, itk::NormalizeImageFilter< TInputImage, TOutputImage >, itk::NormalizeToConstantImageFilter< TInputImage, TOutputImage >, itk::NotImageFilter< TInputImage, TOutputImage >, itk::OrImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::PolylineMask2DImageFilter< TInputImage, TPolyline, TOutputImage >, itk::PolylineMaskImageFilter< TInputImage, TPolyline, TVector, TOutputImage >, itk::RescaleIntensityImageFilter< TInputImage, TOutputImage >, itk::RGBToLuminanceImageFilter< TInputImage, TOutputImage >, itk::RoundImageFilter< TInputImage, TOutputImage >, itk::ShiftScaleImageFilter< TInputImage, TOutputImage >, itk::SigmoidImageFilter< TInputImage, TOutputImage >, itk::SinImageFilter< TInputImage, TOutputImage >, itk::SqrtImageFilter< TInputImage, TOutputImage >, itk::SquareImageFilter< TInputImage, TOutputImage >, itk::SubtractImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::SymmetricEigenAnalysisImageFilter< TInputImage, TOutputImage >, itk::SymmetricEigenAnalysisFixedDimensionImageFilter< TMatrixDimension, TInputImage, TOutputImage >, itk::TanImageFilter< TInputImage, TOutputImage >, itk::TernaryAddImageFilter< TInputImage1, TInputImage2, TInputImage3, TOutputImage >, itk::TernaryMagnitudeImageFilter< TInputImage1, TInputImage2, TInputImage3, TOutputImage >, itk::TernaryMagnitudeSquaredImageFilter< TInputImage1, TInputImage2, TInputImage3, TOutputImage >, itk::TernaryOperatorImageFilter< TMask, TImage >, itk::VectorIndexSelectionCastImageFilter< TInputImage, TOutputImage >, itk::VectorMagnitudeImageFilter< TInputImage, TOutputImage >, itk::VectorRescaleIntensityImageFilter< TInputImage, TOutputImage >, itk::WeightedAddImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::XorImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::BinaryContourImageFilter< TInputImage, TOutputImage >, itk::ChangeLabelImageFilter< TInputImage, TOutputImage >, itk::LabelContourImageFilter< TInputImage, TOutputImage >, itk::AdditiveGaussianNoiseImageFilter< TInputImage, TOutputImage >, itk::NoiseBaseImageFilter< TInputImage, TOutputImage >, itk::NoiseBaseImageFilter< TInputImage, TInputImage >, itk::SaltAndPepperNoiseImageFilter< TInputImage, TOutputImage >, itk::ShotNoiseImageFilter< TInputImage, TOutputImage >, itk::SpeckleNoiseImageFilter< TInputImage, TOutputImage >, itk::GaborImageSource< TOutputImage >, itk::GaussianImageSource< TOutputImage >, itk::GenerateImageSource< TOutputImage >, itk::GridImageSource< TOutputImage >, itk::ParametricImageSource< TOutputImage >, itk::PhysicalPointImageSource< TOutputImage >, itk::AccumulateImageFilter< TInputImage, TOutputImage >, itk::AdaptiveHistogramEqualizationImageFilter< TImageType, TKernel >, itk::BinaryProjectionImageFilter< TInputImage, TOutputImage >, itk::GetAverageSliceImageFilter< TInputImage, TOutputImage >, itk::ImagePCAShapeModelEstimator< TInputImage, TOutputImage >, itk::ImageShapeModelEstimatorBase< TInputImage, TOutputImage >, itk::ImageShapeModelEstimatorBase< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::LabelOverlapMeasuresImageFilter< TLabelImage >, itk::LabelStatisticsImageFilter< TInputImage, TLabelImage >, itk::MaximumProjectionImageFilter< TInputImage, TOutputImage >, itk::MeanProjectionImageFilter< TInputImage, TOutputImage, TAccumulate >, itk::MedianProjectionImageFilter< TInputImage, TOutputImage >, itk::MinimumMaximumImageFilter< TInputImage >, itk::MinimumProjectionImageFilter< TInputImage, TOutputImage >, itk::ProjectionImageFilter< TInputImage, TOutputImage, TAccumulator >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::BinaryAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Function::BinaryThresholdAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MaximumAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MeanAccumulator< TInputImage::PixelType, typename NumericTraits< typename TOutputImage::PixelType >::AccumulateType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MedianAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MinimumAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::StandardDeviationAccumulator< TInputImage::PixelType, typename NumericTraits< typename TOutputImage::PixelType >::AccumulateType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::SumAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::StandardDeviationProjectionImageFilter< TInputImage, TOutputImage, TAccumulate >, itk::StatisticsImageFilter< TInputImage >, itk::SumProjectionImageFilter< TInputImage, TOutputImage >, itk::AggregateLabelMapFilter< TImage >, itk::AttributeKeepNObjectsLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeOpeningLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributePositionLabelMapFilter< TImage, TAttributeAccessor, VPhysicalPosition >, itk::AttributeRelabelLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeRelabelLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::AttributeSelectionLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeSelectionLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::AttributeUniqueLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeUniqueLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::AutoCropLabelMapFilter< TInputImage >, itk::BinaryFillholeImageFilter< TInputImage >, itk::BinaryGrindPeakImageFilter< TInputImage >, itk::BinaryNotImageFilter< TImage >, itk::BinaryReconstructionByDilationImageFilter< TInputImage >, itk::BinaryReconstructionByErosionImageFilter< TInputImage >, itk::BinaryReconstructionLabelMapFilter< TImage, TMarkerImage, TAttributeAccessor >, itk::BinaryShapeKeepNObjectsImageFilter< TInputImage >, itk::BinaryShapeOpeningImageFilter< TInputImage >, itk::BinaryStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::BinaryStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::ChangeLabelLabelMapFilter< TImage >, itk::ChangeRegionLabelMapFilter< TInputImage >, itk::ConvertLabelMapFilter< TInputImage, TOutputImage >, itk::CropLabelMapFilter< TInputImage >, itk::InPlaceLabelMapFilter< TInputImage >, itk::InPlaceLabelMapFilter< TImage >, itk::LabelMapFilter< TInputImage, TOutputImage >, itk::LabelMapFilter< TImage, TImage >, itk::LabelMapFilter< TInputImage, TInputImage >, itk::LabelMapFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::LabelMapFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::LabelMapMaskImageFilter< TInputImage, TOutputImage >, itk::LabelMapToAttributeImageFilter< TInputImage, TOutputImage, TAttributeAccessor >, itk::LabelMapToBinaryImageFilter< TInputImage, TOutputImage >, itk::LabelMapToLabelImageFilter< TInputImage, TOutputImage >, itk::LabelSelectionLabelMapFilter< TImage >, itk::LabelShapeKeepNObjectsImageFilter< TInputImage >, itk::LabelShapeOpeningImageFilter< TInputImage >, itk::LabelStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::LabelStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::LabelUniqueLabelMapFilter< TImage >, itk::MergeLabelMapFilter< TImage >, itk::ObjectByObjectLabelMapFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::PadLabelMapFilter< TInputImage >, itk::RegionFromReferenceLabelMapFilter< TInputImage >, itk::RelabelLabelMapFilter< TImage >, itk::ShapeKeepNObjectsLabelMapFilter< TImage >, itk::ShapeLabelMapFilter< TImage, TLabelImage >, itk::ShapeLabelMapFilter< TImage, Image< TImage::PixelType, TImage::ImageDimension > >, itk::ShapeOpeningLabelMapFilter< TImage >, itk::ShapePositionLabelMapFilter< TImage >, itk::ShapeRelabelImageFilter< TInputImage >, itk::ShapeRelabelLabelMapFilter< TImage >, itk::ShapeUniqueLabelMapFilter< TImage >, itk::ShiftScaleLabelMapFilter< TImage >, itk::StatisticsKeepNObjectsLabelMapFilter< TImage >, itk::StatisticsLabelMapFilter< TImage, TFeatureImage >, itk::StatisticsOpeningLabelMapFilter< TImage >, itk::StatisticsPositionLabelMapFilter< TImage >, itk::StatisticsRelabelImageFilter< TInputImage, TFeatureImage >, itk::StatisticsRelabelLabelMapFilter< TImage >, itk::StatisticsUniqueLabelMapFilter< TImage >, itk::AnchorDilateImageFilter< TImage, TKernel >, itk::AnchorErodeDilateImageFilter< TImage, TKernel, TFunction1 >, itk::AnchorErodeDilateImageFilter< TImage, TKernel, std::greater< TImage::PixelType > >, itk::AnchorErodeDilateImageFilter< TImage, TKernel, std::less< TImage::PixelType > >, itk::AnchorErodeImageFilter< TImage, TKernel >, itk::AnchorOpenCloseImageFilter< TImage, TKernel, TCompare1, TCompare2 >, itk::AnchorOpenCloseImageFilter< TImage, TKernel, std::greater< TImage::PixelType >, std::less< TImage::PixelType > >, itk::AnchorOpenCloseImageFilter< TImage, TKernel, std::less< TImage::PixelType >, std::greater< TImage::PixelType > >, itk::BasicDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::BasicErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::BlackTopHatImageFilter< TInputImage, TOutputImage, TKernel >, itk::ClosingByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::DoubleThresholdImageFilter< TInputImage, TOutputImage >, itk::GrayscaleConnectedClosingImageFilter< TInputImage, TOutputImage >, itk::GrayscaleConnectedOpeningImageFilter< TInputImage, TOutputImage >, itk::GrayscaleDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleFillholeImageFilter< TInputImage, TOutputImage >, itk::GrayscaleFunctionDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleFunctionErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleGeodesicDilateImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGeodesicErodeImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGrindPeakImageFilter< TInputImage, TOutputImage >, itk::GrayscaleMorphologicalClosingImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleMorphologicalOpeningImageFilter< TInputImage, TOutputImage, TKernel >, itk::HConcaveImageFilter< TInputImage, TOutputImage >, itk::HConvexImageFilter< TInputImage, TOutputImage >, itk::HMaximaImageFilter< TInputImage, TOutputImage >, itk::HMinimaImageFilter< TInputImage, TOutputImage >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel, THistogram >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension >, Function::RankHistogram< TInputImage::PixelType > >, itk::MaskedRankImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel >, itk::MorphologicalGradientImageFilter< TInputImage, TOutputImage, TKernel >, itk::MorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::MovingHistogramDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::MovingHistogramErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::MovingHistogramMorphologicalGradientImageFilter< TInputImage, TOutputImage, TKernel >, itk::MovingHistogramMorphologyImageFilter< TInputImage, TOutputImage, TKernel, THistogram >, itk::MovingHistogramMorphologyImageFilter< TInputImage, TOutputImage, TKernel, Function::MorphologyHistogram< TInputImage::PixelType, std::greater< TInputImage::PixelType > > >, itk::MovingHistogramMorphologyImageFilter< TInputImage, TOutputImage, TKernel, Function::MorphologyHistogram< TInputImage::PixelType, std::less< TInputImage::PixelType > > >, itk::OpeningByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::RankImageFilter< TInputImage, TOutputImage, TKernel >, itk::ReconstructionByDilationImageFilter< TInputImage, TOutputImage >, itk::ReconstructionByErosionImageFilter< TInputImage, TOutputImage >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, TCompare >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::greater< TOutputImage::PixelType > >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::less< TOutputImage::PixelType > >, itk::RegionalMaximaImageFilter< TInputImage, TOutputImage >, itk::RegionalMinimaImageFilter< TInputImage, TOutputImage >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, TFunction1, TFunction2 >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::greater< TInputImage::PixelType >, std::greater< TOutputImage::PixelType > >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::less< TInputImage::PixelType >, std::less< TOutputImage::PixelType > >, itk::ValuedRegionalMaximaImageFilter< TInputImage, TOutputImage >, itk::ValuedRegionalMinimaImageFilter< TInputImage, TOutputImage >, itk::VanHerkGilWermanDilateImageFilter< TImage, TKernel >, itk::VanHerkGilWermanErodeDilateImageFilter< TImage, TKernel, TFunction1 >, itk::VanHerkGilWermanErodeDilateImageFilter< TImage, TKernel, MaxFunctor< TImage::PixelType > >, itk::VanHerkGilWermanErodeDilateImageFilter< TImage, TKernel, MinFunctor< TImage::PixelType > >, itk::VanHerkGilWermanErodeImageFilter< TImage, TKernel >, itk::WhiteTopHatImageFilter< TInputImage, TOutputImage, TKernel >, itk::ChainCodeToFourierSeriesPathFilter< TInputChainCodePath, TOutputFourierSeriesPath >, itk::ContourExtractor2DImageFilter< TInputImage >, itk::ExtractOrthogonalSwath2DImageFilter< TImage >, itk::ImageAndPathToImageFilter< TInputImage, TInputPath, TOutputImage >, itk::ImageAndPathToImageFilter< TImage, ParametricPath< 2 >, TImage >, itk::ImageToPathFilter< TInputImage, TOutputPath >, itk::ImageToPathFilter< TInputImage, PolyLineParametricPath< 2 > >, itk::OrthogonalSwath2DPathFilter< TFourierSeriesPath, TSwathMeritImage >, itk::PathAndImageToPathFilter< TInputPath, TInputImage, TOutputPath >, itk::PathAndImageToPathFilter< TFourierSeriesPath, TSwathMeritImage, OrthogonallyCorrected2DParametricPath >, itk::PathSource< TOutputPath >, itk::PathSource< TOutputFourierSeriesPath >, itk::PathSource< PolyLineParametricPath< 2 > >, itk::PathSource< OrthogonallyCorrected2DParametricPath >, itk::PathSource< TOutputChainCodePath >, itk::PathToChainCodePathFilter< TInputPath, TOutputChainCodePath >, itk::PathToImageFilter< TInputPath, TOutputImage >, itk::PathToPathFilter< TInputPath, TOutputPath >, itk::PathToPathFilter< TInputChainCodePath, TOutputFourierSeriesPath >, itk::PathToPathFilter< TFourierSeriesPath, OrthogonallyCorrected2DParametricPath >, itk::PathToPathFilter< TInputPath, TOutputChainCodePath >, itk::BorderQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::CleanQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >, itk::DelaunayConformingQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscreteCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscreteCurvatureQuadEdgeMeshFilter< TInputMesh, TInputMesh >, itk::DiscreteCurvatureTensorQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscreteGaussianCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscreteMaximumCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscreteMeanCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscreteMinimumCurvatureQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscretePrincipalCurvaturesQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DiscretePrincipalCurvaturesQuadEdgeMeshFilter< TInputMesh, TInputMesh >, itk::EdgeDecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >, itk::LaplacianDeformationQuadEdgeMeshFilter< TInputMesh, TOutputMesh, TSolverTraits >, itk::LaplacianDeformationQuadEdgeMeshFilterWithHardConstraints< TInputMesh, TOutputMesh, TSolverTraits >, itk::LaplacianDeformationQuadEdgeMeshFilterWithSoftConstraints< TInputMesh, TOutputMesh, TSolverTraits >, itk::NormalQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::ParameterizationQuadEdgeMeshFilter< TInputMesh, TOutputMesh, TSolverTraits >, itk::QuadricDecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >, itk::SmoothingQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::SquaredEdgeLengthDecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >, itk::BinomialBlurImageFilter< TInputImage, TOutputImage >, itk::BoxMeanImageFilter< TInputImage, TOutputImage >, itk::BoxSigmaImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TInputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::FFTDiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::MeanImageFilter< TInputImage, TOutputImage >, itk::MedianImageFilter< TInputImage, TOutputImage >, itk::RecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::SmoothingRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::SpatialFunctionImageEvaluatorFilter< TSpatialFunction, TInputImage, TOutputImage >, itk::BinaryThresholdImageFilter< TInputImage, TOutputImage >, itk::BinaryThresholdProjectionImageFilter< TInputImage, TOutputImage >, itk::HistogramThresholdCalculator< THistogram, TOutput >, itk::HistogramThresholdCalculator< THistogram, double >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TOutputImage >, itk::HuangThresholdCalculator< THistogram, TOutput >, itk::HuangThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::IntermodesThresholdCalculator< THistogram, TOutput >, itk::IntermodesThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::IsoDataThresholdCalculator< THistogram, TOutput >, itk::IsoDataThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::KappaSigmaThresholdImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::KittlerIllingworthThresholdCalculator< THistogram, TOutput >, itk::KittlerIllingworthThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::LiThresholdCalculator< THistogram, TOutput >, itk::LiThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::MaximumEntropyThresholdCalculator< THistogram, TOutput >, itk::MaximumEntropyThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::MomentsThresholdCalculator< THistogram, TOutput >, itk::MomentsThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::OtsuMultipleThresholdsImageFilter< TInputImage, TOutputImage >, itk::OtsuThresholdCalculator< THistogram, TOutput >, itk::OtsuThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::RenyiEntropyThresholdCalculator< THistogram, TOutput >, itk::RenyiEntropyThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::ShanbhagThresholdCalculator< THistogram, TOutput >, itk::ShanbhagThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::ThresholdImageFilter< TImage >, itk::ThresholdLabelerImageFilter< TInputImage, TOutputImage >, itk::TriangleThresholdCalculator< THistogram, TOutput >, itk::TriangleThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::YenThresholdCalculator< THistogram, TOutput >, itk::YenThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::GDCMSeriesFileNames, itk::ImageFileReader< TOutputImage, ConvertPixelTraits >, itk::ImageFileWriter< TInputImage >, itk::ImageSeriesReader< TOutputImage >, itk::ImageSeriesWriter< TInputImage, TOutputImage >, itk::MeshFileReader< TOutputMesh, ConvertPointPixelTraits, ConvertCellPixelTraits >, itk::MeshFileWriter< TInputMesh >, itk::AreaClosingImageFilter< TInputImage, TOutputImage, TAttribute >, itk::AreaOpeningImageFilter< TInputImage, TOutputImage, TAttribute >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, TAttribute, TFunction >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, typename TInputImage::SpacingType::ValueType, std::less< TInputImage::PixelType > >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, typename TInputImage::SpacingType::ValueType, std::greater< TInputImage::PixelType > >, itk::ConformalFlatteningMeshFilter< TInputMesh, TOutputMesh >, itk::DirectFourierReconstructionImageToImageFilter< TInputImage, TOutputImage >, itk::FastApproximateRankImageFilter< TInputImage, TOutputImage >, itk::GridForwardWarpImageFilter< TDisplacementField, TOutputImage >, itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >, itk::MiniPipelineSeparableImageFilter< TInputImage, TOutputImage, TFilter >, itk::MiniPipelineSeparableImageFilter< TInputImage, TOutputImage, RankImageFilter< TInputImage, TInputImage, FlatStructuringElement< TInputImage::ImageDimension > > >, itk::MultiphaseDenseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFunction, TIdCell >, itk::MultiphaseDenseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, ScalarChanAndVeseLevelSetFunction< TInputImage, TFeatureImage > >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFiniteDifferenceFunction, TIdCell >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFunction, unsigned int >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, ScalarChanAndVeseLevelSetFunction< TInputImage, TFeatureImage >, unsigned int >, itk::MultiphaseSparseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFunction, TIdCell >, itk::MultiphaseSparseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, ScalarChanAndVeseLevelSetFunction< TInputImage, TFeatureImage >, unsigned int >, itk::RobustAutomaticThresholdImageFilter< TInputImage, TGradientImage, TOutputImage >, itk::ScalarChanAndVeseDenseLevelSetImageFilter< TInputImage, TFeatureImage, TOutputImage, TFunction, TSharedData >, itk::ScalarChanAndVeseSparseLevelSetImageFilter< TInputImage, TFeatureImage, TOutputImage, TFunction, TSharedData, TIdCell >, itk::StochasticFractalDimensionImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::EigenAnalysis2DImageFilter< TInputImage, TEigenValueImage, TEigenVectorImage >, itk::NarrowBandImageFilterBase< TInputImage, TOutputImage >, itk::NarrowBandImageFilterBase< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::Statistics::CovarianceSampleFilter< TSample >, itk::HistogramToEntropyImageFilter< THistogram, TImage >, itk::HistogramToImageFilter< THistogram, TImage, TFunction >, itk::HistogramToImageFilter< THistogram, Image< double, 3 >, Function::HistogramEntropyFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< SizeValueType, 3 >, Function::HistogramIntensityFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< double, 3 >, Function::HistogramLogProbabilityFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< float, 3 >, Function::HistogramProbabilityFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToIntensityImageFilter< THistogram, TImage >, itk::HistogramToLogProbabilityImageFilter< THistogram, TImage >, itk::HistogramToProbabilityImageFilter< THistogram, TImage >, itk::Statistics::HistogramToRunLengthFeaturesFilter< THistogram >, itk::Statistics::HistogramToTextureFeaturesFilter< THistogram >, itk::Statistics::ImageClassifierFilter< TSample, TInputImage, TOutputImage >, itk::Statistics::ImageToHistogramFilter< TImage >, itk::Statistics::ImageToListSampleFilter< TImage, TMaskImage >, itk::Statistics::MaskedImageToHistogramFilter< TImage, TMaskImage >, itk::Statistics::MeanSampleFilter< TSample >, itk::Statistics::NeighborhoodSampler< TSample >, itk::Statistics::SampleClassifierFilter< TSample >, itk::Statistics::SampleToSubsampleFilter< TSample >, itk::Statistics::ScalarImageToCooccurrenceListSampleFilter< TImage >, itk::Statistics::ScalarImageToCooccurrenceMatrixFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::Statistics::ScalarImageToRunLengthFeaturesFilter< TImageType, THistogramFrequencyContainer >, itk::Statistics::ScalarImageToRunLengthMatrixFilter< TImageType, THistogramFrequencyContainer >, itk::Statistics::ScalarImageToTextureFeaturesFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::Statistics::StandardDeviationPerComponentSampleFilter< TSample >, itk::Statistics::WeightedCovarianceSampleFilter< TSample >, itk::Statistics::WeightedMeanSampleFilter< TSample >, itk::BlockMatchingImageFilter< TFixedImage, TMovingImage, TFeatures, TDisplacements, TSimilarities >, itk::ImageRegistrationMethod< TFixedImage, TMovingImage >, itk::ImageToSpatialObjectRegistrationMethod< TFixedImage, TMovingSpatialObject >, itk::MultiResolutionImageRegistrationMethod< TFixedImage, TMovingImage >, itk::MultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::PointSetToImageRegistrationMethod< TFixedPointSet, TMovingImage >, itk::PointSetToPointSetRegistrationMethod< TFixedPointSet, TMovingPointSet >, itk::PointSetToSpatialObjectDemonsRegistration< TFixedPointSet, TMovingSpatialObject >, itk::RecursiveMultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::GPUDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TParentImageFilter >, itk::GPUPDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TParentImageFilter >, itk::GPUPDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::CurvatureRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TImageForceFunction >, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::DiffeomorphicDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::FastSymmetricForcesDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::LevelSetMotionRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::MultiResolutionPDEDeformableRegistration< TFixedImage, TMovingImage, TDisplacementField, TRealType, TFloatImageType, TRegistrationType, TDefaultRegistrationType >, itk::PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::SymmetricForcesDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::BSplineSyNImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, BSplineSmoothingOnUpdateDisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, DisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, TimeVaryingBSplineVelocityFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::SyNImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::SyNImageRegistrationMethod< TFixedImage, TMovingImage, BSplineSmoothingOnUpdateDisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::TimeVaryingBSplineVelocityFieldImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::TimeVaryingVelocityFieldImageRegistrationMethodv4< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::BayesianClassifierImageFilter< TInputVectorImage, TLabelsType, TPosteriorsPrecisionType, TPriorsPrecisionType >, itk::BayesianClassifierInitializationImageFilter< TInputImage, TProbabilityPrecisionType >, itk::ScalarImageKmeansImageFilter< TInputImage, TOutputImage >, itk::ConnectedComponentFunctorImageFilter< TInputImage, TOutputImage, TFunctor, TMaskImage >, itk::ConnectedComponentFunctorImageFilter< TInputImage, TOutputImage, Functor::SimilarPixelsFunctor< TInputImage::ValueType >, TInputImage >, itk::ConnectedComponentFunctorImageFilter< TInputImage, TOutputImage, Functor::SimilarVectorsFunctor< TInputImage::ValueType >, TInputImage >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TInputImage >, itk::HardConnectedComponentImageFilter< TInputImage, TOutputImage >, itk::RelabelComponentImageFilter< TInputImage, TOutputImage >, itk::ScalarConnectedComponentImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::ThresholdMaximumConnectedComponentsImageFilter< TInputImage, TOutputImage >, itk::VectorConnectedComponentImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::DeformableSimplexMesh3DBalloonForceFilter< TInputMesh, TOutputMesh >, itk::DeformableSimplexMesh3DFilter< TInputMesh, TOutputMesh >, itk::DeformableSimplexMesh3DGradientConstraintForceFilter< TInputMesh, TOutputMesh >, itk::KLMRegionGrowImageFilter< TInputImage, TOutputImage >, itk::RegionGrowImageFilter< TInputImage, TOutputImage >, itk::BinaryMedianImageFilter< TInputImage, TOutputImage >, itk::LabelVotingImageFilter< TInputImage, TOutputImage >, itk::MultiLabelSTAPLEImageFilter< TInputImage, TOutputImage, TWeights >, itk::VotingBinaryHoleFillingImageFilter< TInputImage, TOutputImage >, itk::VotingBinaryImageFilter< TInputImage, TOutputImage >, itk::VotingBinaryIterativeHoleFillingImageFilter< TImage >, itk::AnisotropicFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::BinaryMaskToNarrowBandPointSetFilter< TInputImage, TOutputMesh >, itk::CannySegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::CollidingFrontsImageFilter< TInputImage, TOutputImage >, itk::CurvesLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ExtensionVelocitiesImageFilter< TLevelSet, TAuxValue, VAuxDimension >, itk::GeodesicActiveContourLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::GeodesicActiveContourShapePriorLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ImplicitManifoldNormalVectorFilter< TInputImage, TSparseOutputImage >, itk::IsotropicFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::LaplacianSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::NarrowBandCurvesLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType, TOutputImage >, itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, float, Image< float, TInputImage::ImageDimension > >, itk::NarrowBandThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ParallelSparseFieldLevelSetImageFilter< TInputImage, TOutputImage >, itk::ReinitializeLevelSetImageFilter< TLevelSet >, itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >, itk::ShapeDetectionLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ShapePriorSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ShapePriorSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >, itk::SparseFieldFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::SparseFieldLevelSetImageFilter< TInputImage, TOutputImage >, itk::SparseFieldLevelSetImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::UnsharpMaskLevelSetImageFilter< TInputImage, TOutputImage >, itk::VectorThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::LevelSetDomainMapImageFilter< TInputImage, TOutputImage >, itk::MRFImageFilter< TInputImage, TClassifiedImage >, itk::RGBGibbsPriorFilter< TInputImage, TClassifiedImage >, itk::ConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::ConnectedThresholdImageFilter< TInputImage, TOutputImage >, itk::IsolatedConnectedImageFilter< TInputImage, TOutputImage >, itk::NeighborhoodConnectedImageFilter< TInputImage, TOutputImage >, itk::VectorConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::SLICImageFilter< TInputImage, TOutputImage, TDistancePixel >, itk::VoronoiDiagram2DGenerator< TCoordType >, itk::VoronoiPartitioningImageFilter< TInputImage, TOutputImage >, itk::VoronoiSegmentationImageFilter< TInputImage, TOutputImage, TBinaryPriorImage >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, TBinaryPriorImage >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, Image< unsigned char, 2 > >, itk::VoronoiSegmentationRGBImageFilter< TInputImage, TOutputImage >, itk::IsolatedWatershedImageFilter< TInputImage, TOutputImage >, itk::MorphologicalWatershedFromMarkersImageFilter< TInputImage, TLabelImage >, itk::MorphologicalWatershedImageFilter< TInputImage, TOutputImage >, itk::TobogganImageFilter< TInputImage, TOutputImage >, itk::watershed::BoundaryResolver< TPixelType, TDimension >, itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >, itk::WatershedImageFilter< TInputImage >, itk::watershed::Relabeler< TScalar, TImageDimension >, itk::watershed::Relabeler< ScalarType, Self::ImageDimension >, itk::watershed::Segmenter< TInputImage >, itk::watershed::Segmenter< InputImageType >, itk::watershed::SegmentTreeGenerator< TScalar >, itk::watershed::SegmentTreeGenerator< ScalarType >, itk::TemporalProcessObject, itk::VideoSource< TOutputVideoStream >, itk::VideoSource< TVideoStream >, itk::VideoSource< itk::VideoStream< TImageToImageFilter::OutputImageType > >, itk::VideoToVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::VideoToVideoFilter< TVideoStream, TVideoStream >, itk::VideoToVideoFilter< itk::VideoStream< TImageToImageFilter::InputImageType >, itk::VideoStream< TImageToImageFilter::OutputImageType > >, itk::DecimateFramesVideoFilter< TVideoStream >, itk::FrameAverageVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::FrameDifferenceVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::ImageFilterToVideoFilterWrapper< TImageToImageFilter >, itk::VideoFileReader< TOutputVideoStream >, and itk::VideoFileWriter< TInputVideoStream >.
GetNumberOfIndexedInputs()
DataObjectPointerArraySizeType itk::ProcessObject::GetNumberOfIndexedInputs () const
Get the number of defined Indexed inputs.
This is merely the size of the index input vector, not the number of inputs that have valid DataObject's assigned. The Primary inputs is handled as a special case. Use GetNumberOfValidRequiredInputs() to determine how many indexed inputs are non-null.
All indexed inputs up to this value are defined.
See also
GetNumberOfInputs
GetNumberOfValidRequiredInputs
GetNumberOfIndexedOutputs()
DataObjectPointerArraySizeType itk::ProcessObject::GetNumberOfIndexedOutputs () const
The number of defined Indexed outputs.
GetNumberOfInputs()
DataObjectPointerArraySizeType itk::ProcessObject::GetNumberOfInputs () const
Get the size of the input container.
If the Primary input is nullptr it is not counted. This is not the number of inputs that have valid DataObject's assigned. Use GetNumberOfValidRequiredInputs() to determine how many inputs are non-null.
See also
GetNumberOfValidRequiredInputs
GetNumberOfIndexedInputs
Referenced by itk::HistogramThresholdCalculator< THistogram, TOutput >::GetInput().
GetNumberOfOutputs()
DataObjectPointerArraySizeType itk::ProcessObject::GetNumberOfOutputs () const
Get the size of the output container.
Referenced by itk::HistogramThresholdCalculator< THistogram, TOutput >::GetOutput(), and itk::HistogramThresholdCalculator< THistogram, TOutput >::GetThreshold().
GetNumberOfRequiredInputs()
virtual const DataObjectPointerArraySizeType & itk::ProcessObject::GetNumberOfRequiredInputs () const protected virtual
GetNumberOfRequiredOutputs()
virtual const DataObjectPointerArraySizeType & itk::ProcessObject::GetNumberOfRequiredOutputs () const protected virtual
GetNumberOfValidRequiredInputs()
virtual DataObjectPointerArraySizeType itk::ProcessObject::GetNumberOfValidRequiredInputs () const virtual
Get the number of valid indexed inputs.
Returns the number of non-null indexed inputs. This method is used to determine whether the correct number of inputs are set to valid values.
See also
GetNumberOfInputs
GetNumberOfIndexedInputs
Reimplemented in itk::MultiResolutionPDEDeformableRegistration< TFixedImage, TMovingImage, TDisplacementField, TRealType, TFloatImageType, TRegistrationType, TDefaultRegistrationType >, and itk::PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >.
GetNumberOfWorkUnits()
virtual const ThreadIdType & itk::ProcessObject::GetNumberOfWorkUnits () const virtual
Get/Set the number of work units to create when executing.
GetOutput() [1/4]
DataObject * itk::ProcessObject::GetOutput (const DataObjectIdentifierType & key) protected
Return an output
Referenced by itk::watershed::Segmenter< TInputImage >::GetBoundary(), itk::BlockMatchingImageFilter< TFixedImage, TMovingImage, TFeatures, TDisplacements, TSimilarities >::GetDisplacements(), itk::watershed::BoundaryResolver< TPixelType, TDimension >::GetEquivalencyTable(), itk::Testing::HashImageFilter< TImageType >::GetHashOutput(), itk::HistogramThresholdCalculator< THistogram, TOutput >::GetOutput(), itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >::GetOutputImage(), itk::watershed::Relabeler< TScalar, TImageDimension >::GetOutputImage(), itk::watershed::Segmenter< TInputImage >::GetOutputImage(), itk::watershed::SegmentTreeGenerator< TScalar >::GetOutputSegmentTree(), itk::BSplineScatteredDataPointSetToImageFilter< TInputPointSet, TOutputImage >::GetPhiLattice(), itk::watershed::Segmenter< TInputImage >::GetSegmentTable(), itk::BlockMatchingImageFilter< TFixedImage, TMovingImage, TFeatures, TDisplacements, TSimilarities >::GetSimilarities(), and itk::HistogramThresholdCalculator< THistogram, TOutput >::GetThreshold().
GetOutput() [2/4]
const DataObject * itk::ProcessObject::GetOutput (const DataObjectIdentifierType & key) const protected
Return an output
GetOutput() [3/4]
DataObject * itk::ProcessObject::GetOutput (DataObjectPointerArraySizeType i) protected
Method used internally for getting an indexed output.
GetOutput() [4/4]
const DataObject * itk::ProcessObject::GetOutput (DataObjectPointerArraySizeType i) const protected
Method used internally for getting an indexed output.
GetOutputNames()
NameArray itk::ProcessObject::GetOutputNames () const
Return an array with the defined names of the outputs.
The names are ordered lexicographically, and match the order of the data object produced by GetOutputs()
GetOutputs()
DataObjectPointerArray itk::ProcessObject::GetOutputs ()
Return an array with the defined named outputs.
The order of the outputs match the order of the input names produced by GetOutputNames().
GetPrimaryInput() [1/2]
DataObject * itk::ProcessObject::GetPrimaryInput () inline protected
Return the main input
Definition at line 603 of file itkProcessObject.h.
GetPrimaryInput() [2/2]
const DataObject * itk::ProcessObject::GetPrimaryInput () const inline protected
Return the main input
Definition at line 608 of file itkProcessObject.h.
GetPrimaryInputName()
virtual const char * itk::ProcessObject::GetPrimaryInputName () const inline protected virtual
Set/Get the name associated with the Primary input. Defaults to "Primary".
Definition at line 618 of file itkProcessObject.h.
GetPrimaryOutput() [1/2]
DataObject * itk::ProcessObject::GetPrimaryOutput () inline protected
Return the main output
Definition at line 737 of file itkProcessObject.h.
GetPrimaryOutput() [2/2]
const DataObject * itk::ProcessObject::GetPrimaryOutput () const inline protected
Return the main output
Definition at line 742 of file itkProcessObject.h.
GetPrimaryOutputName()
virtual const char * itk::ProcessObject::GetPrimaryOutputName () const inline protected virtual
Set/Get the name associated with the Primary output. Defaults to "Primary".
Definition at line 714 of file itkProcessObject.h.
GetProgress()
virtual float itk::ProcessObject::GetProgress () const inline virtual
Get the execution progress of a process object.
Deprecated:
Set the execution progress of a process object. The progress is a floating number in [0,1] with 0 meaning no progress and 1 meaning the filter has completed execution. The ProgressEvent is NOT invoked. This method is deprecated because filters should not be calling SetProgress directly but should be using UpdateProgress or IncrementProgress instead.
The progress is a floating number in [0,1] with 0 meaning no progress and 1 meaning the filter has completed execution.
Definition at line 325 of file itkProcessObject.h.
GetReleaseDataBeforeUpdateFlag()
virtual const bool & itk::ProcessObject::GetReleaseDataBeforeUpdateFlag () const virtual
Turn on/off the flags to control whether the bulk data belonging to the outputs of this ProcessObject are released/reallocated during an Update(). In limited memory scenarios, a user may want to force the elements of a pipeline to release any bulk data that is going to be regenerated anyway during an Update() in order to control peak memory allocation. Note that this flag is different from the ReleaseDataFlag. ReleaseDataFlag manages the deallocation of a ProcessObject's bulk output data once that data has been consumed by a downstream ProcessObject. The ReleaseDataBeforeUpdateFlag manages the deallocation/reallocation of bulk data during a pipeline update to control peak memory utilization. Default value is on.
GetReleaseDataFlag()
virtual bool itk::ProcessObject::GetReleaseDataFlag () const virtual
Turn on/off the flags to control whether the bulk data belonging to the outputs of this ProcessObject are released after being used by a downstream ProcessObject. Default value is off. Another options for controlling memory utilization is the ReleaseDataBeforeUpdateFlag.
GetRequiredInputNames()
NameArray itk::ProcessObject::GetRequiredInputNames () const
Return an array with the names of the required inputs.
GetThreaderUpdateProgress()
virtual bool itk::ProcessObject::GetThreaderUpdateProgress () const protected virtual
When true, the MultiThreader will report course grain progress. If set to false, a progress must be explicitly updated in derived filters.
HasInput()
bool itk::ProcessObject::HasInput (const DataObjectIdentifierType & key) const
Return true if the input with this name is defined
HasOutput()
bool itk::ProcessObject::HasOutput (const DataObjectIdentifierType & key) const
Return true if the output with this name is defined.
IncrementProgress()
void itk::ProcessObject::IncrementProgress (float increment)
Increment the progress of the process object.
Atomically add the the current progress and may invoke observers of the ProgressEvent. Progress is represented in [0.0,1.0] or percentage. This method will invoke the ProgressEvent when called by the same as the pipeline.
Multiple threads may call this method and the total progress will be atomically incremented.
IsIndexedInputName()
bool itk::ProcessObject::IsIndexedInputName (const DataObjectIdentifierType &) const protected
IsIndexedOutputName()
bool itk::ProcessObject::IsIndexedOutputName (const DataObjectIdentifierType &) const protected
IsRequiredInputName()
bool itk::ProcessObject::IsRequiredInputName (const DataObjectIdentifierType &) const protected
Query if the named input is required by name.
MakeIndexFromInputName()
DataObjectPointerArraySizeType itk::ProcessObject::MakeIndexFromInputName (const DataObjectIdentifierType & name) const protected
MakeIndexFromName()
DataObjectPointerArraySizeType itk::ProcessObject::MakeIndexFromName (const DataObjectIdentifierType &) const private
MakeIndexFromOutputName()
DataObjectPointerArraySizeType itk::ProcessObject::MakeIndexFromOutputName (const DataObjectIdentifierType & name) const protected
MakeNameFromIndex()
DataObjectIdentifierType itk::ProcessObject::MakeNameFromIndex (DataObjectPointerArraySizeType) const private
MakeNameFromInputIndex()
DataObjectIdentifierType itk::ProcessObject::MakeNameFromInputIndex (DataObjectPointerArraySizeType idx) const protected
MakeNameFromOutputIndex()
DataObjectIdentifierType itk::ProcessObject::MakeNameFromOutputIndex (DataObjectPointerArraySizeType idx) const protected
MakeOutput() [1/2]
virtual DataObjectPointer itk::ProcessObject::MakeOutput (const DataObjectIdentifierType &) virtual
Make a DataObject of the correct type to used as the specified output.
Every ProcessObject subclass must be able to create a DataObject that can be used as a specified output. This method is automatically called when DataObject::DisconnectPipeline() is called. DataObject::DisconnectPipeline, disconnects a data object from being an output of its current source. When the data object is disconnected, the ProcessObject needs to construct a replacement output data object so that the ProcessObject is in a valid state. So DataObject::DisconnectPipeline eventually calls ProcessObject::MakeOutput. Note that MakeOutput always returns a itkSmartPointer to a DataObject. ImageSource and MeshSource override this method to create the correct type of image and mesh respectively. If a filter has multiple outputs of different types, then that filter must provide an implementation of MakeOutput().
Reimplemented in itk::DanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::DanielssonDistanceMapImageFilter< ImageType, ImageType >, itk::SignedDanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel, THistogram >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension >, Function::RankHistogram< TInputImage::PixelType > >, itk::MinimumMaximumImageFilter< TInputImage >, itk::StatisticsImageFilter< TInputImage >, itk::ImageSource< TOutputImage >, itk::ImageSource< TImageType >, itk::ImageSource< TInputImage >, itk::ImageSource< TImage >, itk::ImageSource< TInputImage1 >, itk::ImageSource< Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageSource< VectorImage< float, TInputImage::ImageDimension > >, itk::ImageSource< Image< float, TInputImage::ImageDimension > >, itk::ImageSource< VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< DiffusionTensor3D< double >, 3 > >, itk::ImageSource< TEigenValueImage >, itk::ImageSource< Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageSource< TLevelSet >, itk::ImageSource< TSparseOutputImageType >, itk::ImageSource< Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< TPixel, 3 > >, itk::ImageSource< Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< double, 3 > >, itk::ImageSource< Image< SizeValueType, 3 > >, itk::ImageSource< Image< float, 3 > >, itk::ImageSource< Image< TOutputPixelType, 2 > >, itk::ImageSource< Image< double, TInputImage::ImageDimension > >, itk::ImageSource< TSparseOutputImage >, itk::ImageSource< Image< TPixel, 2 > >, itk::ImageSource< Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageSource< TLabelImage >, itk::ImageSource< Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageSource< Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageSource< TClassifiedImage >, itk::ImageSource< itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageSource< TDisplacementField >, itk::ImageSource< Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageSource< Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageSource< Image< IdentifierType, TInputImage::ImageDimension > >, and itk::ImageSource< ImageType >.
MakeOutput() [2/2]
virtual DataObjectPointer itk::ProcessObject::MakeOutput (DataObjectPointerArraySizeType idx) virtual
Make a DataObject of the correct type to used as the specified output.
Every ProcessObject subclass must be able to create a DataObject that can be used as a specified output. This method is automatically called when DataObject::DisconnectPipeline() is called. DataObject::DisconnectPipeline, disconnects a data object from being an output of its current source. When the data object is disconnected, the ProcessObject needs to construct a replacement output data object so that the ProcessObject is in a valid state. So DataObject::DisconnectPipeline eventually calls ProcessObject::MakeOutput. Note that MakeOutput always returns a itkSmartPointer to a DataObject. ImageSource and MeshSource override this method to create the correct type of image and mesh respectively. If a filter has multiple outputs of different types, then that filter must provide an implementation of MakeOutput().
Reimplemented in itk::DanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::DanielssonDistanceMapImageFilter< ImageType, ImageType >, itk::SignedDanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel, THistogram >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension >, Function::RankHistogram< TInputImage::PixelType > >, itk::ImageToMeshFilter< TInputImage, TOutputMesh >, itk::ImageToMeshFilter< TImage, PointSet< Matrix< SpacePrecisionType, TImage::ImageDimension, TImage::ImageDimension >, TImage::ImageDimension > >, itk::MeshSource< TOutputMesh >, itk::MeshSource< PointSet< Vector< typename TFeatures::PointType::ValueType, TFeatures::PointDimension >, TFeatures::PointDimension > >, itk::MeshSource< TInputMesh >, itk::MeshSource< TOutput >, itk::MeshSource< PointSet< Matrix< SpacePrecisionType, TImage::ImageDimension, TImage::ImageDimension >, TImage::ImageDimension > >, itk::MeshSource< TOutputPointSet >, itk::MeshSource< VoronoiDiagram2D< TCoordType > >, itk::Testing::HashImageFilter< TImageType >, itk::DanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::DanielssonDistanceMapImageFilter< ImageType, ImageType >, itk::SignedDanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::MultiScaleHessianBasedMeasureImageFilter< TInputImage, THessianImage, TOutputImage >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel, THistogram >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension >, Function::RankHistogram< TInputImage::PixelType > >, itk::PathSource< TOutputPath >, itk::PathSource< TOutputFourierSeriesPath >, itk::PathSource< PolyLineParametricPath< 2 > >, itk::PathSource< OrthogonallyCorrected2DParametricPath >, itk::PathSource< TOutputChainCodePath >, itk::EigenAnalysis2DImageFilter< TInputImage, TEigenValueImage, TEigenVectorImage >, itk::Statistics::ImageToListSampleFilter< TImage, TMaskImage >, itk::Statistics::MeanSampleFilter< TSample >, itk::Statistics::SampleClassifierFilter< TSample >, itk::Statistics::SampleToSubsampleFilter< TSample >, itk::Statistics::ScalarImageToCooccurrenceListSampleFilter< TImage >, itk::Statistics::ScalarImageToCooccurrenceMatrixFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::Statistics::ScalarImageToRunLengthMatrixFilter< TImageType, THistogramFrequencyContainer >, itk::BayesianClassifierImageFilter< TInputVectorImage, TLabelsType, TPosteriorsPrecisionType, TPriorsPrecisionType >, itk::watershed::BoundaryResolver< TPixelType, TDimension >, itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >, itk::watershed::Relabeler< TScalar, TImageDimension >, itk::watershed::Relabeler< ScalarType, Self::ImageDimension >, itk::watershed::Segmenter< TInputImage >, itk::watershed::Segmenter< InputImageType >, itk::watershed::SegmentTreeGenerator< TScalar >, itk::watershed::SegmentTreeGenerator< ScalarType >, itk::VideoSource< TOutputVideoStream >, itk::VideoSource< TVideoStream >, itk::VideoSource< itk::VideoStream< TImageToImageFilter::OutputImageType > >, itk::Statistics::CovarianceSampleFilter< TSample >, itk::Statistics::StandardDeviationPerComponentSampleFilter< TSample >, itk::ImageRegistrationMethod< TFixedImage, TMovingImage >, itk::ImageToSpatialObjectRegistrationMethod< TFixedImage, TMovingSpatialObject >, itk::MultiResolutionImageRegistrationMethod< TFixedImage, TMovingImage >, itk::PointSetToImageRegistrationMethod< TFixedPointSet, TMovingImage >, itk::PointSetToPointSetRegistrationMethod< TFixedPointSet, TMovingPointSet >, itk::HistogramThresholdCalculator< THistogram, TOutput >, itk::HistogramThresholdCalculator< THistogram, double >, itk::Statistics::HistogramToRunLengthFeaturesFilter< THistogram >, itk::Statistics::HistogramToTextureFeaturesFilter< THistogram >, itk::Statistics::ImageToHistogramFilter< TImage >, itk::Statistics::ScalarImageToRunLengthFeaturesFilter< TImageType, THistogramFrequencyContainer >, itk::Statistics::ScalarImageToTextureFeaturesFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, BSplineSmoothingOnUpdateDisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, DisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, TimeVaryingBSplineVelocityFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageSource< TOutputImage >, itk::ImageSource< TImageType >, itk::ImageSource< TInputImage >, itk::ImageSource< TImage >, itk::ImageSource< TInputImage1 >, itk::ImageSource< Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageSource< VectorImage< float, TInputImage::ImageDimension > >, itk::ImageSource< Image< float, TInputImage::ImageDimension > >, itk::ImageSource< VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< DiffusionTensor3D< double >, 3 > >, itk::ImageSource< TEigenValueImage >, itk::ImageSource< Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageSource< TLevelSet >, itk::ImageSource< TSparseOutputImageType >, itk::ImageSource< Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< TPixel, 3 > >, itk::ImageSource< Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< double, 3 > >, itk::ImageSource< Image< SizeValueType, 3 > >, itk::ImageSource< Image< float, 3 > >, itk::ImageSource< Image< TOutputPixelType, 2 > >, itk::ImageSource< Image< double, TInputImage::ImageDimension > >, itk::ImageSource< TSparseOutputImage >, itk::ImageSource< Image< TPixel, 2 > >, itk::ImageSource< Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageSource< TLabelImage >, itk::ImageSource< Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageSource< Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageSource< TClassifiedImage >, itk::ImageSource< itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageSource< TDisplacementField >, itk::ImageSource< Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageSource< Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageSource< Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageSource< ImageType >, and itk::BlockMatchingImageFilter< TFixedImage, TMovingImage, TFeatures, TDisplacements, TSimilarities >.
PopBackInput()
virtual void itk::ProcessObject::PopBackInput () protected virtual
Reimplemented in itk::ImageToImageFilter< TInputImage, TOutputImage >, itk::ImageToImageFilter< TImageType, TImageType >, itk::ImageToImageFilter< TInputImage, TInputImage >, itk::ImageToImageFilter< TImage, TImage >, itk::ImageToImageFilter< TInputImage1, TInputImage1 >, itk::ImageToImageFilter< TInputVectorImage, Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage1, TOutputImage >, itk::ImageToImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TReferenceImagePixelType, 3 >, Image< DiffusionTensor3D< double >, 3 > >, itk::ImageToImageFilter< TInputImage, TEigenValueImage >, itk::ImageToImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< float, TLevelSet::ImageDimension >, TLevelSet >, itk::ImageToImageFilter< TInputImageType, TSparseOutputImageType >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TDisplacementField, TOutputImage >, itk::ImageToImageFilter< Image< SymmetricSecondRankTensor< double, 3 >, 3 >, Image< TPixel, 3 > >, itk::ImageToImageFilter< TInputImage, Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TInputPixelType, 2 >, Image< TOutputPixelType, 2 > >, itk::ImageToImageFilter< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TSparseOutputImage >, itk::ImageToImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageToImageFilter< TLabelImage, TLabelImage >, itk::ImageToImageFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TLabelImage, TOutputImage >, itk::ImageToImageFilter< TInputImage, TClassifiedImage >, itk::ImageToImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TLabelImage >, itk::ImageToImageFilter< TDisplacementField, TDisplacementField >, itk::ImageToImageFilter< TFeatureImage, TOutputImage >, itk::ImageToImageFilter< TLevelSet, TLevelSet >, itk::ImageToImageFilter< TInputImage, Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageToImageFilter< TMask, TImage >, itk::ImageToImageFilter< TTimeVaryingVelocityField, Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageToImageFilter< TInputImage, Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< ImageType, ImageType >, and itk::ImageToImageFilter< FeatureImageType, ImageType >.
PopFrontInput()
virtual void itk::ProcessObject::PopFrontInput () protected virtual
Reimplemented in itk::ImageToImageFilter< TInputImage, TOutputImage >, itk::ImageToImageFilter< TImageType, TImageType >, itk::ImageToImageFilter< TInputImage, TInputImage >, itk::ImageToImageFilter< TImage, TImage >, itk::ImageToImageFilter< TInputImage1, TInputImage1 >, itk::ImageToImageFilter< TInputVectorImage, Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage1, TOutputImage >, itk::ImageToImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TReferenceImagePixelType, 3 >, Image< DiffusionTensor3D< double >, 3 > >, itk::ImageToImageFilter< TInputImage, TEigenValueImage >, itk::ImageToImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< float, TLevelSet::ImageDimension >, TLevelSet >, itk::ImageToImageFilter< TInputImageType, TSparseOutputImageType >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TDisplacementField, TOutputImage >, itk::ImageToImageFilter< Image< SymmetricSecondRankTensor< double, 3 >, 3 >, Image< TPixel, 3 > >, itk::ImageToImageFilter< TInputImage, Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TInputPixelType, 2 >, Image< TOutputPixelType, 2 > >, itk::ImageToImageFilter< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TSparseOutputImage >, itk::ImageToImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageToImageFilter< TLabelImage, TLabelImage >, itk::ImageToImageFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TLabelImage, TOutputImage >, itk::ImageToImageFilter< TInputImage, TClassifiedImage >, itk::ImageToImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TLabelImage >, itk::ImageToImageFilter< TDisplacementField, TDisplacementField >, itk::ImageToImageFilter< TFeatureImage, TOutputImage >, itk::ImageToImageFilter< TLevelSet, TLevelSet >, itk::ImageToImageFilter< TInputImage, Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageToImageFilter< TMask, TImage >, itk::ImageToImageFilter< TTimeVaryingVelocityField, Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageToImageFilter< TInputImage, Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< ImageType, ImageType >, and itk::ImageToImageFilter< FeatureImageType, ImageType >.
PrepareOutputs()
virtual void itk::ProcessObject::PrepareOutputs () virtual
An opportunity to deallocate a ProcessObject's bulk data storage. Some filters may wish to reuse existing bulk data storage to avoid unnecessary deallocation/allocation sequences. The default implementation calls Initialize() on each output. DataObject::Initialize() frees its bulk data by default.
Reimplemented in itk::WatershedImageFilter< TInputImage >.
PrintSelf()
void itk::ProcessObject::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from itk::Object.
Reimplemented in itk::MultiphaseDenseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFunction, TIdCell >, itk::MultiphaseDenseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, ScalarChanAndVeseLevelSetFunction< TInputImage, TFeatureImage > >, itk::STAPLEImageFilter< TInputImage, TOutputImage >, itk::LaplacianImageFilter< TInputImage, TOutputImage >, itk::LaplacianSharpeningImageFilter< TInputImage, TOutputImage >, itk::GradientMagnitudeImageFilter< TInputImage, TOutputImage >, itk::LabelVotingImageFilter< TInputImage, TOutputImage >, itk::MultiLabelSTAPLEImageFilter< TInputImage, TOutputImage, TWeights >, itk::CollidingFrontsImageFilter< TInputImage, TOutputImage >, itk::VTKImageExport< TInputImage >, itk::VTKImageExportBase, itk::VTKImageImport< TOutputImage >, itk::ImageSink< TLabelImage >, itk::ImageSink< TImage >, itk::ImageSource< TImageType >, itk::ImageSource< TInputImage >, itk::ImageSource< TImage >, itk::ImageSource< TInputImage1 >, itk::ImageSource< Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageSource< VectorImage< float, TInputImage::ImageDimension > >, itk::ImageSource< Image< float, TInputImage::ImageDimension > >, itk::ImageSource< VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< DiffusionTensor3D< double >, 3 > >, itk::ImageSource< TEigenValueImage >, itk::ImageSource< Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageSource< TLevelSet >, itk::ImageSource< TSparseOutputImageType >, itk::ImageSource< Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< TPixel, 3 > >, itk::ImageSource< Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageSource< Image< double, 3 > >, itk::ImageSource< Image< SizeValueType, 3 > >, itk::ImageSource< Image< float, 3 > >, itk::ImageSource< Image< TOutputPixelType, 2 > >, itk::ImageSource< Image< double, TInputImage::ImageDimension > >, itk::ImageSource< TSparseOutputImage >, itk::ImageSource< Image< TPixel, 2 > >, itk::ImageSource< Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageSource< TLabelImage >, itk::ImageSource< Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageSource< Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageSource< TClassifiedImage >, itk::ImageSource< itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageSource< TDisplacementField >, itk::ImageSource< Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageSource< Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageSource< Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageSource< Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageSource< ImageType >, itk::ImageToImageFilter< TImageType, TImageType >, itk::ImageToImageFilter< TInputImage, TInputImage >, itk::ImageToImageFilter< TImage, TImage >, itk::ImageToImageFilter< TInputImage1, TInputImage1 >, itk::ImageToImageFilter< TInputVectorImage, Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage1, TOutputImage >, itk::ImageToImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TReferenceImagePixelType, 3 >, Image< DiffusionTensor3D< double >, 3 > >, itk::ImageToImageFilter< TInputImage, TEigenValueImage >, itk::ImageToImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< float, TLevelSet::ImageDimension >, TLevelSet >, itk::ImageToImageFilter< TInputImageType, TSparseOutputImageType >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TDisplacementField, TOutputImage >, itk::ImageToImageFilter< Image< SymmetricSecondRankTensor< double, 3 >, 3 >, Image< TPixel, 3 > >, itk::ImageToImageFilter< TInputImage, Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TInputPixelType, 2 >, Image< TOutputPixelType, 2 > >, itk::ImageToImageFilter< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TSparseOutputImage >, itk::ImageToImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageToImageFilter< TLabelImage, TLabelImage >, itk::ImageToImageFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TLabelImage, TOutputImage >, itk::ImageToImageFilter< TInputImage, TClassifiedImage >, itk::ImageToImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TLabelImage >, itk::ImageToImageFilter< TDisplacementField, TDisplacementField >, itk::ImageToImageFilter< TFeatureImage, TOutputImage >, itk::ImageToImageFilter< TLevelSet, TLevelSet >, itk::ImageToImageFilter< TInputImage, Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageToImageFilter< TMask, TImage >, itk::ImageToImageFilter< TTimeVaryingVelocityField, Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageToImageFilter< TInputImage, Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< ImageType, ImageType >, itk::ImageToImageFilter< FeatureImageType, ImageType >, itk::InPlaceImageFilter< TInputImage, TOutputImage >, itk::InPlaceImageFilter< TInputImage, TInputImage >, itk::InPlaceImageFilter< TInputImage1, TInputImage1 >, itk::InPlaceImageFilter< TInputImage1, TOutputImage >, itk::InPlaceImageFilter< TImage, TImage >, itk::InPlaceImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::InPlaceImageFilter< TInputImageType, TSparseOutputImageType >, itk::InPlaceImageFilter< TImageType, TImageType >, itk::InPlaceImageFilter< TInputImage, TSparseOutputImage >, itk::InPlaceImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::InPlaceImageFilter< TLabelImage, TOutputImage >, itk::InPlaceImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::InPlaceImageFilter< TFeatureImage, TOutputImage >, itk::InPlaceImageFilter< TDisplacementField, TDisplacementField >, itk::InPlaceImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::InPlaceImageFilter< TMask, TImage >, itk::InPlaceImageFilter< FeatureImageType, ImageType >, itk::StreamingImageFilter< TInputImage, TOutputImage >, itk::StreamingProcessObject, itk::DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage >, itk::DenseFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField >, itk::FiniteDifferenceImageFilter< TInputImage, TOutputImage >, itk::FiniteDifferenceImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::FiniteDifferenceImageFilter< TInputImageType, TSparseOutputImageType >, itk::FiniteDifferenceImageFilter< TInputImage, TSparseOutputImage >, itk::FiniteDifferenceImageFilter< TDisplacementField, TDisplacementField >, itk::FiniteDifferenceSparseImageFilter< TInputImageType, TSparseOutputImageType >, itk::FiniteDifferenceSparseImageFilter< TInputImage, TSparseOutputImage >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, BinaryThresholdImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, BoxImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, CastImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, DiscreteGaussianImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, FiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TInputImage, InPlaceImageFilter< TInputImage, TInputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, MeanImageFilter< TInputImage, TOutputImage > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, typename TOutputImage::PixelType > >, itk::GPUImageToImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUImageToImageFilter< TInputImage, TOutputImage, InPlaceImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, BinaryThresholdImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, CastImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, FiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, InPlaceImageFilter< TInputImage, TOutputImage > >, itk::GPUDenseFiniteDifferenceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUDenseFiniteDifferenceImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUDenseFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUDenseFiniteDifferenceImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUDenseFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUFiniteDifferenceImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::BSplineDecompositionImageFilter< TInputImage, TOutputImage >, itk::BinaryMask3DMeshSource< TInputImage, TOutputMesh >, itk::ConnectedRegionsMeshFilter< TInputMesh, TOutputMesh >, itk::ImageToParametricSpaceFilter< TInputImage, TOutputMesh >, itk::InteriorExteriorMeshFilter< TInputMesh, TOutputMesh, TSpatialFunction >, itk::MeshSource< TOutputMesh >, itk::MeshSource< PointSet< Vector< typename TFeatures::PointType::ValueType, TFeatures::PointDimension >, TFeatures::PointDimension > >, itk::MeshSource< TInputMesh >, itk::MeshSource< TOutput >, itk::MeshSource< PointSet< Matrix< SpacePrecisionType, TImage::ImageDimension, TImage::ImageDimension >, TImage::ImageDimension > >, itk::MeshSource< TOutputPointSet >, itk::MeshSource< VoronoiDiagram2D< TCoordType > >, itk::ParametricSpaceToImageSpaceMeshFilter< TInputMesh, TOutputMesh >, itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >, itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >, itk::TransformMeshFilter< TInputMesh, TOutputMesh, TTransform >, itk::TriangleMeshToBinaryImageFilter< TInputMesh, TOutputImage >, itk::TriangleMeshToSimplexMeshFilter< TInputMesh, TOutputMesh >, itk::VTKPolyDataReader< TOutputMesh >, itk::WarpMeshFilter< TInputMesh, TOutputMesh, TDisplacementField >, itk::SpatialObjectToImageFilter< TInputSpatialObject, TOutputImage >, itk::SpatialObjectToPointSetFilter< TPointBasedSpatialObject, TOutputPointSet >, itk::PipelineMonitorImageFilter< TImageType >, itk::RandomImageSource< TOutputImage >, itk::Testing::ComparisonImageFilter< TInputImage, TOutputImage >, itk::Testing::ExtractSliceImageFilter< TInputImage, TOutputImage >, itk::Testing::HashImageFilter< TImageType >, itk::Testing::StretchIntensityImageFilter< TInputImage, TOutputImage >, itk::AnisotropicDiffusionImageFilter< TInputImage, TOutputImage >, itk::AntiAliasBinaryImageFilter< TInputImage, TOutputImage >, itk::MRIBiasFieldCorrectionFilter< TInputImage, TOutputImage, TMaskImage >, itk::N4BiasFieldCorrectionImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::BinaryClosingByReconstructionImageFilter< TInputImage, TKernel >, itk::BinaryDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryMorphologicalClosingImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryMorphologicalOpeningImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::BinaryOpeningByReconstructionImageFilter< TInputImage, TKernel >, itk::BinaryPruningImageFilter< TInputImage, TOutputImage >, itk::DilateObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::ErodeObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::ObjectMorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::ScalarToRGBColormapImageFilter< TInputImage, TOutputImage >, itk::ConvolutionImageFilterBase< TInputImage, TKernelImage, TOutputImage >, itk::ConvolutionImageFilterBase< TInputImage, TInputImage, TInputImage >, itk::ConvolutionImageFilterBase< TInputImage, TKernelSource::OutputImageType, TInputImage >, itk::FFTConvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::FFTConvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::FFTConvolutionImageFilter< TInputImage, TKernelSource::OutputImageType, TInputImage, double >, itk::FFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage >, itk::MaskedFFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::NormalizedCorrelationImageFilter< TInputImage, TMaskImage, TOutputImage, TOperatorValueType >, itk::BinaryMinMaxCurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::CurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::MinMaxCurvatureFlowImageFilter< TInputImage, TOutputImage >, itk::InverseDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::InverseDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::IterativeDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::IterativeDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::IterativeDeconvolutionImageFilter< TInputImage, TKernelSource::OutputImageType, TInputImage >, itk::LandweberDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::LandweberDeconvolutionImageFilter< TInputImage, TInputImage, TInputImage, double >, itk::ParametricBlindLeastSquaresDeconvolutionImageFilter< TInputImage, TKernelSource, TOutputImage >, itk::RichardsonLucyDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::TikhonovDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::WienerDeconvolutionImageFilter< TInputImage, TKernelImage, TOutputImage, TInternalPrecision >, itk::PatchBasedDenoisingBaseImageFilter< TInputImage, TOutputImage >, itk::PatchBasedDenoisingImageFilter< TInputImage, TOutputImage >, itk::DiffusionTensor3DReconstructionImageFilter< TReferenceImagePixelType, TGradientImagePixelType, TTensorPixelType, TMaskImageType >, itk::TensorFractionalAnisotropyImageFilter< TInputImage, TOutputImage >, itk::TensorRelativeAnisotropyImageFilter< TInputImage, TOutputImage >, itk::ComposeDisplacementFieldsImageFilter< TInputImage, TOutputImage >, itk::DisplacementFieldJacobianDeterminantFilter< TInputImage, TRealType, TOutputImage >, itk::DisplacementFieldToBSplineImageFilter< TInputImage, TInputPointSet, TOutputImage >, itk::ExponentialDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::InverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::InvertDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::IterativeInverseDisplacementFieldImageFilter< TInputImage, TOutputImage >, itk::LandmarkDisplacementFieldSource< TOutputImage >, itk::TimeVaryingVelocityFieldIntegrationImageFilter< TTimeVaryingVelocityField, TDisplacementField >, itk::TransformToDisplacementFieldFilter< TOutputImage, TParametersValueType >, itk::ApproximateSignedDistanceMapImageFilter< TInputImage, TOutputImage >, itk::ContourDirectedMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::ContourMeanDistanceImageFilter< TInputImage1, TInputImage2 >, itk::DanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::DanielssonDistanceMapImageFilter< ImageType, ImageType >, itk::DirectedHausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::FastChamferDistanceImageFilter< TInputImage, TOutputImage >, itk::HausdorffDistanceImageFilter< TInputImage1, TInputImage2 >, itk::IsoContourDistanceImageFilter< TInputImage, TOutputImage >, itk::SignedDanielssonDistanceMapImageFilter< TInputImage, TOutputImage, TVoronoiImage >, itk::SignedMaurerDistanceMapImageFilter< TInputImage, TOutputImage >, itk::FastMarchingExtensionImageFilter< TLevelSet, TAuxValue, VAuxDimension, TSpeedImage >, itk::FastMarchingImageFilter< TLevelSet, TSpeedImage >, itk::FastMarchingImageFilter< TLevelSet, Image< float, TLevelSet::ImageDimension > >, itk::FastMarchingUpwindGradientImageFilter< TLevelSet, TSpeedImage >, itk::ComplexToComplex1DFFTImageFilter< TInputImage, TOutputImage >, itk::ComplexToComplex1DFFTImageFilter< TInputImage, TInputImage >, itk::FFTPadImageFilter< TInputImage, TOutputImage >, itk::FFTShiftImageFilter< TInputImage, TOutputImage >, itk::FFTWComplexToComplexFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWForwardFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWHalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWInverseFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWRealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, itk::Forward1DFFTImageFilter< TInputImage, TOutputImage >, itk::Forward1DFFTImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::Inverse1DFFTImageFilter< TInputImage, TOutputImage >, itk::Inverse1DFFTImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::GPUAnisotropicDiffusionImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUAnisotropicDiffusionImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUBoxImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUBoxImageFilter< TInputImage, TOutputImage, MeanImageFilter< TInputImage, TOutputImage > >, itk::GPUNeighborhoodOperatorImageFilter< TInputImage, TOutputImage, TOperatorValueType, TParentImageFilter >, itk::GPUDiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::GPUMeanImageFilter< TInputImage, TOutputImage >, itk::CheckerBoardImageFilter< TImage >, itk::SimilarityIndexImageFilter< TInputImage1, TInputImage2 >, itk::JoinSeriesImageFilter< TInputImage, TOutputImage >, itk::BilateralImageFilter< TInputImage, TOutputImage >, itk::CannyEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::CannyEdgeDetectionImageFilter< ImageType, ImageType >, itk::DerivativeImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianDerivativeImageFilter< TInputImage, TOutputImage >, itk::GradientVectorFlowImageFilter< TInputImage, TOutputImage, TInternalPixel >, itk::Hessian3DToVesselnessMeasureImageFilter< TPixel >, itk::HessianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::HessianToObjectnessMeasureImageFilter< TInputImage, TOutputImage >, itk::HoughTransform2DCirclesImageFilter< TInputPixelType, TOutputPixelType, TRadiusPixelType >, itk::HoughTransform2DLinesImageFilter< TInputPixelType, TOutputPixelType >, itk::LaplacianRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::MaskFeaturePointSelectionFilter< TImage, TMask, TFeatures >, itk::MultiScaleHessianBasedMeasureImageFilter< TInputImage, THessianImage, TOutputImage >, itk::SimpleContourExtractorImageFilter< TInputImage, TOutputImage >, itk::SobelEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::UnsharpMaskImageFilter< TInputImage, TOutputImage, TInternalPrecision >, itk::ZeroCrossingBasedEdgeDetectionImageFilter< TInputImage, TOutputImage >, itk::ZeroCrossingImageFilter< TInputImage, TOutputImage >, itk::BoxImageFilter< TInputImage, TOutputImage >, itk::BoxImageFilter< TImageType, TImageType >, itk::BoxImageFilter< TImage, TImage >, itk::BoxImageFilter< TInputImage, TInputImage >, itk::KernelImageFilter< TInputImage, TOutputImage, TKernel >, itk::KernelImageFilter< TImageType, TImageType, Neighborhood< bool, TImageType::ImageDimension > >, itk::KernelImageFilter< TImage, TImage, TKernel >, itk::KernelImageFilter< TInputImage, TInputImage, TKernel >, itk::KernelImageFilter< TInputImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension > >, itk::MaskNeighborhoodOperatorImageFilter< TInputImage, TMaskImage, TOutputImage, TOperatorValueType >, itk::MovingHistogramImageFilterBase< TInputImage, TOutputImage, TKernel >, itk::MovingHistogramImageFilterBase< TImageType, TImageType, Neighborhood< bool, TImageType::ImageDimension > >, itk::MovingHistogramImageFilterBase< TInputImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension > >, itk::NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, TOperatorValueType >, itk::NeighborhoodOperatorImageFilter< TInputImage, TOutputImage, typename TOutputImage::PixelType >, itk::RecursiveSeparableImageFilter< TInputImage, TOutputImage >, itk::RecursiveSeparableImageFilter< TInputImage, TInputImage >, itk::VectorNeighborhoodOperatorImageFilter< TInputImage, TOutputImage >, itk::FrequencyBandImageFilter< TImageType, TFrequencyIterator >, itk::UnaryFrequencyDomainFilter< TImageType, TFrequencyIterator >, itk::UnaryFrequencyDomainFilter< TImageType, FrequencyFFTLayoutImageRegionIteratorWithIndex< TImageType > >, itk::LabelMapContourOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::LabelMapOverlayImageFilter< TLabelMap, TFeatureImage, TOutputImage >, itk::LabelOverlayImageFilter< TInputImage, TLabelImage, TOutputImage >, itk::LabelToRGBImageFilter< TLabelImage, TOutputImage >, itk::DifferenceOfGaussiansGradientImageFilter< TInputImage, TDataType >, itk::GradientImageFilter< TInputImage, TOperatorValueType, TOutputValueType, TOutputImageType >, itk::GradientMagnitudeRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::GradientRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::VectorGradientMagnitudeImageFilter< TInputImage, TRealType, TOutputImage >, itk::BinShrinkImageFilter< TInputImage, TOutputImage >, itk::BSplineCenteredL2ResampleImageFilterBase< TInputImage, TOutputImage >, itk::BSplineCenteredResampleImageFilterBase< TInputImage, TOutputImage >, itk::BSplineControlPointImageFilter< TInputImage, TOutputImage >, itk::BSplineL2ResampleImageFilterBase< TInputImage, TOutputImage >, itk::BSplineResampleImageFilterBase< TInputImage, TOutputImage >, itk::BSplineScatteredDataPointSetToImageFilter< TInputPointSet, TOutputImage >, itk::BSplineUpsampleImageFilter< TInputImage, TOutputImage, ResamplerType >, itk::ChangeInformationImageFilter< TInputImage >, itk::ConstantPadImageFilter< TInputImage, TOutputImage >, itk::CropImageFilter< TInputImage, TOutputImage >, itk::CyclicShiftImageFilter< TInputImage, TOutputImage >, itk::CyclicShiftImageFilter< TInputImage, TOutputImage >, itk::ExpandImageFilter< TInputImage, TOutputImage >, itk::FlipImageFilter< TImage >, itk::InterpolateImageFilter< TInputImage, TOutputImage >, itk::InterpolateImagePointsFilter< TInputImage, TOutputImage, TCoordType, InterpolatorType >, itk::OrientImageFilter< TInputImage, TOutputImage >, itk::PadImageFilter< TInputImage, TOutputImage >, itk::PadImageFilterBase< TInputImage, TOutputImage >, itk::PadImageFilterBase< TInputImage, TInputImage >, itk::PasteImageFilter< TInputImage, TSourceImage, TOutputImage >, itk::PermuteAxesImageFilter< TImage >, itk::RegionOfInterestImageFilter< TInputImage, TOutputImage >, itk::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType, TTransformPrecisionType >, itk::ShrinkImageFilter< TInputImage, TOutputImage >, itk::SliceBySliceImageFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::SliceImageFilter< TInputImage, TOutputImage >, itk::TileImageFilter< TInputImage, TOutputImage >, itk::WarpImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::WarpVectorImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::ClampImageFilter< TInputImage, TOutputImage >, itk::DivideOrZeroOutImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::HistogramMatchingImageFilter< TInputImage, TOutputImage, THistogramMeasurement >, itk::IntensityWindowingImageFilter< TInputImage, TOutputImage >, itk::InvertIntensityImageFilter< TInputImage, TOutputImage >, itk::MaskImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::MaskNegatedImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::NormalizeToConstantImageFilter< TInputImage, TOutputImage >, itk::PolylineMaskImageFilter< TInputImage, TPolyline, TVector, TOutputImage >, itk::RescaleIntensityImageFilter< TInputImage, TOutputImage >, itk::ShiftScaleImageFilter< TInputImage, TOutputImage >, itk::SymmetricEigenAnalysisImageFilter< TInputImage, TOutputImage >, itk::SymmetricEigenAnalysisFixedDimensionImageFilter< TMatrixDimension, TInputImage, TOutputImage >, itk::VectorRescaleIntensityImageFilter< TInputImage, TOutputImage >, itk::BinaryContourImageFilter< TInputImage, TOutputImage >, itk::ChangeLabelImageFilter< TInputImage, TOutputImage >, itk::LabelContourImageFilter< TInputImage, TOutputImage >, itk::AdditiveGaussianNoiseImageFilter< TInputImage, TOutputImage >, itk::NoiseBaseImageFilter< TInputImage, TOutputImage >, itk::NoiseBaseImageFilter< TInputImage, TInputImage >, itk::SaltAndPepperNoiseImageFilter< TInputImage, TOutputImage >, itk::ShotNoiseImageFilter< TInputImage, TOutputImage >, itk::SpeckleNoiseImageFilter< TInputImage, TOutputImage >, itk::GaborImageSource< TOutputImage >, itk::GaussianImageSource< TOutputImage >, itk::GenerateImageSource< TOutputImage >, itk::GridImageSource< TOutputImage >, itk::ParametricImageSource< TOutputImage >, itk::AccumulateImageFilter< TInputImage, TOutputImage >, itk::AdaptiveHistogramEqualizationImageFilter< TImageType, TKernel >, itk::BinaryProjectionImageFilter< TInputImage, TOutputImage >, itk::GetAverageSliceImageFilter< TInputImage, TOutputImage >, itk::ImagePCAShapeModelEstimator< TInputImage, TOutputImage >, itk::ImageShapeModelEstimatorBase< TInputImage, TOutputImage >, itk::ImageShapeModelEstimatorBase< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::LabelOverlapMeasuresImageFilter< TLabelImage >, itk::LabelStatisticsImageFilter< TInputImage, TLabelImage >, itk::MinimumMaximumImageFilter< TInputImage >, itk::ProjectionImageFilter< TInputImage, TOutputImage, TAccumulator >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::BinaryAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Function::BinaryThresholdAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MaximumAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MeanAccumulator< TInputImage::PixelType, typename NumericTraits< typename TOutputImage::PixelType >::AccumulateType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MedianAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::MinimumAccumulator< TInputImage::PixelType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::StandardDeviationAccumulator< TInputImage::PixelType, typename NumericTraits< typename TOutputImage::PixelType >::AccumulateType > >, itk::ProjectionImageFilter< TInputImage, TOutputImage, Functor::SumAccumulator< TInputImage::PixelType, TOutputImage::PixelType > >, itk::StatisticsImageFilter< TInputImage >, itk::AggregateLabelMapFilter< TImage >, itk::AttributeKeepNObjectsLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeOpeningLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributePositionLabelMapFilter< TImage, TAttributeAccessor, VPhysicalPosition >, itk::AttributeRelabelLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeRelabelLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::AttributeSelectionLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeSelectionLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::AttributeUniqueLabelMapFilter< TImage, TAttributeAccessor >, itk::AttributeUniqueLabelMapFilter< TImage, Functor::LabelLabelObjectAccessor< TImage::LabelObjectType > >, itk::AutoCropLabelMapFilter< TInputImage >, itk::BinaryFillholeImageFilter< TInputImage >, itk::BinaryGrindPeakImageFilter< TInputImage >, itk::BinaryNotImageFilter< TImage >, itk::BinaryReconstructionByDilationImageFilter< TInputImage >, itk::BinaryReconstructionByErosionImageFilter< TInputImage >, itk::BinaryReconstructionLabelMapFilter< TImage, TMarkerImage, TAttributeAccessor >, itk::BinaryShapeKeepNObjectsImageFilter< TInputImage >, itk::BinaryShapeOpeningImageFilter< TInputImage >, itk::BinaryStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::BinaryStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::ChangeLabelLabelMapFilter< TImage >, itk::ChangeRegionLabelMapFilter< TInputImage >, itk::CropLabelMapFilter< TInputImage >, itk::InPlaceLabelMapFilter< TInputImage >, itk::InPlaceLabelMapFilter< TImage >, itk::LabelMapMaskImageFilter< TInputImage, TOutputImage >, itk::LabelMapToAttributeImageFilter< TInputImage, TOutputImage, TAttributeAccessor >, itk::LabelMapToBinaryImageFilter< TInputImage, TOutputImage >, itk::LabelShapeKeepNObjectsImageFilter< TInputImage >, itk::LabelShapeOpeningImageFilter< TInputImage >, itk::LabelStatisticsKeepNObjectsImageFilter< TInputImage, TFeatureImage >, itk::LabelStatisticsOpeningImageFilter< TInputImage, TFeatureImage >, itk::MergeLabelMapFilter< TImage >, itk::ObjectByObjectLabelMapFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::PadLabelMapFilter< TInputImage >, itk::RegionFromReferenceLabelMapFilter< TInputImage >, itk::ShapeKeepNObjectsLabelMapFilter< TImage >, itk::ShapeLabelMapFilter< TImage, TLabelImage >, itk::ShapeLabelMapFilter< TImage, Image< TImage::PixelType, TImage::ImageDimension > >, itk::ShapeOpeningLabelMapFilter< TImage >, itk::ShapePositionLabelMapFilter< TImage >, itk::ShapeRelabelImageFilter< TInputImage >, itk::ShapeRelabelLabelMapFilter< TImage >, itk::ShapeUniqueLabelMapFilter< TImage >, itk::ShiftScaleLabelMapFilter< TImage >, itk::StatisticsLabelMapFilter< TImage, TFeatureImage >, itk::StatisticsRelabelImageFilter< TInputImage, TFeatureImage >, itk::AnchorErodeDilateImageFilter< TImage, TKernel, TFunction1 >, itk::AnchorErodeDilateImageFilter< TImage, TKernel, std::greater< TImage::PixelType > >, itk::AnchorErodeDilateImageFilter< TImage, TKernel, std::less< TImage::PixelType > >, itk::AnchorOpenCloseImageFilter< TImage, TKernel, TCompare1, TCompare2 >, itk::AnchorOpenCloseImageFilter< TImage, TKernel, std::greater< TImage::PixelType >, std::less< TImage::PixelType > >, itk::AnchorOpenCloseImageFilter< TImage, TKernel, std::less< TImage::PixelType >, std::greater< TImage::PixelType > >, itk::BlackTopHatImageFilter< TInputImage, TOutputImage, TKernel >, itk::ClosingByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::DoubleThresholdImageFilter< TInputImage, TOutputImage >, itk::GrayscaleConnectedClosingImageFilter< TInputImage, TOutputImage >, itk::GrayscaleConnectedOpeningImageFilter< TInputImage, TOutputImage >, itk::GrayscaleDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleFillholeImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGeodesicDilateImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGeodesicErodeImageFilter< TInputImage, TOutputImage >, itk::GrayscaleGrindPeakImageFilter< TInputImage, TOutputImage >, itk::GrayscaleMorphologicalClosingImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleMorphologicalOpeningImageFilter< TInputImage, TOutputImage, TKernel >, itk::HConcaveImageFilter< TInputImage, TOutputImage >, itk::HConvexImageFilter< TInputImage, TOutputImage >, itk::HMaximaImageFilter< TInputImage, TOutputImage >, itk::HMinimaImageFilter< TInputImage, TOutputImage >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel, THistogram >, itk::MaskedMovingHistogramImageFilter< TInputImage, TMaskImage, TOutputImage, FlatStructuringElement< TInputImage::ImageDimension >, Function::RankHistogram< TInputImage::PixelType > >, itk::MaskedRankImageFilter< TInputImage, TMaskImage, TOutputImage, TKernel >, itk::MorphologicalGradientImageFilter< TInputImage, TOutputImage, TKernel >, itk::MorphologyImageFilter< TInputImage, TOutputImage, TKernel >, itk::MovingHistogramMorphologyImageFilter< TInputImage, TOutputImage, TKernel, THistogram >, itk::MovingHistogramMorphologyImageFilter< TInputImage, TOutputImage, TKernel, Function::MorphologyHistogram< TInputImage::PixelType, std::greater< TInputImage::PixelType > > >, itk::MovingHistogramMorphologyImageFilter< TInputImage, TOutputImage, TKernel, Function::MorphologyHistogram< TInputImage::PixelType, std::less< TInputImage::PixelType > > >, itk::OpeningByReconstructionImageFilter< TInputImage, TOutputImage, TKernel >, itk::RankImageFilter< TInputImage, TOutputImage, TKernel >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, TCompare >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::greater< TOutputImage::PixelType > >, itk::ReconstructionImageFilter< TInputImage, TOutputImage, std::less< TOutputImage::PixelType > >, itk::RegionalMaximaImageFilter< TInputImage, TOutputImage >, itk::RegionalMinimaImageFilter< TInputImage, TOutputImage >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, TFunction1, TFunction2 >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::greater< TInputImage::PixelType >, std::greater< TOutputImage::PixelType > >, itk::ValuedRegionalExtremaImageFilter< TInputImage, TOutputImage, std::less< TInputImage::PixelType >, std::less< TOutputImage::PixelType > >, itk::VanHerkGilWermanErodeDilateImageFilter< TImage, TKernel, TFunction1 >, itk::VanHerkGilWermanErodeDilateImageFilter< TImage, TKernel, MaxFunctor< TImage::PixelType > >, itk::VanHerkGilWermanErodeDilateImageFilter< TImage, TKernel, MinFunctor< TImage::PixelType > >, itk::WhiteTopHatImageFilter< TInputImage, TOutputImage, TKernel >, itk::ChainCodeToFourierSeriesPathFilter< TInputChainCodePath, TOutputFourierSeriesPath >, itk::ContourExtractor2DImageFilter< TInputImage >, itk::ExtractOrthogonalSwath2DImageFilter< TImage >, itk::ImageAndPathToImageFilter< TInputImage, TInputPath, TOutputImage >, itk::ImageAndPathToImageFilter< TImage, ParametricPath< 2 >, TImage >, itk::ImageToPathFilter< TInputImage, TOutputPath >, itk::ImageToPathFilter< TInputImage, PolyLineParametricPath< 2 > >, itk::OrthogonalSwath2DPathFilter< TFourierSeriesPath, TSwathMeritImage >, itk::PathAndImageToPathFilter< TInputPath, TInputImage, TOutputPath >, itk::PathAndImageToPathFilter< TFourierSeriesPath, TSwathMeritImage, OrthogonallyCorrected2DParametricPath >, itk::PathSource< TOutputPath >, itk::PathSource< TOutputFourierSeriesPath >, itk::PathSource< PolyLineParametricPath< 2 > >, itk::PathSource< OrthogonallyCorrected2DParametricPath >, itk::PathSource< TOutputChainCodePath >, itk::PathToChainCodePathFilter< TInputPath, TOutputChainCodePath >, itk::PathToImageFilter< TInputPath, TOutputImage >, itk::PathToPathFilter< TInputPath, TOutputPath >, itk::PathToPathFilter< TInputChainCodePath, TOutputFourierSeriesPath >, itk::PathToPathFilter< TFourierSeriesPath, OrthogonallyCorrected2DParametricPath >, itk::PathToPathFilter< TInputPath, TOutputChainCodePath >, itk::BorderQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::CleanQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::DecimationQuadEdgeMeshFilter< TInput, TOutput, TCriterion >, itk::DelaunayConformingQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::LaplacianDeformationQuadEdgeMeshFilter< TInputMesh, TOutputMesh, TSolverTraits >, itk::LaplacianDeformationQuadEdgeMeshFilterWithHardConstraints< TInputMesh, TOutputMesh, TSolverTraits >, itk::LaplacianDeformationQuadEdgeMeshFilterWithSoftConstraints< TInputMesh, TOutputMesh, TSolverTraits >, itk::NormalQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::ParameterizationQuadEdgeMeshFilter< TInputMesh, TOutputMesh, TSolverTraits >, itk::SmoothingQuadEdgeMeshFilter< TInputMesh, TOutputMesh >, itk::BinomialBlurImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TInputImage >, itk::DiscreteGaussianImageFilter< TInputImage, TOutputImage >, itk::RecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::SmoothingRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::SpatialFunctionImageEvaluatorFilter< TSpatialFunction, TInputImage, TOutputImage >, itk::BinaryThresholdImageFilter< TInputImage, TOutputImage >, itk::BinaryThresholdProjectionImageFilter< TInputImage, TOutputImage >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TOutputImage >, itk::HuangThresholdCalculator< THistogram, TOutput >, itk::IntermodesThresholdCalculator< THistogram, TOutput >, itk::IntermodesThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::KappaSigmaThresholdImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::OtsuMultipleThresholdsImageFilter< TInputImage, TOutputImage >, itk::OtsuThresholdCalculator< THistogram, TOutput >, itk::RenyiEntropyThresholdCalculator< THistogram, TOutput >, itk::ThresholdImageFilter< TImage >, itk::ThresholdLabelerImageFilter< TInputImage, TOutputImage >, itk::GDCMSeriesFileNames, itk::ImageFileReader< TOutputImage, ConvertPixelTraits >, itk::ImageFileWriter< TInputImage >, itk::ImageSeriesReader< TOutputImage >, itk::ImageSeriesWriter< TInputImage, TOutputImage >, itk::MeshFileReader< TOutputMesh, ConvertPointPixelTraits, ConvertCellPixelTraits >, itk::MeshFileWriter< TInputMesh >, itk::AreaClosingImageFilter< TInputImage, TOutputImage, TAttribute >, itk::AreaOpeningImageFilter< TInputImage, TOutputImage, TAttribute >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, TAttribute, TFunction >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, typename TInputImage::SpacingType::ValueType, std::less< TInputImage::PixelType > >, itk::AttributeMorphologyBaseImageFilter< TInputImage, TOutputImage, typename TInputImage::SpacingType::ValueType, std::greater< TInputImage::PixelType > >, itk::ConformalFlatteningMeshFilter< TInputMesh, TOutputMesh >, itk::DirectFourierReconstructionImageToImageFilter< TInputImage, TOutputImage >, itk::FastApproximateRankImageFilter< TInputImage, TOutputImage >, itk::GridForwardWarpImageFilter< TDisplacementField, TOutputImage >, itk::LabelGeometryImageFilter< TLabelImage, TIntensityImage >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFiniteDifferenceFunction, TIdCell >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFunction, unsigned int >, itk::MultiphaseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, ScalarChanAndVeseLevelSetFunction< TInputImage, TFeatureImage >, unsigned int >, itk::MultiphaseSparseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, TFunction, TIdCell >, itk::MultiphaseSparseFiniteDifferenceImageFilter< TInputImage, TFeatureImage, TOutputImage, ScalarChanAndVeseLevelSetFunction< TInputImage, TFeatureImage >, unsigned int >, itk::RobustAutomaticThresholdImageFilter< TInputImage, TGradientImage, TOutputImage >, itk::StochasticFractalDimensionImageFilter< TInputImage, TMaskImage, TOutputImage >, itk::NarrowBandImageFilterBase< TInputImage, TOutputImage >, itk::NarrowBandImageFilterBase< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::Statistics::CovarianceSampleFilter< TSample >, itk::HistogramToImageFilter< THistogram, TImage, TFunction >, itk::HistogramToImageFilter< THistogram, Image< double, 3 >, Function::HistogramEntropyFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< SizeValueType, 3 >, Function::HistogramIntensityFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< double, 3 >, Function::HistogramLogProbabilityFunction< SizeValueType, TImage::PixelType > >, itk::HistogramToImageFilter< THistogram, Image< float, 3 >, Function::HistogramProbabilityFunction< SizeValueType, TImage::PixelType > >, itk::Statistics::HistogramToRunLengthFeaturesFilter< THistogram >, itk::Statistics::HistogramToTextureFeaturesFilter< THistogram >, itk::Statistics::ImageClassifierFilter< TSample, TInputImage, TOutputImage >, itk::Statistics::ImageToHistogramFilter< TImage >, itk::Statistics::ImageToListSampleFilter< TImage, TMaskImage >, itk::Statistics::MeanSampleFilter< TSample >, itk::Statistics::NeighborhoodSampler< TSample >, itk::Statistics::SampleClassifierFilter< TSample >, itk::Statistics::SampleToSubsampleFilter< TSample >, itk::Statistics::ScalarImageToCooccurrenceListSampleFilter< TImage >, itk::Statistics::ScalarImageToCooccurrenceMatrixFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::Statistics::ScalarImageToRunLengthFeaturesFilter< TImageType, THistogramFrequencyContainer >, itk::Statistics::ScalarImageToRunLengthMatrixFilter< TImageType, THistogramFrequencyContainer >, itk::Statistics::ScalarImageToTextureFeaturesFilter< TImageType, THistogramFrequencyContainer, TMaskImageType >, itk::Statistics::StandardDeviationPerComponentSampleFilter< TSample >, itk::Statistics::WeightedCovarianceSampleFilter< TSample >, itk::Statistics::WeightedMeanSampleFilter< TSample >, itk::BlockMatchingImageFilter< TFixedImage, TMovingImage, TFeatures, TDisplacements, TSimilarities >, itk::ImageRegistrationMethod< TFixedImage, TMovingImage >, itk::ImageToSpatialObjectRegistrationMethod< TFixedImage, TMovingSpatialObject >, itk::MultiResolutionImageRegistrationMethod< TFixedImage, TMovingImage >, itk::MultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::PointSetToImageRegistrationMethod< TFixedPointSet, TMovingImage >, itk::PointSetToPointSetRegistrationMethod< TFixedPointSet, TMovingPointSet >, itk::PointSetToSpatialObjectDemonsRegistration< TFixedPointSet, TMovingSpatialObject >, itk::RecursiveMultiResolutionPyramidImageFilter< TInputImage, TOutputImage >, itk::GPUDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TParentImageFilter >, itk::GPUPDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TParentImageFilter >, itk::GPUPDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::CurvatureRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField, TImageForceFunction >, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::DiffeomorphicDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::FastSymmetricForcesDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::LevelSetMotionRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::MultiResolutionPDEDeformableRegistration< TFixedImage, TMovingImage, TDisplacementField, TRealType, TFloatImageType, TRegistrationType, TDefaultRegistrationType >, itk::PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::SymmetricForcesDemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, BSplineSmoothingOnUpdateDisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, DisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, TimeVaryingBSplineVelocityFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::SyNImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::SyNImageRegistrationMethod< TFixedImage, TMovingImage, BSplineSmoothingOnUpdateDisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >, itk::TimeVaryingBSplineVelocityFieldImageRegistrationMethod< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::TimeVaryingVelocityFieldImageRegistrationMethodv4< TFixedImage, TMovingImage, TOutputTransform, TVirtualImage, TPointSet >, itk::BayesianClassifierImageFilter< TInputVectorImage, TLabelsType, TPosteriorsPrecisionType, TPriorsPrecisionType >, itk::BayesianClassifierInitializationImageFilter< TInputImage, TProbabilityPrecisionType >, itk::ScalarImageKmeansImageFilter< TInputImage, TOutputImage >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::ConnectedComponentImageFilter< TInputImage, TOutputImage, TInputImage >, itk::HardConnectedComponentImageFilter< TInputImage, TOutputImage >, itk::RelabelComponentImageFilter< TInputImage, TOutputImage >, itk::ThresholdMaximumConnectedComponentsImageFilter< TInputImage, TOutputImage >, itk::DeformableSimplexMesh3DBalloonForceFilter< TInputMesh, TOutputMesh >, itk::DeformableSimplexMesh3DFilter< TInputMesh, TOutputMesh >, itk::DeformableSimplexMesh3DGradientConstraintForceFilter< TInputMesh, TOutputMesh >, itk::KLMRegionGrowImageFilter< TInputImage, TOutputImage >, itk::RegionGrowImageFilter< TInputImage, TOutputImage >, itk::BinaryMedianImageFilter< TInputImage, TOutputImage >, itk::VotingBinaryHoleFillingImageFilter< TInputImage, TOutputImage >, itk::VotingBinaryImageFilter< TInputImage, TOutputImage >, itk::VotingBinaryIterativeHoleFillingImageFilter< TImage >, itk::AnisotropicFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::BinaryMaskToNarrowBandPointSetFilter< TInputImage, TOutputMesh >, itk::CurvesLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::GeodesicActiveContourLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::GeodesicActiveContourShapePriorLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ImplicitManifoldNormalVectorFilter< TInputImage, TSparseOutputImage >, itk::IsotropicFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::LaplacianSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::NarrowBandCurvesLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType, TOutputImage >, itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, float, Image< float, TInputImage::ImageDimension > >, itk::NarrowBandThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ParallelSparseFieldLevelSetImageFilter< TInputImage, TOutputImage >, itk::ReinitializeLevelSetImageFilter< TLevelSet >, itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >, itk::ShapeDetectionLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ShapePriorSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::ShapePriorSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, float >, itk::SparseFieldFourthOrderLevelSetImageFilter< TInputImage, TOutputImage >, itk::SparseFieldLevelSetImageFilter< TInputImage, TOutputImage >, itk::SparseFieldLevelSetImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::UnsharpMaskLevelSetImageFilter< TInputImage, TOutputImage >, itk::VectorThresholdSegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >, itk::LevelSetDomainMapImageFilter< TInputImage, TOutputImage >, itk::MRFImageFilter< TInputImage, TClassifiedImage >, itk::RGBGibbsPriorFilter< TInputImage, TClassifiedImage >, itk::ConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::ConnectedThresholdImageFilter< TInputImage, TOutputImage >, itk::IsolatedConnectedImageFilter< TInputImage, TOutputImage >, itk::NeighborhoodConnectedImageFilter< TInputImage, TOutputImage >, itk::VectorConfidenceConnectedImageFilter< TInputImage, TOutputImage >, itk::SLICImageFilter< TInputImage, TOutputImage, TDistancePixel >, itk::VoronoiDiagram2DGenerator< TCoordType >, itk::VoronoiPartitioningImageFilter< TInputImage, TOutputImage >, itk::VoronoiSegmentationImageFilter< TInputImage, TOutputImage, TBinaryPriorImage >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, TBinaryPriorImage >, itk::VoronoiSegmentationImageFilterBase< TInputImage, TOutputImage, Image< unsigned char, 2 > >, itk::VoronoiSegmentationRGBImageFilter< TInputImage, TOutputImage >, itk::IsolatedWatershedImageFilter< TInputImage, TOutputImage >, itk::MorphologicalWatershedFromMarkersImageFilter< TInputImage, TLabelImage >, itk::MorphologicalWatershedImageFilter< TInputImage, TOutputImage >, itk::TobogganImageFilter< TInputImage, TOutputImage >, itk::watershed::BoundaryResolver< TPixelType, TDimension >, itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >, itk::WatershedImageFilter< TInputImage >, itk::watershed::Relabeler< TScalar, TImageDimension >, itk::watershed::Relabeler< ScalarType, Self::ImageDimension >, itk::watershed::Segmenter< TInputImage >, itk::watershed::Segmenter< InputImageType >, itk::watershed::SegmentTreeGenerator< TScalar >, itk::watershed::SegmentTreeGenerator< ScalarType >, itk::TemporalProcessObject, itk::VideoSource< TOutputVideoStream >, itk::VideoSource< TVideoStream >, itk::VideoSource< itk::VideoStream< TImageToImageFilter::OutputImageType > >, itk::VideoToVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::VideoToVideoFilter< TVideoStream, TVideoStream >, itk::VideoToVideoFilter< itk::VideoStream< TImageToImageFilter::InputImageType >, itk::VideoStream< TImageToImageFilter::OutputImageType > >, itk::DecimateFramesVideoFilter< TVideoStream >, itk::FrameAverageVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::FrameDifferenceVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::ImageFilterToVideoFilterWrapper< TImageToImageFilter >, itk::VideoFileReader< TOutputVideoStream >, itk::VideoFileWriter< TInputVideoStream >, and itk::RegularSphereMeshSource< TOutputMesh >.
progressFixedToFloat()
static constexpr float itk::ProcessObject::progressFixedToFloat (uint32_t fixed) inline static constexpr protected
Internal method to convert internal integer progress to float [0.0, 1.0]
Definition at line 916 of file itkProcessObject.h.
progressFloatToFixed()
static uint32_t itk::ProcessObject::progressFloatToFixed (float f) inline static protected
Internal method convert floating point progress [0.0, 1.0] to internal integer representation. Values outside the [0.0, 1.0] range are clamped.
Definition at line 927 of file itkProcessObject.h.
PropagateRequestedRegion()
virtual void itk::ProcessObject::PropagateRequestedRegion (DataObject * output) virtual
Send the requested region information back up the pipeline (to the filters that precede this one).
Reimplemented in itk::VTKImageImport< TOutputImage >, itk::StreamingImageFilter< TInputImage, TOutputImage >, itk::StreamingProcessObject, and itk::PipelineMonitorImageFilter< TImageType >.
PropagateResetPipeline()
virtual void itk::ProcessObject::PropagateResetPipeline () protected virtual
Called to allocate the input array. Copies old inputs. Propagate a call to ResetPipeline() up the pipeline. Called only from DataObject.
PushBackInput()
virtual void itk::ProcessObject::PushBackInput (const DataObject * input) protected virtual
Push/Pop an indexed input of this process object.
These methods allow a filter to model its input vector as a queue or stack. These routines may not be appropriate for all filters, especially filters with different types of inputs. These routines follow the semantics of STL.
Reimplemented in itk::ImageToImageFilter< TInputImage, TOutputImage >, itk::ImageToImageFilter< TImageType, TImageType >, itk::ImageToImageFilter< TInputImage, TInputImage >, itk::ImageToImageFilter< TImage, TImage >, itk::ImageToImageFilter< TInputImage1, TInputImage1 >, itk::ImageToImageFilter< TInputVectorImage, Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage1, TOutputImage >, itk::ImageToImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TReferenceImagePixelType, 3 >, Image< DiffusionTensor3D< double >, 3 > >, itk::ImageToImageFilter< TInputImage, TEigenValueImage >, itk::ImageToImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< float, TLevelSet::ImageDimension >, TLevelSet >, itk::ImageToImageFilter< TInputImageType, TSparseOutputImageType >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TDisplacementField, TOutputImage >, itk::ImageToImageFilter< Image< SymmetricSecondRankTensor< double, 3 >, 3 >, Image< TPixel, 3 > >, itk::ImageToImageFilter< TInputImage, Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TInputPixelType, 2 >, Image< TOutputPixelType, 2 > >, itk::ImageToImageFilter< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TSparseOutputImage >, itk::ImageToImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageToImageFilter< TLabelImage, TLabelImage >, itk::ImageToImageFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TLabelImage, TOutputImage >, itk::ImageToImageFilter< TInputImage, TClassifiedImage >, itk::ImageToImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TLabelImage >, itk::ImageToImageFilter< TDisplacementField, TDisplacementField >, itk::ImageToImageFilter< TFeatureImage, TOutputImage >, itk::ImageToImageFilter< TLevelSet, TLevelSet >, itk::ImageToImageFilter< TInputImage, Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageToImageFilter< TMask, TImage >, itk::ImageToImageFilter< TTimeVaryingVelocityField, Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageToImageFilter< TInputImage, Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< ImageType, ImageType >, and itk::ImageToImageFilter< FeatureImageType, ImageType >.
PushFrontInput()
virtual void itk::ProcessObject::PushFrontInput (const DataObject * input) protected virtual
Reimplemented in itk::ImageToImageFilter< TInputImage, TOutputImage >, itk::ImageToImageFilter< TImageType, TImageType >, itk::ImageToImageFilter< TInputImage, TInputImage >, itk::ImageToImageFilter< TImage, TImage >, itk::ImageToImageFilter< TInputImage1, TInputImage1 >, itk::ImageToImageFilter< TInputVectorImage, Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage1, TOutputImage >, itk::ImageToImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TReferenceImagePixelType, 3 >, Image< DiffusionTensor3D< double >, 3 > >, itk::ImageToImageFilter< TInputImage, TEigenValueImage >, itk::ImageToImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< float, TLevelSet::ImageDimension >, TLevelSet >, itk::ImageToImageFilter< TInputImageType, TSparseOutputImageType >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TDisplacementField, TOutputImage >, itk::ImageToImageFilter< Image< SymmetricSecondRankTensor< double, 3 >, 3 >, Image< TPixel, 3 > >, itk::ImageToImageFilter< TInputImage, Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TInputPixelType, 2 >, Image< TOutputPixelType, 2 > >, itk::ImageToImageFilter< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TSparseOutputImage >, itk::ImageToImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageToImageFilter< TLabelImage, TLabelImage >, itk::ImageToImageFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TLabelImage, TOutputImage >, itk::ImageToImageFilter< TInputImage, TClassifiedImage >, itk::ImageToImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TLabelImage >, itk::ImageToImageFilter< TDisplacementField, TDisplacementField >, itk::ImageToImageFilter< TFeatureImage, TOutputImage >, itk::ImageToImageFilter< TLevelSet, TLevelSet >, itk::ImageToImageFilter< TInputImage, Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageToImageFilter< TMask, TImage >, itk::ImageToImageFilter< TTimeVaryingVelocityField, Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageToImageFilter< TInputImage, Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< ImageType, ImageType >, and itk::ImageToImageFilter< FeatureImageType, ImageType >.
ReleaseDataBeforeUpdateFlagOn()
virtual void itk::ProcessObject::ReleaseDataBeforeUpdateFlagOn () virtual
Turn on/off the flags to control whether the bulk data belonging to the outputs of this ProcessObject are released/reallocated during an Update(). In limited memory scenarios, a user may want to force the elements of a pipeline to release any bulk data that is going to be regenerated anyway during an Update() in order to control peak memory allocation. Note that this flag is different from the ReleaseDataFlag. ReleaseDataFlag manages the deallocation of a ProcessObject's bulk output data once that data has been consumed by a downstream ProcessObject. The ReleaseDataBeforeUpdateFlag manages the deallocation/reallocation of bulk data during a pipeline update to control peak memory utilization. Default value is on.
ReleaseDataFlagOff()
void itk::ProcessObject::ReleaseDataFlagOff () inline
Turn on/off the flags to control whether the bulk data belonging to the outputs of this ProcessObject are released after being used by a downstream ProcessObject. Default value is off. Another options for controlling memory utilization is the ReleaseDataBeforeUpdateFlag.
Definition at line 471 of file itkProcessObject.h.
ReleaseDataFlagOn()
void itk::ProcessObject::ReleaseDataFlagOn () inline
Turn on/off the flags to control whether the bulk data belonging to the outputs of this ProcessObject are released after being used by a downstream ProcessObject. Default value is off. Another options for controlling memory utilization is the ReleaseDataBeforeUpdateFlag.
Definition at line 466 of file itkProcessObject.h.
ReleaseInputs()
virtual void itk::ProcessObject::ReleaseInputs () protected virtual
A filter may need to release its input's bulk data after it has finished calculating a new output. The filter may need to release the inputs because the user has turned on the ReleaseDataFlag or it may need to release the inputs because the filter is an "in place" filter and it has overwritten its input with its output data. The implementation here simply checks the ReleaseDataFlag of the inputs. InPlaceImageFilter overrides this method so release the input it has overwritten.
See also
InPlaceImageFilter::ReleaseInputs()
Reimplemented in itk::InPlaceImageFilter< TInputImage, TOutputImage >, itk::InPlaceImageFilter< TInputImage, TOutputImage >, itk::InPlaceImageFilter< TInputImage, TInputImage >, itk::InPlaceImageFilter< TInputImage1, TInputImage1 >, itk::InPlaceImageFilter< TInputImage1, TOutputImage >, itk::InPlaceImageFilter< TImage, TImage >, itk::InPlaceImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::InPlaceImageFilter< TInputImageType, TSparseOutputImageType >, itk::InPlaceImageFilter< TImageType, TImageType >, itk::InPlaceImageFilter< TInputImage, TSparseOutputImage >, itk::InPlaceImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::InPlaceImageFilter< TLabelImage, TOutputImage >, itk::InPlaceImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::InPlaceImageFilter< TFeatureImage, TOutputImage >, itk::InPlaceImageFilter< TDisplacementField, TDisplacementField >, itk::InPlaceImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::InPlaceImageFilter< TMask, TImage >, itk::InPlaceImageFilter< FeatureImageType, ImageType >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, TParentImageFilter >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, AnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, BinaryThresholdImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, CastImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TDisplacementField, TDisplacementField, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, DenseFiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, FiniteDifferenceImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, GradientAnisotropicDiffusionImageFilter< TInputImage, TOutputImage > >, itk::GPUInPlaceImageFilter< TDisplacementField, TDisplacementField, PDEDeformableRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField > >, and itk::GPUInPlaceImageFilter< TInputImage, TOutputImage, InPlaceImageFilter< TInputImage, TOutputImage > >.
RemoveInput() [1/2]
virtual void itk::ProcessObject::RemoveInput (const DataObjectIdentifierType & key) protected virtual
Remove an input.
If the input is the last indexed input the number of indexed inputs will be reduced by one. Otherwise, if the input is required or indexed it will be set to nullptr.
RemoveInput() [2/2]
virtual void itk::ProcessObject::RemoveInput (DataObjectPointerArraySizeType) protected virtual
RemoveOutput() [1/2]
virtual void itk::ProcessObject::RemoveOutput (const DataObjectIdentifierType & key) protected virtual
Remove an output
RemoveOutput() [2/2]
virtual void itk::ProcessObject::RemoveOutput (DataObjectPointerArraySizeType idx) protected virtual
RemoveRequiredInputName()
bool itk::ProcessObject::RemoveRequiredInputName (const DataObjectIdentifierType &) protected
Remove the named input from the required inputs.
The named input remains defined or set afterwards.
ResetPipeline()
virtual void itk::ProcessObject::ResetPipeline () virtual
Reset the pipeline.
If an exception is thrown during an Update(), the pipeline may be in an inconsistent state. This method clears the internal state of the pipeline so Update() can be called.
Reimplemented in itk::StreamingProcessObject.
RestoreInputReleaseDataFlags()
virtual void itk::ProcessObject::RestoreInputReleaseDataFlags () protected virtual
Restore the cached input ReleaseDataFlags.
SetAbortGenerateData()
virtual void itk::ProcessObject::SetAbortGenerateData (bool _arg) virtual
Set the AbortGenerateData flag for the process object.
Process objects may handle premature termination of execution in different ways.
SetInput()
virtual void itk::ProcessObject::SetInput (const DataObjectIdentifierType & key, DataObject * input) protected virtual
Protected method for setting indexed and named inputs.
Subclasses make use of them for setting input. As this method only used the base DataObject pointer, derived classes should expose a type check methods.
Reimplemented in itk::ImageToImageFilter< TInputImage, TOutputImage >, itk::ImageToImageFilter< TImageType, TImageType >, itk::ImageToImageFilter< TInputImage, TInputImage >, itk::ImageToImageFilter< TImage, TImage >, itk::ImageToImageFilter< TInputImage1, TInputImage1 >, itk::ImageToImageFilter< TInputVectorImage, Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage1, TOutputImage >, itk::ImageToImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TReferenceImagePixelType, 3 >, Image< DiffusionTensor3D< double >, 3 > >, itk::ImageToImageFilter< TInputImage, TEigenValueImage >, itk::ImageToImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< float, TLevelSet::ImageDimension >, TLevelSet >, itk::ImageToImageFilter< TInputImageType, TSparseOutputImageType >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TDisplacementField, TOutputImage >, itk::ImageToImageFilter< Image< SymmetricSecondRankTensor< double, 3 >, 3 >, Image< TPixel, 3 > >, itk::ImageToImageFilter< TInputImage, Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TInputPixelType, 2 >, Image< TOutputPixelType, 2 > >, itk::ImageToImageFilter< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TSparseOutputImage >, itk::ImageToImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageToImageFilter< TLabelImage, TLabelImage >, itk::ImageToImageFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TLabelImage, TOutputImage >, itk::ImageToImageFilter< TInputImage, TClassifiedImage >, itk::ImageToImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TLabelImage >, itk::ImageToImageFilter< TDisplacementField, TDisplacementField >, itk::ImageToImageFilter< TFeatureImage, TOutputImage >, itk::ImageToImageFilter< TLevelSet, TLevelSet >, itk::ImageToImageFilter< TInputImage, Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageToImageFilter< TMask, TImage >, itk::ImageToImageFilter< TTimeVaryingVelocityField, Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageToImageFilter< TInputImage, Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< ImageType, ImageType >, itk::ImageToImageFilter< FeatureImageType, ImageType >, itk::PointSetToImageFilter< TInputPointSet, TOutputImage >, itk::TriangleMeshToBinaryImageFilter< TInputMesh, TOutputImage >, itk::SpatialObjectToImageFilter< TInputSpatialObject, TOutputImage >, itk::Testing::ExtractSliceImageFilter< TInputImage, TOutputImage >, itk::TransformToDisplacementFieldFilter< TOutputImage, TParametersValueType >, itk::PathToImageFilter< TInputPath, TOutputImage >, itk::HistogramThresholdCalculator< THistogram, TOutput >, itk::HistogramThresholdCalculator< THistogram, double >, and itk::VoronoiSegmentationRGBImageFilter< TInputImage, TOutputImage >.
Referenced by itk::SegmentationLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType >::SetFeatureImage().
SetMultiThreader()
void itk::ProcessObject::SetMultiThreader (MultiThreaderType * threader)
Set the multithreader used by this class.
SetNthInput()
virtual void itk::ProcessObject::SetNthInput (DataObjectPointerArraySizeType idx, DataObject * input) protected virtual
Referenced by itk::watershed::BoundaryResolver< TPixelType, TDimension >::SetBoundaryA(), itk::watershed::BoundaryResolver< TPixelType, TDimension >::SetBoundaryB(), itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >::SetEquivalencyTable(), itk::NarrowBandLevelSetImageFilter< TInputImage, TFeatureImage, TOutputPixelType, TOutputImage >::SetFeatureImage(), itk::HistogramThresholdCalculator< THistogram, TOutput >::SetInput(), itk::WatershedImageFilter< TInputImage >::SetInput(), itk::watershed::SegmentTreeGenerator< TScalar >::SetInputEquivalencyTable(), itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >::SetInputImage(), itk::watershed::Relabeler< TScalar, TImageDimension >::SetInputImage(), itk::watershed::Segmenter< TInputImage >::SetInputImage(), itk::watershed::SegmentTreeGenerator< TScalar >::SetInputSegmentTable(), itk::watershed::Relabeler< TScalar, TImageDimension >::SetInputSegmentTree(), itk::ChangeInformationImageFilter< TInputImage >::SetReferenceImage(), and itk::DiffusionTensor3DReconstructionImageFilter< TReferenceImagePixelType, TGradientImagePixelType, TTensorPixelType, TMaskImageType >::SetReferenceImage().
SetNthOutput()
virtual void itk::ProcessObject::SetNthOutput (DataObjectPointerArraySizeType idx, DataObject * output) protected virtual
Protected methods for setting outputs. Subclasses make use of them for getting output.
Referenced by itk::watershed::BoundaryResolver< TPixelType, TDimension >::BoundaryResolver(), itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >::EquivalenceRelabeler(), itk::HistogramThresholdCalculator< THistogram, TOutput >::HistogramThresholdCalculator(), itk::watershed::Segmenter< TInputImage >::SetBoundary(), itk::watershed::BoundaryResolver< TPixelType, TDimension >::SetEquivalencyTable(), itk::watershed::EquivalenceRelabeler< TScalar, TImageDimension >::SetOutputImage(), itk::watershed::Relabeler< TScalar, TImageDimension >::SetOutputImage(), itk::watershed::Segmenter< TInputImage >::SetOutputImage(), and itk::watershed::Segmenter< TInputImage >::SetSegmentTable().
SetNumberOfIndexedInputs()
void itk::ProcessObject::SetNumberOfIndexedInputs (DataObjectPointerArraySizeType num) protected
Define the number of indexed inputs defined.
The new indexed inputs' values are set to nullptr. If the size is reduced then the input definition is removed entirely from the named input entries and index inputs.
SetNumberOfIndexedOutputs()
void itk::ProcessObject::SetNumberOfIndexedOutputs (DataObjectPointerArraySizeType num) protected
Called to allocate the output array. Copies old outputs.
SetNumberOfRequiredInputs()
virtual void itk::ProcessObject::SetNumberOfRequiredInputs (DataObjectPointerArraySizeType) protected virtual
Set the number of required indexed inputs.
If an input is not associated with an index and only a named entry, it is not considered in this count. In the method VerifyPreconditions(), GetNumberOfValidRequiredInputs() is checked to be at least this value.
Note
SetNumberOfRequiredIndexInputs maybe a better name.
SetNumberOfRequiredOutputs()
virtual void itk::ProcessObject::SetNumberOfRequiredOutputs (DataObjectPointerArraySizeType _arg) protected virtual
Referenced by itk::HistogramThresholdCalculator< THistogram, TOutput >::HistogramThresholdCalculator().
SetNumberOfWorkUnits()
virtual void itk::ProcessObject::SetNumberOfWorkUnits (ThreadIdType _arg) virtual
Get/Set the number of work units to create when executing.
Reimplemented in itk::GradientMagnitudeRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::GrayscaleDilateImageFilter< TInputImage, TOutputImage, TKernel >, itk::GrayscaleErodeImageFilter< TInputImage, TOutputImage, TKernel >, itk::SmoothingRecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::MiniPipelineSeparableImageFilter< TInputImage, TOutputImage, TFilter >, and itk::MiniPipelineSeparableImageFilter< TInputImage, TOutputImage, RankImageFilter< TInputImage, TInputImage, FlatStructuringElement< TInputImage::ImageDimension > > >.
SetOutput()
virtual void itk::ProcessObject::SetOutput (const DataObjectIdentifierType & name, DataObject * output) protected virtual
Set an output
SetPrimaryInput()
virtual void itk::ProcessObject::SetPrimaryInput (DataObject * object) protected virtual
Set the main input
SetPrimaryInputName()
virtual void itk::ProcessObject::SetPrimaryInputName (const DataObjectIdentifierType & key) protected virtual
Set/Get the name associated with the Primary input. Defaults to "Primary".
SetPrimaryOutput()
virtual void itk::ProcessObject::SetPrimaryOutput (DataObject * object) protected virtual
Set the main output
SetPrimaryOutputName()
virtual void itk::ProcessObject::SetPrimaryOutputName (const DataObjectIdentifierType & key) protected virtual
Set/Get the name associated with the Primary output. Defaults to "Primary".
SetReleaseDataBeforeUpdateFlag()
virtual void itk::ProcessObject::SetReleaseDataBeforeUpdateFlag (bool _arg) virtual
Turn on/off the flags to control whether the bulk data belonging to the outputs of this ProcessObject are released/reallocated during an Update(). In limited memory scenarios, a user may want to force the elements of a pipeline to release any bulk data that is going to be regenerated anyway during an Update() in order to control peak memory allocation. Note that this flag is different from the ReleaseDataFlag. ReleaseDataFlag manages the deallocation of a ProcessObject's bulk output data once that data has been consumed by a downstream ProcessObject. The ReleaseDataBeforeUpdateFlag manages the deallocation/reallocation of bulk data during a pipeline update to control peak memory utilization. Default value is on.
SetReleaseDataFlag()
virtual void itk::ProcessObject::SetReleaseDataFlag (bool val) virtual
Turn on/off the flags to control whether the bulk data belonging to the outputs of this ProcessObject are released after being used by a downstream ProcessObject. Default value is off. Another options for controlling memory utilization is the ReleaseDataBeforeUpdateFlag.
SetRequiredInputNames()
void itk::ProcessObject::SetRequiredInputNames (const NameArray &) protected
Set all required named inputs.
All named inputs remain defined or set.
SetThreaderUpdateProgress()
virtual void itk::ProcessObject::SetThreaderUpdateProgress (bool arg) protected virtual
When true, the MultiThreader will report course grain progress. If set to false, a progress must be explicitly updated in derived filters.
ThreaderUpdateProgressOn()
virtual void itk::ProcessObject::ThreaderUpdateProgressOn () protected virtual
When true, the MultiThreader will report course grain progress. If set to false, a progress must be explicitly updated in derived filters.
Update()
virtual void itk::ProcessObject::Update () virtual
Bring this filter up-to-date.
Update() checks modified times against last execution times, and re-executes objects if necessary. A side effect of this method is that the whole pipeline may execute in order to bring this filter up-to-date. This method updates the currently prescribed requested region. If no requested region has been set on the output, then the requested region will be set to the largest possible region. Once the requested region is set, Update() will make sure the specified requested region is up-to-date. This is a confusing side effect to users who are just calling Update() on a filter. A first call to Update() will cause the largest possible region to be updated. A second call to Update() will update that same region. If a modification to the upstream pipeline cause a filter to have a different largest possible region, this second call to Update() will not cause the output requested region to be reset to the new largest possible region. Instead, the output requested region will be the same as the last time Update() was called. To have a filter always to produce its largest possible region, users should call UpdateLargestPossibleRegion() instead.
Reimplemented in itk::ImageSink< TInputImage >, itk::ImageSink< TLabelImage >, itk::ImageSink< TImage >, itk::ImageFileWriter< TInputImage >, itk::ImageSeriesWriter< TInputImage, TOutputImage >, itk::MeshFileWriter< TInputMesh >, and itk::VideoFileWriter< TInputVideoStream >.
Referenced by itk::WatershedImageFilter< TInputImage >::GetBasicSegmentation().
UpdateLargestPossibleRegion()
virtual void itk::ProcessObject::UpdateLargestPossibleRegion () virtual
Sets the output requested region to the largest possible region and updates.
This is the method users should call if they want the entire dataset to be processed. If a user wants to update the same output region as a previous call to Update() or a previous call to UpdateLargestPossibleRegion(), then they should call the method Update().
Reimplemented in itk::ImageSink< TInputImage >, itk::ImageSink< TLabelImage >, itk::ImageSink< TImage >, itk::ImageFileWriter< TInputImage >, and itk::VideoFileWriter< TInputVideoStream >.
UpdateOutputData()
virtual void itk::ProcessObject::UpdateOutputData (DataObject * output) virtual
Actually generate new output
Reimplemented in itk::StreamingImageFilter< TInputImage, TOutputImage >, itk::StreamingProcessObject, itk::FFTWComplexToComplexFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWForwardFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWHalfHermitianToRealInverseFFTImageFilter< TInputImage, TOutputImage >, itk::FFTWRealToHalfHermitianForwardFFTImageFilter< TInputImage, TOutputImage >, and itk::TemporalProcessObject.
UpdateOutputInformation()
virtual void itk::ProcessObject::UpdateOutputInformation () virtual
Update the information describing the output data.
This method traverses up the pipeline gathering modified time information. On the way back down the pipeline, this method calls GenerateOutputInformation() to set any necessary information about the output data objects. For instance, a filter that shrinks an image will need to provide an implementation for GenerateOutputInformation() that changes the spacing of the pixels. Such filters should call their superclass' implementation of GenerateOutputInformation prior to changing the information values they need (i.e. GenerateOutputInformation() should call Superclass::GenerateOutputInformation() prior to changing the information.
Reimplemented in itk::VTKImageImport< TOutputImage >, itk::watershed::Segmenter< TInputImage >, itk::watershed::Segmenter< InputImageType >, itk::TemporalProcessObject, itk::VideoToVideoFilter< TInputVideoStream, TOutputVideoStream >, itk::VideoToVideoFilter< TVideoStream, TVideoStream >, itk::VideoToVideoFilter< itk::VideoStream< TImageToImageFilter::InputImageType >, itk::VideoStream< TImageToImageFilter::OutputImageType > >, and itk::VideoFileReader< TOutputVideoStream >.
UpdateProgress()
void itk::ProcessObject::UpdateProgress (float progress)
Update the progress of the process object.
Sets the Progress ivar to amount and invokes any observers for the ProgressEvent. The parameter amount should be in [0,1] and is the cumulative (not incremental) progress.
Multiple thread should not call this method, since they may have computed different values and increments may get lost.
VerifyInputInformation()
virtual void itk::ProcessObject::VerifyInputInformation () protected virtual
Verifies that the inputs meta-data is consistent and valid for continued execution of the pipeline, throws an exception if not valid.
This method is called immediately before GenerateOutputInformation().
The ProcessObject implementation does nothing. Subclasses might check if all the inputs are in the same coordinate frame.
Reimplemented in itk::ImageSink< TInputImage >, itk::ImageSink< TLabelImage >, itk::ImageSink< TImage >, itk::ImageToImageFilter< TInputImage, TOutputImage >, itk::ImageToImageFilter< TImageType, TImageType >, itk::ImageToImageFilter< TInputImage, TInputImage >, itk::ImageToImageFilter< TImage, TImage >, itk::ImageToImageFilter< TInputImage1, TInputImage1 >, itk::ImageToImageFilter< TInputVectorImage, Image< unsigned char, TInputVectorImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage1, TOutputImage >, itk::ImageToImageFilter< TInputImage, Image< float, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, VectorImage< typename TInputImage::PixelType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< TDataType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TReferenceImagePixelType, 3 >, Image< DiffusionTensor3D< double >, 3 > >, itk::ImageToImageFilter< TInputImage, TEigenValueImage >, itk::ImageToImageFilter< TInputImage, Image< std::complex< typename TInputImage::PixelType >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename TInputImage::PixelType::value_type, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType >::ValueType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< float, TLevelSet::ImageDimension >, TLevelSet >, itk::ImageToImageFilter< TInputImageType, TSparseOutputImageType >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< float, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< CovariantVector< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TDisplacementField, TOutputImage >, itk::ImageToImageFilter< Image< SymmetricSecondRankTensor< double, 3 >, 3 >, Image< TPixel, 3 > >, itk::ImageToImageFilter< TInputImage, Image< SymmetricSecondRankTensor< typename NumericTraits< typename TInputImage::PixelType >::RealType, TInputImage::ImageDimension >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< Image< TInputPixelType, 2 >, Image< TOutputPixelType, 2 > >, itk::ImageToImageFilter< TInputImage, Image< double, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TSparseOutputImage >, itk::ImageToImageFilter< TInputImage1, Functor::MakeJoin< TInputImage1, TInputImage2 >::ImageType >, itk::ImageToImageFilter< TLabelImage, TLabelImage >, itk::ImageToImageFilter< TLabelMap, Image< RGBPixel< typename TFeatureImage::PixelType >, TFeatureImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< RGBPixel< unsigned char >, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TLabelImage, TOutputImage >, itk::ImageToImageFilter< TInputImage, TClassifiedImage >, itk::ImageToImageFilter< TInputImage1, itk::Image< std::complex< typename TInputImage1::PixelType >, TInputImage1::ImageDimension > >, itk::ImageToImageFilter< TInputImage, TLabelImage >, itk::ImageToImageFilter< TDisplacementField, TDisplacementField >, itk::ImageToImageFilter< TFeatureImage, TOutputImage >, itk::ImageToImageFilter< TLevelSet, TLevelSet >, itk::ImageToImageFilter< TInputImage, Image< unsigned char, TInputImage::ImageDimension > >, itk::ImageToImageFilter< TInputImage, Image< typename NumericTraits< typename TInputImage::PixelType::ValueType >::RealType, TInputImage::Dimension > >, itk::ImageToImageFilter< TMask, TImage >, itk::ImageToImageFilter< TTimeVaryingVelocityField, Image< typename TTimeVaryingVelocityField::PixelType, TTimeVaryingVelocityField::ImageDimension - 1 > >, itk::ImageToImageFilter< TInputImage, Image< IdentifierType, TInputImage::ImageDimension > >, itk::ImageToImageFilter< ImageType, ImageType >, itk::ImageToImageFilter< FeatureImageType, ImageType >, itk::Testing::ComparisonImageFilter< TInputImage, TOutputImage >, itk::ConvolutionImageFilterBase< TInputImage, TKernelImage, TOutputImage >, itk::ConvolutionImageFilterBase< TInputImage, TInputImage, TInputImage >, itk::ConvolutionImageFilterBase< TInputImage, TKernelSource::OutputImageType, TInputImage >, itk::MaskedFFTNormalizedCorrelationImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::JoinSeriesImageFilter< TInputImage, TOutputImage >, itk::ChangeInformationImageFilter< TInputImage >, itk::CropImageFilter< TInputImage, TOutputImage >, itk::InterpolateImagePointsFilter< TInputImage, TOutputImage, TCoordType, InterpolatorType >, itk::PasteImageFilter< TInputImage, TSourceImage, TOutputImage >, itk::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType, TTransformPrecisionType >, itk::SliceBySliceImageFilter< TInputImage, TOutputImage, TInputFilter, TOutputFilter, TInternalInputImage, TInternalOutputImage >, itk::SliceImageFilter< TInputImage, TOutputImage >, itk::TileImageFilter< TInputImage, TOutputImage >, itk::WarpImageFilter< TInputImage, TOutputImage, TDisplacementField >, itk::HistogramMatchingImageFilter< TInputImage, TOutputImage, THistogramMeasurement >, itk::DemonsRegistrationFilter< TFixedImage, TMovingImage, TDisplacementField >, itk::MultiResolutionPDEDeformableRegistration< TFixedImage, TMovingImage, TDisplacementField, TRealType, TFloatImageType, TRegistrationType, TDefaultRegistrationType >, and itk::IsolatedWatershedImageFilter< TInputImage, TOutputImage >.
VerifyPreconditions()
virtual void itk::ProcessObject::VerifyPreconditions () protected virtual
Verifies that the process object has been configured correctly, that all required inputs are set, and needed parameters are set appropriately. If not valid an exceptions will be thrown.
This method is called before UpdateOutputInformation() is propagated to the inputs.
The ProcessObject's implementation verifies that the m_NumberOfRequiredInputs are set and not null.
Reimplemented in itk::TransformGeometryImageFilter< TInputImage, TOutputImage >, itk::DiffusionTensor3DReconstructionImageFilter< TReferenceImagePixelType, TGradientImagePixelType, TTensorPixelType, TMaskImageType >, itk::HessianToObjectnessMeasureImageFilter< TInputImage, TOutputImage >, itk::HoughTransform2DCirclesImageFilter< TInputPixelType, TOutputPixelType, TRadiusPixelType >, itk::UnsharpMaskImageFilter< TInputImage, TOutputImage, TInternalPrecision >, itk::FrequencyBandImageFilter< TImageType, TFrequencyIterator >, itk::PasteImageFilter< TInputImage, TSourceImage, TOutputImage >, itk::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType, TTransformPrecisionType >, itk::DivideImageFilter< TInputImage1, TInputImage2, TOutputImage >, itk::HistogramMatchingImageFilter< TInputImage, TOutputImage, THistogramMeasurement >, itk::RecursiveGaussianImageFilter< TInputImage, TOutputImage >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::HistogramThresholdImageFilter< TInputImage, TOutputImage, TOutputImage >, itk::IntermodesThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, itk::OtsuThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >, and itk::ScalarImageKmeansImageFilter< TInputImage, TOutputImage >.
Friends And Related Function Documentation
DataObject
friend class DataObject friend
Friends of ProcessObject
Definition at line 998 of file itkProcessObject.h.
DataObjectConstIterator
friend class DataObjectConstIterator friend
Definition at line 1003 of file itkProcessObject.h.
DataObjectIterator
friend class DataObjectIterator friend
Definition at line 1007 of file itkProcessObject.h.
InputDataObjectConstIterator
friend class InputDataObjectConstIterator friend
Definition at line 1004 of file itkProcessObject.h.
InputDataObjectIterator
friend class InputDataObjectIterator friend
Definition at line 1008 of file itkProcessObject.h.
OutputDataObjectConstIterator
friend class OutputDataObjectConstIterator friend
Definition at line 1005 of file itkProcessObject.h.
OutputDataObjectIterator
friend class OutputDataObjectIterator friend
Definition at line 1009 of file itkProcessObject.h.
ProgressReporter
friend class ProgressReporter friend
Definition at line 1000 of file itkProcessObject.h.
TestProcessObject
friend class TestProcessObject friend
Definition at line 1011 of file itkProcessObject.h.
TotalProgressReporter
friend class TotalProgressReporter friend
Definition at line 1001 of file itkProcessObject.h.
Member Data Documentation
m_AbortGenerateData
bool itk::ProcessObject::m_AbortGenerateData private
These support the progress method and aborting filter execution.
Definition at line 981 of file itkProcessObject.h.
m_CachedInputReleaseDataFlags
std::map<DataObjectIdentifierType, bool> itk::ProcessObject::m_CachedInputReleaseDataFlags private
An array that caches the ReleaseDataFlags of the inputs
Definition at line 969 of file itkProcessObject.h.
m_IndexedInputs
std::vector<DataObjectPointerMap::iterator> itk::ProcessObject::m_IndexedInputs private
Definition at line 965 of file itkProcessObject.h.
m_IndexedOutputs
std::vector<DataObjectPointerMap::iterator> itk::ProcessObject::m_IndexedOutputs private
Definition at line 966 of file itkProcessObject.h.
m_Inputs
DataObjectPointerMap itk::ProcessObject::m_Inputs private
Named input and outputs containers
Definition at line 962 of file itkProcessObject.h.
Referenced by itk::InputDataObjectConstIterator::InputDataObjectConstIterator(), and itk::InputDataObjectIterator::InputDataObjectIterator().
m_MultiThreader
itk::SmartPointer<MultiThreaderType> itk::ProcessObject::m_MultiThreader private
Support processing data in multiple threads. Used by subclasses (e.g., ImageSource).
Definition at line 989 of file itkProcessObject.h.
m_NumberOfRequiredInputs
DataObjectPointerArraySizeType itk::ProcessObject::m_NumberOfRequiredInputs private
Definition at line 971 of file itkProcessObject.h.
m_NumberOfRequiredOutputs
DataObjectPointerArraySizeType itk::ProcessObject::m_NumberOfRequiredOutputs private
Definition at line 972 of file itkProcessObject.h.
m_NumberOfWorkUnits
ThreadIdType itk::ProcessObject::m_NumberOfWorkUnits private
Definition at line 990 of file itkProcessObject.h.
m_OutputInformationMTime
TimeStamp itk::ProcessObject::m_OutputInformationMTime protected
Time when GenerateOutputInformation was last called.
Definition at line 950 of file itkProcessObject.h.
m_Outputs
DataObjectPointerMap itk::ProcessObject::m_Outputs private
Definition at line 963 of file itkProcessObject.h.
Referenced by itk::OutputDataObjectConstIterator::OutputDataObjectConstIterator(), and itk::OutputDataObjectIterator::OutputDataObjectIterator().
m_Progress
std::atomic<uint32_t> itk::ProcessObject::m_Progress private
Definition at line 982 of file itkProcessObject.h.
m_ReleaseDataBeforeUpdateFlag
bool itk::ProcessObject::m_ReleaseDataBeforeUpdateFlag private
Memory management ivars
Definition at line 995 of file itkProcessObject.h.
m_RequiredInputNames
NameSet itk::ProcessObject::m_RequiredInputNames private
The required inputs
Definition at line 978 of file itkProcessObject.h.
m_ThreaderUpdateProgress
bool itk::ProcessObject::m_ThreaderUpdateProgress { true } private
Definition at line 992 of file itkProcessObject.h.
m_UpdateThreadID
std::thread::id itk::ProcessObject::m_UpdateThreadID private
Definition at line 985 of file itkProcessObject.h.
m_Updating
bool itk::ProcessObject::m_Updating protected
These ivars are made protected so filters like itkStreamingImageFilter can access them directly. This flag indicates when the pipeline is executing. It prevents infinite recursion when pipelines have loops.
Definition at line 947 of file itkProcessObject.h.
The documentation for this class was generated from the following file:
itkProcessObject.h