ITK: itk::QuadEdgeMeshBaseIterator< TQuadEdge > Class Template Reference
itk::QuadEdgeMeshBaseIterator< TQuadEdge > Class Template Reference
Group Core » Module ITKQuadEdgeMesh
#include <itkQuadEdgeMeshBaseIterator.h>
Public Types
enum {
OperatorOnext = 0 ,
OperatorSym = 1 ,
OperatorLnext = 2 ,
OperatorRnext = 3 ,
OperatorDnext = 4 ,
OperatorOprev = 5 ,
OperatorLprev = 6 ,
OperatorRprev = 7 ,
OperatorDprev = 8 ,
OperatorInvOnext = 9 ,
OperatorInvLnext = 10 ,
OperatorInvRnext = 11 ,
OperatorInvDnext = 12
}
using QuadEdgeType = TQuadEdge
using Self = QuadEdgeMeshBaseIterator
Public Member Functions
QuadEdgeType * GetIterator () const
int GetOpType () const
bool GetStart () const
QuadEdgeType * GetStartEdge () const
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
Self & operator++ ()
Self & operator++ (int)
Self & operator= (const Self &r)
bool operator== (const Self &r) const
QuadEdgeMeshBaseIterator (const QuadEdgeMeshBaseIterator &)=default
QuadEdgeMeshBaseIterator (QuadEdgeType *e, int op=OperatorOnext, bool start=true)
virtual ~QuadEdgeMeshBaseIterator ()=default
Protected Member Functions
virtual void GoToNext ()
Detailed Description
template<typename TQuadEdge>
class itk::QuadEdgeMeshBaseIterator< TQuadEdge >
Base iterator class for QuadEdgeMesh.
Definition at line 60 of file itkQuadEdgeMeshBaseIterator.h.
Member Typedef Documentation
QuadEdgeType
template<typename TQuadEdge > using itk::QuadEdgeMeshBaseIterator< TQuadEdge >::QuadEdgeType = TQuadEdge
Definition at line 65 of file itkQuadEdgeMeshBaseIterator.h.
Self
template<typename TQuadEdge > using itk::QuadEdgeMeshBaseIterator< TQuadEdge >::Self = QuadEdgeMeshBaseIterator
Definition at line 64 of file itkQuadEdgeMeshBaseIterator.h.
Member Enumeration Documentation
anonymous enum
template<typename TQuadEdge > anonymous enum
Enumerator
OperatorOnext
OperatorSym
OperatorLnext
OperatorRnext
OperatorDnext
OperatorOprev
OperatorLprev
OperatorRprev
OperatorDprev
OperatorInvOnext
OperatorInvLnext
OperatorInvRnext
OperatorInvDnext
Definition at line 68 of file itkQuadEdgeMeshBaseIterator.h.
Constructor & Destructor Documentation
QuadEdgeMeshBaseIterator() [1/2]
template<typename TQuadEdge > itk::QuadEdgeMeshBaseIterator< TQuadEdge >::QuadEdgeMeshBaseIterator (QuadEdgeType * e, int op = OperatorOnext, bool start = true) inline
Definition at line 87 of file itkQuadEdgeMeshBaseIterator.h.
QuadEdgeMeshBaseIterator() [2/2]
template<typename TQuadEdge > itk::QuadEdgeMeshBaseIterator< TQuadEdge >::QuadEdgeMeshBaseIterator (const QuadEdgeMeshBaseIterator< TQuadEdge > &) default
~QuadEdgeMeshBaseIterator()
template<typename TQuadEdge > virtual itk::QuadEdgeMeshBaseIterator< TQuadEdge >::~QuadEdgeMeshBaseIterator () virtual default
Member Function Documentation
GetIterator()
template<typename TQuadEdge > QuadEdgeType * itk::QuadEdgeMeshBaseIterator< TQuadEdge >::GetIterator () const inline
Definition at line 117 of file itkQuadEdgeMeshBaseIterator.h.
Referenced by itk::QuadEdgeMeshConstIterator< TQuadEdge >::operator=(), and itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::operator=().
GetOpType()
template<typename TQuadEdge > int itk::QuadEdgeMeshBaseIterator< TQuadEdge >::GetOpType () const inline
Definition at line 122 of file itkQuadEdgeMeshBaseIterator.h.
Referenced by itk::QuadEdgeMeshConstIterator< TQuadEdge >::operator=(), and itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::operator=().
GetStart()
template<typename TQuadEdge > bool itk::QuadEdgeMeshBaseIterator< TQuadEdge >::GetStart () const inline
Definition at line 127 of file itkQuadEdgeMeshBaseIterator.h.
Referenced by itk::QuadEdgeMeshConstIterator< TQuadEdge >::operator=(), and itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::operator=().
GetStartEdge()
template<typename TQuadEdge > QuadEdgeType * itk::QuadEdgeMeshBaseIterator< TQuadEdge >::GetStartEdge () const inline
Definition at line 112 of file itkQuadEdgeMeshBaseIterator.h.
Referenced by itk::QuadEdgeMeshConstIterator< TQuadEdge >::operator=(), and itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::operator=().
GoToNext()
template<typename TQuadEdge > virtual void itk::QuadEdgeMeshBaseIterator< TQuadEdge >::GoToNext () inline protected virtual
Method that should do all the iteration work.
Definition at line 168 of file itkQuadEdgeMeshBaseIterator.h.
References itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorDnext, itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorDprev, itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorInvDnext, itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorInvLnext, itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorInvOnext, itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorInvRnext, itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorLnext, itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorLprev, itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorOnext, itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorOprev, itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorRnext, itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorRprev, and itk::QuadEdgeMeshBaseIterator< TQuadEdge >::OperatorSym.
Referenced by itk::QuadEdgeMeshBaseIterator< TQuadEdge >::operator++().
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION()
template<typename TQuadEdge > itk::QuadEdgeMeshBaseIterator< TQuadEdge >::ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
operator++() [1/2]
template<typename TQuadEdge > Self & itk::QuadEdgeMeshBaseIterator< TQuadEdge >::operator++ () inline
Definition at line 143 of file itkQuadEdgeMeshBaseIterator.h.
References itk::QuadEdgeMeshBaseIterator< TQuadEdge >::GoToNext().
operator++() [2/2]
template<typename TQuadEdge > Self & itk::QuadEdgeMeshBaseIterator< TQuadEdge >::operator++ (int) inline
Definition at line 155 of file itkQuadEdgeMeshBaseIterator.h.
References itk::QuadEdgeMeshBaseIterator< TQuadEdge >::GoToNext().
operator=()
template<typename TQuadEdge > Self & itk::QuadEdgeMeshBaseIterator< TQuadEdge >::operator= (const Self & r) inline
Definition at line 99 of file itkQuadEdgeMeshBaseIterator.h.
operator==()
template<typename TQuadEdge > bool itk::QuadEdgeMeshBaseIterator< TQuadEdge >::operator== (const Self & r) const inline
Iteration methods.
Definition at line 134 of file itkQuadEdgeMeshBaseIterator.h.
The documentation for this class was generated from the following file:
itkQuadEdgeMeshBaseIterator.h