ITK: itk::PhasedArray3DSpecialCoordinatesImage< TPixel > Class Template Reference
itk::PhasedArray3DSpecialCoordinatesImage< TPixel > Class Template Reference
Data Representation Objects » Image Representation Objects | Group Core » Module ITKCommon
#include <itkPhasedArray3DSpecialCoordinatesImage.h>
Detailed Description
template<typename TPixel>
class itk::PhasedArray3DSpecialCoordinatesImage< TPixel >
Templated 3D nonrectilinear-coordinate image class for phased-array "range" images.
*
* y-axis <--------------------+
*                             |\
*                          /  | \
*                          `~-|  \
*                       /     |   \
*                        ele- |    \
*                    / vation |     \
* projection                  |      v x-axis
* to y-z plane -> o           |
*                             v z-axis
*
*
In a phased array "range" image, a point in space is represented by the angle between its projection onto the x-z plane and the z-axis (the azimuth coordinate), the angle between its projection onto the y-z plane and the z-axis (the elevation coordinate), and by its distance from the origin (the radius). See the diagram above, which illustrates elevation.
The equations form performing the conversion from Cartesian coordinates to 3D phased array coordinates are as follows:
azimuth = arctan(x/y) elevation = arctan(y/z) radius = std::sqrt(x^2 + y^2 + z^2)
The reversed transforms are:
z = radius / std::sqrt(1 + (tan(azimuth))^2 + (tan(elevation))^2); x = z * std::tan(azimuth) y = z * std::tan(elevation)
PhasedArray3DSpecialCoordinatesImages are templated over a pixel type and follow the SpecialCoordinatesImage interface. The data in an image is arranged in a 1D array as [radius-index][elevation-index][azimuth-index] with azimuth-index varying most rapidly. The Index type reverses the order so that Index[0] = azimuth-index, Index[1] = elevation-index, and Index[2] = radius-index.
Azimuth is discretized into m_AzimuthAngularSeparation intervals per angular voxel, the most negative azimuth interval containing data is then mapped to azimuth-index=0, and the largest azimuth interval containing data is then mapped to azimuth-index=(number of samples along azimuth axis - 1). Elevation is discretized in the same manner. This way, the mapping to Cartesian space is symmetric about the z axis such that the line defined by azimuth/2,elevation/2 = z-axis. Radius is discretized into m_RadiusSampleSize units per angular voxel. The smallest range interval containing data is then mapped to radius-index=0, such that radius = m_FirstSampleDistance + (radius-index * m_RadiusSampleSize).
See also
SpecialCoordinatesImage
Definition at line 95 of file itkPhasedArray3DSpecialCoordinatesImage.h.
Public Types
using AccessorFunctorType = DefaultPixelAccessorFunctor< Self >
using AccessorType = DefaultPixelAccessor< PixelType >
using ConstPointer = SmartPointer< const Self >
using ConstWeakPointer = WeakPointer< const Self >
using InternalPixelType = TPixel
using NeighborhoodAccessorFunctorType = NeighborhoodAccessorFunctor< Self >
using PixelContainer = ImportImageContainer< SizeValueType, PixelType >
using PixelContainerConstPointer = typename PixelContainer::ConstPointer
using PixelContainerPointer = typename PixelContainer::Pointer
using PixelType = TPixel
using Pointer = SmartPointer< Self >
using Self = PhasedArray3DSpecialCoordinatesImage
using Superclass = SpecialCoordinatesImage< TPixel, 3 >
using ValueType = TPixel
Public Types inherited from itk::SpecialCoordinatesImage< TPixel, 3 >
using AccessorFunctorType = DefaultPixelAccessorFunctor< Self >
using AccessorType = DefaultPixelAccessor< PixelType >
using ConstPointer = SmartPointer< const Self >
using ConstWeakPointer = WeakPointer< const Self >
using InternalPixelType = TPixel
using IOPixelType = PixelType
using PixelContainer = ImportImageContainer< SizeValueType, PixelType >
using PixelContainerConstPointer = typename PixelContainer::ConstPointer
using PixelContainerPointer = typename PixelContainer::Pointer
using PixelType = TPixel
using Pointer = SmartPointer< Self >
using Self = SpecialCoordinatesImage
using Superclass = ImageBase< VImageDimension >
using ValueType = TPixel
Public Types inherited from itk::ImageBase< VImageDimension >
using ConstPointer = SmartPointer< const Self >
using DirectionType = Matrix< SpacePrecisionType, VImageDimension, VImageDimension >
using ImageDimensionType = unsigned int
using IndexType = Index< VImageDimension >
using IndexValueType = typename IndexType::IndexValueType
using OffsetType = Offset< VImageDimension >
using OffsetValueType = typename OffsetType::OffsetValueType
using Pointer = SmartPointer< Self >
using PointType = Point< PointValueType, VImageDimension >
using PointValueType = SpacePrecisionType
using RegionType = ImageRegion< VImageDimension >
using Self = ImageBase
using SizeType = Size< VImageDimension >
using SizeValueType = typename SizeType::SizeValueType
using SpacingType = Vector< SpacingValueType, VImageDimension >
using SpacingValueType = SpacePrecisionType
using Superclass = DataObject
Public Types inherited from itk::DataObject
using ConstPointer = SmartPointer< const Self >
using DataObjectIdentifierType = std::string
using DataObjectPointerArraySizeType = std::vector< Pointer >::size_type
using Pointer = SmartPointer< Self >
using Self = DataObject
using Superclass = Object
Public Types inherited from itk::Object
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = Object
using Superclass = LightObject
Public Types inherited from itk::LightObject
using ConstPointer = SmartPointer< const Self >
using Pointer = SmartPointer< Self >
using Self = LightObject
Public Member Functions
NeighborhoodAccessorFunctorType GetNeighborhoodAccessor ()
const NeighborhoodAccessorFunctorType GetNeighborhoodAccessor () const
AccessorType GetPixelAccessor ()
const AccessorType GetPixelAccessor () const
itkOverrideGetNameOfClassMacro (PhasedArray3DSpecialCoordinatesImage)
virtual void SetAzimuthAngularSeparation (double _arg)
virtual void SetElevationAngularSeparation (double _arg)
virtual void SetFirstSampleDistance (double _arg)
virtual void SetRadiusSampleSize (double _arg)
template<typename TCoordRep >
void TransformLocalVectorToPhysicalVector (FixedArray< TCoordRep, 3 > &) const
template<typename TCoordRep , typename TIndexRep >
bool TransformPhysicalPointToContinuousIndex (const Point< TCoordRep, 3 > &point, ContinuousIndex< TIndexRep, 3 > &index) const
template<typename TCoordRep >
bool TransformPhysicalPointToIndex (const Point< TCoordRep, 3 > &point, IndexType &index) const
template<typename TCoordRep >
void TransformPhysicalVectorToLocalVector (const FixedArray< TCoordRep, 3 > &, FixedArray< TCoordRep, 3 > &) const
template<typename TIndexRep , typename TCoordRep >
ContinuousIndex< TIndexRep, 3 > TransformPhysicalPointToContinuousIndex (const Point< TCoordRep, 3 > &point) const
template<typename TCoordRep >
IndexType TransformPhysicalPointToIndex (const Point< TCoordRep, 3 > &point) const
template<typename TCoordRep , typename TIndexRep >
void TransformContinuousIndexToPhysicalPoint (const ContinuousIndex< TIndexRep, 3 > &index, Point< TCoordRep, 3 > &point) const
template<typename TCoordRep , typename TIndexRep >
Point< TCoordRep, 3 > TransformContinuousIndexToPhysicalPoint (const ContinuousIndex< TIndexRep, 3 > &index) const
template<typename TCoordRep >
void TransformIndexToPhysicalPoint (const IndexType &index, Point< TCoordRep, 3 > &point) const
template<typename TCoordRep >
Point< TCoordRep, 3 > TransformIndexToPhysicalPoint (const IndexType &index) const
Public Member Functions inherited from itk::SpecialCoordinatesImage< TPixel, 3 >
void Allocate (bool initialize=false) override
void FillBuffer (const TPixel &value)
TPixel & GetPixel (const IndexType &index)
const TPixel & GetPixel (const IndexType &index) const
AccessorType GetPixelAccessor ()
const AccessorType GetPixelAccessor () const
PixelContainer * GetPixelContainer ()
const PixelContainer * GetPixelContainer () const
void Initialize () override
itkOverrideGetNameOfClassMacro (SpecialCoordinatesImage)
TPixel & operator[] (const IndexType &index)
const TPixel & operator[] (const IndexType &index) const
void SetPixel (const IndexType &index, const TPixel &value)
void SetPixelContainer (PixelContainer *container)
TPixel * GetBufferPointer ()
const TPixel * GetBufferPointer () const
void SetSpacing (const SpacingType &) override
void SetSpacing (const double[VImageDimension]) override
void SetSpacing (const float[VImageDimension]) override
void SetOrigin (const PointType) override
void SetOrigin (const double[VImageDimension]) override
void SetOrigin (const float[VImageDimension]) override
Public Member Functions inherited from itk::ImageBase< VImageDimension >
virtual void Allocate (bool initialize=false)
void AllocateInitialized ()
OffsetValueType ComputeOffset (const IndexType &ind) const
void CopyInformation (const DataObject *data) override
virtual const RegionType & GetBufferedRegion () const
virtual const DirectionType & GetDirection () const
virtual const DirectionType & GetInverseDirection () const
virtual const RegionType & GetLargestPossibleRegion () const
virtual const PointType & GetOrigin () const
virtual const RegionType & GetRequestedRegion () const
virtual const SpacingType & GetSpacing () const
virtual void Graft (const Self *image)
void Initialize () override
bool IsCongruentImageGeometry (const ImageBase *otherImage, double coordinateTolerance, double directionTolerance) const
bool IsSameImageGeometryAs (const ImageBase *otherImage, double coordinateTolerance=1e-6, double directionTolerance=1e-6) const
itkOverrideGetNameOfClassMacro (ImageBase)
bool RequestedRegionIsOutsideOfTheBufferedRegion () override
virtual void SetBufferedRegion (const RegionType &region)
virtual void SetDirection (const DirectionType &direction)
virtual void SetLargestPossibleRegion (const RegionType &region)
virtual void SetRegions (const SizeType &size)
void SetRequestedRegion (const DataObject *data) override
virtual void SetRequestedRegion (const RegionType &region)
void SetRequestedRegionToLargestPossibleRegion () override
void TransformLocalVectorToPhysicalVector (const FixedArray< TCoordRep, VImageDimension > &inputGradient, FixedArray< TCoordRep, VImageDimension > &outputGradient) const
ContinuousIndex< TIndexRep, VImageDimension > TransformPhysicalPointToContinuousIndex (const Point< TCoordRep, VImageDimension > &point) const
bool TransformPhysicalPointToContinuousIndex (const Point< TCoordRep, VImageDimension > &point, ContinuousIndex< TIndexRep, VImageDimension > &index) const
bool TransformPhysicalPointToIndex (const Point< TCoordRep, VImageDimension > &point, IndexType &index) const
void TransformPhysicalVectorToLocalVector (const FixedArray< TCoordRep, VImageDimension > &inputGradient, FixedArray< TCoordRep, VImageDimension > &outputGradient) const
void UpdateOutputData () override
void UpdateOutputInformation () override
bool VerifyRequestedRegion () override
virtual void SetRegions (const RegionType &region)
const OffsetValueType * GetOffsetTable () const
IndexType ComputeIndex (OffsetValueType offset) const
IndexType TransformPhysicalPointToIndex (const Point< TCoordRep, VImageDimension > &point) const
void TransformContinuousIndexToPhysicalPoint (const ContinuousIndex< TIndexRep, VImageDimension > &index, Point< TCoordRep, VImageDimension > &point) const
Point< TCoordRep, VImageDimension > TransformContinuousIndexToPhysicalPoint (const ContinuousIndex< TIndexRep, VImageDimension > &index) const
void TransformIndexToPhysicalPoint (const IndexType &index, Point< TCoordRep, VImageDimension > &point) const
Point< TCoordRep, VImageDimension > TransformIndexToPhysicalPoint (const IndexType &index) const
TVector TransformLocalVectorToPhysicalVector (const TVector &inputGradient) const
TVector TransformPhysicalVectorToLocalVector (const TVector &inputGradient) const
virtual unsigned int GetNumberOfComponentsPerPixel () const
virtual void SetNumberOfComponentsPerPixel (unsigned int)
Public Member Functions inherited from itk::DataObject
virtual void CopyInformation (const DataObject *)
virtual void DataHasBeenGenerated ()
void DisconnectPipeline ()
bool GetDataReleased () const
virtual const bool & GetReleaseDataFlag () const
SmartPointer< ProcessObject > GetSource () const
DataObjectPointerArraySizeType GetSourceOutputIndex () const
const DataObjectIdentifierType & GetSourceOutputName () const
virtual ModifiedTimeType GetUpdateMTime () const
virtual void Graft (const DataObject *)
virtual void Initialize ()
itkOverrideGetNameOfClassMacro (DataObject)
virtual void PrepareForNewData ()
virtual void PropagateRequestedRegion ()
void ReleaseData ()
virtual void ReleaseDataFlagOn ()
virtual bool RequestedRegionIsOutsideOfTheBufferedRegion ()
virtual void ResetPipeline ()
void SetReleaseDataFlag (bool flag)
virtual void SetRequestedRegion (const DataObject *)
virtual void SetRequestedRegionToLargestPossibleRegion ()
bool ShouldIReleaseData () const
virtual void Update ()
virtual void UpdateOutputData ()
virtual void UpdateOutputInformation ()
void UpdateSource () const
virtual bool VerifyRequestedRegion ()
void SetPipelineMTime (ModifiedTimeType time)
virtual const ModifiedTimeType & GetPipelineMTime () const
virtual void SetRealTimeStamp (RealTimeStamp _arg)
virtual const RealTimeStamp & GetRealTimeStamp () const
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *)
unsigned long AddObserver (const EventObject &event, Command *) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
itkOverrideGetNameOfClassMacro (Object)
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag)
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void UnRegister () const noexcept override
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual const std::string & GetObjectName () const
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual Pointer CreateAnother () const
virtual void Delete ()
virtual int GetReferenceCount () const
itkVirtualGetNameOfClassMacro (LightObject)
void Print (std::ostream &os, Indent indent=0) const
virtual void Register () const
virtual void SetReferenceCount (int)
virtual void UnRegister () const noexcept
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from itk::SpecialCoordinatesImage< TPixel, 3 >
static Pointer New ()
Static Public Member Functions inherited from itk::ImageBase< VImageDimension >
static unsigned int GetImageDimension ()
static Pointer New ()
Static Public Member Functions inherited from itk::DataObject
static bool GetGlobalReleaseDataFlag ()
static void GlobalReleaseDataFlagOff ()
static void GlobalReleaseDataFlagOn ()
static Pointer New ()
static void SetGlobalReleaseDataFlag (bool val)
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Static Public Attributes
static constexpr unsigned int ImageDimension = 3
Static Public Attributes inherited from itk::SpecialCoordinatesImage< TPixel, 3 >
static constexpr unsigned int ImageDimension
Static Public Attributes inherited from itk::ImageBase< VImageDimension >
static constexpr ImageDimensionType ImageDimension
Protected Member Functions
PhasedArray3DSpecialCoordinatesImage ()
void PrintSelf (std::ostream &os, Indent indent) const override
~PhasedArray3DSpecialCoordinatesImage () override=default
Protected Member Functions inherited from itk::SpecialCoordinatesImage< TPixel, 3 >
void PrintSelf (std::ostream &os, Indent indent) const override
SpecialCoordinatesImage ()=default
~SpecialCoordinatesImage () override=default
Protected Member Functions inherited from itk::ImageBase< VImageDimension >
virtual void ComputeIndexToPhysicalPointMatrices ()
void ComputeOffsetTable ()
void Graft (const DataObject *data) override
ImageBase ()=default
virtual void InitializeBufferedRegion ()
void PrintSelf (std::ostream &os, Indent indent) const override
~ImageBase () override=default
OffsetValueType FastComputeOffset (const IndexType &ind) const
IndexType FastComputeIndex (OffsetValueType offset) const
Protected Member Functions inherited from itk::DataObject
DataObject ()
void PrintSelf (std::ostream &os, Indent indent) const override
virtual void PropagateResetPipeline ()
~DataObject () override
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
void PrintSelf (std::ostream &os, Indent indent) const override
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintSelf (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Private Attributes
double m_AzimuthAngularSeparation {}
double m_ElevationAngularSeparation {}
double m_FirstSampleDistance {}
double m_RadiusSampleSize {}
Additional Inherited Members
Protected Attributes inherited from itk::ImageBase< VImageDimension >
SpacingType m_Spacing
PointType m_Origin
DirectionType m_Direction
DirectionType m_InverseDirection
DirectionType m_IndexToPhysicalPoint
DirectionType m_PhysicalPointToIndex
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount {}
Member Typedef Documentation
AccessorFunctorType
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::AccessorFunctorType = DefaultPixelAccessorFunctor<Self>
Accessor functor to choose between accessors: DefaultPixelAccessor for the Image, and DefaultVectorPixelAccessor for the vector image. The functor provides a generic API between the two accessors.
Definition at line 135 of file itkPhasedArray3DSpecialCoordinatesImage.h.
AccessorType
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::AccessorType = DefaultPixelAccessor<PixelType>
Accessor type that convert data between internal and external representations.
Definition at line 130 of file itkPhasedArray3DSpecialCoordinatesImage.h.
ConstPointer
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::ConstPointer = SmartPointer<const Self>
Definition at line 104 of file itkPhasedArray3DSpecialCoordinatesImage.h.
ConstWeakPointer
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::ConstWeakPointer = WeakPointer<const Self>
Definition at line 105 of file itkPhasedArray3DSpecialCoordinatesImage.h.
InternalPixelType
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::InternalPixelType = TPixel
Internal Pixel representation. Used to maintain a uniform API with Image Adaptors and allow to keep a particular internal representation of data while showing a different external representation.
Definition at line 124 of file itkPhasedArray3DSpecialCoordinatesImage.h.
NeighborhoodAccessorFunctorType
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::NeighborhoodAccessorFunctorType = NeighborhoodAccessorFunctor<Self>
Typedef for the functor used to access a neighborhood of pixel pointers.
Definition at line 139 of file itkPhasedArray3DSpecialCoordinatesImage.h.
PixelContainer
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::PixelContainer = ImportImageContainer<SizeValueType, PixelType>
Container used to store pixels in the image.
Definition at line 159 of file itkPhasedArray3DSpecialCoordinatesImage.h.
PixelContainerConstPointer
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::PixelContainerConstPointer = typename PixelContainer::ConstPointer
Definition at line 182 of file itkPhasedArray3DSpecialCoordinatesImage.h.
PixelContainerPointer
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::PixelContainerPointer = typename PixelContainer::Pointer
A pointer to the pixel container.
Definition at line 181 of file itkPhasedArray3DSpecialCoordinatesImage.h.
PixelType
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::PixelType = TPixel
Pixel type alias support Used to declare pixel type in filters or other operations.
Definition at line 115 of file itkPhasedArray3DSpecialCoordinatesImage.h.
Pointer
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::Pointer = SmartPointer<Self>
Definition at line 103 of file itkPhasedArray3DSpecialCoordinatesImage.h.
Self
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::Self = PhasedArray3DSpecialCoordinatesImage
Standard class type aliases
Definition at line 101 of file itkPhasedArray3DSpecialCoordinatesImage.h.
Superclass
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::Superclass = SpecialCoordinatesImage<TPixel, 3>
Definition at line 102 of file itkPhasedArray3DSpecialCoordinatesImage.h.
ValueType
template<typename TPixel > using itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::ValueType = TPixel
Typedef alias for PixelType
Definition at line 118 of file itkPhasedArray3DSpecialCoordinatesImage.h.
Constructor & Destructor Documentation
PhasedArray3DSpecialCoordinatesImage()
template<typename TPixel > itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::PhasedArray3DSpecialCoordinatesImage () inline protected
Definition at line 413 of file itkPhasedArray3DSpecialCoordinatesImage.h.
References itk::Math::pi.
~PhasedArray3DSpecialCoordinatesImage()
template<typename TPixel > itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::~PhasedArray3DSpecialCoordinatesImage () override protected default
Member Function Documentation
GetNeighborhoodAccessor() [1/2]
template<typename TPixel > NeighborhoodAccessorFunctorType itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::GetNeighborhoodAccessor () inline
Return the NeighborhoodAccessor functor
Definition at line 400 of file itkPhasedArray3DSpecialCoordinatesImage.h.
GetNeighborhoodAccessor() [2/2]
template<typename TPixel > const NeighborhoodAccessorFunctorType itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::GetNeighborhoodAccessor () const inline
Return the NeighborhoodAccessor functor
Definition at line 407 of file itkPhasedArray3DSpecialCoordinatesImage.h.
GetPixelAccessor() [1/2]
template<typename TPixel > AccessorType itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::GetPixelAccessor () inline
Return the Pixel Accessor object
Definition at line 386 of file itkPhasedArray3DSpecialCoordinatesImage.h.
GetPixelAccessor() [2/2]
template<typename TPixel > const AccessorType itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::GetPixelAccessor () const inline
Return the Pixel Accesor object
Definition at line 393 of file itkPhasedArray3DSpecialCoordinatesImage.h.
itkOverrideGetNameOfClassMacro()
template<typename TPixel > itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::itkOverrideGetNameOfClassMacro (PhasedArray3DSpecialCoordinatesImage< TPixel >)
Run-time type information (and related methods).
New()
template<typename TPixel > static Pointer itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::New () static
Method for creation through the object factory.
PrintSelf()
template<typename TPixel > void itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Reimplemented from itk::DataObject.
SetAzimuthAngularSeparation()
template<typename TPixel > virtual void itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::SetAzimuthAngularSeparation (double _arg) virtual
Set the number of radians between each azimuth unit.
SetElevationAngularSeparation()
template<typename TPixel > virtual void itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::SetElevationAngularSeparation (double _arg) virtual
Set the number of radians between each elevation unit.
SetFirstSampleDistance()
template<typename TPixel > virtual void itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::SetFirstSampleDistance (double _arg) virtual
Set the distance to add to the radius.
SetRadiusSampleSize()
template<typename TPixel > virtual void itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::SetRadiusSampleSize (double _arg) virtual
Set the number of cartesian units between each unit along the R .
TransformContinuousIndexToPhysicalPoint() [1/2]
template<typename TPixel > template<typename TCoordRep , typename TIndexRep > Point< TCoordRep, 3 > itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformContinuousIndexToPhysicalPoint (const ContinuousIndex< TIndexRep, 3 > & index) const inline
Returns a physical point from a continuous index.
Definition at line 315 of file itkPhasedArray3DSpecialCoordinatesImage.h.
References itk::point().
TransformContinuousIndexToPhysicalPoint() [2/2]
template<typename TPixel > template<typename TCoordRep , typename TIndexRep > void itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformContinuousIndexToPhysicalPoint (const ContinuousIndex< TIndexRep, 3 > & index, Point< TCoordRep, 3 > & point) const inline
Get a physical point (in the space which the origin and spacing information comes from) from a continuous index (in the index space)
See also
Transform
Definition at line 289 of file itkPhasedArray3DSpecialCoordinatesImage.h.
References itk::ImageRegion< VImageDimension >::GetSize(), and itk::point().
TransformIndexToPhysicalPoint() [1/2]
template<typename TPixel > template<typename TCoordRep > Point< TCoordRep, 3 > itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformIndexToPhysicalPoint (const IndexType & index) const inline
Returns a physical point from a discrete index.
Definition at line 355 of file itkPhasedArray3DSpecialCoordinatesImage.h.
References itk::point().
TransformIndexToPhysicalPoint() [2/2]
template<typename TPixel > template<typename TCoordRep > void itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformIndexToPhysicalPoint (const IndexType & index, Point< TCoordRep, 3 > & point) const inline
Get a physical point (in the space which the origin and spacing information comes from) from a discrete index (in the index space)
See also
Transform
Definition at line 330 of file itkPhasedArray3DSpecialCoordinatesImage.h.
References itk::ImageRegion< VImageDimension >::GetSize(), and itk::point().
TransformLocalVectorToPhysicalVector()
template<typename TPixel > template<typename TCoordRep > void itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformLocalVectorToPhysicalVector (FixedArray< TCoordRep, 3 > &) const inline
Definition at line 376 of file itkPhasedArray3DSpecialCoordinatesImage.h.
TransformPhysicalPointToContinuousIndex() [1/2]
template<typename TPixel > template<typename TIndexRep , typename TCoordRep > ContinuousIndex< TIndexRep, 3 > itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformPhysicalPointToContinuousIndex (const Point< TCoordRep, 3 > & point) const inline
Returns the continuous index from a physical point
Definition at line 187 of file itkPhasedArray3DSpecialCoordinatesImage.h.
References itk::ImageRegion< VImageDimension >::GetSize(), itk::Math::pi_over_2, and itk::point().
TransformPhysicalPointToContinuousIndex() [2/2]
template<typename TPixel > template<typename TCoordRep , typename TIndexRep > bool itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformPhysicalPointToContinuousIndex (const Point< TCoordRep, 3 > & point, ContinuousIndex< TIndexRep, 3 > & index) const inline
Get the continuous index from a physical point.
Returns true if the resulting index is within the image, false otherwise.
Note
For performance reasons, if you do not need to use the bool return value, please call the corresponding overload instead, which has only one parameter (the point), and returns the continuous index.
See also
Transform
Definition at line 222 of file itkPhasedArray3DSpecialCoordinatesImage.h.
References itk::point().
TransformPhysicalPointToIndex() [1/2]
template<typename TPixel > template<typename TCoordRep > IndexType itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformPhysicalPointToIndex (const Point< TCoordRep, 3 > & point) const inline
Returns the index (discrete) from a physical point. Floating point index results are truncated to integers.
Definition at line 238 of file itkPhasedArray3DSpecialCoordinatesImage.h.
References itk::ImageRegion< VImageDimension >::GetSize(), itk::Math::pi_over_2, and itk::point().
TransformPhysicalPointToIndex() [2/2]
template<typename TPixel > template<typename TCoordRep > bool itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformPhysicalPointToIndex (const Point< TCoordRep, 3 > & point, IndexType & index) const inline
Get the index (discrete) from a physical point. Floating point index results are truncated to integers. Returns true if the resulting index is within the image, false otherwise
Note
For performance reasons, if you do not need to use the bool return value, please call the corresponding overload instead, which has only one parameter (the point), and returns the index.
See also
Transform
Definition at line 273 of file itkPhasedArray3DSpecialCoordinatesImage.h.
References itk::point().
TransformPhysicalVectorToLocalVector()
template<typename TPixel > template<typename TCoordRep > void itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformPhysicalVectorToLocalVector (const FixedArray< TCoordRep, 3 > & , FixedArray< TCoordRep, 3 > &) const inline
Definition at line 381 of file itkPhasedArray3DSpecialCoordinatesImage.h.
Member Data Documentation
ImageDimension
template<typename TPixel > constexpr unsigned int itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::ImageDimension = 3 static constexpr
Dimension of the image. This constant is used by functions that are templated over image type (as opposed to being templated over pixel type and dimension) when they need compile time access to the dimension of the image.
Definition at line 145 of file itkPhasedArray3DSpecialCoordinatesImage.h.
m_AzimuthAngularSeparation
template<typename TPixel > double itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::m_AzimuthAngularSeparation {} private
Definition at line 428 of file itkPhasedArray3DSpecialCoordinatesImage.h.
m_ElevationAngularSeparation
template<typename TPixel > double itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::m_ElevationAngularSeparation {} private
Definition at line 429 of file itkPhasedArray3DSpecialCoordinatesImage.h.
m_FirstSampleDistance
template<typename TPixel > double itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::m_FirstSampleDistance {} private
Definition at line 431 of file itkPhasedArray3DSpecialCoordinatesImage.h.
m_RadiusSampleSize
template<typename TPixel > double itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::m_RadiusSampleSize {} private
Definition at line 430 of file itkPhasedArray3DSpecialCoordinatesImage.h.
The documentation for this class was generated from the following file:
itkPhasedArray3DSpecialCoordinatesImage.h