ITK: itk::ImageIORegionAdaptor< VDimension > Class Template Reference
itk::ImageIORegionAdaptor< VDimension > Class Template Reference
Group Core » Module ITKCommon
#include <itkImageIORegion.h>
Detailed Description
template<unsigned int VDimension>
class itk::ImageIORegionAdaptor< VDimension >
Helper class for converting ImageRegions into ImageIORegions and back.
Definition at line 202 of file itkImageIORegion.h.
Public Types
using ImageIndexType = typename ImageRegionType::IndexType
using ImageIORegionType = ImageIORegion
using ImageRegionType = ImageRegion< VDimension >
using ImageSizeType = typename ImageRegionType::SizeType
Static Public Member Functions
static void Convert (const ImageIORegionType &inIORegion, ImageRegionType &outImageRegion, const ImageIndexType &largestRegionIndex)
static void Convert (const ImageRegionType &inImageRegion, ImageIORegionType &outIORegion, const ImageIndexType &largestRegionIndex)
Member Typedef Documentation
ImageIndexType
template<unsigned int VDimension> using itk::ImageIORegionAdaptor< VDimension >::ImageIndexType = typename ImageRegionType::IndexType
Definition at line 209 of file itkImageIORegion.h.
ImageIORegionType
template<unsigned int VDimension> using itk::ImageIORegionAdaptor< VDimension >::ImageIORegionType = ImageIORegion
Definition at line 206 of file itkImageIORegion.h.
ImageRegionType
template<unsigned int VDimension> using itk::ImageIORegionAdaptor< VDimension >::ImageRegionType = ImageRegion<VDimension>
Definition at line 205 of file itkImageIORegion.h.
ImageSizeType
template<unsigned int VDimension> using itk::ImageIORegionAdaptor< VDimension >::ImageSizeType = typename ImageRegionType::SizeType
Definition at line 208 of file itkImageIORegion.h.
Member Function Documentation
Convert() [1/2]
template<unsigned int VDimension> static void itk::ImageIORegionAdaptor< VDimension >::Convert (const ImageIORegionType & inIORegion, ImageRegionType & outImageRegion, const ImageIndexType & largestRegionIndex) inline static
Definition at line 252 of file itkImageIORegion.h.
References itk::ImageIORegion::GetImageDimension(), itk::ImageIORegion::GetIndex(), itk::ImageIORegion::GetSize(), itk::ImageRegion< VImageDimension >::SetIndex(), and itk::ImageRegion< VImageDimension >::SetSize().
Convert() [2/2]
template<unsigned int VDimension> static void itk::ImageIORegionAdaptor< VDimension >::Convert (const ImageRegionType & inImageRegion, ImageIORegionType & outIORegion, const ImageIndexType & largestRegionIndex) inline static
Definition at line 212 of file itkImageIORegion.h.
References itk::ImageIORegion::GetImageDimension(), itk::ImageRegion< VImageDimension >::GetIndex(), itk::ImageRegion< VImageDimension >::GetSize(), itk::ImageIORegion::SetIndex(), and itk::ImageIORegion::SetSize().
The documentation for this class was generated from the following file:
itkImageIORegion.h