ITK: itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix > Class Template Reference
itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix > Class Template Reference
#include <itkSymmetricEigenAnalysis.h>
Public Types
using EigenMatrixType = TEigenMatrix
using MatrixType = TMatrix
using VectorType = TVector
Public Member Functions
unsigned int ComputeEigenValues (const TMatrix &A, TVector &EigenValues) const
unsigned int ComputeEigenValuesAndVectors (const TMatrix &A, TVector &EigenValues, TEigenMatrix &EigenVectors) const
constexpr unsigned int GetDimension () const
constexpr unsigned int GetOrder () const
bool GetOrderEigenMagnitudes () const
bool GetOrderEigenValues () const
constexpr bool GetUseEigenLibrary () const
void SetOrderEigenMagnitudes (const bool b)
void SetOrderEigenValues (const bool b)
SymmetricEigenAnalysisFixedDimension ()=default
~SymmetricEigenAnalysisFixedDimension ()=default
Private Member Functions
template<typename QMatrix >
auto ComputeEigenValuesAndVectorsWithEigenLibraryImpl (const QMatrix &A, TVector &EigenValues, TEigenMatrix &EigenVectors, bool) const -> decltype(GetPointerToMatrixData(A), static_cast< unsigned int >(1))
template<typename QMatrix >
auto ComputeEigenValuesAndVectorsWithEigenLibraryImpl (const QMatrix &A, TVector &EigenValues, TEigenMatrix &EigenVectors, long) const -> decltype(static_cast< unsigned int >(1))
template<typename QMatrix >
auto ComputeEigenValuesWithEigenLibraryImpl (const QMatrix &A, TVector &EigenValues, bool) const -> decltype(GetPointerToMatrixData(A), static_cast< unsigned int >(1))
template<typename QMatrix >
auto ComputeEigenValuesWithEigenLibraryImpl (const QMatrix &A, TVector &EigenValues, long) const -> decltype(static_cast< unsigned int >(1))
template<typename QMatrix = TMatrix>
auto GetMatrixValueType (bool) const -> typename QMatrix::element_type
template<typename QMatrix = TMatrix>
auto GetMatrixValueType (bool) const -> typename QMatrix::ValueType
Private Attributes
EigenValueOrderEnum m_OrderEigenValues { EigenValueOrderEnum::OrderByValue }
Detailed Description
template<unsigned int VDimension, typename TMatrix, typename TVector, typename TEigenMatrix = TMatrix>
class itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >
Definition at line 760 of file itkSymmetricEigenAnalysis.h.
Member Typedef Documentation
EigenMatrixType
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> using itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::EigenMatrixType = TEigenMatrix
Definition at line 779 of file itkSymmetricEigenAnalysis.h.
MatrixType
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> using itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::MatrixType = TMatrix
Definition at line 778 of file itkSymmetricEigenAnalysis.h.
VectorType
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> using itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::VectorType = TVector
Definition at line 780 of file itkSymmetricEigenAnalysis.h.
Constructor & Destructor Documentation
SymmetricEigenAnalysisFixedDimension()
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::SymmetricEigenAnalysisFixedDimension () default
~SymmetricEigenAnalysisFixedDimension()
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::~SymmetricEigenAnalysisFixedDimension () default
Member Function Documentation
ComputeEigenValues()
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::ComputeEigenValues (const TMatrix & A, TVector & EigenValues) const inline
Compute Eigen values of A A is any type that overloads the [][] operator and contains the symmetric matrix. In practice only the upper triangle of the matrix will be accessed. (Both itk::Matrix and vnl_matrix overload [][] operator.)
'EigenValues' is any type that overloads the [] operator and will contain the eigen values.
No size checking is performed. A is expected to be a square matrix of size VDimension. 'EigenValues' is expected to be of length VDimension. The matrix is not checked to see if it is symmetric.
Definition at line 796 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::Functor::SymmetricEigenAnalysisFixedDimensionFunction< TMatrixDimension, TInputImage::PixelType, TInputImage ::PixelType >::operator()().
ComputeEigenValuesAndVectors()
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> unsigned int itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectors (const TMatrix & A, TVector & EigenValues, TEigenMatrix & EigenVectors) const inline
Compute Eigen values and vectors of A A is any type that overloads the [][] operator and contains the symmetric matrix. In practice only the upper triangle of the matrix will be accessed. (Both itk::Matrix and vnl_matrix overload [][] operator.)
'EigenValues' is any type that overloads the [] operator and will contain the eigen values.
'EigenVectors' is any type that provides access to its elements with the [][] operator. It is expected be of size VDimension * VDimension.
No size checking is performed. A is expected to be a square matrix of size VDimension. 'EigenValues' is expected to be of length VDimension. The matrix is not checked to see if it is symmetric.
Each row of the matrix 'EigenVectors' represents an eigen vector. (unlike MATLAB where the columns of the [EigenVectors, EigenValues] = eig(A) contains the eigenvectors).
Definition at line 822 of file itkSymmetricEigenAnalysis.h.
ComputeEigenValuesAndVectorsWithEigenLibraryImpl() [1/2]
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix > auto itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsWithEigenLibraryImpl (const QMatrix & A, TVector & EigenValues, TEigenMatrix & EigenVectors, bool) const -> decltype(GetPointerToMatrixData(A), static_cast<unsigned int>(1)) inline private
Definition at line 912 of file itkSymmetricEigenAnalysis.h.
ComputeEigenValuesAndVectorsWithEigenLibraryImpl() [2/2]
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix > auto itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsWithEigenLibraryImpl (const QMatrix & A, TVector & EigenValues, TEigenMatrix & EigenVectors, long) const -> decltype(static_cast<unsigned int>(1)) inline private
Definition at line 970 of file itkSymmetricEigenAnalysis.h.
ComputeEigenValuesWithEigenLibraryImpl() [1/2]
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix > auto itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesWithEigenLibraryImpl (const QMatrix & A, TVector & EigenValues, bool) const -> decltype(GetPointerToMatrixData(A), static_cast<unsigned int>(1)) inline private
Definition at line 1072 of file itkSymmetricEigenAnalysis.h.
ComputeEigenValuesWithEigenLibraryImpl() [2/2]
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix > auto itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesWithEigenLibraryImpl (const QMatrix & A, TVector & EigenValues, long) const -> decltype(static_cast<unsigned int>(1)) inline private
Definition at line 1032 of file itkSymmetricEigenAnalysis.h.
GetDimension()
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> constexpr unsigned int itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetDimension () const inline constexpr
Definition at line 867 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::Functor::SymmetricEigenAnalysisFixedDimensionFunction< TMatrixDimension, TInputImage::PixelType, TInputImage ::PixelType >::GetDimension(), and itk::operator<<().
GetMatrixValueType() [1/2]
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix = TMatrix> auto itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetMatrixValueType (bool) const -> typename QMatrix::element_type inline private
Definition at line 890 of file itkSymmetricEigenAnalysis.h.
GetMatrixValueType() [2/2]
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> template<typename QMatrix = TMatrix> auto itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetMatrixValueType (bool) const -> typename QMatrix::ValueType inline private
Definition at line 896 of file itkSymmetricEigenAnalysis.h.
GetOrder()
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> constexpr unsigned int itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetOrder () const inline constexpr
Definition at line 862 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::operator<<().
GetOrderEigenMagnitudes()
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> bool itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetOrderEigenMagnitudes () const inline
Definition at line 857 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::operator<<().
GetOrderEigenValues()
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> bool itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetOrderEigenValues () const inline
Definition at line 840 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::operator<<().
GetUseEigenLibrary()
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> constexpr bool itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetUseEigenLibrary () const inline constexpr
Definition at line 872 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::operator<<().
SetOrderEigenMagnitudes()
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> void itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::SetOrderEigenMagnitudes (const bool b) inline
Definition at line 845 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::Functor::SymmetricEigenAnalysisFixedDimensionFunction< TMatrixDimension, TInputImage::PixelType, TInputImage ::PixelType >::OrderEigenValuesBy().
SetOrderEigenValues()
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> void itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::SetOrderEigenValues (const bool b) inline
Definition at line 828 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::Functor::SymmetricEigenAnalysisFixedDimensionFunction< TMatrixDimension, TInputImage::PixelType, TInputImage ::PixelType >::OrderEigenValuesBy().
Member Data Documentation
m_OrderEigenValues
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix = TMatrix> EigenValueOrderEnum itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::m_OrderEigenValues { EigenValueOrderEnum::OrderByValue } private
Definition at line 878 of file itkSymmetricEigenAnalysis.h.
The documentation for this class was generated from the following file:
itkSymmetricEigenAnalysis.h