ITK: itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge > Class Template Reference
itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge > Class Template Reference
Group Core » Module ITKQuadEdgeMesh
#include <itkQuadEdgeMeshBaseIterator.h>
Public Types
using NoConstType = QuadEdgeMeshIteratorGeom< TGeometricalQuadEdge >
using OriginRefType = typename QuadEdgeType::OriginRefType
using QuadEdgeType = TGeometricalQuadEdge
using Self = QuadEdgeMeshConstIteratorGeom
using Superclass = QuadEdgeMeshConstIterator< TGeometricalQuadEdge >
Public Types inherited from itk::QuadEdgeMeshConstIterator< TGeometricalQuadEdge >
using NoConstType = QuadEdgeMeshIterator< TGeometricalQuadEdge >
using QuadEdgeType = TGeometricalQuadEdge
using Self = QuadEdgeMeshConstIterator
using Superclass = QuadEdgeMeshBaseIterator< TGeometricalQuadEdge >
Public Types inherited from itk::QuadEdgeMeshBaseIterator< TGeometricalQuadEdge >
enum
using QuadEdgeType = TGeometricalQuadEdge
using Self = QuadEdgeMeshBaseIterator
Public Member Functions
const OriginRefType operator* () const
Self & operator= (const NoConstType &r)
QuadEdgeMeshConstIteratorGeom (const QuadEdgeMeshConstIteratorGeom &)=default
QuadEdgeMeshConstIteratorGeom (const QuadEdgeType *e=(QuadEdgeType *) 0, int op=Superclass::OperatorOnext, bool start=true)
~QuadEdgeMeshConstIteratorGeom () override=default
Public Member Functions inherited from itk::QuadEdgeMeshConstIterator< TGeometricalQuadEdge >
Self & operator= (const NoConstType &r)
QuadEdgeMeshConstIterator (const QuadEdgeMeshConstIterator &)=default
QuadEdgeMeshConstIterator (const QuadEdgeType *e=(QuadEdgeType *) 0, int op=Superclass::OperatorOnext, bool start=true)
const QuadEdgeType * Value () const
~QuadEdgeMeshConstIterator () override=default
Public Member Functions inherited from itk::QuadEdgeMeshBaseIterator< TGeometricalQuadEdge >
QuadEdgeType * GetIterator () const
int GetOpType () const
bool GetStart () const
QuadEdgeType * GetStartEdge () const
ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION (Self)
Self & operator++ ()
Self & operator++ (int)
Self & operator= (const Self &r)
bool operator== (const Self &r) const
QuadEdgeMeshBaseIterator (const QuadEdgeMeshBaseIterator &)=default
QuadEdgeMeshBaseIterator (QuadEdgeType *e, int op=OperatorOnext, bool start=true)
virtual ~QuadEdgeMeshBaseIterator ()=default
Additional Inherited Members
Protected Member Functions inherited from itk::QuadEdgeMeshBaseIterator< TGeometricalQuadEdge >
virtual void GoToNext ()
Detailed Description
template<typename TGeometricalQuadEdge>
class itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >
Const geometrical iterator.
Definition at line 348 of file itkQuadEdgeMeshBaseIterator.h.
Member Typedef Documentation
NoConstType
template<typename TGeometricalQuadEdge > using itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::NoConstType = QuadEdgeMeshIteratorGeom<TGeometricalQuadEdge>
Definition at line 355 of file itkQuadEdgeMeshBaseIterator.h.
OriginRefType
template<typename TGeometricalQuadEdge > using itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::OriginRefType = typename QuadEdgeType::OriginRefType
Geometric value type.
Definition at line 359 of file itkQuadEdgeMeshBaseIterator.h.
QuadEdgeType
template<typename TGeometricalQuadEdge > using itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::QuadEdgeType = TGeometricalQuadEdge
Definition at line 356 of file itkQuadEdgeMeshBaseIterator.h.
Self
template<typename TGeometricalQuadEdge > using itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::Self = QuadEdgeMeshConstIteratorGeom
Hierarchy type alias and values.
Definition at line 353 of file itkQuadEdgeMeshBaseIterator.h.
Superclass
template<typename TGeometricalQuadEdge > using itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::Superclass = QuadEdgeMeshConstIterator<TGeometricalQuadEdge>
Definition at line 354 of file itkQuadEdgeMeshBaseIterator.h.
Constructor & Destructor Documentation
QuadEdgeMeshConstIteratorGeom() [1/2]
template<typename TGeometricalQuadEdge > itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::QuadEdgeMeshConstIteratorGeom (const QuadEdgeType * e = (QuadEdgeType *)0, int op = Superclass::OperatorOnext, bool start = true) inline
Definition at line 362 of file itkQuadEdgeMeshBaseIterator.h.
QuadEdgeMeshConstIteratorGeom() [2/2]
template<typename TGeometricalQuadEdge > itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::QuadEdgeMeshConstIteratorGeom (const QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge > &) default
~QuadEdgeMeshConstIteratorGeom()
template<typename TGeometricalQuadEdge > itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::~QuadEdgeMeshConstIteratorGeom () override default
Member Function Documentation
operator*()
template<typename TGeometricalQuadEdge > const OriginRefType itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::operator* () const inline
Definition at line 382 of file itkQuadEdgeMeshBaseIterator.h.
operator=()
template<typename TGeometricalQuadEdge > Self & itk::QuadEdgeMeshConstIteratorGeom< TGeometricalQuadEdge >::operator= (const NoConstType & r) inline
Definition at line 373 of file itkQuadEdgeMeshBaseIterator.h.
References itk::QuadEdgeMeshBaseIterator< TQuadEdge >::GetIterator(), itk::QuadEdgeMeshBaseIterator< TQuadEdge >::GetOpType(), itk::QuadEdgeMeshBaseIterator< TQuadEdge >::GetStart(), and itk::QuadEdgeMeshBaseIterator< TQuadEdge >::GetStartEdge().
The documentation for this class was generated from the following file:
itkQuadEdgeMeshBaseIterator.h