ITK: itkAddImageFilter.h File Reference
itkAddImageFilter.h File Reference
#include "itkBinaryGeneratorImageFilter.h"
#include "itkArithmeticOpsFunctors.h"
#include "itkNumericTraits.h"
Classes
class AddImageFilter< TInputImage1, TInputImage2, TOutputImage >
Namespaces
itk
Typedefs
using ConstPointer = SmartPointer< const Self >
using FunctorType = Functor::Add2< typename TInputImage1::PixelType, typename TInputImage2::PixelType, typename TOutputImage::PixelType >
using Pointer = SmartPointer< Self >
using Self = AddImageFilter
using Superclass = BinaryGeneratorImageFilter< TInputImage1, TInputImage2, TOutputImage >
Functions
AddImageFilter ()
virtual ::itk::LightObject::Pointer CreateAnother () const
virtual const char * GetNameOfClass () const
static Pointer New ()
~AddImageFilter () override=default
Typedef Documentation
ConstPointer
using ConstPointer = SmartPointer<const Self>
Examples
Examples/DataRepresentation/Path/PolyLineParametricPath1.cxx, Examples/Filtering/ResampleVolumesToBeIsotropic.cxx, Examples/Filtering/SubsampleVolume.cxx, Examples/Filtering/WarpImageFilter1.cxx, Examples/IO/DicomImageReadPrintTags.cxx, Examples/IO/DicomSeriesReadPrintTags.cxx, Examples/IO/ImageReadImageSeriesWrite.cxx, Examples/Iterators/ImageLinearIteratorWithIndex.cxx, Examples/Iterators/ImageLinearIteratorWithIndex2.cxx, Examples/Iterators/ImageRandomConstIteratorWithIndex.cxx, Examples/Iterators/ImageRegionIteratorWithIndex.cxx, Examples/Iterators/ImageSliceIteratorWithIndex.cxx, Examples/RegistrationITKv4/BSplineWarping1.cxx, Examples/RegistrationITKv4/BSplineWarping2.cxx, Examples/RegistrationITKv4/ChangeInformationImageFilter.cxx, Examples/RegistrationITKv4/DeformableRegistration12.cxx, Examples/RegistrationITKv4/DeformableRegistration13.cxx, Examples/RegistrationITKv4/DeformableRegistration14.cxx, Examples/RegistrationITKv4/DeformableRegistration15.cxx, Examples/RegistrationITKv4/DeformableRegistration2.cxx, Examples/RegistrationITKv4/DeformableRegistration4.cxx, Examples/RegistrationITKv4/DeformableRegistration5.cxx, Examples/RegistrationITKv4/DeformableRegistration6.cxx, Examples/RegistrationITKv4/DeformableRegistration7.cxx, Examples/RegistrationITKv4/DeformableRegistration8.cxx, Examples/RegistrationITKv4/DisplacementFieldInitialization.cxx, Examples/RegistrationITKv4/ImageRegistration1.cxx, Examples/RegistrationITKv4/ImageRegistration14.cxx, Examples/RegistrationITKv4/ImageRegistration15.cxx, Examples/RegistrationITKv4/ImageRegistration16.cxx, Examples/RegistrationITKv4/ImageRegistration17.cxx, Examples/RegistrationITKv4/LandmarkWarping2.cxx, Examples/RegistrationITKv4/MeanSquaresImageMetric1.cxx, Examples/RegistrationITKv4/ModelToImageRegistration2.cxx, Examples/RegistrationITKv4/ThinPlateSplineWarp.cxx, Examples/Statistics/ImageHistogram1.cxx, and Examples/Statistics/MembershipSample.cxx.
Definition at line 93 of file itkAddImageFilter.h.
FunctorType
using FunctorType = Functor::Add2<typename TInputImage1::PixelType, typename TInputImage2::PixelType, typename TOutputImage::PixelType>
Definition at line 96 of file itkAddImageFilter.h.
Pointer
using Pointer = SmartPointer<Self>
Examples
Examples/DataRepresentation/Image/Image2.cxx, Examples/DataRepresentation/Image/RGBImage.cxx, Examples/DataRepresentation/Mesh/AutomaticMesh.cxx, Examples/DataRepresentation/Mesh/MeshCellVisitor2.cxx, Examples/DataRepresentation/Mesh/PointSet2.cxx, Examples/DataRepresentation/Mesh/PointSet3.cxx, Examples/Filtering/CompositeFilterExample.cxx, Examples/Filtering/DiffusionTensor3DReconstructionImageFilter.cxx, Examples/Filtering/DigitallyReconstructedRadiograph1.cxx, Examples/Filtering/OtsuMultipleThresholdImageFilter.cxx, Examples/Filtering/SecondDerivativeRecursiveGaussianImageFilter.cxx, Examples/IO/DicomImageReadChangeHeaderWrite.cxx, Examples/IO/DicomImageReadPrintTags.cxx, Examples/IO/DicomSeriesReadImageWrite.cxx, Examples/IO/DicomSeriesReadPrintTags.cxx, Examples/IO/RGBImageReadWrite.cxx, Examples/IO/TransformReadWrite.cxx, Examples/Iterators/NeighborhoodIterators4.cxx, Examples/Iterators/NeighborhoodIterators5.cxx, Examples/Iterators/NeighborhoodIterators6.cxx, Examples/RegistrationITKv4/DeformableRegistration1.cxx, Examples/RegistrationITKv4/DeformableRegistration10.cxx, Examples/RegistrationITKv4/DeformableRegistration11.cxx, Examples/RegistrationITKv4/DeformableRegistration15.cxx, Examples/RegistrationITKv4/DeformableRegistration16.cxx, Examples/RegistrationITKv4/DeformableRegistration17.cxx, Examples/RegistrationITKv4/DeformableRegistration3.cxx, Examples/RegistrationITKv4/DeformableRegistration5.cxx, Examples/RegistrationITKv4/DeformableRegistration9.cxx, Examples/RegistrationITKv4/ImageRegistration1.cxx, Examples/RegistrationITKv4/ImageRegistration10.cxx, Examples/RegistrationITKv4/ImageRegistration11.cxx, Examples/RegistrationITKv4/ImageRegistration12.cxx, Examples/RegistrationITKv4/ImageRegistration13.cxx, Examples/RegistrationITKv4/ImageRegistration18.cxx, Examples/RegistrationITKv4/ImageRegistration19.cxx, Examples/RegistrationITKv4/ImageRegistration2.cxx, Examples/RegistrationITKv4/ImageRegistration20.cxx, Examples/RegistrationITKv4/ImageRegistration3.cxx, Examples/RegistrationITKv4/ImageRegistration4.cxx, Examples/RegistrationITKv4/ImageRegistration5.cxx, Examples/RegistrationITKv4/ImageRegistration6.cxx, Examples/RegistrationITKv4/ImageRegistration7.cxx, Examples/RegistrationITKv4/ImageRegistration8.cxx, Examples/RegistrationITKv4/ImageRegistration9.cxx, Examples/RegistrationITKv4/ImageRegistrationHistogramPlotter.cxx, Examples/RegistrationITKv4/IterativeClosestPoint3.cxx, Examples/RegistrationITKv4/LandmarkWarping2.cxx, Examples/RegistrationITKv4/ModelToImageRegistration2.cxx, Examples/RegistrationITKv4/MultiResImageRegistration1.cxx, Examples/RegistrationITKv4/MultiResImageRegistration2.cxx, Examples/RegistrationITKv4/MultiResImageRegistration3.cxx, Examples/RegistrationITKv4/MultiStageImageRegistration1.cxx, Examples/RegistrationITKv4/MultiStageImageRegistration2.cxx, Examples/RegistrationITKv4/ThinPlateSplineWarp.cxx, Examples/Segmentation/GibbsPriorImageFilter1.cxx, Examples/Segmentation/HoughTransform2DCirclesImageFilter.cxx, Examples/Segmentation/HoughTransform2DLinesImageFilter.cxx, Examples/Segmentation/LaplacianSegmentationLevelSetImageFilter.cxx, Examples/Segmentation/ThresholdSegmentationLevelSetImageFilter.cxx, Examples/SpatialObjects/BlobSpatialObject.cxx, Examples/SpatialObjects/LandmarkSpatialObject.cxx, Examples/SpatialObjects/LineSpatialObject.cxx, Examples/SpatialObjects/MeshSpatialObject.cxx, Examples/SpatialObjects/SpatialObjectToImageStatisticsCalculator.cxx, Examples/SpatialObjects/SurfaceSpatialObject.cxx, Examples/SpatialObjects/TubeSpatialObject.cxx, Examples/Statistics/KdTree.cxx, Examples/Statistics/MembershipSampleGenerator.cxx, Examples/Statistics/NeighborhoodSampler.cxx, Examples/Statistics/PointSetToAdaptor.cxx, Examples/Statistics/ScalarImageMarkovRandomField1.cxx, and Examples/Statistics/SelectiveSubsampleGenerator.cxx.
Definition at line 92 of file itkAddImageFilter.h.
Self
using Self = AddImageFilter
Standard class type aliases.
Definition at line 88 of file itkAddImageFilter.h.
Superclass
using Superclass = BinaryGeneratorImageFilter<TInputImage1, TInputImage2, TOutputImage>
Examples
Examples/Statistics/ExpectationMaximizationMixtureModelEstimator.cxx.
Definition at line 89 of file itkAddImageFilter.h.
Function Documentation
AddImageFilter()
AddImageFilter () protected
Definition at line 114 of file itkAddImageFilter.h.
CreateAnother()
virtual::itk::LightObject::Pointer CreateAnother () const
GetNameOfClass()
virtual const char* GetNameOfClass () const virtual
Runtime information support.
Referenced by itk::KernelTransform< double, 3 >::ComputeJacobianWithRespectToPosition(), itk::Rigid3DPerspectiveTransform< TParametersValueType >::ComputeJacobianWithRespectToPosition(), itk::BSplineBaseTransform< double, 3, 3 >::ComputeJacobianWithRespectToPosition(), itk::Transform< TParametersValueType, VDimension, VDimension >::ComputeJacobianWithRespectToPosition(), itk::ImageBoundaryCondition< ImageType, ImageType >::Print(), itk::Transform< TParametersValueType, VDimension, VDimension >::TransformCovariantVector(), itk::Transform< TParametersValueType, VDimension, VDimension >::TransformDiffusionTensor3D(), itk::Transform< TParametersValueType, VDimension, VDimension >::TransformSymmetricSecondRankTensor(), and itk::Transform< TParametersValueType, VDimension, VDimension >::TransformVector().
New()
static Pointer New () static
Method for creation through the object factory.
Examples
Examples/DataRepresentation/Image/Image1.cxx, Examples/DataRepresentation/Image/Image2.cxx, Examples/DataRepresentation/Image/Image3.cxx, Examples/DataRepresentation/Image/Image4.cxx, Examples/DataRepresentation/Image/Image5.cxx, Examples/DataRepresentation/Image/ImageAdaptor1.cxx, Examples/DataRepresentation/Image/ImageAdaptor2.cxx, Examples/DataRepresentation/Image/ImageAdaptor3.cxx, Examples/DataRepresentation/Image/ImageAdaptor4.cxx, Examples/DataRepresentation/Image/RGBImage.cxx, Examples/DataRepresentation/Image/VectorImage.cxx, Examples/DataRepresentation/Mesh/AutomaticMesh.cxx, Examples/DataRepresentation/Mesh/ImageToPointSet.cxx, Examples/DataRepresentation/Mesh/Mesh1.cxx, Examples/DataRepresentation/Mesh/Mesh2.cxx, Examples/DataRepresentation/Mesh/Mesh3.cxx, Examples/DataRepresentation/Mesh/MeshCellsIteration.cxx, Examples/DataRepresentation/Mesh/MeshCellVisitor.cxx, Examples/DataRepresentation/Mesh/MeshCellVisitor2.cxx, Examples/DataRepresentation/Mesh/MeshKComplex.cxx, Examples/DataRepresentation/Mesh/MeshPolyLine.cxx, Examples/DataRepresentation/Mesh/MeshTraits.cxx, Examples/DataRepresentation/Mesh/PointSet1.cxx, Examples/DataRepresentation/Mesh/PointSet2.cxx, Examples/DataRepresentation/Mesh/PointSet3.cxx, Examples/DataRepresentation/Mesh/PointSetWithCovariantVectors.cxx, Examples/DataRepresentation/Mesh/PointSetWithVectors.cxx, Examples/DataRepresentation/Mesh/RGBPointSet.cxx, Examples/DataRepresentation/Path/PolyLineParametricPath1.cxx, Examples/Filtering/AntiAliasBinaryImageFilter.cxx, Examples/Filtering/BilateralImageFilter.cxx, Examples/Filtering/BinaryMedianImageFilter.cxx, Examples/Filtering/BinaryMinMaxCurvatureFlowImageFilter.cxx, Examples/Filtering/BinaryThresholdImageFilter.cxx, Examples/Filtering/BinomialBlurImageFilter.cxx, Examples/Filtering/CannyEdgeDetectionImageFilter.cxx, Examples/Filtering/CastingImageFilters.cxx, Examples/Filtering/CompositeFilterExample.cxx, Examples/Filtering/CurvatureAnisotropicDiffusionImageFilter.cxx, Examples/Filtering/CurvatureFlowImageFilter.cxx, Examples/Filtering/DanielssonDistanceMapImageFilter.cxx, Examples/Filtering/DerivativeImageFilter.cxx, Examples/Filtering/DiffusionTensor3DReconstructionImageFilter.cxx, Examples/Filtering/DigitallyReconstructedRadiograph1.cxx, Examples/Filtering/DiscreteGaussianImageFilter.cxx, Examples/Filtering/FFTDirectInverse.cxx, Examples/Filtering/FFTDirectInverse2.cxx, Examples/Filtering/FFTImageFilter.cxx, Examples/Filtering/FFTImageFilterFourierDomainFiltering.cxx, Examples/Filtering/FlipImageFilter.cxx, Examples/Filtering/GaussianBlurImageFunction.cxx, Examples/Filtering/GradientAnisotropicDiffusionImageFilter.cxx, Examples/Filtering/GradientMagnitudeImageFilter.cxx, Examples/Filtering/GradientMagnitudeRecursiveGaussianImageFilter.cxx, Examples/Filtering/GradientRecursiveGaussianImageFilter.cxx, Examples/Filtering/GradientVectorFlowImageFilter.cxx, Examples/Filtering/GrayscaleFunctionDilateImageFilter.cxx, Examples/Filtering/LaplacianImageFilter.cxx, Examples/Filtering/LaplacianRecursiveGaussianImageFilter1.cxx, Examples/Filtering/LaplacianRecursiveGaussianImageFilter2.cxx, Examples/Filtering/LaplacianSharpeningImageFilter.cxx, Examples/Filtering/MathematicalMorphologyBinaryFilters.cxx, Examples/Filtering/MathematicalMorphologyGrayscaleFilters.cxx, Examples/Filtering/MeanImageFilter.cxx, Examples/Filtering/MedianImageFilter.cxx, Examples/Filtering/MinMaxCurvatureFlowImageFilter.cxx, Examples/Filtering/MorphologicalImageEnhancement.cxx, Examples/Filtering/OtsuMultipleThresholdImageFilter.cxx, Examples/Filtering/OtsuThresholdImageFilter.cxx, Examples/Filtering/ResampleImageFilter.cxx, Examples/Filtering/ResampleImageFilter2.cxx, Examples/Filtering/ResampleImageFilter3.cxx, Examples/Filtering/ResampleImageFilter4.cxx, Examples/Filtering/ResampleImageFilter5.cxx, Examples/Filtering/ResampleImageFilter6.cxx, Examples/Filtering/ResampleImageFilter7.cxx, Examples/Filtering/ResampleImageFilter8.cxx, Examples/Filtering/ResampleImageFilter9.cxx, Examples/Filtering/ResampleOrientedImageFilter.cxx, Examples/Filtering/ResampleVolumesToBeIsotropic.cxx, Examples/Filtering/RGBCurvatureAnisotropicDiffusionImageFilter.cxx, Examples/Filtering/RGBGradientAnisotropicDiffusionImageFilter.cxx, Examples/Filtering/RGBToGrayscale.cxx, Examples/Filtering/ScaleSpaceGenerator2D.cxx, Examples/Filtering/SecondDerivativeRecursiveGaussianImageFilter.cxx, Examples/Filtering/SigmoidImageFilter.cxx, Examples/Filtering/SignedDanielssonDistanceMapImageFilter.cxx, Examples/Filtering/SmoothingRecursiveGaussianImageFilter.cxx, Examples/Filtering/SmoothingRecursiveGaussianImageFilter2.cxx, Examples/Filtering/SpatialObjectToImage1.cxx, Examples/Filtering/SpatialObjectToImage2.cxx, Examples/Filtering/SpatialObjectToImage3.cxx, Examples/Filtering/SubsampleVolume.cxx, Examples/Filtering/SurfaceExtraction.cxx, Examples/Filtering/ThresholdImageFilter.cxx, Examples/Filtering/VectorCurvatureAnisotropicDiffusionImageFilter.cxx, Examples/Filtering/VectorGradientAnisotropicDiffusionImageFilter.cxx, Examples/Filtering/VectorIndexSelection.cxx, Examples/Filtering/VesselnessMeasureImageFilter.cxx, Examples/Filtering/VotingBinaryHoleFillingImageFilter.cxx, Examples/Filtering/VotingBinaryIterativeHoleFillingImageFilter.cxx, Examples/Filtering/WarpImageFilter1.cxx, Examples/Filtering/ZeroCrossingBasedEdgeDetectionImageFilter.cxx, Examples/Installation/HelloWorld.cxx, Examples/IO/ComplexImageReadWrite.cxx, Examples/IO/CovariantVectorImageExtractComponent.cxx, Examples/IO/CovariantVectorImageRead.cxx, Examples/IO/CovariantVectorImageWrite.cxx, Examples/IO/DicomImageReadChangeHeaderWrite.cxx, Examples/IO/DicomImageReadPrintTags.cxx, Examples/IO/DicomImageReadWrite.cxx, Examples/IO/DicomPrintPatientInformation.cxx, Examples/IO/DicomSeriesReadGaussianImageWrite.cxx, Examples/IO/DicomSeriesReadImageWrite.cxx, Examples/IO/DicomSeriesReadImageWrite2.cxx, Examples/IO/DicomSeriesReadPrintTags.cxx, Examples/IO/DicomSeriesReadSeriesWrite.cxx, Examples/IO/ImageReadCastWrite.cxx, Examples/IO/ImageReadDicomSeriesWrite.cxx, Examples/IO/ImageReadExportVTK.cxx, Examples/IO/ImageReadExtractFilterInsertWrite.cxx, Examples/IO/ImageReadExtractWrite.cxx, Examples/IO/ImageReadImageSeriesWrite.cxx, Examples/IO/ImageReadRegionOfInterestWrite.cxx, Examples/IO/ImageReadWrite.cxx, Examples/IO/ImageSeriesReadWrite.cxx, Examples/IO/ImageSeriesReadWrite2.cxx, Examples/IO/IOPlugin.cxx, Examples/IO/RGBImageReadWrite.cxx, Examples/IO/RGBImageSeriesReadWrite.cxx, Examples/IO/TransformReadWrite.cxx, Examples/IO/VectorImageReadWrite.cxx, Examples/IO/VisibleHumanPasteWrite.cxx, Examples/IO/VisibleHumanStreamReadWrite.cxx, Examples/IO/XML/itkParticleSwarmOptimizerDOMReader.cxx, Examples/IO/XML/ParticleSwarmOptimizerReadWrite.cxx, Examples/Iterators/ImageLinearIteratorWithIndex.cxx, Examples/Iterators/ImageLinearIteratorWithIndex2.cxx, Examples/Iterators/ImageRandomConstIteratorWithIndex.cxx, Examples/Iterators/ImageRegionIterator.cxx, Examples/Iterators/ImageRegionIteratorWithIndex.cxx, Examples/Iterators/ImageSliceIteratorWithIndex.cxx, Examples/Iterators/NeighborhoodIterators1.cxx, Examples/Iterators/NeighborhoodIterators2.cxx, Examples/Iterators/NeighborhoodIterators3.cxx, Examples/Iterators/NeighborhoodIterators4.cxx, Examples/Iterators/NeighborhoodIterators5.cxx, Examples/Iterators/NeighborhoodIterators6.cxx, Examples/Iterators/ShapedNeighborhoodIterators1.cxx, Examples/Iterators/ShapedNeighborhoodIterators2.cxx, Examples/Numerics/FourierDescriptors1.cxx, Examples/RegistrationITKv4/BSplineWarping1.cxx, Examples/RegistrationITKv4/BSplineWarping2.cxx, Examples/RegistrationITKv4/ChangeInformationImageFilter.cxx, Examples/RegistrationITKv4/DeformableRegistration1.cxx, Examples/RegistrationITKv4/DeformableRegistration10.cxx, Examples/RegistrationITKv4/DeformableRegistration11.cxx, Examples/RegistrationITKv4/DeformableRegistration12.cxx, Examples/RegistrationITKv4/DeformableRegistration13.cxx, Examples/RegistrationITKv4/DeformableRegistration14.cxx, Examples/RegistrationITKv4/DeformableRegistration15.cxx, Examples/RegistrationITKv4/DeformableRegistration16.cxx, Examples/RegistrationITKv4/DeformableRegistration17.cxx, Examples/RegistrationITKv4/DeformableRegistration2.cxx, Examples/RegistrationITKv4/DeformableRegistration3.cxx, Examples/RegistrationITKv4/DeformableRegistration4.cxx, Examples/RegistrationITKv4/DeformableRegistration5.cxx, Examples/RegistrationITKv4/DeformableRegistration6.cxx, Examples/RegistrationITKv4/DeformableRegistration7.cxx, Examples/RegistrationITKv4/DeformableRegistration8.cxx, Examples/RegistrationITKv4/DeformableRegistration9.cxx, Examples/RegistrationITKv4/DisplacementFieldInitialization.cxx, Examples/RegistrationITKv4/ImageRegistration1.cxx, Examples/RegistrationITKv4/ImageRegistration10.cxx, Examples/RegistrationITKv4/ImageRegistration11.cxx, Examples/RegistrationITKv4/ImageRegistration12.cxx, Examples/RegistrationITKv4/ImageRegistration13.cxx, Examples/RegistrationITKv4/ImageRegistration14.cxx, Examples/RegistrationITKv4/ImageRegistration15.cxx, Examples/RegistrationITKv4/ImageRegistration16.cxx, Examples/RegistrationITKv4/ImageRegistration17.cxx, Examples/RegistrationITKv4/ImageRegistration18.cxx, Examples/RegistrationITKv4/ImageRegistration19.cxx, Examples/RegistrationITKv4/ImageRegistration2.cxx, Examples/RegistrationITKv4/ImageRegistration20.cxx, Examples/RegistrationITKv4/ImageRegistration3.cxx, Examples/RegistrationITKv4/ImageRegistration4.cxx, Examples/RegistrationITKv4/ImageRegistration5.cxx, Examples/RegistrationITKv4/ImageRegistration6.cxx, Examples/RegistrationITKv4/ImageRegistration7.cxx, Examples/RegistrationITKv4/ImageRegistration8.cxx, Examples/RegistrationITKv4/ImageRegistration9.cxx, Examples/RegistrationITKv4/ImageRegistrationHistogramPlotter.cxx, Examples/RegistrationITKv4/IterativeClosestPoint1.cxx, Examples/RegistrationITKv4/IterativeClosestPoint2.cxx, Examples/RegistrationITKv4/IterativeClosestPoint3.cxx, Examples/RegistrationITKv4/LandmarkWarping2.cxx, Examples/RegistrationITKv4/MeanSquaresImageMetric1.cxx, Examples/RegistrationITKv4/ModelToImageRegistration1.cxx, Examples/RegistrationITKv4/ModelToImageRegistration2.cxx, Examples/RegistrationITKv4/MultiResImageRegistration1.cxx, Examples/RegistrationITKv4/MultiResImageRegistration2.cxx, Examples/RegistrationITKv4/MultiResImageRegistration3.cxx, Examples/RegistrationITKv4/MultiStageImageRegistration1.cxx, Examples/RegistrationITKv4/MultiStageImageRegistration2.cxx, Examples/RegistrationITKv4/ThinPlateSplineWarp.cxx, Examples/Segmentation/CannySegmentationLevelSetImageFilter.cxx, Examples/Segmentation/ConfidenceConnected.cxx, Examples/Segmentation/ConfidenceConnected3D.cxx, Examples/Segmentation/ConnectedThresholdImageFilter.cxx, Examples/Segmentation/CurvesLevelSetImageFilter.cxx, Examples/Segmentation/FastMarchingImageFilter.cxx, Examples/Segmentation/GeodesicActiveContourImageFilter.cxx, Examples/Segmentation/GeodesicActiveContourShapePriorLevelSetImageFilter.cxx, Examples/Segmentation/GibbsPriorImageFilter1.cxx, Examples/Segmentation/HoughTransform2DCirclesImageFilter.cxx, Examples/Segmentation/HoughTransform2DLinesImageFilter.cxx, Examples/Segmentation/IsolatedConnectedImageFilter.cxx, Examples/Segmentation/LaplacianSegmentationLevelSetImageFilter.cxx, Examples/Segmentation/NeighborhoodConnectedImageFilter.cxx, Examples/Segmentation/RelabelComponentImageFilter.cxx, Examples/Segmentation/ShapeDetectionLevelSetFilter.cxx, Examples/Segmentation/ThresholdSegmentationLevelSetImageFilter.cxx, Examples/Segmentation/VectorConfidenceConnected.cxx, Examples/Segmentation/WatershedSegmentation1.cxx, Examples/Segmentation/WatershedSegmentation2.cxx, Examples/SpatialObjects/ArrowSpatialObject.cxx, Examples/SpatialObjects/BlobSpatialObject.cxx, Examples/SpatialObjects/BoundingBoxFromImageMaskSpatialObject.cxx, Examples/SpatialObjects/DTITubeSpatialObject.cxx, Examples/SpatialObjects/EllipseSpatialObject.cxx, Examples/SpatialObjects/GaussianSpatialObject.cxx, Examples/SpatialObjects/GroupSpatialObject.cxx, Examples/SpatialObjects/ImageMaskSpatialObject.cxx, Examples/SpatialObjects/ImageSpatialObject.cxx, Examples/SpatialObjects/LandmarkSpatialObject.cxx, Examples/SpatialObjects/LineSpatialObject.cxx, Examples/SpatialObjects/MeshSpatialObject.cxx, Examples/SpatialObjects/ReadWriteSpatialObject.cxx, Examples/SpatialObjects/SceneSpatialObject.cxx, Examples/SpatialObjects/SpatialObjectHierarchy.cxx, Examples/SpatialObjects/SpatialObjectToImageStatisticsCalculator.cxx, Examples/SpatialObjects/SpatialObjectTransforms.cxx, Examples/SpatialObjects/SurfaceSpatialObject.cxx, Examples/SpatialObjects/TubeSpatialObject.cxx, Examples/SpatialObjects/VesselTubeSpatialObject.cxx, Examples/Statistics/BayesianClassifier.cxx, Examples/Statistics/BayesianClassifierInitializer.cxx, Examples/Statistics/BayesianPluginClassifier.cxx, Examples/Statistics/EuclideanDistanceMetric.cxx, Examples/Statistics/ExpectationMaximizationMixtureModelEstimator.cxx, Examples/Statistics/GaussianMembershipFunction.cxx, Examples/Statistics/Histogram.cxx, Examples/Statistics/ImageEntropy1.cxx, Examples/Statistics/ImageHistogram1.cxx, Examples/Statistics/ImageHistogram2.cxx, Examples/Statistics/ImageHistogram3.cxx, Examples/Statistics/ImageHistogram4.cxx, Examples/Statistics/ImageMutualInformation1.cxx, Examples/Statistics/ImageToListSampleAdaptor.cxx, Examples/Statistics/KdTree.cxx, Examples/Statistics/KdTreeBasedKMeansClustering.cxx, Examples/Statistics/ListSample.cxx, Examples/Statistics/MaximumDecisionRule.cxx, Examples/Statistics/MaximumRatioDecisionRule.cxx, Examples/Statistics/MembershipSample.cxx, Examples/Statistics/MembershipSampleGenerator.cxx, Examples/Statistics/MinimumDecisionRule.cxx, Examples/Statistics/NeighborhoodSampler.cxx, Examples/Statistics/NormalVariateGenerator.cxx, Examples/Statistics/PointSetToAdaptor.cxx, Examples/Statistics/PointSetToListSampleAdaptor.cxx, Examples/Statistics/SampleSorting.cxx, Examples/Statistics/SampleStatistics.cxx, Examples/Statistics/SampleToHistogramFilter.cxx, Examples/Statistics/ScalarImageKmeansClassifier.cxx, Examples/Statistics/ScalarImageKmeansModelEstimator.cxx, Examples/Statistics/ScalarImageMarkovRandomField1.cxx, Examples/Statistics/SelectiveSubsampleGenerator.cxx, Examples/Statistics/Subsample.cxx, and Examples/Statistics/WeightedSampleStatistics.cxx.
Referenced by itk::IOTestHelper::AllocateImageFromRegionAndSpacing(), AssertTopologicalInvariants(), itk::BinaryImageToLevelSetImageAdaptorBase< TInput, ShiSparseLevelSetImage< TInput::ImageDimension > >::BinaryImageToLevelSetImageAdaptorBase(), itk::LevelSetContainer< TIdentifier, LevelSetDenseImage< TImage > >::CopyInformationAndAllocate(), itk::CopyMeshToMeshCellData(), itk::CopyMeshToMeshPointData(), itk::CopyMeshToMeshPoints(), itk::BSplineDeformableTransform< TParametersValueType, VDimension, VSplineOrder >::CreateAnother(), itk::CreateObjectFunction< T >::CreateObject(), itk::DenseFiniteDifferenceImageFilter< TDisplacementField, TDisplacementField >::DenseFiniteDifferenceImageFilter(), itk::WhitakerSparseLevelSetImage< TOutput, VDimension >::GetAsLabelObject(), itk::SpatialObjectReader< VDimension, PixelType, TMeshTraits >::GetGroup(), itk::v3::Rigid3DTransform< TParametersValueType >::GetInverseTransform(), itk::IdentityTransform< TParametersValueType, VDimension >::GetInverseTransform(), itk::CastSpatialObjectFilter< ObjectDimension >::GetOutput(), itk::ShapeLabelObject< TLabel, VImageDimension >::GetPhysicalAxesToPrincipalAxesTransform(), itk::StatisticsLabelObject< TLabel, VImageDimension >::GetPhysicalAxesToWeightedPrincipalAxesTransform(), itk::ShapeLabelObject< TLabel, VImageDimension >::GetPrincipalAxesToPhysicalAxesTransform(), itk::StatisticsLabelObject< TLabel, VImageDimension >::GetWeightedPrincipalAxesToPhysicalAxesTransform(), itk::HuangThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >::HuangThresholdImageFilter(), itk::IntermodesThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >::IntermodesThresholdImageFilter(), itk::IsoDataThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >::IsoDataThresholdImageFilter(), itk::LabelStatisticsImageFilter< TInputImage, TLabelImage >::LabelStatistics::LabelStatistics(), itk::LiThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >::LiThresholdImageFilter(), itk::ImageRegistrationMethodv4< TFixedImage, TMovingImage, DisplacementFieldTransform< double, TFixedImage::ImageDimension >, TFixedImage, PointSet< unsigned int, TFixedImage::ImageDimension > >::MakeOutputTransform(), itk::MaximumEntropyThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >::MaximumEntropyThresholdImageFilter(), itk::MetaSceneConverter< VDimension, PixelType, TMeshTraits >::MetaObjectToSpatialObject(), itk::MomentsThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >::MomentsThresholdImageFilter(), itk::NarrowBandImageFilterBase< TInputImage, Image< float, TInputImage::ImageDimension > >::NarrowBandImageFilterBase(), itk::OtsuThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >::OtsuThresholdImageFilter(), itk::QuadEdgeMeshEulerOperatorSplitEdgeFunction< TMesh, TQEType >::QuadEdgeMeshEulerOperatorSplitEdgeFunction(), itk::IOTestHelper::ReadImage(), itk::ObjectFactoryBase::RegisterInternalFactoryOnce(), itk::RawImageIOFactory< TPixel, VImageDimension >::RegisterOneFactory(), itk::SpatialObjectFactory< T >::RegisterSpatialObject(), itk::TransformFactory< T >::RegisterTransform(), itk::RenyiEntropyThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >::RenyiEntropyThresholdImageFilter(), itk::SegmentationLevelSetFunction< TImageType, TImageType >::SegmentationLevelSetFunction(), itk::FastMarchingImageFilter< TLevelSet, Image< float, TLevelSet::ImageDimension > >::SetBinaryMask(), itk::ScanlineFilterCommon< TInputImage, TOutputImage >::SetupLineOffsets(), itk::ShanbhagThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >::ShanbhagThresholdImageFilter(), itk::SimplexMeshToTriangleMeshFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::SimplexCellVisitor(), itk::SimplexMeshAdaptTopologyFilter< TInputMesh, TOutputMesh >::SimplexCellVisitor::SimplexCellVisitor(), itk::SimplexMeshVolumeCalculator< TInputMesh >::SimplexCellVisitor::SimplexCellVisitor(), itk::MetaSceneConverter< VDimension, PixelType, TMeshTraits >::SpatialObjectToMetaObject(), test(), itk::TriangleThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >::TriangleThresholdImageFilter(), itk::VectorThresholdSegmentationLevelSetFunction< TImageType, TFeatureImageType >::VectorThresholdSegmentationLevelSetFunction(), itk::VoronoiDiagram2D< TCoordType >::VertexListClear(), itk::VTKPolyDataMeshIO::WriteCellsBufferAsASCII(), itk::VTKPolyDataMeshIO::WriteCellsBufferAsBINARY(), itk::IOTestHelper::WriteImage(), and itk::YenThresholdImageFilter< TInputImage, TOutputImage, TMaskImage >::YenThresholdImageFilter().
~AddImageFilter()
~AddImageFilter () override protected default