ITK: itk::ImageToImageFilterDetail Namespace Reference
itk::ImageToImageFilterDetail Namespace Reference
Classes
struct BinaryBooleanDispatch
struct BinaryIntDispatch
struct BinaryUnsignedIntDispatch
struct BooleanDispatch
struct DispatchBase
class ExtractImageFilterRegionCopier
class ImageInformationCopier
class ImageRegionCopier
struct IntDispatch
struct UnsignedIntDispatch
Functions
template<unsigned int T1, unsigned int T2>
void ExtractImageFilterCopyRegion (const typename BinaryUnsignedIntDispatch< T1, T2 >::FirstEqualsSecondType &firstEqualsSecond, ImageRegion< T1 > &destRegion, const ImageRegion< T2 > &srcRegion, const ImageRegion< T1 > &)
template<unsigned int T1, unsigned int T2>
void ExtractImageFilterCopyRegion (const typename BinaryUnsignedIntDispatch< T1, T2 >::FirstGreaterThanSecondType &, ImageRegion< T1 > &destRegion, const ImageRegion< T2 > &srcRegion, const ImageRegion< T1 > &totalInputExtractionRegion)
template<unsigned int D1, unsigned int D2>
void ImageToImageFilterDefaultCopyInformation (const typename BinaryUnsignedIntDispatch< D1, D2 >::FirstEqualsSecondType &, ImageBase< D1 > *destImage, const ImageBase< D2 > *srcImage)
template<unsigned int D1, unsigned int D2>
void ImageToImageFilterDefaultCopyInformation (const typename BinaryUnsignedIntDispatch< D1, D2 >::FirstGreaterThanSecondType &, ImageBase< D1 > *destImage, const ImageBase< D2 > *srcImage)
template<unsigned int D1, unsigned int D2>
void ImageToImageFilterDefaultCopyRegion (const typename BinaryUnsignedIntDispatch< D1, D2 >::FirstEqualsSecondType &, ImageRegion< D1 > &destRegion, const ImageRegion< D2 > &srcRegion)
template<unsigned int D1, unsigned int D2>
void ImageToImageFilterDefaultCopyRegion (const typename BinaryUnsignedIntDispatch< D1, D2 >::FirstGreaterThanSecondType &, ImageRegion< D1 > &destRegion, const ImageRegion< D2 > &srcRegion)
template<unsigned int D1, unsigned int D2>
void ImageToImageFilterDefaultCopyRegion (const typename BinaryUnsignedIntDispatch< D1, D2 >::FirstLessThanSecondType &, ImageRegion< D1 > &destRegion, const ImageRegion< D2 > &srcRegion)
template<unsigned int D1, unsigned int D2>
bool operator!= (const ImageRegionCopier< D1, D2 > &c1, const ImageRegionCopier< D1, D2 > &c2)
template<unsigned int T1, unsigned int T2>
void ExtractImageFilterCopyRegion (const typename BinaryUnsignedIntDispatch< T1, T2 >::FirstLessThanSecondType &firstLessThanSecond, ImageRegion< T1 > &destRegion, const ImageRegion< T2 > &srcRegion, const ImageRegion< T1 > &totalInputExtractionRegion)
template<unsigned int D1, unsigned int D2>
std::ostream & operator<< (std::ostream &os, const ImageRegionCopier< D1, D2 > &)
Detailed Description
ImageToImageFilterDetail namespace to house implementations of functions that are dependent on dimension. These functions are overloaded based on type unique for each different dimension. These functions cannot be member functions of a class like ImageToImageFilter since explicit instantiation of an ImageToImageFilter would force the instantiation of all versions of these overloaded functions.
Function Documentation
ExtractImageFilterCopyRegion() [1/3]
template<unsigned int T1, unsigned int T2> void itk::ImageToImageFilterDetail::ExtractImageFilterCopyRegion (const typename BinaryUnsignedIntDispatch< T1, T2 >::FirstEqualsSecondType & firstEqualsSecond, ImageRegion< T1 > & destRegion, const ImageRegion< T2 > & srcRegion, const ImageRegion< T1 > &)
Call the base class version: ImageToImageFilterDefaultCopyRegion
Definition at line 42 of file itkExtractImageFilterRegionCopier.h.
ExtractImageFilterCopyRegion() [2/3]
template<unsigned int T1, unsigned int T2> void itk::ImageToImageFilterDetail::ExtractImageFilterCopyRegion (const typename BinaryUnsignedIntDispatch< T1, T2 >::FirstGreaterThanSecondType & , ImageRegion< T1 > & destRegion, const ImageRegion< T2 > & srcRegion, const ImageRegion< T1 > & totalInputExtractionRegion)
Copy an image region (start index and size) for the case where the source region has a lesser dimension than the destination region. This version is "smart" in that it looks at what dimensions should be collapsed. This information is passed in the parameter totalInputExtractionRegion. Any values within totalInputExtractionRegion.Size that are zero correspond to the dimension to be collapsed.
Note that the use of source and destination reflect where where is information is coming from and going to. When used in the pipeline mechanism, the region requested by the output of a filter is used to define the region required on the input. In this case the output of the filter is the source and the input of the filter is the destination.
Definition at line 85 of file itkExtractImageFilterRegionCopier.h.
References itk::ImageRegion< VImageDimension >::GetIndex(), itk::ImageRegion< VImageDimension >::GetSize(), itk::ImageRegion< VImageDimension >::SetIndex(), and itk::ImageRegion< VImageDimension >::SetSize().
ExtractImageFilterCopyRegion() [3/3]
template<unsigned int T1, unsigned int T2> void itk::ImageToImageFilterDetail::ExtractImageFilterCopyRegion (const typename BinaryUnsignedIntDispatch< T1, T2 >::FirstLessThanSecondType & firstLessThanSecond, ImageRegion< T1 > & destRegion, const ImageRegion< T2 > & srcRegion, const ImageRegion< T1 > & totalInputExtractionRegion)
Call the base class version: ImageToImageFilterDefaultCopyRegion
Definition at line 56 of file itkExtractImageFilterRegionCopier.h.
ImageToImageFilterDefaultCopyInformation() [1/2]
template<unsigned int D1, unsigned int D2> void itk::ImageToImageFilterDetail::ImageToImageFilterDefaultCopyInformation (const typename BinaryUnsignedIntDispatch< D1, D2 >::FirstEqualsSecondType & , ImageBase< D1 > * destImage, const ImageBase< D2 > * srcImage)
Definition at line 363 of file itkImageToImageFilterDetail.h.
References itk::ImageBase< VImageDimension >::CopyInformation().
ImageToImageFilterDefaultCopyInformation() [2/2]
template<unsigned int D1, unsigned int D2> void itk::ImageToImageFilterDetail::ImageToImageFilterDefaultCopyInformation (const typename BinaryUnsignedIntDispatch< D1, D2 >::FirstGreaterThanSecondType & , ImageBase< D1 > * destImage, const ImageBase< D2 > * srcImage)
Definition at line 373 of file itkImageToImageFilterDetail.h.
References itk::ImageBase< VImageDimension >::GetDirection(), itk::ImageBase< VImageDimension >::GetNumberOfComponentsPerPixel(), itk::ImageBase< VImageDimension >::GetOrigin(), itk::ImageBase< VImageDimension >::GetSpacing(), itk::ImageBase< VImageDimension >::SetDirection(), itk::ImageBase< VImageDimension >::SetNumberOfComponentsPerPixel(), itk::ImageBase< VImageDimension >::SetOrigin(), and itk::ImageBase< VImageDimension >::SetSpacing().
ImageToImageFilterDefaultCopyRegion() [1/3]
template<unsigned int D1, unsigned int D2> void itk::ImageToImageFilterDetail::ImageToImageFilterDefaultCopyRegion (const typename BinaryUnsignedIntDispatch< D1, D2 >::FirstEqualsSecondType & , ImageRegion< D1 > & destRegion, const ImageRegion< D2 > & srcRegion)
Copy an image region (start index and size) for the case where the source and destination region are the same dimension. This is a trivial copy of a region. This is an overloaded function. The other versions of this functions handle the case where the destination dimension is greater than the source dimension and the case where the destination dimension is less than the source dimension.
Note that the use of source and destination reflect where where is information is coming from and going to. When used in the pipeline mechanism, the region requested by the output of a filter is used to define the region required on the input. In this case the output of the filter is the source region and the input of the filter is the destination region.
Definition at line 192 of file itkImageToImageFilterDetail.h.
ImageToImageFilterDefaultCopyRegion() [2/3]
template<unsigned int D1, unsigned int D2> void itk::ImageToImageFilterDetail::ImageToImageFilterDefaultCopyRegion (const typename BinaryUnsignedIntDispatch< D1, D2 >::FirstGreaterThanSecondType & , ImageRegion< D1 > & destRegion, const ImageRegion< D2 > & srcRegion)
Copy an image region (start index and size) for the case where the source region has a lesser dimension than the destination region. This copies the source into the first part of the destination. This is an overloaded function. The other versions of this functions handle the case where the source dimension is less than the destination dimension and the case where the destination and source are the same dimension.
Note that the use of source and destination reflect where where is information is coming from and going to. When used in the pipeline mechanism, the region requested by the output of a filter is used to define the region required on the input. In this case the output of the filter is the source and the input of the filter is the destination.
Definition at line 259 of file itkImageToImageFilterDetail.h.
References itk::ImageRegion< VImageDimension >::GetIndex(), itk::ImageRegion< VImageDimension >::GetSize(), itk::ImageRegion< VImageDimension >::SetIndex(), and itk::ImageRegion< VImageDimension >::SetSize().
ImageToImageFilterDefaultCopyRegion() [3/3]
template<unsigned int D1, unsigned int D2> void itk::ImageToImageFilterDetail::ImageToImageFilterDefaultCopyRegion (const typename BinaryUnsignedIntDispatch< D1, D2 >::FirstLessThanSecondType & , ImageRegion< D1 > & destRegion, const ImageRegion< D2 > & srcRegion)
Copy an image region (start index and size) for the case where the source region has a greater dimension than the destination region. This copies the first portion of the source into destination. This is an overloaded function. The other versions of this functions handle the case where the source dimension is less than the destination dimension and the case where the destination and source are the same dimension.
Note that the use of source and destination reflect where where is information is coming from and going to. When used in the pipeline mechanism, the region requested by the output of a filter is used to define the region required on the input. In this case the output of the filter is the source and the input of the filter is the destination.
Definition at line 217 of file itkImageToImageFilterDetail.h.
References itk::ImageRegion< VImageDimension >::GetIndex(), itk::ImageRegion< VImageDimension >::GetSize(), itk::ImageRegion< VImageDimension >::SetIndex(), and itk::ImageRegion< VImageDimension >::SetSize().
operator!=()
template<unsigned int D1, unsigned int D2> bool itk::ImageToImageFilterDetail::operator!= (const ImageRegionCopier< D1, D2 > & c1, const ImageRegionCopier< D1, D2 > & c2)
operator!= for ImageRegionCopier objects.
Definition at line 355 of file itkImageToImageFilterDetail.h.
operator<<()
template<unsigned int D1, unsigned int D2> std::ostream & itk::ImageToImageFilterDetail::operator<< (std::ostream & os, const ImageRegionCopier< D1, D2 > &)
Stream operator for ImageRegionCopier objects. Just prints the RTTI typename.
Definition at line 344 of file itkImageToImageFilterDetail.h.