ITK: itk Namespace Reference
itk Namespace Reference
Namespaces
namespace Accessor
namespace Concept
namespace detail
namespace fftw
namespace Function
namespace Functor
namespace GTest
namespace i18n
namespace ImageToImageFilterDetail
namespace MakeUniqueForOverwriteImplDetail
namespace Math
namespace MeshIOTestHelper
namespace NeighborhoodAlgorithm
namespace print_helper
namespace Statistics
namespace testhelper
namespace Testing
namespace v3
namespace watershed
Classes
class AbsImageAdaptor
class AbsImageFilter
class AbsoluteValueDifferenceImageFilter
class AccumulateImageFilter
class AcosImageAdaptor
class AcosImageFilter
class AdaptImageFilter
class AdaptiveHistogramEqualizationImageFilter
class AddImageAdaptor
class AdditiveGaussianNoiseImageFilter
class AffineTransform
class AggregateLabelMapFilter
class AmoebaOptimizer
class AmoebaOptimizerv4
class AnchorCloseImageFilter
class AnchorDilateImageFilter
class AnchorErodeDilateImageFilter
class AnchorErodeDilateLine
class AnchorErodeImageFilter
class AnchorOpenCloseImageFilter
class AnchorOpenCloseLine
class AnchorOpenImageFilter
class AndImageFilter
class AnisotropicDiffusionFunction
class AnisotropicDiffusionImageFilter
class AnisotropicFourthOrderLevelSetImageFilter
class AnnulusOperator
class AntiAliasBinaryImageFilter
class ANTSNeighborhoodCorrelationImageToImageMetricv4
class ANTSNeighborhoodCorrelationImageToImageMetricv4GetValueAndDerivativeThreader
class ApproximateSignedDistanceMapImageFilter
class ArchetypeSeriesFileNames
class AreaClosingImageFilter
class AreaOpeningImageFilter
class Array
class Array2D
class ArrowSpatialObject
class AsinImageAdaptor
class AsinImageFilter
class Atan2ImageFilter
class AtanImageAdaptor
class AtanImageFilter
class AtanRegularizedHeavisideStepFunction
class AttributeKeepNObjectsLabelMapFilter
class AttributeLabelObject
class AttributeMorphologyBaseImageFilter
class AttributeOpeningLabelMapFilter
class AttributePositionLabelMapFilter
class AttributeRelabelLabelMapFilter
class AttributeSelectionLabelMapFilter
class AttributeUniqueLabelMapFilter
class AuthalicMatrixCoefficients
class AutoCropLabelMapFilter
class AutomaticTopologyMeshSource
class AutoPointer
class AutoPointerDataObjectDecorator
class AuxVarTypeDefault
class AzimuthElevationToCartesianTransform
class BackwardDifferenceOperator
class BandNode
class BarycentricCombination
class BasicDilateImageFilter
class BasicErodeImageFilter
class BayesianClassifierImageFilter
class BayesianClassifierInitializationImageFilter
class BilateralImageFilter
class BinaryBallStructuringElement
class BinaryClosingByReconstructionImageFilter
class BinaryContourImageFilter
class BinaryCrossStructuringElement
class BinaryDilateImageFilter
class BinaryErodeImageFilter
class BinaryFillholeImageFilter
class BinaryFunctorImageFilter
class BinaryGeneratorImageFilter
class BinaryGrindPeakImageFilter
class BinaryImageToLabelMapFilter
class BinaryImageToLevelSetImageAdaptor
class BinaryImageToLevelSetImageAdaptor< TInput, MalcolmSparseLevelSetImage< TInput::ImageDimension > >
class BinaryImageToLevelSetImageAdaptor< TInput, ShiSparseLevelSetImage< TInput::ImageDimension > >
class BinaryImageToLevelSetImageAdaptor< TInput, WhitakerSparseLevelSetImage< TOutput, TInput::ImageDimension > >
class BinaryImageToLevelSetImageAdaptor< TInputImage, LevelSetDenseImage< TLevelSetImage > >
class BinaryImageToLevelSetImageAdaptorBase
class BinaryImageToShapeLabelMapFilter
class BinaryImageToSparseLevelSetImageAdaptorBase
class BinaryImageToStatisticsLabelMapFilter
class BinaryMagnitudeImageFilter
class BinaryMask3DMeshSource
class BinaryMaskToNarrowBandPointSetFilter
class BinaryMedianImageFilter
class BinaryMinMaxCurvatureFlowFunction
class BinaryMinMaxCurvatureFlowImageFilter
class BinaryMorphologicalClosingImageFilter
class BinaryMorphologicalOpeningImageFilter
class BinaryMorphologyImageFilter
class BinaryNotImageFilter
class BinaryOpeningByReconstructionImageFilter
class BinaryProjectionImageFilter
class BinaryPruningImageFilter
class BinaryReconstructionByDilationImageFilter
class BinaryReconstructionByErosionImageFilter
class BinaryReconstructionLabelMapFilter
class BinaryShapeKeepNObjectsImageFilter
class BinaryShapeOpeningImageFilter
class BinaryStatisticsKeepNObjectsImageFilter
class BinaryStatisticsOpeningImageFilter
class BinaryThinningImageFilter
class BinaryThresholdImageFilter
class BinaryThresholdImageFunction
class BinaryThresholdProjectionImageFilter
class BinaryThresholdSpatialFunction
class BinomialBlurImageFilter
class BinShrinkImageFilter
class BioRadImageIO
class BioRadImageIOFactory
class BlackTopHatImageFilter
class BlobSpatialObject
class BlockMatchingImageFilter
class BluePixelAccessor
class BMPImageIO
class BMPImageIOFactory
class Boolean
class BorderQuadEdgeMeshFilter
class BorderQuadEdgeMeshFilterEnums
class BoundedReciprocalImageFilter
class BoundingBox
class BoxImageFilter
class BoxMeanImageFilter
class BoxSigmaImageFilter
class BoxSpatialObject
class BresenhamLine
class Bruker2dseqImageIO
class Bruker2dseqImageIOFactory
class BSplineBaseTransform
class BSplineCenteredL2ResampleImageFilterBase
class BSplineCenteredResampleImageFilterBase
class BSplineControlPointImageFilter
class BSplineControlPointImageFunction
class BSplineDecompositionImageFilter
class BSplineDeformableTransform
class BSplineDerivativeKernelFunction
class BSplineDownsampleImageFilter
class BSplineExponentialDiffeomorphicTransform
class BSplineExponentialDiffeomorphicTransformParametersAdaptor
class BSplineInterpolateImageFunction
class BSplineInterpolationWeightFunction
class BSplineKernelFunction
class BSplineL2ResampleImageFilterBase
class BSplineResampleImageFilterBase
class BSplineResampleImageFunction
class BSplineScatteredDataPointSetToImageFilter
class BSplineSmoothingOnUpdateDisplacementFieldTransform
class BSplineSmoothingOnUpdateDisplacementFieldTransformParametersAdaptor
class BSplineSyNImageRegistrationMethod
class BSplineTransform
class BSplineTransformInitializer
class BSplineTransformParametersAdaptor
class BSplineUpsampleImageFilter
class BufferedImageNeighborhoodPixelAccessPolicy
class BuildInformation
class ByteSwapper
class BYUMeshIO
class BYUMeshIOFactory
class CannyEdgeDetectionImageFilter
class CannySegmentationLevelSetFunction
class CannySegmentationLevelSetImageFilter
class CastImageFilter
class CastSpatialObjectFilter
class CellInterface
class CellInterfaceVisitor
class CellInterfaceVisitorImplementation
class CellTraitsInfo
class CenteredAffineTransform
class CenteredEuler3DTransform
class CenteredRigid2DTransform
class CenteredSimilarity2DTransform
class CenteredTransformInitializer
class CenteredVersorTransformInitializer
class CentralDifferenceImageFunction
class ChainCodePath
class ChainCodePath2D
class ChainCodeToFourierSeriesPathFilter
class ChangeInformationImageFilter
class ChangeLabelImageFilter
class ChangeLabelLabelMapFilter
class ChangeRegionLabelMapFilter
class CheckerBoardImageFilter
class ClampImageFilter
class ClassifierBase
class CleanQuadEdgeMeshFilter
class ClosingByReconstructionImageFilter
class CollidingFrontsImageFilter
class ColorTable
class Command
class CommandIterationUpdate
class CommandIterationUpdatev4
class CommandVnlIterationUpdate
class CommonEnums
class CompareHistogramImageToImageMetric
class CompensatedSummation
class ComplexBSplineInterpolateImageFunction
class ComplexConjugateImageAdaptor
class ComplexToComplex1DFFTImageFilter
class ComplexToComplexFFTImageFilter
class ComplexToComplexFFTImageFilterEnums
class ComplexToImaginaryImageAdaptor
class ComplexToImaginaryImageFilter
class ComplexToModulusImageAdaptor
class ComplexToModulusImageFilter
class ComplexToPhaseImageAdaptor
class ComplexToPhaseImageFilter
class ComplexToRealImageAdaptor
class ComplexToRealImageFilter
class ComposeDisplacementFieldsImageFilter
class ComposeImageFilter
class ComposeScaleSkewVersor3DTransform
class CompositeTransform
class CompositeTransformIOHelperTemplate
class ConditionalConstIterator
struct ConditionVariableType
class ConfidenceConnectedImageFilter
class ConformalFlatteningMeshFilter
class ConformalMatrixCoefficients
class ConicShellInteriorExteriorSpatialFunction
class ConjugateGradientLineSearchOptimizerv4Template
class ConjugateGradientOptimizer
class ConnectedComponentFunctorImageFilter
class ConnectedComponentImageFilter
class ConnectedImageNeighborhoodShape
class ConnectedRegionsMeshFilter
class ConnectedThresholdImageFilter
class ConnectedThresholdImageFilterEnums
class ConstantBoundaryCondition
class ConstantBoundaryImageNeighborhoodPixelAccessPolicy
class ConstantPadImageFilter
class ConstantVelocityFieldTransform
class ConstantVelocityFieldTransformParametersAdaptor
class ConstNeighborhoodIterator
class ConstNeighborhoodIteratorWithOnlyIndex
class ConstrainedRegionBasedLevelSetFunctionSharedData
class ConstrainedValueAdditionImageFilter
class ConstrainedValueDifferenceImageFilter
class ConstShapedNeighborhoodIterator
class ConstSliceIterator
class ConstSparseFieldLayerIterator
class ContinuousIndex
class ContourDirectedMeanDistanceImageFilter
class ContourExtractor2DImageFilter
class ContourMeanDistanceImageFilter
class ContourSpatialObject
class ContourSpatialObjectEnums
class ContourSpatialObjectPoint
class ConvertLabelMapFilter
class ConvertPixelBuffer
class ConvertPixelBuffer< InputPixelType, Array< T >, OutputConvertTraits >
class ConvertPixelBuffer< InputPixelType, VariableLengthVector< T >, OutputConvertTraits >
class ConvolutionImageFilter
class ConvolutionImageFilterBase
class ConvolutionImageFilterBaseEnums
class CorrelationCoefficientHistogramImageToImageMetric
class CorrelationImageToImageMetricv4
class CorrelationImageToImageMetricv4GetValueAndDerivativeThreader
class CorrelationImageToImageMetricv4HelperThreader
class CorrespondenceDataStructureIterator
class CosImageAdaptor
class CosImageFilter
class CostFunctionTemplate
class CovarianceImageFunction
class CovariantVector
class CoxDeBoorBSplineKernelFunction
class CreateObjectFunction
class CreateObjectFunctionBase
class CropImageFilter
class CropLabelMapFilter
class CrossHelper
class CStyleCommand
class CSVArray2DDataObject
class CSVArray2DFileReader
class CSVFileReaderBase
class CSVNumericObjectFileWriter
class CumulativeGaussianCostFunction
class CumulativeGaussianOptimizer
class CurvatureAnisotropicDiffusionImageFilter
class CurvatureFlowFunction
class CurvatureFlowImageFilter
class CurvatureNDAnisotropicDiffusionFunction
class CurvatureRegistrationFilter
class CurvesLevelSetFunction
class CurvesLevelSetImageFilter
class CyclicShiftImageFilter
class DanielssonDistanceMapImageFilter
class DataObject
class DataObjectConstIterator
class DataObjectDecorator
class DataObjectError
class DataObjectIterator
class DecimateFramesVideoFilter
class DecimationQuadEdgeMeshFilter
class DefaultConvertPixelTraits
class DefaultConvertPixelTraits< Matrix< VComponent, VRows, VCols > >
class DefaultConvertPixelTraits< Offset< VDimension > >
class DefaultConvertPixelTraits< std::complex< TComponent > >
class DefaultConvertPixelTraits< VariableLengthVector< VComponent > >
class DefaultConvertPixelTraits< VariableSizeMatrix< VComponent > >
class DefaultDynamicMeshTraits
class DefaultImageToImageMetricTraitsv4
class DefaultPixelAccessor
class DefaultPixelAccessorFunctor
class DefaultStaticMeshTraits
class DefaultVectorPixelAccessor
class DefaultVectorPixelAccessorFunctor
class DeformableSimplexMesh3DBalloonForceFilter
class DeformableSimplexMesh3DFilter
class DeformableSimplexMesh3DGradientConstraintForceFilter
class DeformableSimplexMesh3DGradientConstraintForceFilterEnums
class DelaunayConformingQuadEdgeMeshFilter
class DemonsImageToImageMetricv4
class DemonsImageToImageMetricv4GetValueAndDerivativeThreader
class DemonsRegistrationFilter
class DemonsRegistrationFunction
class DenseFiniteDifferenceImageFilter
class DerivativeImageFilter
class DerivativeOperator
class DiffeomorphicDemonsRegistrationFilter
class DifferenceOfGaussiansGradientImageFilter
class DiffusionTensor3D
class DiffusionTensor3DReconstructionImageFilter
class DiffusionTensor3DReconstructionImageFilterEnums
class DilateObjectMorphologyImageFilter
class DirectedHausdorffDistanceImageFilter
class DirectFourierReconstructionImageToImageFilter
class Directory
class DiscreteCurvatureQuadEdgeMeshFilter
class DiscreteCurvatureTensorQuadEdgeMeshFilter
class DiscreteGaussianCurvatureQuadEdgeMeshFilter
class DiscreteGaussianDerivativeImageFilter
class DiscreteGaussianDerivativeImageFunction
class DiscreteGaussianImageFilter
class DiscreteGradientMagnitudeGaussianImageFunction
class DiscreteHessianGaussianImageFunction
class DiscreteLevelSetImage
class DiscreteMaximumCurvatureQuadEdgeMeshFilter
class DiscreteMeanCurvatureQuadEdgeMeshFilter
class DiscreteMinimumCurvatureQuadEdgeMeshFilter
class DiscretePrincipalCurvaturesQuadEdgeMeshFilter
class DisplacementFieldJacobianDeterminantFilter
class DisplacementFieldToBSplineImageFilter
class DisplacementFieldTransform
class DisplacementFieldTransformParametersAdaptor
class DivideImageFilter
class DivideOrZeroOutImageFilter
class DomainThreader
class DOMNode
class DOMNodeXMLReader
class DOMNodeXMLWriter
class DOMReader
class DOMTextNode
class DOMWriter
class DoubleThresholdImageFilter
class DTITubeSpatialObject
class DTITubeSpatialObjectPoint
class DTITubeSpatialObjectPointEnums
class DynamicLoader
class EdgeDecimationQuadEdgeMeshFilter
class EdgePotentialImageFilter
class EigenAnalysis2DImageFilter
class ElasticBodyReciprocalSplineKernelTransform
class ElasticBodySplineKernelTransform
class ElementWrapperInterface
class ElementWrapperPointerInterface
class EllipseSpatialObject
class EllipsoidInteriorExteriorSpatialFunction
class EquivalencyTable
class ErodeObjectMorphologyImageFilter
class ESMDemonsRegistrationFunction
class ESMDemonsRegistrationFunctionEnums
class EuclideanDistancePointMetric
class EuclideanDistancePointSetToPointSetMetricv4
class Euler2DTransform
class Euler3DTransform
class EventObject
class ExhaustiveOptimizer
class ExhaustiveOptimizerv4
class ExpandImageFilter
class ExpectationBasedPointSetToPointSetMetricv4
class ExpImageAdaptor
class ExpImageFilter
class ExpNegativeImageAdaptor
class ExpNegativeImageFilter
class ExponentialDisplacementFieldImageFilter
class ExtensionVelocitiesImageFilter
class ExtractImageFilter
class ExtractImageFilterEnums
class ExtractOrthogonalSwath2DImageFilter
class ExtrapolateImageFunction
class FancyString
class FastApproximateRankImageFilter
class FastChamferDistanceImageFilter
class FastIncrementalBinaryDilateImageFilter
class FastMarchingBase
class FastMarchingExtensionImageFilter
class FastMarchingExtensionImageFilterBase
class FastMarchingImageFilter
class FastMarchingImageFilterBase
class FastMarchingImageFilterEnums
class FastMarchingImageToNodePairContainerAdaptor
class FastMarchingNumberOfElementsStoppingCriterion
class FastMarchingQuadEdgeMeshFilterBase
class FastMarchingReachedTargetNodesStoppingCriterion
class FastMarchingReachedTargetNodesStoppingCriterionEnums
class FastMarchingThresholdStoppingCriterion
class FastMarchingTraits
class FastMarchingTraits< Image< TInputPixel, VDimension >, Image< TOutputPixel, VDimension > >
class FastMarchingTraits< QuadEdgeMesh< TInputPixel, VDimension, TInputMeshTraits >, QuadEdgeMesh< TOutputPixel, VDimension, TOutputMeshTraits > >
class FastMarchingTraitsBase
class FastMarchingTraitsEnums
class FastMarchingUpwindGradientImageFilter
class FastMarchingUpwindGradientImageFilterBase
class FastSymmetricForcesDemonsRegistrationFilter
class FastSymmetricForcesDemonsRegistrationFunction
class FFTConvolutionImageFilter
class FFTDiscreteGaussianImageFilter
class FFTDiscreteGaussianImageFilterEnums
class FFTDiscreteGaussianImageFilterFactory
class FFTImageFilterFactory
class FFTImageFilterTraits
struct FFTImageFilterTraits< FFTWComplexToComplex1DFFTImageFilter >
struct FFTImageFilterTraits< FFTWComplexToComplexFFTImageFilter >
struct FFTImageFilterTraits< FFTWForward1DFFTImageFilter >
struct FFTImageFilterTraits< FFTWForwardFFTImageFilter >
struct FFTImageFilterTraits< FFTWHalfHermitianToRealInverseFFTImageFilter >
struct FFTImageFilterTraits< FFTWInverse1DFFTImageFilter >
struct FFTImageFilterTraits< FFTWInverseFFTImageFilter >
struct FFTImageFilterTraits< FFTWRealToHalfHermitianForwardFFTImageFilter >
struct FFTImageFilterTraits< VnlComplexToComplex1DFFTImageFilter >
struct FFTImageFilterTraits< VnlComplexToComplexFFTImageFilter >
struct FFTImageFilterTraits< VnlForward1DFFTImageFilter >
struct FFTImageFilterTraits< VnlForwardFFTImageFilter >
struct FFTImageFilterTraits< VnlHalfHermitianToRealInverseFFTImageFilter >
struct FFTImageFilterTraits< VnlInverse1DFFTImageFilter >
struct FFTImageFilterTraits< VnlInverseFFTImageFilter >
struct FFTImageFilterTraits< VnlRealToHalfHermitianForwardFFTImageFilter >
class FFTNormalizedCorrelationImageFilter
class FFTPadImageFilter
class FFTShiftImageFilter
class FFTWComplexToComplex1DFFTImageFilter
class FFTWComplexToComplexFFTImageFilter
class FFTWFFTImageFilterInitFactory
class FFTWForward1DFFTImageFilter
class FFTWForwardFFTImageFilter
class FFTWGlobalConfiguration
class FFTWHalfHermitianToRealInverseFFTImageFilter
class FFTWInverse1DFFTImageFilter
class FFTWInverseFFTImageFilter
class FFTWRealToHalfHermitianForwardFFTImageFilter
class FileListVideoIO
class FileListVideoIOFactory
class FileOutputWindow
class FileTools
class FiniteCylinderSpatialFunction
class FiniteDifferenceFunction
class FiniteDifferenceImageFilter
class FiniteDifferenceSparseImageFilter
class FiniteDifferenceSparseImageFunction
class FixedArray
class FixedCenterOfRotationAffineTransform
class FlatStructuringElement
class FlipImageFilter
class FloatingPointExceptions
class FloatingPointExceptionsEnums
class FloodFilledFunctionConditionalConstIterator
class FloodFilledImageFunctionConditionalConstIterator
class FloodFilledImageFunctionConditionalIterator
class FloodFilledSpatialFunctionConditionalConstIterator
class FloodFilledSpatialFunctionConditionalIterator
class Forward1DFFTImageFilter
class ForwardDifferenceOperator
class ForwardFFTImageFilter
class FourierSeriesPath
class FrameAverageVideoFilter
class FrameDifferenceVideoFilter
class FreeSurferAsciiMeshIO
class FreeSurferAsciiMeshIOFactory
class FreeSurferBinaryMeshIO
class FreeSurferBinaryMeshIOFactory
class FrequencyBandImageFilter
class FrequencyFFTLayoutImageRegionConstIteratorWithIndex
class FrequencyFFTLayoutImageRegionIteratorWithIndex
class FrequencyHalfHermitianFFTLayoutImageRegionConstIteratorWithIndex
class FrequencyHalfHermitianFFTLayoutImageRegionIteratorWithIndex
class FrequencyImageRegionConstIteratorWithIndex
class FrequencyImageRegionIteratorWithIndex
class FrequencyShiftedFFTLayoutImageRegionConstIteratorWithIndex
class FrequencyShiftedFFTLayoutImageRegionIteratorWithIndex
class FRPROptimizer
class FRPROptimizerEnums
class FrustumSpatialFunction
class FrustumSpatialFunctionEnums
class FullToHalfHermitianImageFilter
class FunctionBase
class FunctionCommand
class GaborImageSource
class GaborKernelFunction
class GaussianBlurImageFunction
class GaussianDerivativeImageFunction
class GaussianDerivativeOperator
class GaussianDerivativeOperatorEnums
class GaussianDerivativeSpatialFunction
class GaussianExponentialDiffeomorphicTransform
class GaussianExponentialDiffeomorphicTransformParametersAdaptor
class GaussianImageSource
class GaussianInterpolateImageFunction
class GaussianKernelFunction
class GaussianOperator
class GaussianSmoothingOnUpdateDisplacementFieldTransform
class GaussianSmoothingOnUpdateDisplacementFieldTransformParametersAdaptor
class GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform
class GaussianSpatialFunction
class GaussianSpatialObject
class GDCMImageIO
class GDCMImageIOEnums
class GDCMImageIOFactory
class GDCMSeriesFileNames
class GE4ImageIO
class GE4ImageIOFactory
class GE5ImageIO
class GE5ImageIOFactory
class GEAdwImageIO
class GEAdwImageIOFactory
class GenerateImageSource
class GeodesicActiveContourLevelSetFunction
class GeodesicActiveContourLevelSetImageFilter
class GeodesicActiveContourShapePriorLevelSetFunction
class GeodesicActiveContourShapePriorLevelSetImageFilter
class GeometricalQuadEdge
class GeometryUtilities
class GetAverageSliceImageFilter
class GiftiMeshIO
class GiftiMeshIOFactory
class GiplImageIO
class GiplImageIOFactory
class GPUAnisotropicDiffusionFunction
class GPUAnisotropicDiffusionImageFilter
class GPUBinaryThresholdImageFilter
class GPUBinaryThresholdImageFilterFactory
class GPUBoxImageFilter
class GPUCastImageFilter
class GPUContextManager
class GPUDataManager
class GPUDemonsRegistrationFilter
class GPUDemonsRegistrationFilterFactory
class GPUDemonsRegistrationFunction
class GPUDenseFiniteDifferenceImageFilter
class GPUDiscreteGaussianImageFilter
class GPUFiniteDifferenceFunction
class GPUFiniteDifferenceImageFilter
class GPUGradientAnisotropicDiffusionImageFilter
class GPUGradientAnisotropicDiffusionImageFilterFactory
class GPUGradientNDAnisotropicDiffusionFunction
class GPUImage
class GPUImageDataManager
class GPUImageFactory
class GPUImageOps
class GPUImageToImageFilter
class GPUInPlaceImageFilter
class GPUKernelManager
class GPUMeanImageFilter
class GPUMeanImageFilterFactory
class GPUNeighborhoodOperatorImageFilter
class GPUPDEDeformableRegistrationFilter
class GPUPDEDeformableRegistrationFunction
class GPUReduction
class GPUScalarAnisotropicDiffusionFunction
class GPUTraits
class GPUTraits< Image< TPixelType, VDimension > >
class GPUUnaryFunctorImageFilter
class GradientAnisotropicDiffusionImageFilter
class GradientDescentLineSearchOptimizerv4Template
class GradientDescentOptimizer
class GradientDescentOptimizerBasev4ModifyGradientByLearningRateThreaderTemplate
class GradientDescentOptimizerBasev4ModifyGradientByScalesThreaderTemplate
class GradientDescentOptimizerBasev4Template
class GradientDescentOptimizerEnums
class GradientDescentOptimizerv4Template
class GradientDifferenceImageToImageMetric
class GradientImageFilter
class GradientMagnitudeImageFilter
class GradientMagnitudeRecursiveGaussianImageFilter
class GradientNDAnisotropicDiffusionFunction
class GradientRecursiveGaussianImageFilter
class GradientVectorFlowImageFilter
class GrayscaleConnectedClosingImageFilter
class GrayscaleConnectedOpeningImageFilter
class GrayscaleDilateImageFilter
class GrayscaleErodeImageFilter
class GrayscaleFillholeImageFilter
class GrayscaleFunctionDilateImageFilter
class GrayscaleFunctionErodeImageFilter
class GrayscaleGeodesicDilateImageFilter
class GrayscaleGeodesicErodeImageFilter
class GrayscaleGrindPeakImageFilter
class GrayscaleMorphologicalClosingImageFilter
class GrayscaleMorphologicalOpeningImageFilter
class GreenPixelAccessor
class GridForwardWarpImageFilter
class GridImageSource
class GroupSpatialObject
class HalfHermitianToRealInverseFFTImageFilter
class HalfToFullHermitianImageFilter
class HardConnectedComponentImageFilter
class HardwareWisdomFilenameGenerator
class HarmonicMatrixCoefficients
class HausdorffDistanceImageFilter
class HConcaveImageFilter
class HConvexImageFilter
class HDF5CommonPathNames
class HDF5ImageIO
class HDF5ImageIOFactory
class HDF5TransformIOFactory
class HDF5TransformIOTemplate
class HeavisideStepFunction
class HeavisideStepFunctionBase
class Hessian3DToVesselnessMeasureImageFilter
class HessianRecursiveGaussianImageFilter
class HessianToObjectnessMeasureImageFilter
class HexahedronCell
class HexahedronCellTopology
class HilbertPath
class HistogramAlgorithmBase
class HistogramImageToImageMetric
class HistogramMatchingImageFilter
class HistogramThresholdCalculator
class HistogramThresholdImageFilter
class HistogramToEntropyImageFilter
class HistogramToImageFilter
class HistogramToIntensityImageFilter
class HistogramToLogProbabilityImageFilter
class HistogramToProbabilityImageFilter
class HMaximaImageFilter
class HMinimaImageFilter
class HostnameWisdomFilenameGenerator
class HoughTransform2DCirclesImageFilter
class HoughTransform2DLinesImageFilter
class HuangThresholdCalculator
class HuangThresholdImageFilter
struct IdentityHelper
class IdentityTransform
class Image
class ImageAdaptor
class ImageAlgorithm
class ImageAndPathToImageFilter
class ImageBase
class ImageBoundaryCondition
class ImageBufferRange
class ImageClassifierBase
class ImageConstIterator
class ImageConstIteratorWithIndex
class ImageConstIteratorWithOnlyIndex
class ImageContainerInterface
class ImageDuplicator
class ImageFileReader
class ImageFileWriter
class ImageFileWriterException
class ImageFilterToVideoFilterWrapper
class ImageFunction
class ImageGaussianModelEstimator
class ImageHelper
class ImageIOBase
class ImageIOFactory
class ImageIORegion
class ImageIORegionAdaptor
class ImageIterator
class ImageIteratorWithIndex
class ImageKernelOperator
class ImageKmeansModelEstimator
class ImageLinearConstIteratorWithIndex
class ImageLinearIteratorWithIndex
class ImageMaskSpatialObject
class ImageModelEstimatorBase
class ImageMomentsCalculator
class ImagePCADecompositionCalculator
class ImagePCAShapeModelEstimator
class ImageRandomConstIteratorWithIndex
class ImageRandomConstIteratorWithOnlyIndex
class ImageRandomIteratorWithIndex
class ImageRandomNonRepeatingConstIteratorWithIndex
class ImageRandomNonRepeatingIteratorWithIndex
class ImageRegion
class ImageRegionConstIterator
class ImageRegionConstIteratorWithIndex
class ImageRegionConstIteratorWithOnlyIndex
class ImageRegionExclusionConstIteratorWithIndex
class ImageRegionExclusionIteratorWithIndex
class ImageRegionIterator
class ImageRegionIteratorWithIndex
class ImageRegionRange
class ImageRegionReverseConstIterator
class ImageRegionReverseIterator
class ImageRegionSplitterBase
class ImageRegionSplitterDirection
class ImageRegionSplitterMultidimensional
class ImageRegionSplitterSlowDimension
class ImageRegistrationMethod
class ImageRegistrationMethodv4
class ImageRegistrationMethodv4Enums
class ImageReverseConstIterator
class ImageReverseIterator
class ImageScanlineConstIterator
class ImageScanlineIterator
class ImageSeriesReader
class ImageSeriesWriter
class ImageSeriesWriterException
class ImageShapeModelEstimatorBase
class ImageSink
class ImageSliceConstIteratorWithIndex
class ImageSliceIteratorWithIndex
class ImageSource
class ImageSourceCommon
class ImageSpatialObject
class ImageToImageFilter
class ImageToImageFilterCommon
class ImageToImageMetric
class ImageToImageMetricv4
class ImageToImageMetricv4GetValueAndDerivativeThreader
class ImageToImageMetricv4GetValueAndDerivativeThreader< ThreadedImageRegionPartitioner< TImageToImageMetricv4::VirtualImageDimension >, TImageToImageMetricv4 >
class ImageToImageMetricv4GetValueAndDerivativeThreader< ThreadedIndexedContainerPartitioner, TImageToImageMetricv4 >
class ImageToImageMetricv4GetValueAndDerivativeThreaderBase
class ImageToMeshFilter
class ImageToParametricSpaceFilter
class ImageToPathFilter
class ImageToSpatialObjectMetric
class ImageToSpatialObjectRegistrationMethod
class ImageToVideoFilter
class ImageVectorOptimizerParametersHelper
class ImageVoxel
class ImplicitManifoldNormalVectorFilter
class ImportImageContainer
class ImportImageFilter
class Indent
struct Index
class IndexedContainerInterface
class IndexRange
class InitializationBiasedParticleSwarmOptimizer
class InPlaceImageFilter
class InPlaceLabelMapFilter
class InputDataObjectConstIterator
class InputDataObjectIterator
class IntensityWindowingImageFilter
class InteriorExteriorMeshFilter
class InteriorExteriorSpatialFunction
class IntermodesThresholdCalculator
class IntermodesThresholdImageFilter
class InterpolateImageFilter
class InterpolateImageFunction
class InterpolateImagePointsFilter
class IntrinsicMatrixCoefficients
class InvalidRequestedRegionError
class Inverse1DFFTImageFilter
class InverseDeconvolutionImageFilter
class InverseDisplacementFieldImageFilter
class InverseEuclideanDistanceMatrixCoefficients
class InverseFFTImageFilter
class InvertDisplacementFieldImageFilter
class InvertIntensityImageFilter
class IOCommon
class IOCommonEnums
class IOTestHelper
class IPLCommonImageIO
class IsoContourDistanceImageFilter
class IsoDataThresholdCalculator
class IsoDataThresholdImageFilter
class IsolatedConnectedImageFilter
class IsolatedWatershedImageFilter
class IsotropicFourthOrderLevelSetImageFilter
class IterationReporter
class IterativeDeconvolutionImageFilter
class IterativeInverseDisplacementFieldImageFilter
class JensenHavrdaCharvatTsallisPointSetToPointSetMetricv4
class JoinImageFilter
class JoinSeriesImageFilter
class JointHistogramMutualInformationComputeJointPDFThreader
class JointHistogramMutualInformationComputeJointPDFThreader< ThreadedImageRegionPartitioner< TJointHistogramMetric::VirtualImageDimension >, TJointHistogramMetric >
class JointHistogramMutualInformationComputeJointPDFThreader< ThreadedIndexedContainerPartitioner, TJointHistogramMetric >
class JointHistogramMutualInformationComputeJointPDFThreaderBase
class JointHistogramMutualInformationGetValueAndDerivativeThreader
class JointHistogramMutualInformationImageToImageMetricv4
class JoinTraits
class JPEG2000ImageIO
class JPEG2000ImageIOFactory
class JPEG2000ImageIOInternalEnums
class JPEGImageIO
class JPEGImageIOFactory
class KalmanLinearEstimator
class KappaSigmaThresholdImageCalculator
class KappaSigmaThresholdImageFilter
class KappaStatisticImageToImageMetric
class KernelFunctionBase
class KernelImageFilter
class KernelTransform
class KittlerIllingworthThresholdCalculator
class KittlerIllingworthThresholdImageFilter
class KLMDynamicBorderArray
class KLMRegionGrowImageFilter
class KLMSegmentationBorder
class KLMSegmentationRegion
class KullbackLeiblerCompareHistogramImageToImageMetric
class LabelContourImageFilter
class LabeledPointSetToPointSetMetricv4
class LabelGeometryImageFilter
class LabelImageGaussianInterpolateImageFunction
class LabelImageToLabelMapFilter
class LabelImageToShapeLabelMapFilter
class LabelImageToStatisticsLabelMapFilter
class LabelMap
class LabelMapContourOverlayImageFilter
class LabelMapFilter
class LabelMapMaskImageFilter
class LabelMapOverlayImageFilter
class LabelMapToAttributeImageFilter
class LabelMapToBinaryImageFilter
class LabelMapToLabelImageFilter
class LabelMapToRGBImageFilter
class LabelObject
class LabelObjectLine
class LabelOverlapMeasuresImageFilter
class LabelOverlayImageFilter
class LabelSelectionLabelMapFilter
class LabelShapeKeepNObjectsImageFilter
class LabelShapeOpeningImageFilter
class LabelStatisticsImageFilter
class LabelStatisticsKeepNObjectsImageFilter
class LabelStatisticsOpeningImageFilter
class LabelToRGBImageFilter
class LabelUniqueLabelMapFilter
class LabelVotingImageFilter
class LandmarkBasedTransformInitializer
class LandmarkDisplacementFieldSource
class LandmarkSpatialObject
class LandweberDeconvolutionImageFilter
class LaplacianDeformationQuadEdgeMeshFilter
class LaplacianDeformationQuadEdgeMeshFilterEnums
class LaplacianDeformationQuadEdgeMeshFilterWithHardConstraints
class LaplacianDeformationQuadEdgeMeshFilterWithSoftConstraints
class LaplacianImageFilter
class LaplacianOperator
class LaplacianRecursiveGaussianImageFilter
class LaplacianSegmentationLevelSetFunction
class LaplacianSegmentationLevelSetImageFilter
class LaplacianSharpeningImageFilter
class LBFGS2Optimizerv4Enums
class LBFGS2Optimizerv4Template
class LBFGSBOptimizer
class LBFGSBOptimizerv4
class LBFGSOptimizer
class LBFGSOptimizerBaseHelperv4
class LBFGSOptimizerBasev4
class LBFGSOptimizerv4
class LevelSetBase
class LevelSetContainer
class LevelSetContainer< TIdentifier, LevelSetDenseImage< TImage > >
class LevelSetContainerBase
class LevelSetDenseImage
class LevelSetDomainMapImageFilter
class LevelSetDomainPartition
class LevelSetDomainPartitionBase
class LevelSetDomainPartitionImage
class LevelSetDomainPartitionImageWithKdTree
class LevelSetDomainPartitionMesh
class LevelSetEquationAdvectionTerm
class LevelSetEquationBinaryMaskTerm
class LevelSetEquationChanAndVeseExternalTerm
class LevelSetEquationChanAndVeseInternalTerm
class LevelSetEquationContainer
class LevelSetEquationCurvatureTerm
class LevelSetEquationLaplacianTerm
class LevelSetEquationOverlapPenaltyTerm
class LevelSetEquationPropagationTerm
class LevelSetEquationRegionTerm
class LevelSetEquationTermBase
class LevelSetEquationTermContainer
class LevelSetEvolution
class LevelSetEvolution< TEquationContainer, LevelSetDenseImage< TImage > >
class LevelSetEvolution< TEquationContainer, MalcolmSparseLevelSetImage< VDimension > >
class LevelSetEvolution< TEquationContainer, ShiSparseLevelSetImage< VDimension > >
class LevelSetEvolution< TEquationContainer, WhitakerSparseLevelSetImage< TOutput, VDimension > >
class LevelSetEvolutionBase
class LevelSetEvolutionComputeIterationThreader
class LevelSetEvolutionComputeIterationThreader< LevelSetDenseImage< TImage >, ThreadedImageRegionPartitioner< TImage::ImageDimension >, TLevelSetEvolution >
class LevelSetEvolutionComputeIterationThreader< LevelSetDenseImage< TImage >, ThreadedIteratorRangePartitioner< TLevelSetEvolution::DomainMapImageFilterType::DomainMapType::const_iterator >, TLevelSetEvolution >
class LevelSetEvolutionComputeIterationThreader< WhitakerSparseLevelSetImage< TOutput, VDimension >, ThreadedIteratorRangePartitioner< WhitakerSparseLevelSetImage< TOutput, VDimension >::LayerConstIterator >, TLevelSetEvolution >
class LevelSetEvolutionStoppingCriterion
class LevelSetEvolutionUpdateLevelSetsThreader
class LevelSetEvolutionUpdateLevelSetsThreader< LevelSetDenseImage< TImage >, ThreadedImageRegionPartitioner< TImage::ImageDimension >, TLevelSetEvolution >
class LevelSetFunction
class LevelSetFunctionWithRefitTerm
class LevelSetImage
class LevelSetMotionRegistrationFilter
class LevelSetMotionRegistrationFunction
class LevelSetNeighborhoodExtractor
class LevelSetNode
class LevelSetQuadEdgeMesh
class LevelSetSparseImage
class LevelSetTypeDefault
class LevelSetVelocityNeighborhoodExtractor
class LevenbergMarquardtOptimizer
class LightObject
class LightProcessObject
class LinearInterpolateImageFunction
class LineCell
class LineConstIterator
class LineIterator
class LineSpatialObject
class LineSpatialObjectPoint
class ListNode
class LiThresholdCalculator
class LiThresholdImageFilter
class Log10ImageAdaptor
class Log10ImageFilter
class Logger
class LoggerBase
class LoggerBaseEnums
class LoggerManager
class LoggerOutput
class LoggerThreadWrapper
class LoggerThreadWrapperEnums
class LogImageAdaptor
class LogImageFilter
class LogOutput
class LSMImageIO
class LSMImageIOFactory
class MagnitudeAndPhaseToComplexImageFilter
class MahalanobisDistanceThresholdImageFunction
class MalcolmSparseLevelSetImage
class ManifoldParzenWindowsPointSetFunction
class ManualWisdomFilenameGenerator
class MapContainer
class MapData
class MapFileParser
class MapRecord
class MaskedFFTNormalizedCorrelationImageFilter
class MaskedMovingHistogramImageFilter
class MaskedRankImageFilter
class MaskFeaturePointSelectionFilter
class MaskImageFilter
class MaskNegatedImageFilter
class MaskNeighborhoodOperatorImageFilter
class MatchCardinalityImageToImageMetric
class MathematicalMorphologyEnums
class MatlabTransformIOFactory
class MatlabTransformIOTemplate
class Matrix
class MatrixCoefficients
class MatrixIndexSelectionImageFilter
class MatrixOffsetTransformBase
class MatrixOrthogonalityTolerance
class MatrixOrthogonalityTolerance< double >
class MatrixOrthogonalityTolerance< float >
class MatrixResizeableDataObject
class MattesMutualInformationImageToImageMetric
class MattesMutualInformationImageToImageMetricv4
class MattesMutualInformationImageToImageMetricv4GetValueAndDerivativeThreader
class MaxFunctor
class MaximumEntropyThresholdCalculator
class MaximumEntropyThresholdImageFilter
class MaximumImageFilter
class MaximumProjectionImageFilter
class MaxMeasureBoundCriterion
class MaxPriorityQueueElementWrapper
class MeanImageFilter
class MeanImageFunction
class MeanProjectionImageFilter
class MeanReciprocalSquareDifferenceImageToImageMetric
class MeanReciprocalSquareDifferencePointSetToImageMetric
class MeanSquareRegistrationFunction
class MeanSquaresHistogramImageToImageMetric
class MeanSquaresImageToImageMetric
class MeanSquaresImageToImageMetricv4
class MeanSquaresImageToImageMetricv4GetValueAndDerivativeThreader
class MeanSquaresPointSetToImageMetric
class MedianImageFilter
class MedianImageFunction
class MedianProjectionImageFilter
class MemberCommand
class MemoryProbe
class MemoryProbesCollectorBase
class MemoryUsageObserver
class MemoryUsageObserverBase
class MergeLabelMapFilter
class MergeLabelMapFilterEnums
class Mesh
class MeshConvertPixelTraits
class MeshEnums
class MeshFileReader
class MeshFileReaderException
class MeshFileWriter
class MeshFileWriterException
class MeshIOBase
class MeshIOFactory
class MeshRegion
class MeshSource
class MeshSpatialObject
class MeshToMeshFilter
class MetaArrayReader
class MetaArrayWriter
class MetaArrowConverter
class MetaBlobConverter
class MetaContourConverter
class MetaConverterBase
class MetaDataDictionary
class MetaDataObject
class MetaDataObjectBase
class MetaDTITubeConverter
class MetaEllipseConverter
class MetaEvent
class MetaGaussianConverter
class MetaGroupConverter
class MetaImageConverter
class MetaImageIO
class MetaImageIOFactory
class MetaImageMaskConverter
class MetaLandmarkConverter
class MetaLineConverter
class MetaMeshConverter
class MetaSceneConverter
class MetaSurfaceConverter
class MetaTubeConverter
class MetaVesselTubeConverter
class MINCImageIO
class MINCImageIOFactory
class MinFunctor
class MinimumImageFilter
class MinimumMaximumImageCalculator
class MinimumMaximumImageFilter
class MinimumProjectionImageFilter
class MiniPipelineSeparableImageFilter
class MinMaxCurvatureFlowFunction
class MinMaxCurvatureFlowImageFilter
class MinMeasureBoundCriterion
class MinPriorityQueueElementWrapper
class MirrorPadImageFilter
class ModulusImageFilter
class MomentsThresholdCalculator
class MomentsThresholdImageFilter
class MorphologicalGradientImageFilter
class MorphologicalWatershedFromMarkersImageFilter
class MorphologicalWatershedImageFilter
class MorphologyImageFilter
class MovingHistogramDilateImageFilter
class MovingHistogramErodeImageFilter
class MovingHistogramImageFilter
class MovingHistogramImageFilterBase
class MovingHistogramMorphologicalGradientImageFilter
class MovingHistogramMorphologyImageFilter
class MRASlabIdentifier
class MRCHeaderObject
class MRCImageIO
class MRCImageIOFactory
class MRFImageFilter
class MRFImageFilterEnums
class MRIBiasEnergyFunction
class MRIBiasFieldCorrectionFilter
class MultiGradientOptimizerv4Template
class MultiLabelSTAPLEImageFilter
class MultiphaseDenseFiniteDifferenceImageFilter
class MultiphaseFiniteDifferenceImageFilter
class MultiphaseSparseFiniteDifferenceImageFilter
class MultipleLogOutput
class MultipleValuedCostFunction
class MultipleValuedNonLinearOptimizer
class MultipleValuedNonLinearVnlOptimizer
class MultipleValuedVnlCostFunctionAdaptor
class MultiplyImageFilter
class MultiResolutionImageRegistrationMethod
class MultiResolutionPDEDeformableRegistration
class MultiResolutionPyramidImageFilter
class MultiScaleHessianBasedMeasureImageFilter
class MultiScaleHessianBasedMeasureImageFilterEnums
class MultiStartOptimizerv4Template
class MultiThreaderBase
class MultiThreaderBaseEnums
class MultiTransform
class MultivariateLegendrePolynomial
class MutualInformationHistogramImageToImageMetric
class MutualInformationImageToImageMetric
class N4BiasFieldCorrectionImageFilter
class NarrowBand
class NarrowBandCurvesLevelSetImageFilter
class NarrowBandImageFilterBase
class NarrowBandLevelSetImageFilter
class NarrowBandThresholdSegmentationLevelSetImageFilter
class NaryAddImageFilter
class NaryFunctorImageFilter
class NaryMaximumImageFilter
class NearestNeighborExtrapolateImageFunction
class NearestNeighborInterpolateImageFunction
class Neighborhood
class NeighborhoodAccessorFunctor
class NeighborhoodAllocator
class NeighborhoodBinaryThresholdImageFunction
class NeighborhoodConnectedImageFilter
class NeighborhoodInnerProduct
class NeighborhoodIterator
class NeighborhoodOperator
class NeighborhoodOperatorImageFilter
class NeighborhoodOperatorImageFunction
class NiftiImageIO
class NiftiImageIOEnums
class NiftiImageIOFactory
class NodeOfPermutation
class NodePair
class NoiseBaseImageFilter
class NoiseImageFilter
class NonLinearOptimizer
class NormalBandNode
class NormalizedCorrelationImageFilter
class NormalizedCorrelationImageToImageMetric
class NormalizedCorrelationPointSetToImageMetric
class NormalizedMutualInformationHistogramImageToImageMetric
class NormalizeImageFilter
class NormalizeToConstantImageFilter
class NormalQuadEdgeMeshFilter
class NormalQuadEdgeMeshFilterEnums
class NormalVectorDiffusionFunction
class NormalVectorFunctionBase
class NotImageFilter
class NrrdImageIO
class NrrdImageIOFactory
class NthElementImageAdaptor
class NthElementImageAdaptorHelper
class NthElementPixelAccessor
class NthElementPixelAccessor< TOutputPixelType, itk::VariableLengthVector< TPixelType > >
class NumberOfFacesCriterion
class NumberOfPointsCriterion
class NumberToString
class NumberToString< void >
class NumericSeriesFileNames
class NumericTraits
class NumericTraits< Array< T > >
class NumericTraits< CovariantVector< T, D > >
class NumericTraits< DiffusionTensor3D< T > >
class NumericTraits< FixedArray< T, D > >
class NumericTraits< Point< T, D > >
class NumericTraits< RGBAPixel< T > >
class NumericTraits< RGBPixel< T > >
class NumericTraits< std::vector< T > >
class NumericTraits< SymmetricSecondRankTensor< T, D > >
class NumericTraits< VariableLengthVector< T > >
class NumericTraits< Vector< T, D > >
class Object
class ObjectByObjectLabelMapFilter
class ObjectEnums
class ObjectFactory
class ObjectFactoryBase
class ObjectFactoryEnums
class ObjectMorphologyImageFilter
class ObjectStore
class ObjectStoreEnums
class ObjectToObjectMetric
class ObjectToObjectMetricBaseTemplate
class ObjectToObjectMetricBaseTemplateEnums
class ObjectToObjectMultiMetricv4
class ObjectToObjectOptimizerBaseTemplate
class ObjectToObjectOptimizerBaseTemplateEnums
class OBJMeshIO
class OBJMeshIOFactory
class Octree
class OctreeBase
class OctreeEnums
class OctreeNode
class OctreeNodeBranch
class OFFMeshIO
class OFFMeshIOFactory
struct Offset
class OnePlusOneEvolutionaryOptimizer
class OnePlusOneEvolutionaryOptimizerv4
class OnesMatrixCoefficients
class OneWayEquivalencyTable
class OpeningByReconstructionImageFilter
class Optimizer
class OptimizerParameters
class OptimizerParameterScalesEstimatorTemplate
class OptimizerParametersHelper
class OrientImageFilter
class OrImageFilter
class OrthogonallyCorrected2DParametricPath
class OrthogonalSwath2DPathFilter
class OtsuMultipleThresholdsCalculator
class OtsuMultipleThresholdsImageFilter
class OtsuThresholdCalculator
class OtsuThresholdImageFilter
class OutputDataObjectConstIterator
class OutputDataObjectIterator
class OutputWindow
class PadImageFilter
class PadImageFilterBase
class PadLabelMapFilter
class ParallelSparseFieldCityBlockNeighborList
class ParallelSparseFieldLevelSetImageFilter
class ParallelSparseFieldLevelSetNode
class ParameterizationQuadEdgeMeshFilter
class ParametricBlindLeastSquaresDeconvolutionImageFilter
class ParametricImageSource
class ParametricPath
class ParametricSpaceToImageSpaceMeshFilter
class ParticleSwarmOptimizer
class ParticleSwarmOptimizerBase
class PasteImageFilter
class PatchBasedDenoisingBaseImageFilter
class PatchBasedDenoisingBaseImageFilterEnums
class PatchBasedDenoisingImageFilter
class Path
class PathAndImageToPathFilter
class PathConstIterator
class PathIterator
class PathSource
class PathToChainCodePathFilter
class PathToImageFilter
class PathToPathFilter
class PCAShapeSignedDistanceFunction
class PDEDeformableRegistrationFilter
class PDEDeformableRegistrationFunction
class PeriodicBoundaryCondition
class PermuteAxesImageFilter
class PhasedArray3DSpecialCoordinatesImage
class PhysicalPointImageSource
class PipelineMonitorImageFilter
class PixelAccessor
class PixelTraits
class PNGImageIO
class PNGImageIOFactory
class Point
class Point1D
class PointBasedSpatialObject
class PointSet
class PointSetFunction
class PointSetToImageFilter
class PointSetToImageMetric
class PointSetToImageRegistrationMethod
class PointSetToPointSetMetric
class PointSetToPointSetMetricv4
class PointSetToPointSetMetricWithIndexv4
class PointSetToPointSetRegistrationMethod
class PointSetToSpatialObjectDemonsRegistration
class PointsLocator
class PolygonCell
class PolygonGroupSpatialObjectXMLFileReader
class PolygonGroupSpatialObjectXMLFileWriter
class PolygonSpatialObject
class PolyLineCell
class PolylineMask2DImageFilter
class PolylineMaskImageFilter
class PolyLineParametricPath
class PoolMultiThreader
class PowellOptimizer
class PowellOptimizerv4
class PriorityQueueContainer
class ProcessObject
class ProgressAccumulator
class ProgressReporter
class ProgressTransformer
class ProjectedIterativeDeconvolutionImageFilter
class ProjectedLandweberDeconvolutionImageFilter
class ProjectionImageFilter
class QuadEdge
class QuadEdgeMesh
class QuadEdgeMeshBaseIterator
class QuadEdgeMeshBoundaryEdgesMeshFunction
class QuadEdgeMeshConstFrontIterator
class QuadEdgeMeshConstIterator
class QuadEdgeMeshConstIteratorGeom
class QuadEdgeMeshDecimationCriterion
class QuadEdgeMeshDecimationQuadricElementHelper
class QuadEdgeMeshEulerOperatorCreateCenterVertexFunction
class QuadEdgeMeshEulerOperatorDeleteCenterVertexFunction
class QuadEdgeMeshEulerOperatorFlipEdgeFunction
class QuadEdgeMeshEulerOperatorFlipEdgeFunctionEnums
class QuadEdgeMeshEulerOperatorJoinFacetFunction
class QuadEdgeMeshEulerOperatorJoinVertexFunction
class QuadEdgeMeshEulerOperatorSplitEdgeFunction
class QuadEdgeMeshEulerOperatorSplitFacetFunction
class QuadEdgeMeshEulerOperatorSplitVertexFunction
class QuadEdgeMeshExtendedTraits
class QuadEdgeMeshFrontBaseIterator
class QuadEdgeMeshFrontIterator
class QuadEdgeMeshFunctionBase
class QuadEdgeMeshIterator
class QuadEdgeMeshIteratorGeom
class QuadEdgeMeshLineCell
class QuadEdgeMeshPoint
class QuadEdgeMeshPolygonCell
class QuadEdgeMeshScalarDataVTKPolyDataWriter
class QuadEdgeMeshTopologyChecker
class QuadEdgeMeshToQuadEdgeMeshFilter
class QuadEdgeMeshTraits
class QuadEdgeMeshZipMeshFunction
class QuadraticEdgeCell
class QuadraticTriangleCell
class QuadraticTriangleCellTopology
class QuadricDecimationQuadEdgeMeshFilter
class QuadrilateralCell
class QuadrilateralCellTopology
class QuasiNewtonOptimizerv4EstimateNewtonStepThreaderTemplate
class QuasiNewtonOptimizerv4Template
class QuaternionRigidTransform
class QuaternionRigidTransformGradientDescentOptimizer
class RandomImageSource
class RandomPermutation
class RankImageFilter
class RawImageIO
class RawImageIOFactory
class RayCastInterpolateImageFunction
class RealTimeClock
class RealTimeInterval
class RealTimeStamp
class RealToHalfHermitianForwardFFTImageFilter
class ReceptorMemberCommand
class ReconstructionByDilationImageFilter
class ReconstructionByErosionImageFilter
class ReconstructionImageFilter
class RectangularImageNeighborhoodShape
class RecursiveGaussianImageFilter
class RecursiveGaussianImageFilterEnums
class RecursiveMultiResolutionPyramidImageFilter
class RecursiveSeparableImageFilter
class RedPixelAccessor
class ReflectiveImageRegionConstIterator
class ReflectiveImageRegionIterator
class Region
class RegionalMaximaImageFilter
class RegionalMinimaImageFilter
class RegionBasedLevelSetFunction
class RegionBasedLevelSetFunctionData
class RegionBasedLevelSetFunctionSharedData
class RegionFromReferenceLabelMapFilter
class RegionGrowImageFilter
class RegionOfInterestImageFilter
class RegistrationParameterScalesEstimator
class RegistrationParameterScalesEstimatorEnums
class RegistrationParameterScalesFromIndexShift
class RegistrationParameterScalesFromJacobian
class RegistrationParameterScalesFromPhysicalShift
class RegistrationParameterScalesFromShiftBase
class RegularExpressionSeriesFileNames
class RegularizedHeavisideStepFunction
class RegularSphereMeshSource
class RegularStepGradientDescentBaseOptimizer
class RegularStepGradientDescentBaseOptimizerEnums
class RegularStepGradientDescentOptimizer
class RegularStepGradientDescentOptimizerv4
class ReinitializeLevelSetImageFilter
class RelabelComponentImageFilter
class RelabelLabelMapFilter
class RenyiEntropyThresholdCalculator
class RenyiEntropyThresholdImageFilter
class ResampleImageFilter
class RescaleIntensityImageFilter
class ResourceProbe
class ResourceProbesCollectorBase
class RGBAPixel
class RGBGibbsPriorFilter
class RGBPixel
class RGBToLuminanceImageAdaptor
class RGBToLuminanceImageFilter
class RGBToVectorImageAdaptor
class RichardsonLucyDeconvolutionImageFilter
class Rigid2DTransform
class Rigid3DPerspectiveTransform
class Rigid3DTransform
class RingBuffer
class RobustAutomaticThresholdCalculator
class RobustAutomaticThresholdImageFilter
class RoundImageFilter
class SaltAndPepperNoiseImageFilter
class ScalableAffineTransform
class ScalarAnisotropicDiffusionFunction
class ScalarChanAndVeseDenseLevelSetImageFilter
class ScalarChanAndVeseLevelSetFunction
class ScalarChanAndVeseLevelSetFunctionData
class ScalarChanAndVeseSparseLevelSetImageFilter
class ScalarConnectedComponentImageFilter
class ScalarImageKmeansImageFilter
class ScalarRegionBasedLevelSetFunction
class ScalarToRGBColormapImageFilter
class ScalarToRGBColormapImageFilterEnums
class ScaleLogarithmicTransform
class ScaleSkewVersor3DTransform
class ScaleTransform
class ScaleVersor3DTransform
class ScanlineFilterCommon
class ScatterMatrixImageFunction
class SegmentationBorder
class SegmentationLevelSetFunction
class SegmentationLevelSetImageFilter
class SegmentationRegion
class ShanbhagThresholdCalculator
class ShanbhagThresholdImageFilter
class ShapeDetectionLevelSetFunction
class ShapeDetectionLevelSetImageFilter
class ShapedFloodFilledFunctionConditionalConstIterator
class ShapedFloodFilledImageFunctionConditionalConstIterator
class ShapedFloodFilledImageFunctionConditionalIterator
class ShapedImageNeighborhoodRange
class ShapedNeighborhoodIterator
class ShapeKeepNObjectsLabelMapFilter
class ShapeLabelMapFilter
class ShapeLabelObject
class ShapeOpeningLabelMapFilter
class ShapePositionLabelMapFilter
class ShapePriorMAPCostFunction
class ShapePriorMAPCostFunctionBase
class ShapePriorSegmentationLevelSetFunction
class ShapePriorSegmentationLevelSetImageFilter
class ShapeRelabelImageFilter
class ShapeRelabelLabelMapFilter
class ShapeSignedDistanceFunction
class ShapeUniqueLabelMapFilter
class ShiftScaleImageFilter
class ShiftScaleLabelMapFilter
class ShiSparseLevelSetImage
class ShotNoiseImageFilter
class ShrinkImageFilter
class SiemensVisionImageIO
class SiemensVisionImageIOFactory
class SigmoidImageFilter
class SignedDanielssonDistanceMapImageFilter
class SignedMaurerDistanceMapImageFilter
class Similarity2DTransform
class Similarity3DTransform
class SimilarityIndexImageFilter
class SimpleConstMemberCommand
class SimpleContourExtractorImageFilter
class SimpleDataObjectDecorator
class SimpleFilterWatcher
class SimpleMemberCommand
class SimpleWisdomFilenameGenerator
class SimplexMesh
class SimplexMeshAdaptTopologyFilter
class SimplexMeshGeometry
class SimplexMeshToTriangleMeshFilter
class SimplexMeshVolumeCalculator
class SingletonIndex
class SingleValuedCostFunction
class SingleValuedCostFunctionv4Template
class SingleValuedNonLinearOptimizer
class SingleValuedNonLinearVnlOptimizer
class SingleValuedNonLinearVnlOptimizerv4
class SingleValuedVnlCostFunctionAdaptor
class SingleValuedVnlCostFunctionAdaptorv4
class SinImageAdaptor
class SinImageFilter
class SinRegularizedHeavisideStepFunction
struct Size
class SliceBySliceImageFilter
class SliceImageFilter
class SliceIterator
class SLICImageFilter
class SmapsData_2_6
class SmapsFileParser
class SmapsRecord
class SmartPointer
class SmoothingQuadEdgeMeshFilter
class SmoothingRecursiveGaussianImageFilter
class SobelEdgeDetectionImageFilter
class SobelOperator
class SparseFieldCityBlockNeighborList
class SparseFieldFourthOrderLevelSetImageFilter
class SparseFieldLayer
class SparseFieldLayerIterator
class SparseFieldLevelSetImageFilter
class SparseFieldLevelSetNode
class SparseImage
class SpatialFunction
class SpatialFunctionImageEvaluatorFilter
class SpatialObject
class SpatialObjectDuplicator
class SpatialObjectFactory
class SpatialObjectFactoryBase
class SpatialObjectPoint
class SpatialObjectProperty
class SpatialObjectReader
class SpatialObjectToImageFilter
class SpatialObjectToImageStatisticsCalculator
class SpatialObjectToPointSetFilter
class SpatialObjectWriter
class SpatialOrientationAdapter
class SpatialOrientationEnums
class SpecialCoordinatesImage
class SpeckleNoiseImageFilter
class SphereSignedDistanceFunction
class SphereSpatialFunction
class SPSAOptimizer
class SPSAOptimizerEnums
class SqrtImageAdaptor
class SqrtImageFilter
class SquaredDifferenceImageFilter
class SquaredEdgeLengthDecimationQuadEdgeMeshFilter
class SquareImageFilter
class StandardDeviationProjectionImageFilter
class STAPLEImageFilter
class StatisticsImageFilter
class StatisticsKeepNObjectsLabelMapFilter
class StatisticsLabelMapFilter
class StatisticsLabelObject
class StatisticsOpeningLabelMapFilter
class StatisticsPositionLabelMapFilter
class StatisticsRelabelImageFilter
class StatisticsRelabelLabelMapFilter
class StatisticsUniqueLabelMapFilter
class StdStreamLogOutput
class StdStreamStateSave
class StimulateImageIO
class StimulateImageIOFactory
class STLConstContainerAdaptor
class STLContainerAdaptor
class StochasticFractalDimensionImageFilter
class StoppingCriterionBase
class StreamingImageFilter
class StreamingImageIOBase
class StreamingProcessObject
class StringTools
class StructHashFunction
class SubtractImageFilter
class SumOfSquaresImageFunction
class SumProjectionImageFilter
class SurfaceSpatialObject
class SurfaceSpatialObjectPoint
class SymmetricEigenAnalysis
class SymmetricEigenAnalysisEnums
class SymmetricEigenAnalysisFixedDimension
class SymmetricEigenAnalysisFixedDimensionImageFilter
class SymmetricEigenAnalysisImageFilter
class SymmetricEllipsoidInteriorExteriorSpatialFunction
class SymmetricForcesDemonsRegistrationFilter
class SymmetricForcesDemonsRegistrationFunction
class SymmetricSecondRankTensor
class SyNImageRegistrationMethod
class SysResourceMemoryUsageObserver
class TanImageAdaptor
class TanImageFilter
class TBBMultiThreader
class TemporalDataObject
class TemporalDataObjectEnums
class TemporalProcessObject
class TemporalRegion
class TensorFractionalAnisotropyImageFilter
class TensorRelativeAnisotropyImageFilter
class TernaryAddImageFilter
class TernaryFunctorImageFilter
class TernaryGeneratorImageFilter
class TernaryMagnitudeImageFilter
class TernaryMagnitudeSquaredImageFilter
class TernaryOperatorImageFilter
class TetrahedronCell
class TetrahedronCellTopology
class TextOutput
class ThinPlateR2LogRSplineKernelTransform
class ThinPlateSplineKernelTransform
class ThreadedDomainPartitioner
class ThreadedImageRegionPartitioner
class ThreadedIndexedContainerPartitioner
class ThreadedIteratorRangePartitioner
class ThreadedIteratorRangePartitionerDomain
class ThreadLogger
class ThreadPool
class ThresholdImageFilter
class ThresholdLabelerImageFilter
class ThresholdMaximumConnectedComponentsImageFilter
class ThresholdSegmentationLevelSetFunction
class ThresholdSegmentationLevelSetImageFilter
class TIFFImageIO
class TIFFImageIOFactory
class TikhonovDeconvolutionImageFilter
class TileImageFilter
class TimeProbe
class TimeProbesCollectorBase
class TimeStamp
class TimeVaryingBSplineVelocityFieldImageRegistrationMethod
class TimeVaryingBSplineVelocityFieldTransform
class TimeVaryingBSplineVelocityFieldTransformParametersAdaptor
class TimeVaryingVelocityFieldImageRegistrationMethodv4
class TimeVaryingVelocityFieldIntegrationImageFilter
class TimeVaryingVelocityFieldTransform
class TimeVaryingVelocityFieldTransformParametersAdaptor
class TobogganImageFilter
class TorusInteriorExteriorSpatialFunction
class TotalProgressReporter
class Transform
class TransformBaseTemplate
class TransformBaseTemplateEnums
class TransformFactory
class TransformFactoryBase
class TransformFileReaderTemplate
class TransformFileWriterTemplate
class TransformGeometryImageFilter
class TransformIOBaseTemplate
class TransformIOFactoryTemplate
class TransformMeshFilter
class TransformParametersAdaptor
class TransformParametersAdaptorBase
class TransformToDisplacementFieldFilter
class TranslationTransform
class TriangleCell
class TriangleCellTopology
class TriangleHelper
class TriangleMeshCurvatureCalculator
class TriangleMeshCurvatureCalculatorEnums
class TriangleMeshToBinaryImageFilter
class TriangleMeshToSimplexMeshFilter
class TriangleThresholdCalculator
class TriangleThresholdImageFilter
class TubeSpatialObject
class TubeSpatialObjectPoint
class TxtTransformIOFactory
class TxtTransformIOTemplate
class UnaryCorrespondenceMatrix
class UnaryFrequencyDomainFilter
class UnaryFunctorImageFilter
class UnaryGeneratorImageFilter
class UnconstrainedRegionBasedLevelSetFunctionSharedData
class UnsharpMaskImageFilter
class UnsharpMaskLevelSetImageFilter
class UpdateMalcolmSparseLevelSet
class UpdateShiSparseLevelSet
class UpdateWhitakerSparseLevelSet
class ValarrayImageContainer
class ValuedRegionalExtremaImageFilter
class ValuedRegionalMaximaImageFilter
class ValuedRegionalMinimaImageFilter
class VanHerkGilWermanDilateImageFilter
class VanHerkGilWermanErodeDilateImageFilter
class VanHerkGilWermanErodeImageFilter
class VariableLengthVector
class VariableSizeMatrix
class VarianceImageFunction
class Vector
class VectorAnisotropicDiffusionFunction
class VectorConfidenceConnectedImageFilter
class VectorConnectedComponentImageFilter
class VectorContainer
class VectorCurvatureAnisotropicDiffusionImageFilter
class VectorCurvatureNDAnisotropicDiffusionFunction
class VectorGradientAnisotropicDiffusionImageFilter
class VectorGradientMagnitudeImageFilter
class VectorGradientNDAnisotropicDiffusionFunction
class VectorImage
class VectorImageNeighborhoodAccessorFunctor
class VectorImageToImageAdaptor
class VectorImageToImageMetricTraitsv4
class VectorIndexSelectionCastImageFilter
class VectorInterpolateImageFunction
class VectorLinearInterpolateImageFunction
class VectorLinearInterpolateNearestNeighborExtrapolateImageFunction
class VectorMagnitudeImageFilter
class VectorMeanImageFunction
class VectorNearestNeighborInterpolateImageFunction
class VectorNeighborhoodInnerProduct
class VectorNeighborhoodOperatorImageFilter
class VectorRescaleIntensityImageFilter
class VectorThresholdSegmentationLevelSetFunction
class VectorThresholdSegmentationLevelSetImageFilter
class VectorToRGBImageAdaptor
class VelocityFieldTransform
class Version
class Versor
class VersorRigid3DTransform
class VersorRigid3DTransformOptimizer
class VersorTransform
class VersorTransformOptimizer
class VertexCell
class VideoFileReader
class VideoFileWriter
class VideoIOBase
class VideoIOBaseEnums
class VideoIOFactory
class VideoIOFactoryEnums
class VideoSource
class VideoStream
class VideoToVideoFilter
class VMMapData_10_2
class VMMapFileParser
class VMMapRecord
class VMMapSummaryRecord
class VnlComplexToComplex1DFFTImageFilter
class VnlComplexToComplexFFTImageFilter
class VnlFFTCommon
class VnlFFTImageFilterInitFactory
class VnlForward1DFFTImageFilter
class VnlForwardFFTImageFilter
class VnlHalfHermitianToRealInverseFFTImageFilter
class VnlInverse1DFFTImageFilter
class VnlInverseFFTImageFilter
class VnlRealToHalfHermitianForwardFFTImageFilter
class VolumeSplineKernelTransform
class VoronoiDiagram2D
class VoronoiDiagram2DGenerator
class VoronoiPartitioningImageFilter
class VoronoiSegmentationImageFilter
class VoronoiSegmentationImageFilterBase
class VoronoiSegmentationRGBImageFilter
class VotingBinaryHoleFillingImageFilter
class VotingBinaryImageFilter
class VotingBinaryIterativeHoleFillingImageFilter
class VoxBoCUBImageIO
class VoxBoCUBImageIOFactory
class VTKImageExport
class VTKImageExportBase
class VTKImageImport
class VTKImageIO
class VTKImageIOFactory
class VTKPolyDataMeshIO
class VTKPolyDataMeshIOFactory
class VTKPolyDataReader
class VTKPolyDataWriter
class WarpHarmonicEnergyCalculator
class WarpImageFilter
class WarpMeshFilter
class WarpVectorImageFilter
class WatershedImageFilter
class WatershedMiniPipelineProgressCommand
class WeakPointer
class WeightedAddImageFilter
class WhitakerSparseLevelSetImage
class WhiteTopHatImageFilter
class WienerDeconvolutionImageFilter
class WindowedSincInterpolateImageFunction
class WisdomFilenameGeneratorBase
class WrapPadImageFilter
class XMLFileOutputWindow
class XMLFilterWatcher
class XMLReader
class XMLReaderBase
class XMLWriterBase
class XorImageFilter
class YenThresholdCalculator
class YenThresholdImageFilter
class ZeroCrossingBasedEdgeDetectionImageFilter
class ZeroCrossingImageFilter
class ZeroFluxNeumannBoundaryCondition
class ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy
class ZeroFluxNeumannPadImageFilter
Typedefs
using BooleanStdVectorType = std::vector< Boolean >
using CellGeometryEnum = CommonEnums::CellGeometry
using ChoiceMethodEnum = MergeLabelMapFilterEnums::ChoiceMethod
using CompositeTransformIOHelper = CompositeTransformIOHelperTemplate< double >
using ConjugateGradientLineSearchOptimizerv4 = ConjugateGradientLineSearchOptimizerv4Template< double >
using CostFunction = CostFunctionTemplate< double >
using EigenValueOrderEnum = SymmetricEigenAnalysisEnums::EigenValueOrder
using FilenamesContainer = std::vector< std::string >
using GaussianOrderEnum = RecursiveGaussianImageFilterEnums::GaussianOrder
using GradientDescentOptimizerBasev4 = GradientDescentOptimizerBasev4Template< double >
using GradientDescentOptimizerBasev4ModifyGradientByLearningRateThreader = GradientDescentOptimizerBasev4ModifyGradientByLearningRateThreaderTemplate< double >
using GradientDescentOptimizerBasev4ModifyGradientByScalesThreader = GradientDescentOptimizerBasev4ModifyGradientByScalesThreaderTemplate< double >
using HDF5TransformIO = HDF5TransformIOTemplate< double >
using IdentifierType = SizeValueType
template<unsigned int VDimension>
using ImageRegionIndexRange = IndexRange< VDimension, false >
using IndexValueType = long
using InputStreamType = std::istream
using IOByteOrderEnum = CommonEnums::IOByteOrder
using IOComponentEnum = CommonEnums::IOComponent
using IOFileEnum = CommonEnums::IOFile
using IOFileModeEnum = CommonEnums::IOFileMode
using IOPixelEnum = CommonEnums::IOPixel
using LibHandle = itksys::DynamicLoader::LibraryHandle
using MatlabTransformIO = MatlabTransformIOTemplate< double >
using ModifiedTimeType = SizeValueType
using MultiGradientOptimizerv4 = MultiGradientOptimizerv4Template< double >
using MultiStartOptimizerv4 = MultiStartOptimizerv4Template< double >
using ObjectToObjectMetricBase = ObjectToObjectMetricBaseTemplate< double >
using ObjectToObjectOptimizerBase = ObjectToObjectOptimizerBaseTemplate< double >
using OffsetValueType = long
using OptimizerParameterScalesEstimator = OptimizerParameterScalesEstimatorTemplate< double >
using OutputStreamType = std::ostream
using QuasiNewtonOptimizerv4 = QuasiNewtonOptimizerv4Template< double >
using QuasiNewtonOptimizerv4EstimateNewtonStepThreader = QuasiNewtonOptimizerv4EstimateNewtonStepThreaderTemplate< double >
using SamplingStrategyEnum = RegistrationParameterScalesEstimatorEnums::SamplingStrategy
using SerieUIDContainer = std::vector< std::string >
using SingleValuedCostFunctionv4 = SingleValuedCostFunctionv4Template< double >
using SizeValueType = unsigned long
using SpacePrecisionType = double
using StopConditionObjectToObjectOptimizerEnum = ObjectToObjectOptimizerBaseTemplateEnums::StopConditionObjectToObjectOptimizer
using SymbolPointer = itksys::DynamicLoader::SymbolPointer
using ThreadIdType = unsigned int
using TransformBase = TransformBaseTemplate< double >
using TransformFileReader = itk::TransformFileReaderTemplate< double >
using TransformFileWriter = itk::TransformFileWriterTemplate< double >
using TransformIOBase = itk::TransformIOBaseTemplate< double >
using TransformIOFactory = TransformIOFactoryTemplate< double >
using TxtTransformIO = TxtTransformIOTemplate< double >
template<unsigned int VDimension>
using ZeroBasedIndexRange = IndexRange< VDimension, true >
using GradientDescentLineSearchOptimizerv4 = GradientDescentLineSearchOptimizerv4Template< double >
using GradientDescentOptimizerv4 = GradientDescentOptimizerv4Template< double >
using LBFGS2Optimizerv4 = LBFGS2Optimizerv4Template< double >
Enumerations
enum {
B2_MASKFILE_BLACK = 0 ,
B2_MASKFILE_WHITE = 1 ,
B2_MASKFILE_GRAY = 2
}
enum class GPUFiniteDifferenceFilterEnum : uint8_t {
UNINITIALIZED ,
INITIALIZED
}
Functions
template<typename TInputImage , typename TOutputImage >
void BoxAccumulateFunction (const TInputImage *inputImage, const TOutputImage *outputImage, typename TInputImage::RegionType inputRegion, typename TOutputImage::RegionType outputRegion)
template<typename TInputImage , typename TOutputImage >
void BoxMeanCalculatorFunction (const TInputImage *accImage, TOutputImage *outputImage, typename TInputImage::RegionType inputRegion, typename TOutputImage::RegionType outputRegion, typename TInputImage::SizeType radius)
template<typename TInputImage , typename TOutputImage >
void BoxSigmaCalculatorFunction (const TInputImage *accImage, TOutputImage *outputImage, typename TInputImage::RegionType inputRegion, typename TOutputImage::RegionType outputRegion, typename TInputImage::SizeType radius)
template<typename TInputImage , typename TOutputImage >
void BoxSquareAccumulateFunction (const TInputImage *inputImage, TOutputImage *outputImage, typename TInputImage::RegionType inputRegion, typename TOutputImage::RegionType outputRegion)
void ClearContent (FancyString &input)
void ITKCommon_EXPORT CompensatedSummationAddElement (double &compensation, double &sum, const double element)
void ITKCommon_EXPORT CompensatedSummationAddElement (float &compensation, float &sum, const float element)
template<typename TImage , typename TBres , typename TLine >
int ComputeStartEnd (const typename TImage::IndexType StartIndex, const TLine line, const float tol, const typename TBres::OffsetArray LineOffsets, const typename TImage::RegionType AllImage, unsigned int &start, unsigned int &end)
template<typename TImage , typename TBres >
void CopyLineToImage (const typename TImage::Pointer output, const typename TImage::IndexType StartIndex, const typename TBres::OffsetArray LineOffsets, std::vector< typename TImage::PixelType > &outbuffer, const unsigned int start, const unsigned int end)
template<typename TInputMesh , typename TOutputMesh >
void CopyMeshToMesh (const TInputMesh *in, TOutputMesh *out)
template<typename TInputMesh , typename TOutputMesh >
void CopyMeshToMeshCellData (const TInputMesh *in, TOutputMesh *out)
template<typename TInputMesh , typename TOutputMesh >
void CopyMeshToMeshCells (const TInputMesh *in, TOutputMesh *out)
template<typename TInputMesh , typename TOutputMesh >
void CopyMeshToMeshEdgeCells (const TInputMesh *in, TOutputMesh *out)
template<typename TInputMesh , typename TOutputMesh >
void CopyMeshToMeshPointData (const TInputMesh *in, TOutputMesh *out)
template<typename TInputMesh , typename TOutputMesh >
void CopyMeshToMeshPoints (const TInputMesh *in, TOutputMesh *out)
template<typename TImage >
std::vector< typename TImage::OffsetType > CornerOffsets (const TImage *im)
ITKCommon_EXPORT Vector< double, 3 > CrossProduct (const Vector< double, 3 > &, const Vector< double, 3 > &)
ITKCommon_EXPORT Vector< float, 3 > CrossProduct (const Vector< float, 3 > &, const Vector< float, 3 > &)
ITKCommon_EXPORT Vector< int, 3 > CrossProduct (const Vector< int, 3 > &, const Vector< int, 3 > &)
ITKCommon_EXPORT void CrossProduct (CovariantVector< double, 3 > &, const Vector< double, 3 > &, const Vector< double, 3 > &)
ITKCommon_EXPORT void CrossProduct (CovariantVector< float, 3 > &, const Vector< float, 3 > &, const Vector< float, 3 > &)
ITKCommon_EXPORT void CrossProduct (CovariantVector< int, 3 >, const Vector< int, 3 > &, const Vector< int, 3 > &)
template<typename TImage , typename TBres , typename TAnchor , typename TLine >
void DoAnchorFace (const TImage *input, TImage *output, typename TImage::PixelType border, TLine line, TAnchor &AnchorLine, typename TBres::OffsetArray LineOffsets, std::vector< typename TImage::PixelType > &inbuffer, std::vector< typename TImage::PixelType > &outbuffer, const typename TImage::RegionType AllImage, const typename TImage::RegionType face)
template<typename TImage , typename TBres , typename TFunction , typename TLine >
void DoFace (typename TImage::ConstPointer input, typename TImage::Pointer output, typename TImage::PixelType border, TLine line, const typename TBres::OffsetArray LineOffsets, const unsigned int KernLen, std::vector< typename TImage::PixelType > &pixbuffer, std::vector< typename TImage::PixelType > &fExtBuffer, std::vector< typename TImage::PixelType > &rExtBuffer, const typename TImage::RegionType AllImage, const typename TImage::RegionType face)
template<typename T >
void EncapsulateMetaData (MetaDataDictionary &Dictionary, const char *key, const T &invalue)
template<typename PixelType , typename TFunction >
void FillForwardExt (std::vector< PixelType > &pixbuffer, std::vector< PixelType > &fExtBuffer, const unsigned int KernLen, unsigned int len)
template<typename TImage , typename TBres , typename TLine >
int FillLineBuffer (typename TImage::ConstPointer input, const typename TImage::IndexType StartIndex, const TLine line, const float tol, const typename TBres::OffsetArray LineOffsets, const typename TImage::RegionType AllImage, std::vector< typename TImage::PixelType > &inbuffer, unsigned int &start, unsigned int &end)
template<typename PixelType , typename TFunction >
void FillReverseExt (std::vector< PixelType > &pixbuffer, std::vector< PixelType > &rExtBuffer, const unsigned int KernLen, unsigned int len)
std::string Get64BitPragma ()
template<typename TLine >
unsigned int GetLinePixels (const TLine line)
int GetPixelDimension (const std::type_info &intype)
const std::string ITKIOTransformHDF5_EXPORT GetTransformName (int)
std::string GetTypename (const std::type_info &intype)
void GetTypenameInString (const std::type_info &intype, std::ostringstream &ret)
bool GetValidTypename (const std::type_info &intype, const std::vector< std::string > &validtypes, std::string &retTypeName)
IMAGEIOBASE_TYPEMAP (char, std::numeric_limits< char >::is_signed ? IOComponentEnum::CHAR :IOComponentEnum::UCHAR)
IMAGEIOBASE_TYPEMAP (double, IOComponentEnum::DOUBLE)
IMAGEIOBASE_TYPEMAP (float, IOComponentEnum::FLOAT)
IMAGEIOBASE_TYPEMAP (int, IOComponentEnum::INT)
IMAGEIOBASE_TYPEMAP (long long, IOComponentEnum::LONGLONG)
IMAGEIOBASE_TYPEMAP (long, IOComponentEnum::LONG)
IMAGEIOBASE_TYPEMAP (short, IOComponentEnum::SHORT)
IMAGEIOBASE_TYPEMAP (signed char, IOComponentEnum::CHAR)
IMAGEIOBASE_TYPEMAP (unsigned char, IOComponentEnum::UCHAR)
IMAGEIOBASE_TYPEMAP (unsigned int, IOComponentEnum::UINT)
IMAGEIOBASE_TYPEMAP (unsigned long long, IOComponentEnum::ULONGLONG)
IMAGEIOBASE_TYPEMAP (unsigned long, IOComponentEnum::ULONG)
IMAGEIOBASE_TYPEMAP (unsigned short, IOComponentEnum::USHORT)
EigenValueOrderEnum Int2EigenValueOrderEnum (const uint8_t value)
bool IsGPUAvailable ()
ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE (CovariantVector)
ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE (FixedArray)
ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE (Point)
ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE (Vector)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (bool)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (char)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (double)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (float)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (int)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (long long)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (long)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (short)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (signed char)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (unsigned char)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (unsigned int)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (unsigned long long)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (unsigned long)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (unsigned short)
ITK_MESH_DEFAULTCONVERTTRAITS_ARRAY_TYPE_ALL_TYPES_MACRO (Array)
ITK_MESH_DEFAULTCONVERTTRAITS_ARRAY_TYPE_ALL_TYPES_MACRO (VariableLengthVector)
ITK_MESH_DEFAULTCONVERTTRAITS_COMPLEX_TYPE (double)
ITK_MESH_DEFAULTCONVERTTRAITS_COMPLEX_TYPE (float)
ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO (CovariantVector)
ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO (FixedArray)
ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO (Point)
ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO (Vector)
ITK_MESH_DEFAULTCONVERTTRAITS_MATRIX_TYPE_ALL_TYPES_MACRO (Matrix)
itkGPUKernelClassMacro (GPUBinaryThresholdImageFilterKernel)
itkGPUKernelClassMacro (GPUCastImageFilterKernel)
itkGPUKernelClassMacro (GPUDemonsRegistrationFunctionKernel)
itkGPUKernelClassMacro (GPUGradientNDAnisotropicDiffusionFunctionKernel)
itkGPUKernelClassMacro (GPUImageOpsKernel)
itkGPUKernelClassMacro (GPUMeanImageFilterKernel)
itkGPUKernelClassMacro (GPUNeighborhoodOperatorImageFilterKernel)
itkGPUKernelClassMacro (GPUPDEDeformableRegistrationFilterKernel)
itkGPUKernelClassMacro (GPUReductionKernel)
itkGPUKernelClassMacro (GPUScalarAnisotropicDiffusionFunctionKernel)
class ITKGPUFiniteDifference_EXPORT itkGPUKernelMacro (GPUDenseFiniteDifferenceImageFilterKernel)
template<typename TChainCodePath , typename TPathInput >
void MakeChainCodeTracePath (TChainCodePath &chainPath, const TPathInput &inPath, bool restrictMovement=false)
template<typename TInputImage , typename TLine >
TInputImage::RegionType MakeEnlargedFace (const TInputImage *input, const typename TInputImage::RegionType AllImage, const TLine line)
MESHIOBASE_TYPEMAP (char, IOComponentEnum::CHAR)
MESHIOBASE_TYPEMAP (double, IOComponentEnum::DOUBLE)
MESHIOBASE_TYPEMAP (float, IOComponentEnum::FLOAT)
MESHIOBASE_TYPEMAP (int, IOComponentEnum::INT)
MESHIOBASE_TYPEMAP (long double, IOComponentEnum::LDOUBLE)
MESHIOBASE_TYPEMAP (long long, IOComponentEnum::LONGLONG)
MESHIOBASE_TYPEMAP (long, IOComponentEnum::LONG)
MESHIOBASE_TYPEMAP (short, IOComponentEnum::SHORT)
MESHIOBASE_TYPEMAP (unsigned char, IOComponentEnum::UCHAR)
MESHIOBASE_TYPEMAP (unsigned int, IOComponentEnum::UINT)
MESHIOBASE_TYPEMAP (unsigned long long, IOComponentEnum::ULONGLONG)
MESHIOBASE_TYPEMAP (unsigned long, IOComponentEnum::ULONG)
MESHIOBASE_TYPEMAP (unsigned short, IOComponentEnum::USHORT)
float MvtSunf (int numb)
template<typename TRegion , typename TLine >
bool NeedToDoFace (const TRegion AllImage, const TRegion face, const TLine line)
void OpenCLCheckError (cl_int error, const char *filename="", int lineno=0, const char *location="")
cl_device_id * OpenCLGetAvailableDevices (cl_platform_id platform, cl_device_type devType, cl_uint *numAvailableDevices)
int OpenCLGetLocalBlockSize (unsigned int ImageDim)
cl_device_id OpenCLGetMaxFlopsDev (cl_context cxGPUContext)
void OpenCLPrintDeviceInfo (cl_device_id device, bool verbose=false)
cl_platform_id OpenCLSelectPlatform (const char *name)
template<unsigned int VDimension>
bool operator!= (const Index< VDimension > &one, const Index< VDimension > &two)
template<typename TPixel >
bool operator!= (const NeighborhoodAllocator< TPixel > &lhs, const NeighborhoodAllocator< TPixel > &rhs)
template<unsigned int VDimension>
bool operator!= (const Offset< VDimension > &one, const Offset< VDimension > &two)
template<unsigned int VDimension>
bool operator!= (const Size< VDimension > &one, const Size< VDimension > &two)
template<typename T , unsigned int VVectorDimension>
CovariantVector< T, VVectorDimension > operator* (const T &scalar, const CovariantVector< T, VVectorDimension > &v)
template<typename T , unsigned int VVectorDimension>
Vector< T, VVectorDimension > operator* (const T &scalar, const Vector< T, VVectorDimension > &v)
template<typename T , unsigned int VVectorDimension>
T operator* (const Vector< T, VVectorDimension > &contravariant, const CovariantVector< T, VVectorDimension > &covariant)
template<typename TImage >
ConstNeighborhoodIterator< TImage > operator+ (const ConstNeighborhoodIterator< TImage > &it, const typename ConstNeighborhoodIterator< TImage >::OffsetType &ind)
template<typename TImage >
ConstNeighborhoodIteratorWithOnlyIndex< TImage > operator+ (const ConstNeighborhoodIteratorWithOnlyIndex< TImage > &it, const typename ConstNeighborhoodIteratorWithOnlyIndex< TImage >::OffsetType &ind)
template<typename TImage >
ConstNeighborhoodIterator< TImage > operator+ (const typename ConstNeighborhoodIterator< TImage >::OffsetType &ind, const ConstNeighborhoodIterator< TImage > &it)
template<typename TImage >
ConstNeighborhoodIteratorWithOnlyIndex< TImage > operator+ (const typename ConstNeighborhoodIteratorWithOnlyIndex< TImage >::OffsetType &ind, const ConstNeighborhoodIteratorWithOnlyIndex< TImage > &it)
template<typename TImage >
ConstNeighborhoodIterator< TImage > operator- (const ConstNeighborhoodIterator< TImage > &it, const typename ConstNeighborhoodIterator< TImage >::OffsetType &ind)
template<typename TImage >
ConstNeighborhoodIteratorWithOnlyIndex< TImage > operator- (const ConstNeighborhoodIteratorWithOnlyIndex< TImage > &it, const typename ConstNeighborhoodIteratorWithOnlyIndex< TImage >::OffsetType &ind)
template<unsigned int VDimension>
bool operator< (const Index< VDimension > &one, const Index< VDimension > &two)
template<unsigned int VDimension>
bool operator< (const Offset< VDimension > &one, const Offset< VDimension > &two)
template<unsigned int VDimension>
bool operator< (const Size< VDimension > &one, const Size< VDimension > &two)
template<class T , class TU >
bool operator< (const SmartPointer< T > &l, const SmartPointer< TU > &r) noexcept
template<typename T >
FancyString & operator<< (FancyString &s, const Array< T > &data)
template<typename T >
FancyString & operator<< (FancyString &s, const std::vector< T > &data)
template<typename T >
FancyString & operator<< (FancyString &s, const T &data)
FancyString & operator<< (FancyString &s, void(*mf)(FancyString &))
template<typename TComponent , unsigned int VDimension>
OutputStreamType & operator<< (OutputStreamType &os, const SymmetricSecondRankTensor< TComponent, VDimension > &c)
template<typename TPixel >
std::ostream & operator<< (std::ostream &o, const NeighborhoodAllocator< TPixel > &a)
template<>
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &os, const Array2D< double > &arr)
template<>
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &os, const Array2D< float > &arr)
template<typename TValue >
std::ostream & operator<< (std::ostream &os, const Array2D< TValue > &arr)
template<typename TValue >
std::ostream & operator<< (std::ostream &os, const Array< TValue > &arr)
template<typename T >
std::ostream & operator<< (std::ostream &os, const AutoPointer< T > p)
template<typename TValue , unsigned int VLength>
std::ostream & operator<< (std::ostream &os, const FixedArray< TValue, VLength > &arr)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &os, const ImageIORegion &region)
template<unsigned int VImageDimension>
std::ostream & operator<< (std::ostream &os, const ImageRegion< VImageDimension > &region)
template<unsigned int VDimension>
std::ostream & operator<< (std::ostream &os, const Index< VDimension > &obj)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &os, const LightObject &o)
template<typename T , unsigned int VRows, unsigned int VColumns>
std::ostream & operator<< (std::ostream &os, const Matrix< T, VRows, VColumns > &v)
ITKPolynomials_EXPORT std::ostream & operator<< (std::ostream &os, const MultivariateLegendrePolynomial &poly)
template<typename TPixel , unsigned int VDimension, typename TContainer >
std::ostream & operator<< (std::ostream &os, const Neighborhood< TPixel, VDimension, TContainer > &neighborhood)
template<unsigned int VDimension>
std::ostream & operator<< (std::ostream &os, const Offset< VDimension > &ind)
template<typename T , unsigned int VPointDimension>
std::ostream & operator<< (std::ostream &os, const Point< T, VPointDimension > &vct)
template<typename TComponent >
std::ostream & operator<< (std::ostream &os, const RGBAPixel< TComponent > &c)
template<typename TComponent >
std::ostream & operator<< (std::ostream &os, const RGBPixel< TComponent > &c)
template<unsigned int VDimension>
std::ostream & operator<< (std::ostream &os, const Size< VDimension > &obj)
template<typename T >
std::ostream & operator<< (std::ostream &os, const SmartPointer< T > p)
template<typename TImage , typename TBoundaryCondition >
std::ostream & operator<< (std::ostream &os, const std::vector< itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition > > &mv)
template<typename TMatrix , typename TVector , typename TEigenMatrix >
std::ostream & operator<< (std::ostream &os, const SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix > &s)
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix >
std::ostream & operator<< (std::ostream &os, const SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix > &s)
ITKVideoCore_EXPORT std::ostream & operator<< (std::ostream &os, const TemporalRegion &region)
template<typename T >
std::ostream & operator<< (std::ostream &os, const VariableSizeMatrix< T > &v)
template<typename T , unsigned int VVectorDimension>
std::ostream & operator<< (std::ostream &os, const Vector< T, VVectorDimension > &vct)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Versor< T > &v)
template<typename T >
std::ostream & operator<< (std::ostream &os, const WeakPointer< T > p)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, CellGeometryEnum value)
ITKQuadEdgeMeshFiltering_EXPORT std::ostream & operator<< (std::ostream &out, const BorderQuadEdgeMeshFilterEnums::BorderPick value)
ITKQuadEdgeMeshFiltering_EXPORT std::ostream & operator<< (std::ostream &out, const BorderQuadEdgeMeshFilterEnums::BorderTransform value)
ITKFFT_EXPORT std::ostream & operator<< (std::ostream &out, const ComplexToComplexFFTImageFilterEnums::TransformDirection value)
ITKRegionGrowing_EXPORT std::ostream & operator<< (std::ostream &out, const ConnectedThresholdImageFilterEnums::Connectivity value)
ITKConvolution_EXPORT std::ostream & operator<< (std::ostream &out, const ConvolutionImageFilterBaseEnums::ConvolutionImageFilterOutputRegion value)
ITKDeformableMesh_EXPORT std::ostream & operator<< (std::ostream &out, const DeformableSimplexMesh3DGradientConstraintForceFilterEnums::SIDE value)
ITKDiffusionTensorImage_EXPORT std::ostream & operator<< (std::ostream &out, const DiffusionTensor3DReconstructionImageFilterEnums::GradientImageFormat value)
ITKSpatialObjects_EXPORT std::ostream & operator<< (std::ostream &out, const DTITubeSpatialObjectPointEnums::DTITubeSpatialObjectPointField value)
ITKPDEDeformableRegistration_EXPORT std::ostream & operator<< (std::ostream &out, const ESMDemonsRegistrationFunctionEnums::Gradient value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const ExtractImageFilterEnums::DirectionCollapseStrategy value)
ITKFastMarching_EXPORT std::ostream & operator<< (std::ostream &out, const FastMarchingImageFilterEnums::Label value)
ITKFastMarching_EXPORT std::ostream & operator<< (std::ostream &out, const FastMarchingReachedTargetNodesStoppingCriterionEnums::TargetCondition value)
ITKFastMarching_EXPORT std::ostream & operator<< (std::ostream &out, const FastMarchingTraitsEnums::TopologyCheck value)
ITKSmoothing_EXPORT std::ostream & operator<< (std::ostream &out, const FFTDiscreteGaussianImageFilterEnums::KernelSource value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const FloatingPointExceptionsEnums::ExceptionAction value)
ITKOptimizers_EXPORT std::ostream & operator<< (std::ostream &out, const FRPROptimizerEnums::Optimization value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const FrustumSpatialFunctionEnums::RotationPlane value)
ITKIOGDCM_EXPORT std::ostream & operator<< (std::ostream &out, const GDCMImageIOEnums::Compression value)
ITKGPUFiniteDifference_EXPORT std::ostream & operator<< (std::ostream &out, const GPUFiniteDifferenceFilterEnum value)
ITKOptimizers_EXPORT std::ostream & operator<< (std::ostream &out, const GradientDescentOptimizerEnums::StopConditionGradientDescentOptimizer value)
ITKRegistrationMethodsv4_EXPORT std::ostream & operator<< (std::ostream &out, const ImageRegistrationMethodv4Enums::MetricSamplingStrategy value)
ITKIOImageBase_EXPORT std::ostream & operator<< (std::ostream &out, const IOCommonEnums::AtomicPixel value)
ITKIOJPEG2000_EXPORT std::ostream & operator<< (std::ostream &out, const JPEG2000ImageIOInternalEnums::DecodingFormat value)
ITKIOJPEG2000_EXPORT std::ostream & operator<< (std::ostream &out, const JPEG2000ImageIOInternalEnums::DFMFormat value)
ITKQuadEdgeMeshFiltering_EXPORT std::ostream & operator<< (std::ostream &out, const LaplacianDeformationQuadEdgeMeshFilterEnums::Area value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const LoggerBaseEnums::PriorityLevel value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const LoggerBaseEnums::TimeStampFormat value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const LoggerThreadWrapperEnums::Operation value)
ITKMathematicalMorphology_EXPORT std::ostream & operator<< (std::ostream &out, const MathematicalMorphologyEnums::Algorithm value)
ITKLabelMap_EXPORT std::ostream & operator<< (std::ostream &out, const MergeLabelMapFilterEnums::ChoiceMethod value)
ITKMarkovRandomFieldsClassifiers_EXPORT std::ostream & operator<< (std::ostream &out, const MRFImageFilterEnums::MRFStop value)
ITKImageFeature_EXPORT std::ostream & operator<< (std::ostream &out, const MultiScaleHessianBasedMeasureImageFilterEnums::SigmaStepMethod value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const MultiThreaderBaseEnums::Threader value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const MultiThreaderBaseEnums::ThreadExitCode value)
ITKQuadEdgeMeshFiltering_EXPORT std::ostream & operator<< (std::ostream &out, const NormalQuadEdgeMeshFilterEnums::Weight value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const ObjectEnums::RegionEnum value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const ObjectFactoryEnums::InsertionPosition value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const ObjectStoreEnums::GrowthStrategy value)
ITKOptimizersv4_EXPORT std::ostream & operator<< (std::ostream &out, const ObjectToObjectMetricBaseTemplateEnums::GradientSource value)
ITKOptimizersv4_EXPORT std::ostream & operator<< (std::ostream &out, const ObjectToObjectMetricBaseTemplateEnums::MetricCategory value)
ITKOptimizersv4_EXPORT std::ostream & operator<< (std::ostream &out, const ObjectToObjectOptimizerBaseTemplateEnums::StopConditionObjectToObjectOptimizer value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const OctreeEnums::LeafIdentifier value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const OctreeEnums::Octree value)
ITKDenoising_EXPORT std::ostream & operator<< (std::ostream &out, const PatchBasedDenoisingBaseImageFilterEnums::ComponentSpace value)
ITKDenoising_EXPORT std::ostream & operator<< (std::ostream &out, const PatchBasedDenoisingBaseImageFilterEnums::FilterState value)
ITKDenoising_EXPORT std::ostream & operator<< (std::ostream &out, const PatchBasedDenoisingBaseImageFilterEnums::NoiseModel value)
ITKSmoothing_EXPORT std::ostream & operator<< (std::ostream &out, const RecursiveGaussianImageFilterEnums::GaussianOrder value)
ITKOptimizersv4_EXPORT std::ostream & operator<< (std::ostream &out, const RegistrationParameterScalesEstimatorEnums::SamplingStrategy value)
ITKOptimizers_EXPORT std::ostream & operator<< (std::ostream &out, const RegularStepGradientDescentBaseOptimizerEnums::StopCondition value)
ITKColormap_EXPORT std::ostream & operator<< (std::ostream &out, const ScalarToRGBColormapImageFilterEnums::RGBColormapFilter value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const SpatialOrientationEnums::CoordinateMajornessTerms value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const SpatialOrientationEnums::CoordinateTerms value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const SpatialOrientationEnums::ValidCoordinateOrientations value)
ITKOptimizers_EXPORT std::ostream & operator<< (std::ostream &out, const SPSAOptimizerEnums::StopConditionSPSAOptimizer value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, const SymmetricEigenAnalysisEnums::EigenValueOrder value)
ITKTransform_EXPORT std::ostream & operator<< (std::ostream &out, const TransformBaseTemplateEnums::TransformCategory value)
ITKMesh_EXPORT std::ostream & operator<< (std::ostream &out, const TriangleMeshCurvatureCalculatorEnums::Curvatures value)
ITKVideoIO_EXPORT std::ostream & operator<< (std::ostream &out, const VideoIOBaseEnums::ReadFrom value)
ITKVideoIO_EXPORT std::ostream & operator<< (std::ostream &out, const VideoIOFactoryEnums::IOMode value)
ITKSpatialObjects_EXPORT std::ostream & operator<< (std::ostream &out, ContourSpatialObjectEnums::InterpolationMethod value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, GaussianDerivativeOperatorEnums::InterpolationMode value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, IOByteOrderEnum value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, IOComponentEnum value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, IOFileEnum value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, IOFileModeEnum value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, IOPixelEnum value)
ITKOptimizersv4_EXPORT std::ostream & operator<< (std::ostream &out, LBFGS2Optimizerv4Enums::LineSearchMethod value)
ITKCommon_EXPORT std::ostream & operator<< (std::ostream &out, MeshEnums::MeshClassCellsAllocationMethod value)
ITKQuadEdgeMesh_EXPORT std::ostream & operator<< (std::ostream &out, QuadEdgeMeshEulerOperatorFlipEdgeFunctionEnums::EdgeStatusType value)
ITKVideoCore_EXPORT std::ostream & operator<< (std::ostream &out, TemporalDataObjectEnums::TemporalUnit value)
template<>
ITKCommon_EXPORT std::ostream & operator<<<double > (std::ostream &os, const Array< double > &arr)
template<>
ITKCommon_EXPORT std::ostream & operator<<<float > (std::ostream &os, const Array< float > &arr)
template<unsigned int VDimension>
bool operator<= (const Index< VDimension > &one, const Index< VDimension > &two)
template<unsigned int VDimension>
bool operator<= (const Offset< VDimension > &one, const Offset< VDimension > &two)
template<unsigned int VDimension>
bool operator<= (const Size< VDimension > &one, const Size< VDimension > &two)
template<class T , class TU >
bool operator<= (const SmartPointer< T > &l, const SmartPointer< TU > &r) noexcept
template<unsigned int VDimension>
bool operator== (const Index< VDimension > &one, const Index< VDimension > &two)
template<typename TPixel >
bool operator== (const NeighborhoodAllocator< TPixel > &lhs, const NeighborhoodAllocator< TPixel > &rhs)
template<unsigned int VDimension>
bool operator== (const Offset< VDimension > &one, const Offset< VDimension > &two)
template<unsigned int VDimension>
bool operator== (const Size< VDimension > &one, const Size< VDimension > &two)
template<unsigned int VDimension>
bool operator> (const Index< VDimension > &one, const Index< VDimension > &two)
template<unsigned int VDimension>
bool operator> (const Offset< VDimension > &one, const Offset< VDimension > &two)
template<unsigned int VDimension>
bool operator> (const Size< VDimension > &one, const Size< VDimension > &two)
template<class T , class TU >
bool operator> (const SmartPointer< T > &l, const SmartPointer< TU > &r) noexcept
template<unsigned int VDimension>
bool operator>= (const Index< VDimension > &one, const Index< VDimension > &two)
template<unsigned int VDimension>
bool operator>= (const Offset< VDimension > &one, const Offset< VDimension > &two)
template<unsigned int VDimension>
bool operator>= (const Size< VDimension > &one, const Size< VDimension > &two)
template<class T , class TU >
bool operator>= (const SmartPointer< T > &l, const SmartPointer< TU > &r) noexcept
template<typename T >
FancyString & operator>> (FancyString &s, Array< T > &data)
template<typename T >
FancyString & operator>> (FancyString &s, std::vector< T > &data)
template<typename T >
FancyString & operator>> (FancyString &s, T &data)
template<typename TComponent , unsigned int VDimension>
InputStreamType & operator>> (InputStreamType &is, SymmetricSecondRankTensor< TComponent, VDimension > &dt)
template<typename T , unsigned int VPointDimension>
std::istream & operator>> (std::istream &is, Point< T, VPointDimension > &vct)
template<typename TComponent >
std::istream & operator>> (std::istream &is, RGBAPixel< TComponent > &c)
template<typename TComponent >
std::istream & operator>> (std::istream &is, RGBPixel< TComponent > &c)
template<typename T , unsigned int VVectorDimension>
std::istream & operator>> (std::istream &is, Vector< T, VVectorDimension > &vct)
template<typename T >
std::istream & operator>> (std::istream &is, Versor< T > &v)
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating point (float or double) or *a user-defined "real" numerical type with arithmetic operations defined *sufficient to compute derivatives. **\par Performance *This filter will automatically multithread if run with *SetUsePrincipleComponents
ITKIOImageBase_EXPORT void ReadRawBytesAfterSwapping (IOComponentEnum componentType, void *buffer, IOByteOrderEnum byteOrder, SizeValueType numberOfComponents)
template<typename TIterator >
TIterator * setConnectivity (TIterator *it, bool fullyConnected=false)
template<typename TIterator >
TIterator * setConnectivityLater (TIterator *it, bool fullyConnected=false)
template<typename TIterator >
TIterator * setConnectivityPrevious (TIterator *it, bool fullyConnected=false)
template<typename T >
T * Singleton (const char *globalName, std::function< void(void *)> func, std::function< void()> deleteFunc)
template<typename T >
void swap (Array< T > &a, Array< T > &b)
template<typename T , unsigned int VRows, unsigned int VColumns>
void swap (const Matrix< T, VRows, VColumns > &a, const Matrix< T, VRows, VColumns > &b)
template<typename T , unsigned int VVectorDimension>
void swap (CovariantVector< T, VVectorDimension > &a, CovariantVector< T, VVectorDimension > &b)
template<typename T >
void swap (DiffusionTensor3D< T > &a, DiffusionTensor3D< T > &b)
template<typename TValue , unsigned int VLength>
void swap (FixedArray< TValue, VLength > &a, FixedArray< TValue, VLength > &b)
template<unsigned int VDimension>
void swap (Index< VDimension > &one, Index< VDimension > &two)
void swap (MetaDataDictionary &a, MetaDataDictionary &b)
template<unsigned int VDimension>
void swap (Offset< VDimension > &one, Offset< VDimension > &two)
template<typename TCoordRep , unsigned int VPointDimension>
void swap (Point< TCoordRep, VPointDimension > &a, Point< TCoordRep, VPointDimension > &b)
template<typename T >
void swap (RGBAPixel< T > &a, RGBAPixel< T > &b)
template<typename T >
void swap (RGBPixel< T > &a, RGBPixel< T > &b)
template<unsigned int VDimension>
void swap (Size< VDimension > &one, Size< VDimension > &two)
template<typename T >
void swap (SmartPointer< T > &a, SmartPointer< T > &b) noexcept
template<typename T >
void swap (SymmetricSecondRankTensor< T > &a, SymmetricSecondRankTensor< T > &b)
template<typename T , unsigned int VVectorDimension>
void swap (Vector< T, VVectorDimension > &a, Vector< T, VVectorDimension > &b)
ITKIOImageBase_EXPORT void WriteRawBytesAfterSwapping (IOComponentEnum componentType, const void *buffer, std::ofstream &file, IOByteOrderEnum byteOrder, SizeValueType numberOfBytes, SizeValueType numberOfComponents)
template<typename TAutoPointerBase , typename TAutoPointerDerived >
void TransferAutoPointer (TAutoPointerBase &pa, TAutoPointerDerived &pb)
template<typename TDestination , class TSource >
TDestination bit_cast (const TSource &source)
template<unsigned int VImageDimension, vcl_size_t VMaximumCityblockDistance, bool VIncludeCenterPixel>
auto GenerateConnectedImageNeighborhoodShapeOffsets () noexcept
std::ostream & operator<< (std::ostream &os, const EventObject &e)
itkEventMacroDeclaration (NoEvent, EventObject)
itkEventMacroDeclaration (AnyEvent, EventObject)
itkEventMacroDeclaration (DeleteEvent, AnyEvent)
itkEventMacroDeclaration (StartEvent, AnyEvent)
itkEventMacroDeclaration (EndEvent, AnyEvent)
itkEventMacroDeclaration (ProgressEvent, AnyEvent)
itkEventMacroDeclaration (ExitEvent, AnyEvent)
itkEventMacroDeclaration (AbortEvent, AnyEvent)
itkEventMacroDeclaration (ModifiedEvent, AnyEvent)
itkEventMacroDeclaration (InitializeEvent, AnyEvent)
itkEventMacroDeclaration (IterationEvent, AnyEvent)
itkEventMacroDeclaration (MultiResolutionIterationEvent, IterationEvent)
itkEventMacroDeclaration (PickEvent, AnyEvent)
itkEventMacroDeclaration (StartPickEvent, PickEvent)
itkEventMacroDeclaration (EndPickEvent, PickEvent)
itkEventMacroDeclaration (AbortCheckEvent, PickEvent)
itkEventMacroDeclaration (FunctionEvaluationIterationEvent, IterationEvent)
itkEventMacroDeclaration (GradientEvaluationIterationEvent, IterationEvent)
itkEventMacroDeclaration (FunctionAndGradientEvaluationIterationEvent, IterationEvent)
itkEventMacroDeclaration (UserEvent, AnyEvent)
template<typename TImage >
ImageBufferRange< TImage > MakeImageBufferRange (TImage *const image)
template<typename TImageNeighborhoodShape >
std::vector< Offset< TImageNeighborhoodShape::ImageDimension > > GenerateImageNeighborhoodOffsets (const TImageNeighborhoodShape &shape)
template<unsigned int VImageDimension>
std::vector< Offset< VImageDimension > > GenerateRectangularImageNeighborhoodOffsets (const Size< VImageDimension > &radius)
template<typename... T>
auto MakeIndex (const T... values)
template<typename TContainer >
constexpr TContainer MakeFilled (typename TContainer::const_reference value)
template<typename TUnboundedArray >
auto make_unique_for_overwrite (const vcl_size_t numberOfElements)
template<typename T >
void EncapsulateMetaData (MetaDataDictionary &Dictionary, const std::string &key, const T &invalue)
template<typename T >
bool ExposeMetaData (const MetaDataDictionary &Dictionary, const std::string key, T &outval)
template<typename TValue >
std::string ConvertNumberToString (const TValue val)
template<typename TValue , typename... TVariadic>
auto MakePoint (const TValue firstValue, const TVariadic... otherValues)
template<typename... T>
auto MakeSize (const T... values)
template<class T , class TU >
bool operator== (const SmartPointer< T > &l, const SmartPointer< TU > &r) noexcept
template<class T >
bool operator== (const SmartPointer< T > &l, std::nullptr_t) noexcept
template<class T >
bool operator== (std::nullptr_t, const SmartPointer< T > &r) noexcept
template<class T , class TU >
bool operator!= (const SmartPointer< T > &l, const SmartPointer< TU > &r) noexcept
template<class T >
bool operator!= (const SmartPointer< T > &l, std::nullptr_t) noexcept
template<class T >
bool operator!= (std::nullptr_t, const SmartPointer< T > &r) noexcept
template<typename TValue , typename... TVariadic>
auto MakeVector (const TValue firstValue, const TVariadic... otherValues)
template<typename TFourierSeriesPath , typename TChainCodePath >
void MakeFourierSeriesPathTraceChainCode (TFourierSeriesPath &FSPath, const TChainCodePath &chainPath, unsigned int numHarmonics=8)
template<typename TOutputImage , typename ConvertPixelTraits = DefaultConvertPixelTraits<typename TOutputImage::IOPixelType>>
TOutputImage::Pointer ReadImage (const std::string &filename)
template<typename TImagePointer >
ITK_TEMPLATE_EXPORT void WriteImage (TImagePointer &&image, const std::string &filename, bool compress=false)
template<typename TOutputMesh , typename ConvertPointPixelTraits = MeshConvertPixelTraits<typename TOutputMesh::PixelType>, typename ConvertCellPixelTraits = MeshConvertPixelTraits<typename TOutputMesh::CellPixelType>>
TOutputMesh::Pointer ReadMesh (const std::string &filename)
template<typename TMeshPointer >
ITK_TEMPLATE_EXPORT void WriteMesh (TMeshPointer &&mesh, const std::string &filename, bool compress=false)
ITKIONIFTI_EXPORT std::ostream & operator<< (std::ostream &out, const NiftiImageIOEnums::Analyze75Flavor value)
ITKIONIFTI_EXPORT std::ostream & operator<< (std::ostream &out, const NiftiImageIOEnums::NiftiFileEnum value)
Variables
template<typename TPixelType , typename TCellTraits >
class ITK_TEMPLATE_EXPORT CellInterface
class ITK_FORWARD_EXPORT Command
template class ITKIOTransformBase_EXPORT_EXPLICIT CompositeTransformIOHelperTemplate< double >
template class ITKIOTransformBase_EXPORT_EXPLICIT CompositeTransformIOHelperTemplate< float >
class ITK_FORWARD_EXPORT DataObject
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating so it cannot multithread for data other than in Anisotropic Diffusion of Multivalued Images *with Application to Color Filtering
template<typename TInternalComputationValueType >
class ITK_FORWARD_EXPORT GradientDescentOptimizerBasev4Template
template class ITKIOTransformHDF5_EXPORT_EXPLICIT HDF5TransformIOTemplate< double >
template class ITKIOTransformHDF5_EXPORT_EXPLICIT HDF5TransformIOTemplate< float >
template<unsigned int VImageDimension>
class ITK_TEMPLATE_EXPORT ImageBase
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar images
ITKIOImageBase_EXPORT const char *const ITK_ExperimentDate
ITKIOImageBase_EXPORT const char *const ITK_ExperimentTime
ITKIOImageBase_EXPORT const char *const ITK_FileNotes
ITKIOImageBase_EXPORT const char *const ITK_FileOriginator
ITKIOImageBase_EXPORT const char *const ITK_ImageFileBaseName
ITKIOImageBase_EXPORT const char *const ITK_ImageType
ITKIOImageBase_EXPORT const char *const ITK_InputFilterName
ITKIOImageBase_EXPORT const char *const ITK_NumberOfDimensions
ITKIOImageBase_EXPORT const char *const ITK_OnDiskBitPerPixel
ITKIOImageBase_EXPORT const char *const ITK_OnDiskStorageTypeName
ITKIOImageBase_EXPORT const char *const ITK_Origin
ITKIOImageBase_EXPORT const char *const ITK_OriginationDate
ITKIOImageBase_EXPORT const char *const ITK_PatientID
ITKIOImageBase_EXPORT const char *const ITK_PatientName
ITKIOImageBase_EXPORT const char *const ITK_ScanID
ITKIOImageBase_EXPORT const char *const ITK_Spacing
ITKIOImageBase_EXPORT const char *const ITK_VoxelUnits
ITKIOImageBase_EXPORT const char *const ITK_ZDirection
class ITK_FORWARD_EXPORT KLMSegmentationBorder
class ITK_FORWARD_EXPORT KLMSegmentationRegion
class ITK_FORWARD_EXPORT LBFGSBOptimizerHelper
class ITK_FORWARD_EXPORT LBFGSBOptimizerHelperv4
template<typename TInternalVnlOptimizerType >
class ITK_TEMPLATE_EXPORT LBFGSOptimizerBaseHelperv4
struct ITKIOMINC_HIDDEN MINCImageIOPImpl
template class ITKOptimizersv4_EXPORT_EXPLICIT ObjectToObjectOptimizerBaseTemplate< double >
template class ITKOptimizersv4_EXPORT_EXPLICIT ObjectToObjectOptimizerBaseTemplate< float >
class ITK_FORWARD_EXPORT OctreeBase
class ITK_FORWARD_EXPORT OctreeNodeBranch
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating so it cannot multithread for data other than in Anisotropic Diffusion of Multivalued Images *with Application to Color IEEE Transactions on Image No pp
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating so it cannot multithread for data other than in Anisotropic Diffusion of Multivalued Images *with Application to Color IEEE Transactions on Image Processing
class ITK_FORWARD_EXPORT ProcessObject
template<typename TInternalComputationValueType >
class ITK_FORWARD_EXPORT QuasiNewtonOptimizerv4Template
ITKIOImageBase_EXPORT const char *const ROI_NAME
ITKIOImageBase_EXPORT const char *const ROI_NUM_SEGMENTS
ITKIOImageBase_EXPORT const char *const ROI_PLANE
ITKIOImageBase_EXPORT const char *const ROI_SCAN_ID
ITKIOImageBase_EXPORT const char *const ROI_X_RESOLUTION
ITKIOImageBase_EXPORT const char *const ROI_X_SIZE
ITKIOImageBase_EXPORT const char *const ROI_Y_RESOLUTION
ITKIOImageBase_EXPORT const char *const ROI_Y_SIZE
ITKIOImageBase_EXPORT const char *const ROI_Z_RESOLUTION
ITKIOImageBase_EXPORT const char *const ROI_Z_SIZE
ITKIOImageBase_EXPORT const char *const SPM_ROI_SCALE
class ITK_FORWARD_EXPORT TemporalDataObject
template<typename TIterator >
class ITK_TEMPLATE_EXPORT ThreadedIteratorRangePartitioner
template class ITKIOTransformBase_EXPORT_EXPLICIT TransformFileReaderTemplate< double >
template class ITKIOTransformBase_EXPORT_EXPLICIT TransformFileReaderTemplate< float >
template class ITKIOTransformBase_EXPORT_EXPLICIT TransformFileWriterTemplate< double >
template class ITKIOTransformBase_EXPORT_EXPLICIT TransformFileWriterTemplate< float >
template class ITKIOTransformBase_EXPORT_EXPLICIT TransformIOBaseTemplate< double >
template class ITKIOTransformBase_EXPORT_EXPLICIT TransformIOBaseTemplate< float >
template class ITKIOTransformBase_EXPORT_EXPLICIT TransformIOFactoryTemplate< double >
template class ITKIOTransformBase_EXPORT_EXPLICIT TransformIOFactoryTemplate< float >
template class ITKIOTransformInsightLegacy_EXPORT_EXPLICIT TxtTransformIOTemplate< double >
template class ITKIOTransformInsightLegacy_EXPORT_EXPLICIT TxtTransformIOTemplate< float >
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating so it cannot multithread for data other than in * UsePrincipleComponents
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating so it cannot multithread for data other than in Anisotropic Diffusion of Multivalued Images *with Application to Color IEEE Transactions on Image * Vol
using MutexType = int
using FastMutexType = int
using ThreadFunctionType = void(*)(void *)
using ThreadProcessIdType = int
using ITK_THREAD_RETURN_TYPE = void
using ITK_THREAD_RETURN_FUNCTION_CALL_CONVENTION = itk::ITK_THREAD_RETURN_TYPE
constexpr vcl_size_t ITK_MAX_THREADS = 1
Detailed Description
The "itk" namespace contains all Insight Segmentation and Registration Toolkit (ITK) classes. There are several nested namespaces within the itk:: namespace.
This class generates two 2D-Gaussians (standard deviation RegionSize/2) One is shifted by 7,3 pixels from the other.
These two images are provided to the registration methods in this directory in order to obtain a uniform test input data.
Therefore the solution of the registration is |-7 -3|
TODO: This class needs to be more tightly integrated with the new multi-threaded ImageToImageMetric.
    The specification for this file format is taken from the
    web site https://analyzedirect.com/support/10.0Documents/Analyze_Resource_01.pdf
Author
Hans J. Johnson The University of Iowa 2002
    The specification for this file format is taken from the
    web site https://www.bic.mni.mcgill.ca/ServicesSoftware/MINC
Author
Vladimir S. FONOV Brain Imaging Center, Montreal Neurological Institute, McGill University, Montreal Canada 2012
Leila Baghdadi Mouse Imaging Centre, Toronto, Canada 2005.
Typedef Documentation
BooleanStdVectorType
using itk::BooleanStdVectorType = typedef std::vector<Boolean>
The type alias BooleanStdVectorType provides an alternative to std::vector<bool>. std::vector<bool> is not thread safe due to the possibility of multiple bits being packed together in the same memory location. BooleanStdVectorType does not have such a space optimization. BooleanStdVectorType is semantically like std::vector<bool>, but unlike std::vector<bool>, it does "avoid data races when the contents of the contained object in different elements in the same container [...] are modified concurrently", according to the C++ Standard, section [container.requirements.dataraces], "Container data races".
Definition at line 34 of file itkBooleanStdVector.h.
CellGeometryEnum
using itk::CellGeometryEnum = typedef CommonEnums::CellGeometry
Definition at line 162 of file itkCommonEnums.h.
ChoiceMethodEnum
using itk::ChoiceMethodEnum = typedef MergeLabelMapFilterEnums::ChoiceMethod
Definition at line 53 of file itkMergeLabelMapFilter.h.
CompositeTransformIOHelper
using itk::CompositeTransformIOHelper = typedef CompositeTransformIOHelperTemplate<double>
This helps to meet backward compatibility
Definition at line 98 of file itkCompositeTransformIOHelper.h.
ConjugateGradientLineSearchOptimizerv4
using itk::ConjugateGradientLineSearchOptimizerv4 = typedef ConjugateGradientLineSearchOptimizerv4Template<double>
This helps to meet backward compatibility
Definition at line 102 of file itkConjugateGradientLineSearchOptimizerv4.h.
CostFunction
using itk::CostFunction = typedef CostFunctionTemplate<double>
This helps to meet backward compatibility
Definition at line 69 of file itkCostFunction.h.
EigenValueOrderEnum
using itk::EigenValueOrderEnum = typedef SymmetricEigenAnalysisEnums::EigenValueOrder
Definition at line 142 of file itkSymmetricEigenAnalysis.h.
FastMutexType
using itk::FastMutexType = typedef int
Platform specific type alias for simple types
Definition at line 80 of file itkThreadSupport.h.
FilenamesContainer
using itk::FilenamesContainer = typedef std::vector<std::string>
Todo:
: remove these from the itk:: namespace
Definition at line 60 of file itkGDCMSeriesFileNames.h.
GaussianOrderEnum
using itk::GaussianOrderEnum = typedef RecursiveGaussianImageFilterEnums::GaussianOrder
Definition at line 49 of file itkRecursiveGaussianImageFilter.h.
GradientDescentLineSearchOptimizerv4
using itk::GradientDescentLineSearchOptimizerv4 = typedef GradientDescentLineSearchOptimizerv4Template<double>
This helps to meet backward compatibility
Definition at line 151 of file itkGradientDescentLineSearchOptimizerv4.h.
GradientDescentOptimizerBasev4
using itk::GradientDescentOptimizerBasev4 = typedef GradientDescentOptimizerBasev4Template<double>
This helps to meet backward compatibility
Definition at line 219 of file itkGradientDescentOptimizerBasev4.h.
GradientDescentOptimizerBasev4ModifyGradientByLearningRateThreader
using itk::GradientDescentOptimizerBasev4ModifyGradientByLearningRateThreader = typedef GradientDescentOptimizerBasev4ModifyGradientByLearningRateThreaderTemplate<double>
This helps to meet backward compatibility
Definition at line 68 of file itkGradientDescentOptimizerBasev4ModifyGradientByLearningRateThreader.h.
GradientDescentOptimizerBasev4ModifyGradientByScalesThreader
using itk::GradientDescentOptimizerBasev4ModifyGradientByScalesThreader = typedef GradientDescentOptimizerBasev4ModifyGradientByScalesThreaderTemplate<double>
This helps to meet backward compatibility
Definition at line 68 of file itkGradientDescentOptimizerBasev4ModifyGradientByScalesThreader.h.
GradientDescentOptimizerv4
using itk::GradientDescentOptimizerv4 = typedef GradientDescentOptimizerv4Template<double>
This helps to meet backward compatibility
Definition at line 255 of file itkGradientDescentOptimizerv4.h.
HDF5TransformIO
using itk::HDF5TransformIO = typedef HDF5TransformIOTemplate<double>
This helps to meet backward compatibility
Definition at line 171 of file itkHDF5TransformIO.h.
IdentifierType
using itk::IdentifierType = typedef SizeValueType
Same type as SizeValueType but when used as an Id (pointId, cellId, labelObjectId..)(it is unsigned)
Definition at line 87 of file itkIntTypes.h.
ImageRegionIndexRange
template<unsigned int VDimension> using itk::ImageRegionIndexRange = typedef IndexRange<VDimension, false>
Definition at line 461 of file itkIndexRange.h.
IndexValueType
using itk::IndexValueType = typedef long
The components of the Index array (they are signed)
Definition at line 90 of file itkIntTypes.h.
InputStreamType
using itk::InputStreamType = typedef std::istream
Definition at line 247 of file itkSymmetricSecondRankTensor.h.
IOByteOrderEnum
using itk::IOByteOrderEnum = typedef CommonEnums::IOByteOrder
Definition at line 161 of file itkCommonEnums.h.
IOComponentEnum
using itk::IOComponentEnum = typedef CommonEnums::IOComponent
Definition at line 158 of file itkCommonEnums.h.
IOFileEnum
using itk::IOFileEnum = typedef CommonEnums::IOFile
Definition at line 159 of file itkCommonEnums.h.
IOFileModeEnum
using itk::IOFileModeEnum = typedef CommonEnums::IOFileMode
Definition at line 160 of file itkCommonEnums.h.
IOPixelEnum
using itk::IOPixelEnum = typedef CommonEnums::IOPixel
Definition at line 157 of file itkCommonEnums.h.
ITK_THREAD_RETURN_FUNCTION_CALL_CONVENTION
using itk::ITK_THREAD_RETURN_FUNCTION_CALL_CONVENTION = typedef itk::ITK_THREAD_RETURN_TYPE
Platform specific type alias for simple types
Definition at line 88 of file itkThreadSupport.h.
ITK_THREAD_RETURN_TYPE
using itk::ITK_THREAD_RETURN_TYPE = typedef void
Platform specific type alias for simple types
Definition at line 86 of file itkThreadSupport.h.
LBFGS2Optimizerv4
using itk::LBFGS2Optimizerv4 = typedef LBFGS2Optimizerv4Template<double>
This helps to meet backward compatibility
Definition at line 574 of file itkLBFGS2Optimizerv4.h.
LibHandle
using itk::LibHandle = typedef itksys::DynamicLoader::LibraryHandle
Definition at line 38 of file itkDynamicLoader.h.
MatlabTransformIO
using itk::MatlabTransformIO = typedef MatlabTransformIOTemplate<double>
This helps to meet backward compatibility
Definition at line 75 of file itkMatlabTransformIO.h.
ModifiedTimeType
using itk::ModifiedTimeType = typedef SizeValueType
Type to count and reference the modification time of objects
Definition at line 102 of file itkIntTypes.h.
MultiGradientOptimizerv4
using itk::MultiGradientOptimizerv4 = typedef MultiGradientOptimizerv4Template<double>
This helps to meet backward compatibility
Definition at line 151 of file itkMultiGradientOptimizerv4.h.
MultiStartOptimizerv4
using itk::MultiStartOptimizerv4 = typedef MultiStartOptimizerv4Template<double>
This helps to meet backward compatibility
Definition at line 183 of file itkMultiStartOptimizerv4.h.
MutexType
using itk::MutexType = typedef int
Platform specific type alias for simple types
Definition at line 79 of file itkThreadSupport.h.
ObjectToObjectMetricBase
using itk::ObjectToObjectMetricBase = typedef ObjectToObjectMetricBaseTemplate<double>
This helps to meet backward compatibility
Definition at line 270 of file itkObjectToObjectMetricBase.h.
ObjectToObjectOptimizerBase
using itk::ObjectToObjectOptimizerBase = typedef ObjectToObjectOptimizerBaseTemplate<double>
This helps to meet backward compatibility
Definition at line 312 of file itkObjectToObjectOptimizerBase.h.
OffsetValueType
using itk::OffsetValueType = typedef long
Differences between components of indexes, distance from one pointer to the origin of a buffer (it is signed)
Definition at line 94 of file itkIntTypes.h.
OptimizerParameterScalesEstimator
using itk::OptimizerParameterScalesEstimator = typedef OptimizerParameterScalesEstimatorTemplate<double>
This helps to meet backward compatibility
Definition at line 90 of file itkOptimizerParameterScalesEstimator.h.
OutputStreamType
using itk::OutputStreamType = typedef std::ostream
This extra type alias is necessary for preventing an Internal Compiler Error in Microsoft Visual C++ 6.0. This type alias is not needed for any other compiler.
Definition at line 246 of file itkSymmetricSecondRankTensor.h.
QuasiNewtonOptimizerv4
using itk::QuasiNewtonOptimizerv4 = typedef QuasiNewtonOptimizerv4Template<double>
This helps to meet backward compatibility
Definition at line 211 of file itkQuasiNewtonOptimizerv4.h.
QuasiNewtonOptimizerv4EstimateNewtonStepThreader
using itk::QuasiNewtonOptimizerv4EstimateNewtonStepThreader = typedef QuasiNewtonOptimizerv4EstimateNewtonStepThreaderTemplate<double>
This helps to meet backward compatibility
Definition at line 66 of file itkQuasiNewtonOptimizerv4EstimateNewtonStepThreader.h.
SamplingStrategyEnum
using itk::SamplingStrategyEnum = typedef RegistrationParameterScalesEstimatorEnums::SamplingStrategy
Definition at line 54 of file itkRegistrationParameterScalesEstimator.h.
SerieUIDContainer
using itk::SerieUIDContainer = typedef std::vector<std::string>
Definition at line 61 of file itkGDCMSeriesFileNames.h.
SingleValuedCostFunctionv4
using itk::SingleValuedCostFunctionv4 = typedef SingleValuedCostFunctionv4Template<double>
This helps to meet backward compatibility
Definition at line 94 of file itkSingleValuedCostFunctionv4.h.
SizeValueType
using itk::SizeValueType = typedef unsigned long
Any count of number of items (number of pixels in an image, number of points) (it is unsigned)
Definition at line 83 of file itkIntTypes.h.
SpacePrecisionType
using itk::SpacePrecisionType = typedef double
Definition at line 30 of file itkFloatTypes.h.
StopConditionObjectToObjectOptimizerEnum
using itk::StopConditionObjectToObjectOptimizerEnum = typedef ObjectToObjectOptimizerBaseTemplateEnums::StopConditionObjectToObjectOptimizer
Definition at line 54 of file itkObjectToObjectOptimizerBase.h.
SymbolPointer
using itk::SymbolPointer = typedef itksys::DynamicLoader::SymbolPointer
Definition at line 40 of file itkDynamicLoader.h.
ThreadFunctionType
using itk::ThreadFunctionType = typedef void (*)(void *)
Platform specific type alias for simple types
Definition at line 81 of file itkThreadSupport.h.
ThreadIdType
using itk::ThreadIdType = typedef unsigned int
Type to count and reference number of threads
Definition at line 99 of file itkIntTypes.h.
ThreadProcessIdType
using itk::ThreadProcessIdType = typedef int
Platform specific type alias for simple types
Definition at line 82 of file itkThreadSupport.h.
TransformBase
using itk::TransformBase = typedef TransformBaseTemplate<double>
This helps to meet backward compatibility
Definition at line 184 of file itkTransformBase.h.
TransformFileReader
using itk::TransformFileReader = typedef itk::TransformFileReaderTemplate<double>
This helps to meet backward compatibility
Definition at line 114 of file itkTransformFileReader.h.
TransformFileWriter
using itk::TransformFileWriter = typedef itk::TransformFileWriterTemplate<double>
This helps to meet backward compatibility
Definition at line 129 of file itkTransformFileWriter.h.
TransformIOBase
using itk::TransformIOBase = typedef itk::TransformIOBaseTemplate<double>
This helps to meet backward compatibility
Definition at line 224 of file itkTransformIOBase.h.
TransformIOFactory
using itk::TransformIOFactory = typedef TransformIOFactoryTemplate<double>
This helps to meet backward compatibility
Definition at line 69 of file itkTransformIOFactory.h.
TxtTransformIO
using itk::TxtTransformIO = typedef TxtTransformIOTemplate<double>
This helps to meet backward compatibility
Definition at line 88 of file itkTxtTransformIO.h.
ZeroBasedIndexRange
template<unsigned int VDimension> using itk::ZeroBasedIndexRange = typedef IndexRange<VDimension, true>
Definition at line 464 of file itkIndexRange.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
B2_MASKFILE_BLACK
B2_MASKFILE_WHITE
B2_MASKFILE_GRAY
Definition at line 27 of file itkOctree.h.
GPUFiniteDifferenceFilterEnum
enum class itk::GPUFiniteDifferenceFilterEnum : uint8_t strong
Enumerator
UNINITIALIZED
INITIALIZED
Definition at line 30 of file itkGPUFiniteDifferenceFilterEnum.h.
Function Documentation
bit_cast()
template<typename TDestination , class TSource > TDestination itk::bit_cast (const TSource & source)
Rudimentary bit_cast implementation for C++14/C++17. From C++20, std::bit_cast is preferred.
Definition at line 34 of file itkBitCast.h.
BoxAccumulateFunction()
template<typename TInputImage , typename TOutputImage > void itk::BoxAccumulateFunction (const TInputImage * inputImage, const TOutputImage * outputImage, typename TInputImage::RegionType inputRegion, typename TOutputImage::RegionType outputRegion)
Definition at line 99 of file itkBoxUtilities.h.
References itk::ProgressReporter::CompletedPixel(), itk::Size< VDimension >::Fill(), itk_impl_details::setConnectivityEarlyBox(), and itk::ConstantBoundaryCondition< TInputImage, TOutputImage >::SetConstant().
BoxMeanCalculatorFunction()
template<typename TInputImage , typename TOutputImage > void itk::BoxMeanCalculatorFunction (const TInputImage * accImage, TOutputImage * outputImage, typename TInputImage::RegionType inputRegion, typename TOutputImage::RegionType outputRegion, typename TInputImage::SizeType radius)
Definition at line 206 of file itkBoxUtilities.h.
References itk::ProgressReporter::CompletedPixel(), itk::Index< VDimension >::GetIndex(), itk::ImageRegion< VImageDimension >::SetIndex(), itk::Index< VDimension >::SetIndex(), and itk::ImageRegion< VImageDimension >::SetSize().
BoxSigmaCalculatorFunction()
template<typename TInputImage , typename TOutputImage > void itk::BoxSigmaCalculatorFunction (const TInputImage * accImage, TOutputImage * outputImage, typename TInputImage::RegionType inputRegion, typename TOutputImage::RegionType outputRegion, typename TInputImage::SizeType radius)
Definition at line 397 of file itkBoxUtilities.h.
References itk::ProgressReporter::CompletedPixel(), itk::Index< VDimension >::GetIndex(), itk::ImageRegion< VImageDimension >::SetIndex(), itk::Index< VDimension >::SetIndex(), and itk::ImageRegion< VImageDimension >::SetSize().
BoxSquareAccumulateFunction()
template<typename TInputImage , typename TOutputImage > void itk::BoxSquareAccumulateFunction (const TInputImage * inputImage, TOutputImage * outputImage, typename TInputImage::RegionType inputRegion, typename TOutputImage::RegionType outputRegion)
Definition at line 596 of file itkBoxUtilities.h.
References itk::ProgressReporter::CompletedPixel(), itk::Size< VDimension >::Fill(), itk_impl_details::setConnectivityEarlyBox(), and itk::ConstantBoundaryCondition< TInputImage, TOutputImage >::SetConstant().
ClearContent()
void itk::ClearContent (FancyString & input)
Manipulator to clear all characters in a FancyString.
CompensatedSummationAddElement() [1/2]
void ITKCommon_EXPORT itk::CompensatedSummationAddElement (double & compensation, double & sum, const double element)
CompensatedSummationAddElement() [2/2]
void ITKCommon_EXPORT itk::CompensatedSummationAddElement (float & compensation, float & sum, const float element)
ComputeStartEnd()
template<typename TImage , typename TBres , typename TLine > int itk::ComputeStartEnd (const typename TImage::IndexType StartIndex, const TLine line, const float tol, const typename TBres::OffsetArray LineOffsets, const typename TImage::RegionType AllImage, unsigned int & start, unsigned int & end)
ConvertNumberToString()
template<typename TValue > std::string itk::ConvertNumberToString (const TValue val)
Converts the specified numeric value to a string, using a NumberToString function object. Produces a full precision (lossless) string representation, also for floatand double. Otherwise it is similar to std::to_string
Definition at line 83 of file itkNumberToString.h.
Referenced by itk::MeshIOBase::WriteBufferAsAscii(), itk::OBJMeshIO::WritePointData(), itk::VTKPolyDataMeshIO::WritePointDataBufferAsASCII(), itk::BYUMeshIO::WritePoints(), itk::OBJMeshIO::WritePoints(), and itk::VTKPolyDataMeshIO::WritePointsBufferAsASCII().
CopyLineToImage()
template<typename TImage , typename TBres > void itk::CopyLineToImage (const typename TImage::Pointer output, const typename TImage::IndexType StartIndex, const typename TBres::OffsetArray LineOffsets, std::vector< typename TImage::PixelType > & outbuffer, const unsigned int start, const unsigned int end)
CopyMeshToMesh()
template<typename TInputMesh , typename TOutputMesh > void itk::CopyMeshToMesh (const TInputMesh * in, TOutputMesh * out)
Definition at line 132 of file itkQuadEdgeMeshToQuadEdgeMeshFilter.h.
References CopyMeshToMeshCellData(), CopyMeshToMeshCells(), CopyMeshToMeshEdgeCells(), CopyMeshToMeshPointData(), and CopyMeshToMeshPoints().
CopyMeshToMeshCellData()
template<typename TInputMesh , typename TOutputMesh > void itk::CopyMeshToMeshCellData (const TInputMesh * in, TOutputMesh * out)
Definition at line 144 of file itkQuadEdgeMeshToQuadEdgeMeshFilter.h.
References New(), and point().
Referenced by CopyMeshToMesh().
CopyMeshToMeshCells()
template<typename TInputMesh , typename TOutputMesh > void itk::CopyMeshToMeshCells (const TInputMesh * in, TOutputMesh * out)
Definition at line 211 of file itkQuadEdgeMeshToQuadEdgeMeshFilter.h.
References itk::MeshEnums::CellsAllocatedDynamicallyCellByCell.
Referenced by CopyMeshToMesh().
CopyMeshToMeshEdgeCells()
template<typename TInputMesh , typename TOutputMesh > void itk::CopyMeshToMeshEdgeCells (const TInputMesh * in, TOutputMesh * out)
Definition at line 257 of file itkQuadEdgeMeshToQuadEdgeMeshFilter.h.
Referenced by CopyMeshToMesh().
CopyMeshToMeshPointData()
template<typename TInputMesh , typename TOutputMesh > void itk::CopyMeshToMeshPointData (const TInputMesh * in, TOutputMesh * out)
Definition at line 178 of file itkQuadEdgeMeshToQuadEdgeMeshFilter.h.
References New(), and point().
Referenced by CopyMeshToMesh().
CopyMeshToMeshPoints()
template<typename TInputMesh , typename TOutputMesh > void itk::CopyMeshToMeshPoints (const TInputMesh * in, TOutputMesh * out)
Definition at line 290 of file itkQuadEdgeMeshToQuadEdgeMeshFilter.h.
References itk::FixedArray< TValue, VLength >::Begin(), and New().
Referenced by CopyMeshToMesh().
CornerOffsets()
template<typename TImage > std::vector< typename TImage::OffsetType > itk::CornerOffsets (const TImage * im)
Definition at line 174 of file itkBoxUtilities.h.
References itk::Size< VDimension >::Fill().
CrossProduct() [1/6]
ITKCommon_EXPORT Vector< double, 3 > itk::CrossProduct (const Vector< double, 3 > & , const Vector< double, 3 > &)
CrossProduct() [2/6]
ITKCommon_EXPORT Vector< float, 3 > itk::CrossProduct (const Vector< float, 3 > & , const Vector< float, 3 > &)
CrossProduct() [3/6]
ITKCommon_EXPORT Vector< int, 3 > itk::CrossProduct (const Vector< int, 3 > & , const Vector< int, 3 > &)
CrossProduct() [4/6]
ITKCommon_EXPORT void itk::CrossProduct (CovariantVector< double, 3 > & , const Vector< double, 3 > & , const Vector< double, 3 > &)
CrossProduct() [5/6]
ITKCommon_EXPORT void itk::CrossProduct (CovariantVector< float, 3 > & , const Vector< float, 3 > & , const Vector< float, 3 > &)
CrossProduct() [6/6]
ITKCommon_EXPORT void itk::CrossProduct (CovariantVector< int, 3 > , const Vector< int, 3 > & , const Vector< int, 3 > &)
DoAnchorFace()
template<typename TImage , typename TBres , typename TAnchor , typename TLine > void itk::DoAnchorFace (const TImage * input, TImage * output, typename TImage::PixelType border, TLine line, TAnchor & AnchorLine, typename TBres::OffsetArray LineOffsets, std::vector< typename TImage::PixelType > & inbuffer, std::vector< typename TImage::PixelType > & outbuffer, const typename TImage::RegionType AllImage, const typename TImage::RegionType face)
DoFace()
template<typename TImage , typename TBres , typename TFunction , typename TLine > void itk::DoFace (typename TImage::ConstPointer input, typename TImage::Pointer output, typename TImage::PixelType border, TLine line, const typename TBres::OffsetArray LineOffsets, const unsigned int KernLen, std::vector< typename TImage::PixelType > & pixbuffer, std::vector< typename TImage::PixelType > & fExtBuffer, std::vector< typename TImage::PixelType > & rExtBuffer, const typename TImage::RegionType AllImage, const typename TImage::RegionType face)
EncapsulateMetaData() [1/2]
template<typename T > void itk::EncapsulateMetaData (MetaDataDictionary & Dictionary, const char * key, const T & invalue) inline
Definition at line 237 of file itkMetaDataObject.h.
References EncapsulateMetaData().
EncapsulateMetaData() [2/2]
template<typename T > void itk::EncapsulateMetaData (MetaDataDictionary & Dictionary, const std::string & key, const T & invalue) inline
EncapsulateMetaData is a convenience function that encapsulates raw MetaData into a MetaDataObject that can be put into the MetaDataDictionary.
Parameters
Dictionary TODO
key TODO
invalue the value of type T that is to be encapsulated.
Returns
A smartpointer to a MetaDataObject that is suitable for insertion into a MetaDataDictionary.
Definition at line 227 of file itkMetaDataObject.h.
References itk::MetaDataObject< MetaDataObjectType >::New().
Referenced by EncapsulateMetaData().
ExposeMetaData()
template<typename T > bool itk::ExposeMetaData (const MetaDataDictionary & Dictionary, const std::string key, T & outval) inline
ExposeMetaData provides a shortcut for pulling a value of type T out of a MetaDataDictionary. If Dictionary[key] isn't set, return false, otherwise copy into outval reference and return true.
Parameters
Dictionary – reference to a dictionary
key – string identifier for this object
outval – where to store value found in table.
Definition at line 253 of file itkMetaDataObject.h.
References itk::MetaDataDictionary::End(), itk::MetaDataDictionary::Find(), and itk::MetaDataObject< MetaDataObjectType >::GetMetaDataObjectValue().
Referenced by itk::MetaImageIO::WriteMatrixInMetaData().
FillForwardExt()
template<typename PixelType , typename TFunction > void itk::FillForwardExt (std::vector< PixelType > & pixbuffer, std::vector< PixelType > & fExtBuffer, const unsigned int KernLen, unsigned int len)
FillLineBuffer()
template<typename TImage , typename TBres , typename TLine > int itk::FillLineBuffer (typename TImage::ConstPointer input, const typename TImage::IndexType StartIndex, const TLine line, const float tol, const typename TBres::OffsetArray LineOffsets, const typename TImage::RegionType AllImage, std::vector< typename TImage::PixelType > & inbuffer, unsigned int & start, unsigned int & end)
FillReverseExt()
template<typename PixelType , typename TFunction > void itk::FillReverseExt (std::vector< PixelType > & pixbuffer, std::vector< PixelType > & rExtBuffer, const unsigned int KernLen, unsigned int len)
GenerateConnectedImageNeighborhoodShapeOffsets()
template<unsigned int VImageDimension, vcl_size_t VMaximumCityblockDistance, bool VIncludeCenterPixel> auto itk::GenerateConnectedImageNeighborhoodShapeOffsets () noexcept
Generates the offsets for a connected image neighborhood shape.
Definition at line 270 of file itkConnectedImageNeighborhoodShape.h.
References itk::ConnectedImageNeighborhoodShape< VImageDimension >::GetNumberOfOffsets().
GenerateImageNeighborhoodOffsets()
template<typename TImageNeighborhoodShape > std::vector< Offset< TImageNeighborhoodShape::ImageDimension > > itk::GenerateImageNeighborhoodOffsets (const TImageNeighborhoodShape & shape)
Generates the offsets for a neighborhood of the specified shape.
Definition at line 31 of file itkImageNeighborhoodOffsets.h.
Referenced by GenerateRectangularImageNeighborhoodOffsets().
GenerateRectangularImageNeighborhoodOffsets()
template<unsigned int VImageDimension> std::vector< Offset< VImageDimension > > itk::GenerateRectangularImageNeighborhoodOffsets (const Size< VImageDimension > & radius)
Generates the offsets for a hyperrectangular (box shaped) neighborhood.
Definition at line 43 of file itkImageNeighborhoodOffsets.h.
References GenerateImageNeighborhoodOffsets().
Referenced by itk::SumOfSquaresImageFunction< TInputImage, TCoordRep >::SetNeighborhoodRadius().
Get64BitPragma()
std::string itk::Get64BitPragma ()
Get 64-bit pragma
GetLinePixels()
template<typename TLine > unsigned int itk::GetLinePixels (const TLine line)
GetPixelDimension()
int itk::GetPixelDimension (const std::type_info & intype)
Get pixel dimension (number of channels). For high-dimensional pixel format, only itk::Vector< type, 2/3 > is acceptable.
GetTransformName()
const std::string ITKIOTransformHDF5_EXPORT itk::GetTransformName (int)
GetTypename()
std::string itk::GetTypename (const std::type_info & intype)
Get Typename
GetTypenameInString()
void itk::GetTypenameInString (const std::type_info & intype, std::ostringstream & ret)
Get Typename in String
GetValidTypename()
bool itk::GetValidTypename (const std::type_info & intype, const std::vector< std::string > & validtypes, std::string & retTypeName)
Get Typename in String if a valid type
IMAGEIOBASE_TYPEMAP() [1/13]
itk::IMAGEIOBASE_TYPEMAP (char , std::numeric_limits< char >::is_signed ? IOComponentEnum::CHAR :IOComponentEnum::UCHAR)
IMAGEIOBASE_TYPEMAP() [2/13]
itk::IMAGEIOBASE_TYPEMAP (double , IOComponentEnum::DOUBLE)
IMAGEIOBASE_TYPEMAP() [3/13]
itk::IMAGEIOBASE_TYPEMAP (float , IOComponentEnum::FLOAT)
IMAGEIOBASE_TYPEMAP() [4/13]
itk::IMAGEIOBASE_TYPEMAP (int , IOComponentEnum::INT)
IMAGEIOBASE_TYPEMAP() [5/13]
itk::IMAGEIOBASE_TYPEMAP (long long , IOComponentEnum::LONGLONG)
IMAGEIOBASE_TYPEMAP() [6/13]
itk::IMAGEIOBASE_TYPEMAP (long , IOComponentEnum::LONG)
IMAGEIOBASE_TYPEMAP() [7/13]
itk::IMAGEIOBASE_TYPEMAP (short , IOComponentEnum::SHORT)
IMAGEIOBASE_TYPEMAP() [8/13]
itk::IMAGEIOBASE_TYPEMAP (signed char , IOComponentEnum::CHAR)
IMAGEIOBASE_TYPEMAP() [9/13]
itk::IMAGEIOBASE_TYPEMAP (unsigned char , IOComponentEnum::UCHAR)
IMAGEIOBASE_TYPEMAP() [10/13]
itk::IMAGEIOBASE_TYPEMAP (unsigned int , IOComponentEnum::UINT)
IMAGEIOBASE_TYPEMAP() [11/13]
itk::IMAGEIOBASE_TYPEMAP (unsigned long long , IOComponentEnum::ULONGLONG)
IMAGEIOBASE_TYPEMAP() [12/13]
itk::IMAGEIOBASE_TYPEMAP (unsigned long , IOComponentEnum::ULONG)
IMAGEIOBASE_TYPEMAP() [13/13]
itk::IMAGEIOBASE_TYPEMAP (unsigned short , IOComponentEnum::USHORT)
Int2EigenValueOrderEnum()
EigenValueOrderEnum itk::Int2EigenValueOrderEnum (const uint8_t value) inline
Definition at line 145 of file itkSymmetricEigenAnalysis.h.
References itk::SymmetricEigenAnalysisEnums::DoNotOrder, itk::SymmetricEigenAnalysisEnums::OrderByMagnitude, and itk::SymmetricEigenAnalysisEnums::OrderByValue.
IsGPUAvailable()
bool itk::IsGPUAvailable ()
Check if OpenCL-enabled GPU is present.
Referenced by itk::GPUBinaryThresholdImageFilterFactory::GPUBinaryThresholdImageFilterFactory(), itk::GPUDemonsRegistrationFilterFactory::GPUDemonsRegistrationFilterFactory(), itk::GPUGradientAnisotropicDiffusionImageFilterFactory::GPUGradientAnisotropicDiffusionImageFilterFactory(), itk::GPUImageFactory::GPUImageFactory(), and itk::GPUMeanImageFilterFactory::GPUMeanImageFilterFactory().
ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE() [1/4]
itk::ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE (CovariantVector)
ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE() [2/4]
itk::ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE (FixedArray)
ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE() [3/4]
itk::ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE (Point)
ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE() [4/4]
itk::ITK_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE (Vector)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [1/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (bool)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [2/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (char)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [3/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (double)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [4/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (float)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [5/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (int)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [6/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (long long)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [7/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (long)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [8/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (short)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [9/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (signed char)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [10/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (unsigned char)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [11/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (unsigned int)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [12/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (unsigned long long)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [13/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (unsigned long)
ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL() [14/14]
itk::ITK_DEFAULTCONVERTTRAITS_NATIVE_SPECIAL (unsigned short)
ITK_MESH_DEFAULTCONVERTTRAITS_ARRAY_TYPE_ALL_TYPES_MACRO() [1/2]
itk::ITK_MESH_DEFAULTCONVERTTRAITS_ARRAY_TYPE_ALL_TYPES_MACRO (Array)
ITK_MESH_DEFAULTCONVERTTRAITS_ARRAY_TYPE_ALL_TYPES_MACRO() [2/2]
itk::ITK_MESH_DEFAULTCONVERTTRAITS_ARRAY_TYPE_ALL_TYPES_MACRO (VariableLengthVector)
ITK_MESH_DEFAULTCONVERTTRAITS_COMPLEX_TYPE() [1/2]
itk::ITK_MESH_DEFAULTCONVERTTRAITS_COMPLEX_TYPE (double)
ITK_MESH_DEFAULTCONVERTTRAITS_COMPLEX_TYPE() [2/2]
itk::ITK_MESH_DEFAULTCONVERTTRAITS_COMPLEX_TYPE (float)
ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO() [1/4]
itk::ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO (CovariantVector)
ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO() [2/4]
itk::ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO (FixedArray)
ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO() [3/4]
itk::ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO (Point)
ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO() [4/4]
itk::ITK_MESH_DEFAULTCONVERTTRAITS_FIXEDARRAY_TYPE_ALL_TYPES_MACRO (Vector)
ITK_MESH_DEFAULTCONVERTTRAITS_MATRIX_TYPE_ALL_TYPES_MACRO()
itk::ITK_MESH_DEFAULTCONVERTTRAITS_MATRIX_TYPE_ALL_TYPES_MACRO (Matrix)
itkEventMacroDeclaration() [1/20]
itk::itkEventMacroDeclaration (AbortCheckEvent , PickEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [2/20]
itk::itkEventMacroDeclaration (AbortEvent , AnyEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [3/20]
itk::itkEventMacroDeclaration (AnyEvent , EventObject)
Delclare some common ITK events
itkEventMacroDeclaration() [4/20]
itk::itkEventMacroDeclaration (DeleteEvent , AnyEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [5/20]
itk::itkEventMacroDeclaration (EndEvent , AnyEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [6/20]
itk::itkEventMacroDeclaration (EndPickEvent , PickEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [7/20]
itk::itkEventMacroDeclaration (ExitEvent , AnyEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [8/20]
itk::itkEventMacroDeclaration (FunctionAndGradientEvaluationIterationEvent , IterationEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [9/20]
itk::itkEventMacroDeclaration (FunctionEvaluationIterationEvent , IterationEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [10/20]
itk::itkEventMacroDeclaration (GradientEvaluationIterationEvent , IterationEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [11/20]
itk::itkEventMacroDeclaration (InitializeEvent , AnyEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [12/20]
itk::itkEventMacroDeclaration (IterationEvent , AnyEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [13/20]
itk::itkEventMacroDeclaration (ModifiedEvent , AnyEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [14/20]
itk::itkEventMacroDeclaration (MultiResolutionIterationEvent , IterationEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [15/20]
itk::itkEventMacroDeclaration (NoEvent , EventObject)
Delclare some common ITK events
itkEventMacroDeclaration() [16/20]
itk::itkEventMacroDeclaration (PickEvent , AnyEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [17/20]
itk::itkEventMacroDeclaration (ProgressEvent , AnyEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [18/20]
itk::itkEventMacroDeclaration (StartEvent , AnyEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [19/20]
itk::itkEventMacroDeclaration (StartPickEvent , PickEvent)
Delclare some common ITK events
itkEventMacroDeclaration() [20/20]
itk::itkEventMacroDeclaration (UserEvent , AnyEvent)
Delclare some common ITK events
itkGPUKernelClassMacro() [1/10]
itk::itkGPUKernelClassMacro (GPUBinaryThresholdImageFilterKernel)
Create a helper GPU Kernel class for GPUBinaryThresholdImageFilter
itkGPUKernelClassMacro() [2/10]
itk::itkGPUKernelClassMacro (GPUCastImageFilterKernel)
Create a helper GPU Kernel class for GPUCastImageFilter
itkGPUKernelClassMacro() [3/10]
itk::itkGPUKernelClassMacro (GPUDemonsRegistrationFunctionKernel)
Create a helper GPU Kernel class for GPUDemonsRegistrationFunction
itkGPUKernelClassMacro() [4/10]
itk::itkGPUKernelClassMacro (GPUGradientNDAnisotropicDiffusionFunctionKernel)
Create a helper GPU Kernel class for GPUGradientNDAnisotropicDiffusionFunction
itkGPUKernelClassMacro() [5/10]
itk::itkGPUKernelClassMacro (GPUImageOpsKernel)
Create a helper GPU Kernel class for GPUImageOps
itkGPUKernelClassMacro() [6/10]
itk::itkGPUKernelClassMacro (GPUMeanImageFilterKernel)
Create a helper GPU Kernel class for GPUMeanImageFilter
itkGPUKernelClassMacro() [7/10]
itk::itkGPUKernelClassMacro (GPUNeighborhoodOperatorImageFilterKernel)
Create a helper GPU Kernel class for GPUNeighborhoodOperatorImageFilter
itkGPUKernelClassMacro() [8/10]
itk::itkGPUKernelClassMacro (GPUPDEDeformableRegistrationFilterKernel)
Create a helper GPU Kernel class for GPUPDEDeformableRegistrationFilter
itkGPUKernelClassMacro() [9/10]
itk::itkGPUKernelClassMacro (GPUReductionKernel)
Create a helper GPU Kernel class for GPUReduction
itkGPUKernelClassMacro() [10/10]
itk::itkGPUKernelClassMacro (GPUScalarAnisotropicDiffusionFunctionKernel)
Create a helper GPU Kernel class for GPUScalarAnisotropicDiffusionFunction
itkGPUKernelMacro()
class ITKGPUFiniteDifference_EXPORT itk::itkGPUKernelMacro (GPUDenseFiniteDifferenceImageFilterKernel)
Create a helper GPU Kernel class for GPUDenseFiniteDifferenceImageFilter
make_unique_for_overwrite()
template<typename TUnboundedArray > auto itk::make_unique_for_overwrite (const vcl_size_t numberOfElements)
make_unique_for_overwrite implementation for C++14/C++17, specifically for dynamically sized ("unbounded") arrays. From C++20, std::make_unique_for_overwrite is preferred.
Example (mind the square brackets):
     using ElementType = int;
     size_t numberOfElements{ 42 };
     // Create a buffer that may be used to store the specified number of elements.
     auto buffer = make_unique_for_overwrite<ElementType[]>(numberOfElements);
Definition at line 63 of file itkMakeUniqueForOverwrite.h.
MakeChainCodeTracePath()
template<typename TChainCodePath , typename TPathInput > void itk::MakeChainCodeTracePath (TChainCodePath & chainPath, const TPathInput & inPath, bool restrictMovement = false)
Make a chain code trace another path of same dimensionality. If restrictMovement is true, then individual steps are allowed to move through only one dimension at a time; for 2D paths this results in an 8-connected chain code.
Definition at line 33 of file itkPathFunctions.h.
MakeEnlargedFace()
template<typename TInputImage , typename TLine > TInputImage::RegionType itk::MakeEnlargedFace (const TInputImage * input, const typename TInputImage::RegionType AllImage, const TLine line)
MakeFilled()
template<typename TContainer > constexpr TContainer itk::MakeFilled (typename TContainer::const_reference value) constexpr
Yields a container of the specified type, filled by the specified value, assigned to each of its elements. Only intended for container types of a compile-time fixed size, including instances of FixedArray (and derived classes), Index, Offset, Size, and std::array. Moreover, their size (number of elements) should be greater than zero.
Definition at line 29 of file itkMakeFilled.h.
MakeFourierSeriesPathTraceChainCode()
template<typename TFourierSeriesPath , typename TChainCodePath > void itk::MakeFourierSeriesPathTraceChainCode (TFourierSeriesPath & FSPath, const TChainCodePath & chainPath, unsigned int numHarmonics = 8)
Make a Fourier series path trace a chain code path of same dimensionality. numHarmonics is the number of harmonics (frequency coefficients, which include the "DC" term) to compute. If chainPath has too few steps to calculate numHarmonics (due to the Nyquist criterion), then as many harmonics as possible (chainPath->NumberOfSteps()/2) will be calculated. No fewer than 2 harmonics will be calculated.
Definition at line 81 of file itkPathFunctions.h.
MakeImageBufferRange()
template<typename TImage > ImageBufferRange< TImage > itk::MakeImageBufferRange (TImage *const image)
Creates a range to iterate over the pixels of the specified image. Returns an empty range when the specified argument is a nullptr (which is a valid use case).
Definition at line 681 of file itkImageBufferRange.h.
MakeIndex()
template<typename... T> auto itk::MakeIndex (const T... values)
Makes an Index object, having the specified index values.
Definition at line 597 of file itkIndex.h.
MakePoint()
template<typename TValue , typename... TVariadic> auto itk::MakePoint (const TValue firstValue, const TVariadic... otherValues)
Makes a Point object, having the specified values as coordinates.
Definition at line 376 of file itkPoint.h.
MakeSize()
template<typename... T> auto itk::MakeSize (const T... values)
Makes a Size object, having the specified size values.
Definition at line 495 of file itkSize.h.
MakeVector()
template<typename TValue , typename... TVariadic> auto itk::MakeVector (const TValue firstValue, const TVariadic... otherValues)
Makes a Vector object, having the specified values as coordinates.
Definition at line 338 of file itkVector.h.
MESHIOBASE_TYPEMAP() [1/13]
itk::MESHIOBASE_TYPEMAP (char , IOComponentEnum::CHAR)
MESHIOBASE_TYPEMAP() [2/13]
itk::MESHIOBASE_TYPEMAP (double , IOComponentEnum::DOUBLE)
MESHIOBASE_TYPEMAP() [3/13]
itk::MESHIOBASE_TYPEMAP (float , IOComponentEnum::FLOAT)
MESHIOBASE_TYPEMAP() [4/13]
itk::MESHIOBASE_TYPEMAP (int , IOComponentEnum::INT)
MESHIOBASE_TYPEMAP() [5/13]
itk::MESHIOBASE_TYPEMAP (long double , IOComponentEnum::LDOUBLE)
MESHIOBASE_TYPEMAP() [6/13]
itk::MESHIOBASE_TYPEMAP (long long , IOComponentEnum::LONGLONG)
MESHIOBASE_TYPEMAP() [7/13]
itk::MESHIOBASE_TYPEMAP (long , IOComponentEnum::LONG)
MESHIOBASE_TYPEMAP() [8/13]
itk::MESHIOBASE_TYPEMAP (short , IOComponentEnum::SHORT)
MESHIOBASE_TYPEMAP() [9/13]
itk::MESHIOBASE_TYPEMAP (unsigned char , IOComponentEnum::UCHAR)
MESHIOBASE_TYPEMAP() [10/13]
itk::MESHIOBASE_TYPEMAP (unsigned int , IOComponentEnum::UINT)
MESHIOBASE_TYPEMAP() [11/13]
itk::MESHIOBASE_TYPEMAP (unsigned long long , IOComponentEnum::ULONGLONG)
MESHIOBASE_TYPEMAP() [12/13]
itk::MESHIOBASE_TYPEMAP (unsigned long , IOComponentEnum::ULONG)
MESHIOBASE_TYPEMAP() [13/13]
itk::MESHIOBASE_TYPEMAP (unsigned short , IOComponentEnum::USHORT)
MvtSunf()
float itk::MvtSunf (int numb)
NeedToDoFace()
template<typename TRegion , typename TLine > bool itk::NeedToDoFace (const TRegion AllImage, const TRegion face, const TLine line)
OpenCLCheckError()
void itk::OpenCLCheckError (cl_int error, const char * filename = "", int lineno = 0, const char * location = "")
Check OpenCL error
Referenced by itk::GPUKernelManager::SetKernelArgWithImageAndBufferedRegion().
OpenCLGetAvailableDevices()
cl_device_id * itk::OpenCLGetAvailableDevices (cl_platform_id platform, cl_device_type devType, cl_uint * numAvailableDevices)
Get the devices that are available
OpenCLGetLocalBlockSize()
int itk::OpenCLGetLocalBlockSize (unsigned int ImageDim)
Get the local block size based on the desired Image Dimension currently set as follows: OpenCL workgroup (block) size for 1/2/3D - needs to be tuned based on the GPU architecture 1D : 256 2D : 16x16 = 256 3D : 4x4x4 = 64
OpenCLGetMaxFlopsDev()
cl_device_id itk::OpenCLGetMaxFlopsDev (cl_context cxGPUContext)
Get the device that has the maximum FLOPS in the current context
OpenCLPrintDeviceInfo()
void itk::OpenCLPrintDeviceInfo (cl_device_id device, bool verbose = false)
Print device name and info
OpenCLSelectPlatform()
cl_platform_id itk::OpenCLSelectPlatform (const char * name)
Find the OpenCL platform that matches the "name"
operator!=() [1/7]
template<unsigned int VDimension> bool itk::operator!= (const Index< VDimension > & one, const Index< VDimension > & two) inline
Definition at line 552 of file itkIndex.h.
operator!=() [2/7]
template<typename TPixel > bool itk::operator!= (const NeighborhoodAllocator< TPixel > & lhs, const NeighborhoodAllocator< TPixel > & rhs) inline
Definition at line 213 of file itkNeighborhoodAllocator.h.
operator!=() [3/7]
template<unsigned int VDimension> bool itk::operator!= (const Offset< VDimension > & one, const Offset< VDimension > & two) inline
Definition at line 496 of file itkOffset.h.
operator!=() [4/7]
template<unsigned int VDimension> bool itk::operator!= (const Size< VDimension > & one, const Size< VDimension > & two) inline
Definition at line 450 of file itkSize.h.
operator!=() [5/7]
template<class T , class TU > bool itk::operator!= (const SmartPointer< T > & l, const SmartPointer< TU > & r) noexcept
Comparison of pointers. Not equal comparison.
Definition at line 246 of file itkSmartPointer.h.
operator!=() [6/7]
template<class T > bool itk::operator!= (const SmartPointer< T > & l, std::nullptr_t) noexcept
Comparison of pointers. Not equal comparison.
Definition at line 252 of file itkSmartPointer.h.
operator!=() [7/7]
template<class T > bool itk::operator!= (std::nullptr_t , const SmartPointer< T > & r) noexcept
Comparison of pointers. Not equal comparison.
Definition at line 258 of file itkSmartPointer.h.
operator*() [1/3]
template<typename T , unsigned int VVectorDimension> CovariantVector< T, VVectorDimension > itk::operator* (const T & scalar, const CovariantVector< T, VVectorDimension > & v) inline
Premultiply Operator for product of a vector and a scalar. CovariantVector< T, N > = T * CovariantVector< T,N >
Definition at line 268 of file itkCovariantVector.h.
operator*() [2/3]
template<typename T , unsigned int VVectorDimension> Vector< T, VVectorDimension > itk::operator* (const T & scalar, const Vector< T, VVectorDimension > & v) inline
Premultiply Operator for product of a vector and a scalar. Vector< T, N > = T * Vector< T,N >
Definition at line 302 of file itkVector.h.
operator*() [3/3]
template<typename T , unsigned int VVectorDimension> T itk::operator* (const Vector< T, VVectorDimension > & contravariant, const CovariantVector< T, VVectorDimension > & covariant) inline
Performs the scalar product of a covariant with a contravariant. This scalar product is invariant under affine transformations
Definition at line 276 of file itkCovariantVector.h.
operator+() [1/4]
template<typename TImage > ConstNeighborhoodIterator< TImage > itk::operator+ (const ConstNeighborhoodIterator< TImage > & it, const typename ConstNeighborhoodIterator< TImage >::OffsetType & ind) inline
Definition at line 653 of file itkConstNeighborhoodIterator.h.
operator+() [2/4]
template<typename TImage > ConstNeighborhoodIteratorWithOnlyIndex< TImage > itk::operator+ (const ConstNeighborhoodIteratorWithOnlyIndex< TImage > & it, const typename ConstNeighborhoodIteratorWithOnlyIndex< TImage >::OffsetType & ind) inline
Definition at line 414 of file itkConstNeighborhoodIteratorWithOnlyIndex.h.
operator+() [3/4]
template<typename TImage > ConstNeighborhoodIterator< TImage > itk::operator+ (const typename ConstNeighborhoodIterator< TImage >::OffsetType & ind, const ConstNeighborhoodIterator< TImage > & it) inline
Definition at line 663 of file itkConstNeighborhoodIterator.h.
operator+() [4/4]
template<typename TImage > ConstNeighborhoodIteratorWithOnlyIndex< TImage > itk::operator+ (const typename ConstNeighborhoodIteratorWithOnlyIndex< TImage >::OffsetType & ind, const ConstNeighborhoodIteratorWithOnlyIndex< TImage > & it) inline
Definition at line 425 of file itkConstNeighborhoodIteratorWithOnlyIndex.h.
operator-() [1/2]
template<typename TImage > ConstNeighborhoodIterator< TImage > itk::operator- (const ConstNeighborhoodIterator< TImage > & it, const typename ConstNeighborhoodIterator< TImage >::OffsetType & ind) inline
Definition at line 671 of file itkConstNeighborhoodIterator.h.
operator-() [2/2]
template<typename TImage > ConstNeighborhoodIteratorWithOnlyIndex< TImage > itk::operator- (const ConstNeighborhoodIteratorWithOnlyIndex< TImage > & it, const typename ConstNeighborhoodIteratorWithOnlyIndex< TImage >::OffsetType & ind) inline
Definition at line 433 of file itkConstNeighborhoodIteratorWithOnlyIndex.h.
operator<() [1/4]
template<unsigned int VDimension> bool itk::operator< (const Index< VDimension > & one, const Index< VDimension > & two) inline
Definition at line 558 of file itkIndex.h.
References itk::Index< VDimension >::begin(), and itk::Index< VDimension >::end().
operator<() [2/4]
template<unsigned int VDimension> bool itk::operator< (const Offset< VDimension > & one, const Offset< VDimension > & two) inline
Definition at line 502 of file itkOffset.h.
References itk::Offset< VDimension >::begin(), and itk::Offset< VDimension >::end().
operator<() [3/4]
template<unsigned int VDimension> bool itk::operator< (const Size< VDimension > & one, const Size< VDimension > & two) inline
Definition at line 456 of file itkSize.h.
References itk::Size< VDimension >::begin(), and itk::Size< VDimension >::end().
operator<() [4/4]
template<class T , class TU > bool itk::operator< (const SmartPointer< T > & l, const SmartPointer< TU > & r) noexcept
Comparison of pointers. Less than comparison.
Definition at line 267 of file itkSmartPointer.h.
operator<<() [1/107]
template<typename T > FancyString & itk::operator<< (FancyString & s, const Array< T > & data)
Functions to convert an array of type itk::Array<T> to a string. An exception will be thrown if errors were encountered during the conversion.
operator<<() [2/107]
template<typename T > FancyString & itk::operator<< (FancyString & s, const std::vector< T > & data)
Functions to convert a vector of type std::vector<T> to a string. An exception will be thrown if errors were encountered during the conversion.
operator<<() [3/107]
template<typename T > FancyString & itk::operator<< (FancyString & s, const T & data)
Functions to convert a value of basic data type to a string. An exception will be thrown if errors were encountered during the conversion.
operator<<() [4/107]
FancyString & itk::operator<< (FancyString & s, void(*)(FancyString &) mf)
Definition of FancyString-based manipulators without parameters.
operator<<() [5/107]
template<typename TComponent , unsigned int VDimension> OutputStreamType & itk::operator<< (OutputStreamType & os, const SymmetricSecondRankTensor< TComponent, VDimension > & c)
operator<<() [6/107]
template<typename TPixel > std::ostream & itk::operator<< (std::ostream & o, const NeighborhoodAllocator< TPixel > & a) inline
Definition at line 192 of file itkNeighborhoodAllocator.h.
References itk::NeighborhoodAllocator< TPixel >::begin(), and itk::NeighborhoodAllocator< TPixel >::size().
operator<<() [7/107]
template<> ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & os, const Array2D< double > & arr)
operator<<() [8/107]
template<> ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & os, const Array2D< float > & arr)
operator<<() [9/107]
template<typename TValue > std::ostream & itk::operator<< (std::ostream & os, const Array2D< TValue > & arr)
Definition at line 94 of file itkArray2D.h.
operator<<() [10/107]
template<typename TValue > std::ostream & itk::operator<< (std::ostream & os, const Array< TValue > & arr)
Definition at line 215 of file itkArray.h.
operator<<() [11/107]
template<typename T > std::ostream & itk::operator<< (std::ostream & os, const AutoPointer< T > p)
Definition at line 238 of file itkAutoPointer.h.
References itk::AutoPointer< TObjectType >::IsOwner().
operator<<() [12/107]
std::ostream & itk::operator<< (std::ostream & os, const EventObject & e) inline
Generic inserter operator for EventObject and its subclasses.
Definition at line 107 of file itkEventObject.h.
References itk::Math::e.
operator<<() [13/107]
template<typename TValue , unsigned int VLength> std::ostream & itk::operator<< (std::ostream & os, const FixedArray< TValue, VLength > & arr)
operator<<() [14/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & os, const ImageIORegion & region)
operator<<() [15/107]
template<unsigned int VImageDimension> std::ostream & itk::operator<< (std::ostream & os, const ImageRegion< VImageDimension > & region)
operator<<() [16/107]
template<unsigned int VDimension> std::ostream & itk::operator<< (std::ostream & os, const Index< VDimension > & obj)
Definition at line 525 of file itkIndex.h.
operator<<() [17/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & os, const LightObject & o)
This operator allows all subclasses of LightObject to be printed via <<. It in turn invokes the Print method, which in turn will invoke the PrintSelf method that all objects should define, if they have anything interesting to print out.
operator<<() [18/107]
template<typename T , unsigned int VRows, unsigned int VColumns> std::ostream & itk::operator<< (std::ostream & os, const Matrix< T, VRows, VColumns > & v)
Definition at line 317 of file itkMatrix.h.
References itk::Matrix< T, VRows, VColumns >::GetVnlMatrix().
operator<<() [19/107]
ITKPolynomials_EXPORT std::ostream & itk::operator<< (std::ostream & os, const MultivariateLegendrePolynomial & poly)
operator<<() [20/107]
template<typename TPixel , unsigned int VDimension, typename TContainer > std::ostream & itk::operator<< (std::ostream & os, const Neighborhood< TPixel, VDimension, TContainer > & neighborhood)
Definition at line 333 of file itkNeighborhood.h.
References itk::Neighborhood< TPixel, VDimension, TAllocator >::GetBufferReference(), itk::Neighborhood< TPixel, VDimension, TAllocator >::GetRadius(), and itk::Neighborhood< TPixel, VDimension, TAllocator >::GetSize().
operator<<() [21/107]
template<unsigned int VDimension> std::ostream & itk::operator<< (std::ostream & os, const Offset< VDimension > & ind)
Definition at line 468 of file itkOffset.h.
operator<<() [22/107]
template<typename T , unsigned int VPointDimension> std::ostream & itk::operator<< (std::ostream & os, const Point< T, VPointDimension > & vct)
operator<<() [23/107]
template<typename TComponent > std::ostream & itk::operator<< (std::ostream & os, const RGBAPixel< TComponent > & c)
operator<<() [24/107]
template<typename TComponent > std::ostream & itk::operator<< (std::ostream & os, const RGBPixel< TComponent > & c)
operator<<() [25/107]
template<unsigned int VDimension> std::ostream & itk::operator<< (std::ostream & os, const Size< VDimension > & obj)
Definition at line 423 of file itkSize.h.
operator<<() [26/107]
template<typename T > std::ostream & itk::operator<< (std::ostream & os, const SmartPointer< T > p)
Definition at line 298 of file itkSmartPointer.h.
References itk::SmartPointer< TObjectType >::Print().
operator<<() [27/107]
template<typename TImage , typename TBoundaryCondition > std::ostream & itk::operator<< (std::ostream & os, const std::vector< itk::ConstNeighborhoodIterator< TImage, TBoundaryCondition > > & mv)
operator<<() [28/107]
template<typename TMatrix , typename TVector , typename TEigenMatrix > std::ostream & itk::operator<< (std::ostream & os, const SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix > & s)
Definition at line 745 of file itkSymmetricEigenAnalysis.h.
References itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetDimension(), itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetOrder(), itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetOrderEigenMagnitudes(), itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetOrderEigenValues(), and itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::GetUseEigenLibrary().
operator<<() [29/107]
template<unsigned int VDimension, typename TMatrix , typename TVector , typename TEigenMatrix > std::ostream & itk::operator<< (std::ostream & os, const SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix > & s)
Definition at line 1095 of file itkSymmetricEigenAnalysis.h.
References itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetDimension(), itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetOrder(), itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetOrderEigenMagnitudes(), itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetOrderEigenValues(), and itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::GetUseEigenLibrary().
operator<<() [30/107]
ITKVideoCore_EXPORT std::ostream & itk::operator<< (std::ostream & os, const TemporalRegion & region)
ostream operator
operator<<() [31/107]
template<typename T > std::ostream & itk::operator<< (std::ostream & os, const VariableSizeMatrix< T > & v)
Definition at line 251 of file itkVariableSizeMatrix.h.
References itk::VariableSizeMatrix< T >::GetVnlMatrix().
operator<<() [32/107]
template<typename T , unsigned int VVectorDimension> std::ostream & itk::operator<< (std::ostream & os, const Vector< T, VVectorDimension > & vct)
Print content to an ostream
operator<<() [33/107]
template<typename T > std::ostream & itk::operator<< (std::ostream & os, const Versor< T > & v)
Definition at line 340 of file itkVersor.h.
References itk::Versor< T >::GetW(), itk::Versor< T >::GetX(), itk::Versor< T >::GetY(), and itk::Versor< T >::GetZ().
operator<<() [34/107]
template<typename T > std::ostream & itk::operator<< (std::ostream & os, const WeakPointer< T > p)
Definition at line 160 of file itkWeakPointer.h.
References itk::WeakPointer< TObjectType >::Print().
operator<<() [35/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, CellGeometryEnum value)
operator<<() [36/107]
ITKQuadEdgeMeshFiltering_EXPORT std::ostream & itk::operator<< (std::ostream & out, const BorderQuadEdgeMeshFilterEnums::BorderPick value)
operator<<() [37/107]
ITKQuadEdgeMeshFiltering_EXPORT std::ostream & itk::operator<< (std::ostream & out, const BorderQuadEdgeMeshFilterEnums::BorderTransform value)
operator<<() [38/107]
ITKFFT_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ComplexToComplexFFTImageFilterEnums::TransformDirection value)
operator<<() [39/107]
ITKRegionGrowing_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ConnectedThresholdImageFilterEnums::Connectivity value)
operator<<() [40/107]
ITKConvolution_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ConvolutionImageFilterBaseEnums::ConvolutionImageFilterOutputRegion value)
Define how to print enumerations
operator<<() [41/107]
ITKDeformableMesh_EXPORT std::ostream & itk::operator<< (std::ostream & out, const DeformableSimplexMesh3DGradientConstraintForceFilterEnums::SIDE value)
operator<<() [42/107]
ITKDiffusionTensorImage_EXPORT std::ostream & itk::operator<< (std::ostream & out, const DiffusionTensor3DReconstructionImageFilterEnums::GradientImageFormat value)
operator<<() [43/107]
ITKSpatialObjects_EXPORT std::ostream & itk::operator<< (std::ostream & out, const DTITubeSpatialObjectPointEnums::DTITubeSpatialObjectPointField value)
operator<<() [44/107]
ITKPDEDeformableRegistration_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ESMDemonsRegistrationFunctionEnums::Gradient value)
operator<<() [45/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ExtractImageFilterEnums::DirectionCollapseStrategy value)
Define how to print enumerations
operator<<() [46/107]
ITKFastMarching_EXPORT std::ostream & itk::operator<< (std::ostream & out, const FastMarchingImageFilterEnums::Label value)
operator<<() [47/107]
ITKFastMarching_EXPORT std::ostream & itk::operator<< (std::ostream & out, const FastMarchingReachedTargetNodesStoppingCriterionEnums::TargetCondition value)
operator<<() [48/107]
ITKFastMarching_EXPORT std::ostream & itk::operator<< (std::ostream & out, const FastMarchingTraitsEnums::TopologyCheck value)
operator<<() [49/107]
ITKSmoothing_EXPORT std::ostream & itk::operator<< (std::ostream & out, const FFTDiscreteGaussianImageFilterEnums::KernelSource value)
operator<<() [50/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const FloatingPointExceptionsEnums::ExceptionAction value)
operator<<() [51/107]
ITKOptimizers_EXPORT std::ostream & itk::operator<< (std::ostream & out, const FRPROptimizerEnums::Optimization value)
operator<<() [52/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const FrustumSpatialFunctionEnums::RotationPlane value)
operator<<() [53/107]
ITKIOGDCM_EXPORT std::ostream & itk::operator<< (std::ostream & out, const GDCMImageIOEnums::Compression value)
operator<<() [54/107]
ITKGPUFiniteDifference_EXPORT std::ostream & itk::operator<< (std::ostream & out, const GPUFiniteDifferenceFilterEnum value)
Define how to print enumeration values
operator<<() [55/107]
ITKOptimizers_EXPORT std::ostream & itk::operator<< (std::ostream & out, const GradientDescentOptimizerEnums::StopConditionGradientDescentOptimizer value)
operator<<() [56/107]
ITKRegistrationMethodsv4_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ImageRegistrationMethodv4Enums::MetricSamplingStrategy value)
operator<<() [57/107]
ITKIOImageBase_EXPORT std::ostream & itk::operator<< (std::ostream & out, const IOCommonEnums::AtomicPixel value)
operator<<() [58/107]
ITKIOJPEG2000_EXPORT std::ostream & itk::operator<< (std::ostream & out, const JPEG2000ImageIOInternalEnums::DecodingFormat value)
operator<<() [59/107]
ITKIOJPEG2000_EXPORT std::ostream & itk::operator<< (std::ostream & out, const JPEG2000ImageIOInternalEnums::DFMFormat value)
operator<<() [60/107]
ITKQuadEdgeMeshFiltering_EXPORT std::ostream & itk::operator<< (std::ostream & out, const LaplacianDeformationQuadEdgeMeshFilterEnums::Area value)
operator<<() [61/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const LoggerBaseEnums::PriorityLevel value)
operator<<() [62/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const LoggerBaseEnums::TimeStampFormat value)
operator<<() [63/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const LoggerThreadWrapperEnums::Operation value)
operator<<() [64/107]
ITKMathematicalMorphology_EXPORT std::ostream & itk::operator<< (std::ostream & out, const MathematicalMorphologyEnums::Algorithm value)
Define how to print enumeration values.
operator<<() [65/107]
ITKLabelMap_EXPORT std::ostream & itk::operator<< (std::ostream & out, const MergeLabelMapFilterEnums::ChoiceMethod value)
operator<<() [66/107]
ITKMarkovRandomFieldsClassifiers_EXPORT std::ostream & itk::operator<< (std::ostream & out, const MRFImageFilterEnums::MRFStop value)
operator<<() [67/107]
ITKImageFeature_EXPORT std::ostream & itk::operator<< (std::ostream & out, const MultiScaleHessianBasedMeasureImageFilterEnums::SigmaStepMethod value)
operator<<() [68/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const MultiThreaderBaseEnums::Threader value)
operator<<() [69/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const MultiThreaderBaseEnums::ThreadExitCode value)
operator<<() [70/107]
ITKIONIFTI_EXPORT std::ostream & itk::operator<< (std::ostream & out, const NiftiImageIOEnums::Analyze75Flavor value)
Backwards compatibility for enum values Define how to print enumerations
operator<<() [71/107]
ITKIONIFTI_EXPORT std::ostream & itk::operator<< (std::ostream & out, const NiftiImageIOEnums::NiftiFileEnum value)
Backwards compatibility for enum values Define how to print enumerations
operator<<() [72/107]
ITKQuadEdgeMeshFiltering_EXPORT std::ostream & itk::operator<< (std::ostream & out, const NormalQuadEdgeMeshFilterEnums::Weight value)
operator<<() [73/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ObjectEnums::RegionEnum value)
operator<<() [74/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ObjectFactoryEnums::InsertionPosition value)
operator<<() [75/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ObjectStoreEnums::GrowthStrategy value)
operator<<() [76/107]
ITKOptimizersv4_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ObjectToObjectMetricBaseTemplateEnums::GradientSource value)
operator<<() [77/107]
ITKOptimizersv4_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ObjectToObjectMetricBaseTemplateEnums::MetricCategory value)
operator<<() [78/107]
ITKOptimizersv4_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ObjectToObjectOptimizerBaseTemplateEnums::StopConditionObjectToObjectOptimizer value)
operator<<() [79/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const OctreeEnums::LeafIdentifier value)
operator<<() [80/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const OctreeEnums::Octree value)
operator<<() [81/107]
ITKDenoising_EXPORT std::ostream & itk::operator<< (std::ostream & out, const PatchBasedDenoisingBaseImageFilterEnums::ComponentSpace value)
operator<<() [82/107]
ITKDenoising_EXPORT std::ostream & itk::operator<< (std::ostream & out, const PatchBasedDenoisingBaseImageFilterEnums::FilterState value)
operator<<() [83/107]
ITKDenoising_EXPORT std::ostream & itk::operator<< (std::ostream & out, const PatchBasedDenoisingBaseImageFilterEnums::NoiseModel value)
operator<<() [84/107]
ITKSmoothing_EXPORT std::ostream & itk::operator<< (std::ostream & out, const RecursiveGaussianImageFilterEnums::GaussianOrder value)
operator<<() [85/107]
ITKOptimizersv4_EXPORT std::ostream & itk::operator<< (std::ostream & out, const RegistrationParameterScalesEstimatorEnums::SamplingStrategy value)
operator<<() [86/107]
ITKOptimizers_EXPORT std::ostream & itk::operator<< (std::ostream & out, const RegularStepGradientDescentBaseOptimizerEnums::StopCondition value)
operator<<() [87/107]
ITKColormap_EXPORT std::ostream & itk::operator<< (std::ostream & out, const ScalarToRGBColormapImageFilterEnums::RGBColormapFilter value)
Define how to print enumerations
operator<<() [88/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const SpatialOrientationEnums::CoordinateMajornessTerms value)
operator<<() [89/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const SpatialOrientationEnums::CoordinateTerms value)
operator<<() [90/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const SpatialOrientationEnums::ValidCoordinateOrientations value)
operator<<() [91/107]
ITKOptimizers_EXPORT std::ostream & itk::operator<< (std::ostream & out, const SPSAOptimizerEnums::StopConditionSPSAOptimizer value)
operator<<() [92/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, const SymmetricEigenAnalysisEnums::EigenValueOrder value)
operator<<() [93/107]
ITKTransform_EXPORT std::ostream & itk::operator<< (std::ostream & out, const TransformBaseTemplateEnums::TransformCategory value)
operator<<() [94/107]
ITKMesh_EXPORT std::ostream & itk::operator<< (std::ostream & out, const TriangleMeshCurvatureCalculatorEnums::Curvatures value)
operator<<() [95/107]
ITKVideoIO_EXPORT std::ostream & itk::operator<< (std::ostream & out, const VideoIOBaseEnums::ReadFrom value)
operator<<() [96/107]
ITKVideoIO_EXPORT std::ostream & itk::operator<< (std::ostream & out, const VideoIOFactoryEnums::IOMode value)
operator<<() [97/107]
ITKSpatialObjects_EXPORT std::ostream & itk::operator<< (std::ostream & out, ContourSpatialObjectEnums::InterpolationMethod value)
operator<<() [98/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, GaussianDerivativeOperatorEnums::InterpolationMode value)
operator<<() [99/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, IOByteOrderEnum value)
operator<<() [100/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, IOComponentEnum value)
operator<<() [101/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, IOFileEnum value)
operator<<() [102/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, IOFileModeEnum value)
operator<<() [103/107]
ITKCommon_EXPORT std::ostream & itk::operator<< (std::ostream & out, IOPixelEnum value)
operator<<() [104/107]
ITKOptimizersv4_EXPORT std::ostream & itk::operator<< (std::ostream & out, LBFGS2Optimizerv4Enums::LineSearchMethod value)
operator<<() [105/107]
ITKMesh_EXPORT std::ostream & itk::operator<< (std::ostream & out, const MeshEnums::MeshClassCellsAllocationMethod value)
Define how to print enumeration
operator<<() [106/107]
ITKQuadEdgeMesh_EXPORT std::ostream & itk::operator<< (std::ostream & out, QuadEdgeMeshEulerOperatorFlipEdgeFunctionEnums::EdgeStatusType value)
operator<<() [107/107]
ITKVideoCore_EXPORT std::ostream & itk::operator<< (std::ostream & out, TemporalDataObjectEnums::TemporalUnit value)
operator<<<double >()
template<> ITKCommon_EXPORT std::ostream & itk::operator<<<double > (std::ostream & os, const Array< double > & arr)
operator<<<float >()
template<> ITKCommon_EXPORT std::ostream & itk::operator<<<float > (std::ostream & os, const Array< float > & arr)
operator<=() [1/4]
template<unsigned int VDimension> bool itk::operator<= (const Index< VDimension > & one, const Index< VDimension > & two) inline
Definition at line 572 of file itkIndex.h.
operator<=() [2/4]
template<unsigned int VDimension> bool itk::operator<= (const Offset< VDimension > & one, const Offset< VDimension > & two) inline
Definition at line 516 of file itkOffset.h.
operator<=() [3/4]
template<unsigned int VDimension> bool itk::operator<= (const Size< VDimension > & one, const Size< VDimension > & two) inline
Definition at line 470 of file itkSize.h.
operator<=() [4/4]
template<class T , class TU > bool itk::operator<= (const SmartPointer< T > & l, const SmartPointer< TU > & r) noexcept
Comparison of pointers. Less than or equal to comparison.
Definition at line 283 of file itkSmartPointer.h.
operator==() [1/7]
template<unsigned int VDimension> bool itk::operator== (const Index< VDimension > & one, const Index< VDimension > & two) inline
Definition at line 545 of file itkIndex.h.
References itk::Index< VDimension >::begin(), and itk::Index< VDimension >::end().
Referenced by itk::Vector< T, VVectorDimension >::operator==().
operator==() [2/7]
template<typename TPixel > bool itk::operator== (const NeighborhoodAllocator< TPixel > & lhs, const NeighborhoodAllocator< TPixel > & rhs) inline
Definition at line 204 of file itkNeighborhoodAllocator.h.
References itk::NeighborhoodAllocator< TPixel >::begin(), itk::NeighborhoodAllocator< TPixel >::end(), and itk::NeighborhoodAllocator< TPixel >::size().
operator==() [3/7]
template<unsigned int VDimension> bool itk::operator== (const Offset< VDimension > & one, const Offset< VDimension > & two) inline
Definition at line 489 of file itkOffset.h.
References itk::Offset< VDimension >::begin(), and itk::Offset< VDimension >::end().
operator==() [4/7]
template<unsigned int VDimension> bool itk::operator== (const Size< VDimension > & one, const Size< VDimension > & two) inline
Definition at line 443 of file itkSize.h.
References itk::Size< VDimension >::begin(), and itk::Size< VDimension >::end().
operator==() [5/7]
template<class T , class TU > bool itk::operator== (const SmartPointer< T > & l, const SmartPointer< TU > & r) noexcept
Comparison of pointers. Equality comparison.
Definition at line 225 of file itkSmartPointer.h.
operator==() [6/7]
template<class T > bool itk::operator== (const SmartPointer< T > & l, std::nullptr_t) noexcept
Comparison of pointers. Equality comparison.
Definition at line 231 of file itkSmartPointer.h.
operator==() [7/7]
template<class T > bool itk::operator== (std::nullptr_t , const SmartPointer< T > & r) noexcept
Comparison of pointers. Equality comparison.
Definition at line 237 of file itkSmartPointer.h.
operator>() [1/4]
template<unsigned int VDimension> bool itk::operator> (const Index< VDimension > & one, const Index< VDimension > & two) inline
Definition at line 566 of file itkIndex.h.
operator>() [2/4]
template<unsigned int VDimension> bool itk::operator> (const Offset< VDimension > & one, const Offset< VDimension > & two) inline
Definition at line 510 of file itkOffset.h.
operator>() [3/4]
template<unsigned int VDimension> bool itk::operator> (const Size< VDimension > & one, const Size< VDimension > & two) inline
Definition at line 464 of file itkSize.h.
operator>() [4/4]
template<class T , class TU > bool itk::operator> (const SmartPointer< T > & l, const SmartPointer< TU > & r) noexcept
Comparison of pointers. Greater than comparison.
Definition at line 276 of file itkSmartPointer.h.
operator>=() [1/4]
template<unsigned int VDimension> bool itk::operator>= (const Index< VDimension > & one, const Index< VDimension > & two) inline
Definition at line 580 of file itkIndex.h.
operator>=() [2/4]
template<unsigned int VDimension> bool itk::operator>= (const Offset< VDimension > & one, const Offset< VDimension > & two) inline
Definition at line 524 of file itkOffset.h.
operator>=() [3/4]
template<unsigned int VDimension> bool itk::operator>= (const Size< VDimension > & one, const Size< VDimension > & two) inline
Definition at line 478 of file itkSize.h.
operator>=() [4/4]
template<class T , class TU > bool itk::operator>= (const SmartPointer< T > & l, const SmartPointer< TU > & r) noexcept
Comparison of pointers. Greater than or equal to comparison.
Definition at line 292 of file itkSmartPointer.h.
operator>>() [1/9]
template<typename T > FancyString & itk::operator>> (FancyString & s, Array< T > & data)
Function to convert a string to an array of type itk::Array<T>. Number of elements to read is given by data.GetSize(). An exception will be thrown if errors were encountered during the conversion.
operator>>() [2/9]
template<typename T > FancyString & itk::operator>> (FancyString & s, std::vector< T > & data)
Function to convert a string to a vector of type std::vector<T>. Number of elements to read is given by data.size(). An exception will be thrown if errors were encountered during the conversion.
operator>>() [3/9]
template<typename T > FancyString & itk::operator>> (FancyString & s, T & data)
Functions to convert a string to a value of basic data type. An exception will be thrown if errors were encountered during the conversion.
operator>>() [4/9]
template<typename TComponent , unsigned int VDimension> InputStreamType & itk::operator>> (InputStreamType & is, SymmetricSecondRankTensor< TComponent, VDimension > & dt)
operator>>() [5/9]
template<typename T , unsigned int VPointDimension> std::istream & itk::operator>> (std::istream & is, Point< T, VPointDimension > & vct)
operator>>() [6/9]
template<typename TComponent > std::istream & itk::operator>> (std::istream & is, RGBAPixel< TComponent > & c)
operator>>() [7/9]
template<typename TComponent > std::istream & itk::operator>> (std::istream & is, RGBPixel< TComponent > & c)
operator>>() [8/9]
template<typename T , unsigned int VVectorDimension> std::istream & itk::operator>> (std::istream & is, Vector< T, VVectorDimension > & vct)
Read content from an istream
operator>>() [9/9]
template<typename T > std::istream & itk::operator>> (std::istream & is, Versor< T > & v)
point()
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating itk::point (float or double)
Referenced by itk::AzimuthElevationToCartesianTransform< TParametersValueType, VDimension >::BackTransform(), itk::Rigid2DTransform< TParametersValueType >::BackTransform(), itk::TranslationTransform< TParametersValueType, VDimension >::BackTransform(), itk::AzimuthElevationToCartesianTransform< TParametersValueType, VDimension >::BackTransformPoint(), itk::ImageFunction< TInputImage, TOutput, TCoordRep >::ConvertPointToContinuousIndex(), itk::ImageFunction< TInputImage, TOutput, TCoordRep >::ConvertPointToNearestIndex(), CopyMeshToMeshCellData(), CopyMeshToMeshPointData(), itk::Index< VDimension >::CopyWithCast(), itk::Offset< VDimension >::CopyWithCast(), itk::Index< VDimension >::CopyWithRound(), itk::Offset< VDimension >::CopyWithRound(), itk::SpatialObject< VDimension >::Evaluate(), itk::BinaryThresholdImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::BSplineInterpolateImageFunction< TImageType, TCoordRep, TCoefficientType >::Evaluate(), itk::CovarianceImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::ExtrapolateImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::InterpolateImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::MeanImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::MedianImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::NeighborhoodBinaryThresholdImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::ScatterMatrixImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::SumOfSquaresImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::VarianceImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::VectorInterpolateImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::VectorMeanImageFunction< TInputImage, TCoordRep >::Evaluate(), itk::BSplineInterpolateImageFunction< TImageType, TCoordRep, TCoefficientType >::EvaluateDerivative(), itk::BSplineInterpolateImageFunction< TImageType, TCoordRep, TCoefficientType >::EvaluateValueAndDerivative(), itk::ImageToImageMetric< TFixedImage, TMovingImage >::FixedImageSamplePoint::FixedImageSamplePoint(), itk::PointSetToPointSetMetricv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >::GetLocalNeighborhoodDerivativeWithIndex(), itk::PointSetToPointSetMetricv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >::GetLocalNeighborhoodValueAndDerivativeWithIndex(), itk::PointSetToPointSetMetricv4< TFixedPointSet, TMovingPointSet, TInternalComputationValueType >::GetLocalNeighborhoodValueWithIndex(), itk::ImageFunction< TInputImage, TOutput, TCoordRep >::IsInsideBuffer(), itk::Point1D::Point1D(), itk::ShapePositionLabelMapFilter< TImage >::TemplatedThreadedProcessLabelObject(), itk::ImageAdaptor< TImage, TAccessor >::TransformContinuousIndexToPhysicalPoint(), itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformContinuousIndexToPhysicalPoint(), itk::ImageBase< VImageDimension >::TransformContinuousIndexToPhysicalPoint(), itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformIndexToPhysicalPoint(), itk::ImageAdaptor< TImage, TAccessor >::TransformIndexToPhysicalPoint(), itk::ImageBase< VImageDimension >::TransformIndexToPhysicalPoint(), itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformPhysicalPointToContinuousIndex(), itk::ImageAdaptor< TImage, TAccessor >::TransformPhysicalPointToContinuousIndex(), itk::ImageBase< VImageDimension >::TransformPhysicalPointToContinuousIndex(), itk::PhasedArray3DSpecialCoordinatesImage< TPixel >::TransformPhysicalPointToIndex(), itk::ImageAdaptor< TImage, TAccessor >::TransformPhysicalPointToIndex(), itk::ImageBase< VImageDimension >::TransformPhysicalPointToIndex(), and itk::IdentityTransform< TParametersValueType, VDimension >::TransformPoint().
ReadImage()
template<typename TOutputImage , typename ConvertPixelTraits = DefaultConvertPixelTraits<typename TOutputImage::IOPixelType>> TOutputImage::Pointer itk::ReadImage (const std::string & filename)
Convenience function for reading an image.
TOutputImage is the expected output image type, and the optional ConvertPixelTraits template parameter is used to do the conversion, as specified by ImageFileReader.
The function reads the image from the specified file, and returns the image that it has read.
Definition at line 186 of file itkImageFileReader.h.
References itk::ImageFileReader< TOutputImage, ConvertPixelTraits >::New().
ReadMesh()
template<typename TOutputMesh , typename ConvertPointPixelTraits = MeshConvertPixelTraits<typename TOutputMesh::PixelType>, typename ConvertCellPixelTraits = MeshConvertPixelTraits<typename TOutputMesh::CellPixelType>> TOutputMesh::Pointer itk::ReadMesh (const std::string & filename)
Convenience function for reading a mesh.
TOutputMesh is the expected output mesh type, and the optional ConvertPointPixelTraits, `ConvertCellPixelTraits template parameters are used to do the conversion, as specified by MeshFileReader.
The function reads the mesh from the specified file, and returns the mesh that it has read.
Definition at line 217 of file itkMeshFileReader.h.
References itk::MeshFileReader< TOutputMesh, ConvertPointPixelTraits, ConvertCellPixelTraits >::New().
ReadRawBytesAfterSwapping()
ITKIOImageBase_EXPORT void itk::ReadRawBytesAfterSwapping (IOComponentEnum componentType, void * buffer, IOByteOrderEnum byteOrder, SizeValueType numberOfComponents)
Utility function for reading RAW bytes
setConnectivity()
template<typename TIterator > TIterator * itk::setConnectivity (TIterator * it, bool fullyConnected = false)
Definition at line 28 of file itkConnectedComponentAlgorithm.h.
References itk::GTest::TypedefsAndConstructors::Dimension2::Dimension.
Referenced by itk::ScanlineFilterCommon< TInputImage, TOutputImage >::SetupLineOffsets().
setConnectivityLater()
template<typename TIterator > TIterator * itk::setConnectivityLater (TIterator * it, bool fullyConnected = false)
Definition at line 99 of file itkConnectedComponentAlgorithm.h.
References itk::GTest::TypedefsAndConstructors::Dimension2::Dimension.
setConnectivityPrevious()
template<typename TIterator > TIterator * itk::setConnectivityPrevious (TIterator * it, bool fullyConnected = false)
Definition at line 64 of file itkConnectedComponentAlgorithm.h.
References itk::GTest::TypedefsAndConstructors::Dimension2::Dimension.
Referenced by itk::ScanlineFilterCommon< TInputImage, TOutputImage >::SetupLineOffsets().
Singleton()
template<typename T > T * itk::Singleton (const char * globalName, std::function< void(void *)> func, std::function< void()> deleteFunc)
Definition at line 115 of file itkSingleton.h.
References itk::SingletonIndex::GetGlobalInstance(), itk::SingletonIndex::GetInstance(), itk::SingletonIndex::SetGlobalInstance(), and Unused().
swap() [1/15]
template<typename T > void itk::swap (Array< T > & a, Array< T > & b) inline
Definition at line 242 of file itkArray.h.
References itk::Array< TValue >::Swap().
Referenced by itk::Array< TValue >::Swap(), and itk::Matrix< T, VRows, VColumns >::swap().
swap() [2/15]
template<typename T , unsigned int VRows, unsigned int VColumns> void itk::swap (const Matrix< T, VRows, VColumns > & a, const Matrix< T, VRows, VColumns > & b) inline
Definition at line 327 of file itkMatrix.h.
References itk::Matrix< T, VRows, VColumns >::swap().
Referenced by itk::Matrix< T, VRows, VColumns >::swap().
swap() [3/15]
template<typename T , unsigned int VVectorDimension> void itk::swap (CovariantVector< T, VVectorDimension > & a, CovariantVector< T, VVectorDimension > & b) inline
Definition at line 294 of file itkCovariantVector.h.
References itk::FixedArray< TValue, VLength >::swap().
swap() [4/15]
template<typename T > void itk::swap (DiffusionTensor3D< T > & a, DiffusionTensor3D< T > & b) inline
Definition at line 156 of file itkDiffusionTensor3D.h.
References itk::FixedArray< TValue, VLength >::swap().
swap() [5/15]
template<typename TValue , unsigned int VLength> void itk::swap (FixedArray< TValue, VLength > & a, FixedArray< TValue, VLength > & b) inline
Definition at line 442 of file itkFixedArray.h.
References itk::FixedArray< TValue, VLength >::swap().
Referenced by itk::FixedArray< TValue, VLength >::swap().
swap() [6/15]
template<unsigned int VDimension> void itk::swap (Index< VDimension > & one, Index< VDimension > & two) inline
Definition at line 588 of file itkIndex.h.
References itk::Index< VDimension >::m_InternalArray, and swap().
Referenced by itk::Index< VDimension >::swap(), and swap().
swap() [7/15]
void itk::swap (MetaDataDictionary & a, MetaDataDictionary & b) inline
Definition at line 185 of file itkMetaDataDictionary.h.
References itk::MetaDataDictionary::Swap().
swap() [8/15]
template<unsigned int VDimension> void itk::swap (Offset< VDimension > & one, Offset< VDimension > & two) inline
Definition at line 532 of file itkOffset.h.
References itk::Offset< VDimension >::m_InternalArray, and swap().
Referenced by itk::Offset< VDimension >::swap(), and swap().
swap() [9/15]
template<typename TCoordRep , unsigned int VPointDimension> void itk::swap (Point< TCoordRep, VPointDimension > & a, Point< TCoordRep, VPointDimension > & b) inline
Definition at line 367 of file itkPoint.h.
References itk::FixedArray< TValue, VLength >::swap().
swap() [10/15]
template<typename T > void itk::swap (RGBAPixel< T > & a, RGBAPixel< T > & b) inline
Definition at line 249 of file itkRGBAPixel.h.
References itk::FixedArray< TValue, VLength >::swap().
swap() [11/15]
template<typename T > void itk::swap (RGBPixel< T > & a, RGBPixel< T > & b) inline
Definition at line 244 of file itkRGBPixel.h.
References itk::FixedArray< TValue, VLength >::swap().
swap() [12/15]
template<unsigned int VDimension> void itk::swap (Size< VDimension > & one, Size< VDimension > & two) inline
Definition at line 486 of file itkSize.h.
References itk::Size< VDimension >::m_InternalArray, and swap().
Referenced by itk::Size< VDimension >::swap(), and swap().
swap() [13/15]
template<typename T > void itk::swap (SmartPointer< T > & a, SmartPointer< T > & b) inline noexcept
Definition at line 307 of file itkSmartPointer.h.
swap() [14/15]
template<typename T > void itk::swap (SymmetricSecondRankTensor< T > & a, SymmetricSecondRankTensor< T > & b) inline
Definition at line 259 of file itkSymmetricSecondRankTensor.h.
References itk::FixedArray< TValue, VLength >::swap().
swap() [15/15]
template<typename T , unsigned int VVectorDimension> void itk::swap (Vector< T, VVectorDimension > & a, Vector< T, VVectorDimension > & b) inline
Definition at line 329 of file itkVector.h.
References itk::FixedArray< TValue, VLength >::swap().
TransferAutoPointer()
template<typename TAutoPointerBase , typename TAutoPointerDerived > void itk::TransferAutoPointer (TAutoPointerBase & pa, TAutoPointerDerived & pb)
This templated function is intended to facilitate the transfer between AutoPointers of Derived class to Base class
Definition at line 250 of file itkAutoPointer.h.
WriteImage()
template<typename TImagePointer > ITK_TEMPLATE_EXPORT void itk::WriteImage (TImagePointer && image, const std::string & filename, bool compress = false)
Convenience function for writing an image.
The image parameter may be a either SmartPointer or a raw pointer and const or non-const.
Definition at line 254 of file itkImageFileWriter.h.
References itk::ImageFileWriter< TInputImage >::New().
WriteMesh()
template<typename TMeshPointer > ITK_TEMPLATE_EXPORT void itk::WriteMesh (TMeshPointer && mesh, const std::string & filename, bool compress = false)
Convenience function for writing a mesh.
The mesh parameter may be a either SmartPointer or a raw pointer and const or non-const.
Definition at line 199 of file itkMeshFileWriter.h.
References itk::MeshFileWriter< TInputMesh >::New().
WriteRawBytesAfterSwapping()
ITKIOImageBase_EXPORT void itk::WriteRawBytesAfterSwapping (IOComponentEnum componentType, const void * buffer, std::ofstream & file, IOByteOrderEnum byteOrder, SizeValueType numberOfBytes, SizeValueType numberOfComponents)
Utility function for writing RAW bytes
Variable Documentation
CellInterface
template<typename TPixelType , typename TCellTraits > class ITK_TEMPLATE_EXPORT itk::CellInterface
Definition at line 29 of file itkCellInterfaceVisitor.h.
Command
class ITK_FORWARD_EXPORT itk::Command
Definition at line 42 of file itkObject.h.
CompositeTransformIOHelperTemplate< double >
template class ITKIOTransformBase_EXPORT_EXPLICIT itk::CompositeTransformIOHelperTemplate< double > extern
CompositeTransformIOHelperTemplate< float >
template class ITKIOTransformBase_EXPORT_EXPLICIT itk::CompositeTransformIOHelperTemplate< float > extern
DataObject
class ITK_FORWARD_EXPORT itk::DataObject
Friends of ProcessObject
Definition at line 42 of file itkDataObject.h.
Filtering
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating so it cannot multithread for data other than in Anisotropic Diffusion of Multivalued Images* with Application to Color itk::Filtering
Definition at line 124 of file itkVectorGradientMagnitudeImageFilter.h.
GradientDescentOptimizerBasev4Template
template<typename TInternalComputationValueType > class ITK_FORWARD_EXPORT itk::GradientDescentOptimizerBasev4Template
Definition at line 27 of file itkGradientDescentOptimizerBasev4ModifyGradientByLearningRateThreader.h.
HDF5TransformIOTemplate< double >
template class ITKIOTransformHDF5_EXPORT_EXPLICIT itk::HDF5TransformIOTemplate< double > extern
HDF5TransformIOTemplate< float >
template class ITKIOTransformHDF5_EXPORT_EXPLICIT itk::HDF5TransformIOTemplate< float > extern
ImageBase
template<unsigned int VImageDimension> class ITK_TEMPLATE_EXPORT itk::ImageBase
Definition at line 51 of file itkImageHelper.h.
images
* par Constraints* The filter image with at least two dimensions and a vector* length of at least The theory supports extension to scalar itk::images
Definition at line 107 of file itkVectorGradientMagnitudeImageFilter.h.
ITK_ExperimentDate
ITKIOImageBase_EXPORT const char* const itk::ITK_ExperimentDate extern
ITK_ExperimentTime
ITKIOImageBase_EXPORT const char* const itk::ITK_ExperimentTime extern
ITK_FileNotes
ITKIOImageBase_EXPORT const char* const itk::ITK_FileNotes extern
ITK_FileOriginator
ITKIOImageBase_EXPORT const char* const itk::ITK_FileOriginator extern
ITK_ImageFileBaseName
ITKIOImageBase_EXPORT const char* const itk::ITK_ImageFileBaseName extern
ITK_ImageType
ITKIOImageBase_EXPORT const char* const itk::ITK_ImageType extern
ITK_InputFilterName
ITKIOImageBase_EXPORT const char* const itk::ITK_InputFilterName extern
ITK_MAX_THREADS
constexpr vcl_size_t itk::ITK_MAX_THREADS = 1 constexpr
Platform specific type alias for simple types
Definition at line 78 of file itkThreadSupport.h.
ITK_NumberOfDimensions
ITKIOImageBase_EXPORT const char* const itk::ITK_NumberOfDimensions extern
ITK_OnDiskBitPerPixel
ITKIOImageBase_EXPORT const char* const itk::ITK_OnDiskBitPerPixel extern
ITK_OnDiskStorageTypeName
ITKIOImageBase_EXPORT const char* const itk::ITK_OnDiskStorageTypeName extern
ITK_Origin
ITKIOImageBase_EXPORT const char* const itk::ITK_Origin extern
ITK_OriginationDate
ITKIOImageBase_EXPORT const char* const itk::ITK_OriginationDate extern
ITK_PatientID
ITKIOImageBase_EXPORT const char* const itk::ITK_PatientID extern
ITK_PatientName
ITKIOImageBase_EXPORT const char* const itk::ITK_PatientName extern
ITK_ScanID
ITKIOImageBase_EXPORT const char* const itk::ITK_ScanID extern
ITK_Spacing
ITKIOImageBase_EXPORT const char* const itk::ITK_Spacing extern
ITK_VoxelUnits
ITKIOImageBase_EXPORT const char* const itk::ITK_VoxelUnits extern
ITK_ZDirection
ITKIOImageBase_EXPORT const char* const itk::ITK_ZDirection extern
KLMSegmentationBorder
class ITK_FORWARD_EXPORT itk::KLMSegmentationBorder
Definition at line 91 of file itkKLMSegmentationRegion.h.
KLMSegmentationRegion
class ITK_FORWARD_EXPORT itk::KLMSegmentationRegion
Definition at line 138 of file itkKLMSegmentationBorder.h.
LBFGSBOptimizerHelper
class ITK_FORWARD_EXPORT itk::LBFGSBOptimizerHelper
Definition at line 36 of file itkLBFGSBOptimizer.h.
LBFGSBOptimizerHelperv4
class ITK_FORWARD_EXPORT itk::LBFGSBOptimizerHelperv4
Definition at line 38 of file itkLBFGSBOptimizerv4.h.
LBFGSOptimizerBaseHelperv4
template<typename TInternalVnlOptimizerType > class ITK_TEMPLATE_EXPORT itk::LBFGSOptimizerBaseHelperv4
Definition at line 41 of file itkLBFGSOptimizerBasev4.h.
MINCImageIOPImpl
struct ITKIOMINC_HIDDEN itk::MINCImageIOPImpl
Definition at line 41 of file itkMINCImageIO.h.
ObjectToObjectOptimizerBaseTemplate< double >
template class ITKOptimizersv4_EXPORT_EXPLICIT itk::ObjectToObjectOptimizerBaseTemplate< double > extern
ObjectToObjectOptimizerBaseTemplate< float >
template class ITKOptimizersv4_EXPORT_EXPLICIT itk::ObjectToObjectOptimizerBaseTemplate< float > extern
OctreeBase
class ITK_FORWARD_EXPORT itk::OctreeBase
Definition at line 28 of file itkOctreeNode.h.
OctreeNodeBranch
class ITK_FORWARD_EXPORT itk::OctreeNodeBranch
Definition at line 27 of file itkOctreeNode.h.
pp
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating so it cannot multithread for data other than in Anisotropic Diffusion of Multivalued Images* with Application to Color IEEE Transactions on Image No itk::pp
Definition at line 125 of file itkVectorGradientMagnitudeImageFilter.h.
Processing
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating so it cannot multithread for data other than in Anisotropic Diffusion of Multivalued Images* with Application to Color IEEE Transactions on Image itk::Processing
Definition at line 124 of file itkVectorGradientMagnitudeImageFilter.h.
ProcessObject
class ITK_FORWARD_EXPORT itk::ProcessObject
Friends of DataObject
Definition at line 41 of file itkDataObject.h.
QuasiNewtonOptimizerv4Template
template<typename TInternalComputationValueType > class ITK_FORWARD_EXPORT itk::QuasiNewtonOptimizerv4Template
Definition at line 27 of file itkQuasiNewtonOptimizerv4EstimateNewtonStepThreader.h.
ROI_NAME
ITKIOImageBase_EXPORT const char* const itk::ROI_NAME extern
ROI_NUM_SEGMENTS
ITKIOImageBase_EXPORT const char* const itk::ROI_NUM_SEGMENTS extern
ROI_PLANE
ITKIOImageBase_EXPORT const char* const itk::ROI_PLANE extern
ROI_SCAN_ID
ITKIOImageBase_EXPORT const char* const itk::ROI_SCAN_ID extern
ROI_X_RESOLUTION
ITKIOImageBase_EXPORT const char* const itk::ROI_X_RESOLUTION extern
ROI_X_SIZE
ITKIOImageBase_EXPORT const char* const itk::ROI_X_SIZE extern
ROI_Y_RESOLUTION
ITKIOImageBase_EXPORT const char* const itk::ROI_Y_RESOLUTION extern
ROI_Y_SIZE
ITKIOImageBase_EXPORT const char* const itk::ROI_Y_SIZE extern
ROI_Z_RESOLUTION
ITKIOImageBase_EXPORT const char* const itk::ROI_Z_RESOLUTION extern
ROI_Z_SIZE
ITKIOImageBase_EXPORT const char* const itk::ROI_Z_SIZE extern
SPM_ROI_SCALE
ITKIOImageBase_EXPORT const char* const itk::SPM_ROI_SCALE extern
TemporalDataObject
class ITK_FORWARD_EXPORT itk::TemporalDataObject
Definition at line 29 of file itkTemporalProcessObject.h.
ThreadedIteratorRangePartitioner
template<typename TIterator > class ITK_TEMPLATE_EXPORT itk::ThreadedIteratorRangePartitioner
Definition at line 29 of file itkThreadedIteratorRangePartitioner.h.
TransformFileReaderTemplate< double >
template class ITKIOTransformBase_EXPORT_EXPLICIT itk::TransformFileReaderTemplate< double > extern
TransformFileReaderTemplate< float >
template class ITKIOTransformBase_EXPORT_EXPLICIT itk::TransformFileReaderTemplate< float > extern
TransformFileWriterTemplate< double >
template class ITKIOTransformBase_EXPORT_EXPLICIT itk::TransformFileWriterTemplate< double > extern
TransformFileWriterTemplate< float >
template class ITKIOTransformBase_EXPORT_EXPLICIT itk::TransformFileWriterTemplate< float > extern
TransformIOBaseTemplate< double >
template class ITKIOTransformBase_EXPORT_EXPLICIT itk::TransformIOBaseTemplate< double > extern
TransformIOBaseTemplate< float >
template class ITKIOTransformBase_EXPORT_EXPLICIT itk::TransformIOBaseTemplate< float > extern
TransformIOFactoryTemplate< double >
template class ITKIOTransformBase_EXPORT_EXPLICIT itk::TransformIOFactoryTemplate< double > extern
TransformIOFactoryTemplate< float >
template class ITKIOTransformBase_EXPORT_EXPLICIT itk::TransformIOFactoryTemplate< float > extern
TxtTransformIOTemplate< double >
template class ITKIOTransformInsightLegacy_EXPORT_EXPLICIT itk::TxtTransformIOTemplate< double > extern
TxtTransformIOTemplate< float >
template class ITKIOTransformInsightLegacy_EXPORT_EXPLICIT itk::TxtTransformIOTemplate< float > extern
UsePrincipleComponents
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating so it cannot multithread for data other than in* itk::UsePrincipleComponents
Initial value:
=On mode.
 *
 * \par References
 *
 * [1] G. Sapiro and D. Ringach
Definition at line 119 of file itkVectorGradientMagnitudeImageFilter.h.
Vol
*par Constraints *The filter image with at least two dimensions and a vector *length of at least The theory supports extension to scalar but *the implementation of the itk vector classes do not **The template parameter TRealType must be floating so it cannot multithread for data other than in Anisotropic Diffusion of Multivalued Images* with Application to Color IEEE Transactions on Image * itk::Vol
Definition at line 125 of file itkVectorGradientMagnitudeImageFilter.h.