ITK: itk::detail Namespace Reference
itk::detail Namespace Reference
Functions
template<typename TValueType , unsigned int VRows, unsigned int VColumns>
const TValueType * GetPointerToMatrixData (const itk::Matrix< TValueType, VRows, VColumns > &inputMatrix)
template<typename TValueType >
const TValueType * GetPointerToMatrixData (const vnl_matrix< TValueType > &inputMatrix)
template<typename TValueType , unsigned int VRows, unsigned int VColumns>
const TValueType * GetPointerToMatrixData (const vnl_matrix_fixed< TValueType, VRows, VColumns > &inputMatrix)
template<typename TArray >
std::vector< int > sortEigenValuesByMagnitude (TArray &eigenValues, const unsigned int numberOfElements)
template<typename QMatrix >
void permuteColumnsWithSortIndices (QMatrix &eigenVectors, const std::vector< int > &indicesSortPermutations)
Function Documentation
GetPointerToMatrixData() [1/3]
template<typename TValueType , unsigned int VRows, unsigned int VColumns> const TValueType * itk::detail::GetPointerToMatrixData (const itk::Matrix< TValueType, VRows, VColumns > & inputMatrix)
Definition at line 51 of file itkSymmetricEigenAnalysis.h.
References itk::Matrix< T, VRows, VColumns >::GetVnlMatrix().
Referenced by itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsWithEigenLibraryImpl(), itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsWithEigenLibraryImpl(), itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesWithEigenLibraryImpl(), and itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesWithEigenLibraryImpl().
GetPointerToMatrixData() [2/3]
template<typename TValueType > const TValueType * itk::detail::GetPointerToMatrixData (const vnl_matrix< TValueType > & inputMatrix)
Definition at line 44 of file itkSymmetricEigenAnalysis.h.
GetPointerToMatrixData() [3/3]
template<typename TValueType , unsigned int VRows, unsigned int VColumns> const TValueType * itk::detail::GetPointerToMatrixData (const vnl_matrix_fixed< TValueType, VRows, VColumns > & inputMatrix)
Definition at line 38 of file itkSymmetricEigenAnalysis.h.
permuteColumnsWithSortIndices()
template<typename QMatrix > void itk::detail::permuteColumnsWithSortIndices (QMatrix & eigenVectors, const std::vector< int > & indicesSortPermutations)
Permute a eigenVectors matrix according to the permutation indices computed from the output of a sort function like
See also
detail::sortEigenValuesByMagnitude
Template Parameters
QMatrix a Eigen3 matrix
Parameters
eigenVectors stored in columns
indicesSortPermutations container with the permutations from the output of a sort function.
Definition at line 102 of file itkSymmetricEigenAnalysis.h.
Referenced by itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsWithEigenLibraryImpl(), and itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsWithEigenLibraryImpl().
sortEigenValuesByMagnitude()
template<typename TArray > std::vector< int > itk::detail::sortEigenValuesByMagnitude (TArray & eigenValues, const unsigned int numberOfElements)
Sort input to be ordered by magnitude, and returns container with the permutations required for the sorting.
For example, if input eigenValues = {10, 0, 40}, the output would be: {2,0,1} and the eigenValues would be modified in-place: {40, 10, 0}.
The permutations indices is used to order the matrix of eigenVectors.
See also
permuteEigenVectorsWithSortPermutations
Template Parameters
TArray array type with operator []
Parameters
eigenValues input array, requires operator []
numberOfElements size of array
Returns
the permutations needed to sort the input array
Definition at line 73 of file itkSymmetricEigenAnalysis.h.
References itk::Math::abs().
Referenced by itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsWithEigenLibraryImpl(), itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesAndVectorsWithEigenLibraryImpl(), itk::SymmetricEigenAnalysis< TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesWithEigenLibraryImpl(), and itk::SymmetricEigenAnalysisFixedDimension< VDimension, TMatrix, TVector, TEigenMatrix >::ComputeEigenValuesWithEigenLibraryImpl().