ITK: itk::Offset< VDimension > Struct Template Reference
itk::Offset< VDimension > Struct Template Reference final
Data Access Objects » Image Access Objects | Group Core » Module ITKCommon
#include <itkOffset.h>
Detailed Description
template<unsigned int VDimension = 2>
struct itk::Offset< VDimension >
Represent a n-dimensional offset between two n-dimensional indexes of n-dimensional image.
Offset is a templated class to represent a multi-dimensional offset, i.e. (i,j,k,...). Offset is templated over the dimension of the space. ITK assumes the first element of a size (bounds) is the fastest moving index.
For efficiency, Offset does not define a default constructor, a copy constructor, or an operator=. We rely on the compiler to provide efficient bitwise copies.
Offset is an "aggregate" class. Its data is public (m_InternalArray) allowing for fast and convenient instantiations/assignments.
The following syntax for assigning an aggregate type like this is allowed/suggested:
Offset<3> var{{ 256, 256, 20 }}; // Also prevent narrowing conversions Offset<3> var = {{ 256, 256, 20 }};
The doubled braces {{ and }} are required to prevent ‘gcc -Wall’ (and perhaps other compilers) from complaining about a partly bracketed initializer.
As an aggregate type that is intended to provide highest performance characteristics, this class is not appropriate to inherit from, so setting this struct as final.
See also
Index
ITK Sphinx Examples:
<a href=
<a href=
Definition at line 66 of file itkOffset.h.
Public Types
using const_iterator = const value_type *
using const_reference = const value_type &
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using difference_type = ptrdiff_t
using iterator = value_type *
using OffsetType = Offset< VDimension >
using OffsetValueType = itk::OffsetValueType
using reference = value_type &
using reverse_iterator = std::reverse_iterator< iterator >
using Self = Offset
using size_type = unsigned int
using value_type = itk::OffsetValueType
Public Member Functions
void assign (const value_type &newValue)
reference at (size_type pos)
const_reference at (size_type pos) const
constexpr reference back ()
constexpr const_reference back () const
constexpr iterator begin ()
constexpr const_iterator begin () const
constexpr const_iterator cbegin () const
constexpr const_iterator cend () const
OffsetValueType * data ()
const OffsetValueType * data () const
constexpr bool empty () const
constexpr iterator end ()
constexpr const_iterator end () const
void Fill (OffsetValueType value)
constexpr reference front ()
constexpr const_reference front () const
OffsetValueType GetElement (unsigned long element) const
const OffsetValueType * GetOffset () const
constexpr size_type max_size () const
const Self operator+ (const Self &vec) const
const Self operator+ (const Size< VDimension > &sz) const
const Self operator- (const Self &vec) const
reference operator[] (size_type pos)
const_reference operator[] (size_type pos) const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
void SetElement (unsigned long element, OffsetValueType val)
void SetOffset (const OffsetValueType val[VDimension])
constexpr size_type size () const
void swap (Offset &other) noexcept
const Self & operator+= (const Size< VDimension > &sz)
const Self & operator-= (const Size< VDimension > &sz)
const Self & operator+= (const Self &vec)
const Self & operator-= (const Self &vec)
template<typename TCoordinate >
void CopyWithRound (const FixedArray< TCoordinate, VDimension > &point)
template<typename TCoordinate >
void CopyWithCast (const FixedArray< TCoordinate, VDimension > &point)
Static Public Member Functions
static Self GetBasisOffset (unsigned int dim)
static constexpr unsigned int GetOffsetDimension ()
Public Attributes
OffsetValueType m_InternalArray [VDimension]
Static Public Attributes
static constexpr unsigned int Dimension = VDimension
Private Member Functions
void ExceptionThrowingBoundsCheck (size_type pos) const
Member Typedef Documentation
const_iterator
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::const_iterator = const value_type *
Definition at line 287 of file itkOffset.h.
const_reference
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::const_reference = const value_type &
Definition at line 285 of file itkOffset.h.
const_reverse_iterator
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 291 of file itkOffset.h.
difference_type
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::difference_type = ptrdiff_t
Definition at line 289 of file itkOffset.h.
iterator
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::iterator = value_type *
Definition at line 286 of file itkOffset.h.
OffsetType
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::OffsetType = Offset<VDimension>
Compatible Offset and value type alias.
Definition at line 76 of file itkOffset.h.
OffsetValueType
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::OffsetValueType = itk::OffsetValueType
Definition at line 77 of file itkOffset.h.
reference
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::reference = value_type &
Definition at line 284 of file itkOffset.h.
reverse_iterator
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 290 of file itkOffset.h.
Self
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::Self = Offset
Standard class type aliases.
Definition at line 73 of file itkOffset.h.
size_type
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::size_type = unsigned int
Definition at line 288 of file itkOffset.h.
value_type
template<unsigned int VDimension = 2> using itk::Offset< VDimension >::value_type = itk::OffsetValueType
Mirror the std::array type aliases and member function so that the Offset class can be treated as a container class in a way that is similar to the std::array.
Definition at line 283 of file itkOffset.h.
Member Function Documentation
assign()
template<unsigned int VDimension = 2> void itk::Offset< VDimension >::assign (const value_type & newValue) inline
Mirror behavior of the std::array manipulations See std::array for documentation on these methods
Definition at line 298 of file itkOffset.h.
at() [1/2]
template<unsigned int VDimension = 2> reference itk::Offset< VDimension >::at (size_type pos) inline
Definition at line 400 of file itkOffset.h.
at() [2/2]
template<unsigned int VDimension = 2> const_reference itk::Offset< VDimension >::at (size_type pos) const inline
Definition at line 407 of file itkOffset.h.
back() [1/2]
template<unsigned int VDimension = 2> constexpr reference itk::Offset< VDimension >::back () inline constexpr
Definition at line 426 of file itkOffset.h.
back() [2/2]
template<unsigned int VDimension = 2> constexpr const_reference itk::Offset< VDimension >::back () const inline constexpr
Definition at line 432 of file itkOffset.h.
begin() [1/2]
template<unsigned int VDimension = 2> constexpr iterator itk::Offset< VDimension >::begin () inline constexpr
Definition at line 316 of file itkOffset.h.
Referenced by itk::ConnectedImageNeighborhoodShape< VImageDimension >::FillOffsets(), itk::RectangularImageNeighborhoodShape< VImageDimension >::FillOffsets(), itk::operator<(), and itk::operator==().
begin() [2/2]
template<unsigned int VDimension = 2> constexpr const_iterator itk::Offset< VDimension >::begin () const inline constexpr
Definition at line 322 of file itkOffset.h.
cbegin()
template<unsigned int VDimension = 2> constexpr const_iterator itk::Offset< VDimension >::cbegin () const inline constexpr
Definition at line 310 of file itkOffset.h.
cend()
template<unsigned int VDimension = 2> constexpr const_iterator itk::Offset< VDimension >::cend () const inline constexpr
Definition at line 328 of file itkOffset.h.
CopyWithCast()
template<unsigned int VDimension = 2> template<typename TCoordinate > void itk::Offset< VDimension >::CopyWithCast (const FixedArray< TCoordinate, VDimension > & point) inline
Copy values from a FixedArray by casting each one of the components
Definition at line 261 of file itkOffset.h.
References itk::point().
CopyWithRound()
template<unsigned int VDimension = 2> template<typename TCoordinate > void itk::Offset< VDimension >::CopyWithRound (const FixedArray< TCoordinate, VDimension > & point) inline
Copy values from a FixedArray by rounding each one of the components
Definition at line 249 of file itkOffset.h.
References itk::point().
data() [1/2]
template<unsigned int VDimension = 2> OffsetValueType * itk::Offset< VDimension >::data () inline
Definition at line 438 of file itkOffset.h.
Referenced by itk::ImageRegionRange< TImage >::ComputeOffset().
data() [2/2]
template<unsigned int VDimension = 2> const OffsetValueType * itk::Offset< VDimension >::data () const inline
Definition at line 444 of file itkOffset.h.
empty()
template<unsigned int VDimension = 2> constexpr bool itk::Offset< VDimension >::empty () const inline constexpr
Definition at line 382 of file itkOffset.h.
end() [1/2]
template<unsigned int VDimension = 2> constexpr iterator itk::Offset< VDimension >::end () inline constexpr
Definition at line 334 of file itkOffset.h.
Referenced by itk::ConnectedImageNeighborhoodShape< VImageDimension >::FillOffsets(), itk::operator<(), and itk::operator==().
end() [2/2]
template<unsigned int VDimension = 2> constexpr const_iterator itk::Offset< VDimension >::end () const inline constexpr
Definition at line 340 of file itkOffset.h.
ExceptionThrowingBoundsCheck()
template<unsigned int VDimension = 2> void itk::Offset< VDimension >::ExceptionThrowingBoundsCheck (size_type pos) const inline private
Definition at line 451 of file itkOffset.h.
Fill()
template<unsigned int VDimension = 2> void itk::Offset< VDimension >::Fill (OffsetValueType value) inline
Set one value for the offset in all dimensions. Useful for initializing an offset to zero.
Definition at line 223 of file itkOffset.h.
front() [1/2]
template<unsigned int VDimension = 2> constexpr reference itk::Offset< VDimension >::front () inline constexpr
Definition at line 414 of file itkOffset.h.
front() [2/2]
template<unsigned int VDimension = 2> constexpr const_reference itk::Offset< VDimension >::front () const inline constexpr
Definition at line 420 of file itkOffset.h.
GetBasisOffset()
template<unsigned int VDimension> Offset< VDimension > itk::Offset< VDimension >::GetBasisOffset (unsigned int dim) static
Return a basis vector of the form [0, ..., 0, 1, 0, ... 0] where the "1" is positioned in the location specified by the parameter "dim". Valid values of "dim" are 0, ..., VDimension-1.
Definition at line 463 of file itkOffset.h.
References itk::Offset< VDimension >::m_InternalArray.
GetElement()
template<unsigned int VDimension = 2> OffsetValueType itk::Offset< VDimension >::GetElement (unsigned long element) const inline
Gets the value of one of the elements. This method is mainly intended to facilitate the access to elements from Tcl and Python where C++ notation is not very convenient.
Warning
No bound checking is performed
See also
GetIndex()
SetElement()
Definition at line 215 of file itkOffset.h.
GetOffset()
template<unsigned int VDimension = 2> const OffsetValueType * itk::Offset< VDimension >::GetOffset () const inline
Get the offset. This provides a read only pointer to the offset.
See also
SetOffset()
Definition at line 181 of file itkOffset.h.
Referenced by itk::ConstShapedNeighborhoodIterator< TImage, TBoundaryCondition >::ConstIterator::GetNeighborhoodOffset().
GetOffsetDimension()
template<unsigned int VDimension = 2> static constexpr unsigned int itk::Offset< VDimension >::GetOffsetDimension () inline static constexpr
Get the dimension (size) of the index.
Definition at line 84 of file itkOffset.h.
max_size()
template<unsigned int VDimension = 2> constexpr size_type itk::Offset< VDimension >::max_size () const inline constexpr
Definition at line 376 of file itkOffset.h.
operator+() [1/2]
template<unsigned int VDimension = 2> const Self itk::Offset< VDimension >::operator+ (const Self & vec) const inline
Add two offsets.
Definition at line 92 of file itkOffset.h.
References itk::Offset< VDimension >::m_InternalArray.
operator+() [2/2]
template<unsigned int VDimension = 2> const Self itk::Offset< VDimension >::operator+ (const Size< VDimension > & sz) const inline
Add a size to an offset.
Definition at line 105 of file itkOffset.h.
operator+=() [1/2]
template<unsigned int VDimension = 2> const Self & itk::Offset< VDimension >::operator+= (const Self & vec) inline
Increment offset by an offset.
Definition at line 155 of file itkOffset.h.
References itk::Offset< VDimension >::m_InternalArray.
operator+=() [2/2]
template<unsigned int VDimension = 2> const Self & itk::Offset< VDimension >::operator+= (const Size< VDimension > & sz) inline
Increment index by a size.
Definition at line 118 of file itkOffset.h.
operator-()
template<unsigned int VDimension = 2> const Self itk::Offset< VDimension >::operator- (const Self & vec) const inline
Subtract two offsets.
Definition at line 142 of file itkOffset.h.
References itk::Offset< VDimension >::m_InternalArray.
operator-=() [1/2]
template<unsigned int VDimension = 2> const Self & itk::Offset< VDimension >::operator-= (const Self & vec) inline
Decrement offset by an offset.
Definition at line 167 of file itkOffset.h.
References itk::Offset< VDimension >::m_InternalArray.
operator-=() [2/2]
template<unsigned int VDimension = 2> const Self & itk::Offset< VDimension >::operator-= (const Size< VDimension > & sz) inline
Decrement index by a size.
Definition at line 130 of file itkOffset.h.
operator[]() [1/2]
template<unsigned int VDimension = 2> reference itk::Offset< VDimension >::operator[] (size_type pos) inline
Definition at line 388 of file itkOffset.h.
operator[]() [2/2]
template<unsigned int VDimension = 2> const_reference itk::Offset< VDimension >::operator[] (size_type pos) const inline
Definition at line 394 of file itkOffset.h.
rbegin() [1/2]
template<unsigned int VDimension = 2> reverse_iterator itk::Offset< VDimension >::rbegin () inline
Definition at line 346 of file itkOffset.h.
rbegin() [2/2]
template<unsigned int VDimension = 2> const_reverse_iterator itk::Offset< VDimension >::rbegin () const inline
Definition at line 352 of file itkOffset.h.
rend() [1/2]
template<unsigned int VDimension = 2> reverse_iterator itk::Offset< VDimension >::rend () inline
Definition at line 358 of file itkOffset.h.
rend() [2/2]
template<unsigned int VDimension = 2> const_reverse_iterator itk::Offset< VDimension >::rend () const inline
Definition at line 364 of file itkOffset.h.
SetElement()
template<unsigned int VDimension = 2> void itk::Offset< VDimension >::SetElement (unsigned long element, OffsetValueType val) inline
Sets the value of one of the elements. This method is mainly intended to facilitate the access to elements from Tcl and Python where C++ notation is not very convenient.
Warning
No bound checking is performed.
See also
SetIndex()
GetElement()
Definition at line 203 of file itkOffset.h.
SetOffset()
template<unsigned int VDimension = 2> void itk::Offset< VDimension >::SetOffset (const OffsetValueType val[VDimension]) inline
Set the index. Try to prototype this function so that val has to point to a block of memory that is the appropriate size.
See also
GetOffset()
Definition at line 191 of file itkOffset.h.
size()
template<unsigned int VDimension = 2> constexpr size_type itk::Offset< VDimension >::size () const inline constexpr
Definition at line 370 of file itkOffset.h.
swap()
template<unsigned int VDimension = 2> void itk::Offset< VDimension >::swap (Offset< VDimension > & other) inline noexcept
Definition at line 304 of file itkOffset.h.
References itk::swap().
Member Data Documentation
Dimension
template<unsigned int VDimension = 2> constexpr unsigned int itk::Offset< VDimension >::Dimension = VDimension static constexpr
Dimension constant
Definition at line 80 of file itkOffset.h.
m_InternalArray
template<unsigned int VDimension = 2> OffsetValueType itk::Offset< VDimension >::m_InternalArray[VDimension]
Offset is an "aggregate" class. Its data is public (m_InternalArray) allowing for fast and convenient instantiations/assignments. (See main class documentation for an example of initialization)
Definition at line 243 of file itkOffset.h.
Referenced by itk::Offset< VDimension >::GetBasisOffset(), itk::Offset< VDimension >::operator+(), itk::Offset< VDimension >::operator+=(), itk::Index< VDimension >::operator-(), itk::Offset< VDimension >::operator-(), and itk::Offset< VDimension >::operator-=().
The documentation for this struct was generated from the following file:
itkOffset.h